### ISSUE TITLE
[Request] Enhanced Multi Account

### ISSUE THREAD

**Issue by emoisback** [NecronomiconCoding/NecroBot#1001]
i have a idea,

user will create create folder inside config/profiles example : folder1 and folder2.
inside folder1 and folder2 we have config.json and auth.json for each account.
then we have profiles.json file inside /config with this content :

{
  "Profiles": [
    "folder1",
    "folder2"
  ]
}

at starting up, bot will check profiles.json to get config account.
and when run bot again with path as argument.

you can run folder1 at first exe then run new bot process with folder2 as arguments

but when 2 account is google it will open 2 google.com/device but clipboard copy not work because just 1 device code copied to clipboard, so bot will show the devicecode and user copy paste to google.com/device manualy.

its will have us to manage multiple account

**Comment by marisancans** [comment]
Is it good idea to do that from 1 computer? Don't think so

**Comment by emoisback** [comment]
bot already support for multiple account...
i just wanted to make it more easier...

**Comment by 5andr0** [comment]
use bat/bash files to run multiple bots

**Comment by KurtCocain** [comment]
@emoisback How exactly? I didn't see anywhere how to run multiple accounts with 1 clone?
