### ISSUE TITLE
[Suggestion] Show current GPS location

### ISSUE THREAD

**Issue by NhatL** [NecronomiconCoding/NecroBot#1005]
In case we want to restart the bot, it would be nice to know where we are so we can redo the starting point to be closer than that. Especially if you're using the GPX pathing

**Comment by marisancans** [comment]
Look at config file. Also, default settings doesn't go any further than 1km I think from default location

**Comment by emoisback** [comment]
bot will save your last location into Coord.ini inside config folder when you rerun bot it will use coord.ini instead settings.

**Comment by NhatL** [comment]
Quit the bot just now, the config file still contains my old coordinates.

**Comment by emoisback** [comment]
There is no coord.ini / .json??. Old version have it to remember your location..

I still find code on positionchrckstate.

**Comment by NhatL** [comment]
Nope, coord.ini/.json doesn't exist. I'm using the newest release download :\

**Comment by wind-raven** [comment]
I'm working on this for #1037.  Going to start with pokemon catch and pokestop visits.
