### ISSUE TITLE
2 bug

### ISSUE THREAD

**Issue by Melinio** [NecronomiconCoding/NecroBot#1006]
Errors and ru_RU Translations
![2ec71-clip-57kb](https://cloud.githubusercontent.com/assets/12205598/17190079/265d567e-544d-11e6-9437-c808c3ed7354.png)
![812f7-clip-67kb](https://cloud.githubusercontent.com/assets/12205598/17190082/29a0ea12-544d-11e6-9232-f9eeae6b9ab8.png)

**Comment by ilikesomething** [comment]
Exactly the same issue since i updated to last version.
And i run 2 bots, one is okey and the other one have this problem every 1 min or so.. (tried to reboot : same prob)
