### ISSUE TITLE
Missing config file in release 0.1.8

### ISSUE THREAD

**Issue by ugrkucuk** [NecronomiconCoding/NecroBot#1009]
Hello, i downloaded latest release but it seems that i don't have Config.json file under Config folder. Can someone help? Thanks

**Comment by crausk** [comment]
U need to run the .exe file the close it, it will generate a config and a auth file for you.

**Comment by salvob41** [comment]
in 
`"PokemonsTransferFilter" 
...
"Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 800.0,
      "KeepMinDuplicatePokemon": 2
    },` 

plus, in this release it doesn't use the RazzBerry

**Comment by salvob41** [comment]
I suggest to call this issue: "Bugs in release 0.1.8 "

**Comment by salvob41** [comment]
I am confused about the `"PokemonsTransferFilter":` option in config file. 
What is that?

In the config I suggest to put the "list options" (Pokemon List, Item List) at the end of the config file

**Comment by salvob41** [comment]
#921 Release v 0.1.8 has been dismissed
