### ISSUE TITLE
pokemon still evolve even not in the pokemontoevolve list

### ISSUE THREAD

**Issue by skyicon** [NecronomiconCoding/NecroBot#1014]
my code
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 5.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 100
    },
    {
      "Key": "itemGreatBall",
      "Value": 100
    },
    {
      "Key": "itemUltraBall",
      "Value": 250
    },
    {
      "Key": "itemMasterBall",
      "Value": 200
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 0
    },
    {
      "Key": "itemMaxPotion",
      "Value": 200
    },
    {
      "Key": "itemRevive",
      "Value": 0
    },
    {
      "Key": "itemMaxRevive",
      "Value": 300
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1300,
  "KeepMinDuplicatePokemon": 3,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 2000,
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo",
    "dratini",
    "aerodactyl",
    "arcanine",
    "dragonair",
    "flareon",
    "gyarados",
    "vaporeon"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
    "doduo",
    "diglett",
    "ekans",
    "geodude",
    "growlithe",
    "kabuto",
    "machop",
    "mankey",
    "paras",
    "omanyte",
    "rhyhorn",
    "sandshrew",
    "goldeen",
    "weedle",
    "caterpie",
    "nidoranMale",
    "nidoranFemale"
  ],
  "PokemonsToIgnore": [
    "zubat",
    "pidgey",
    "rattata"
  ],
  "PokemonsTransferFilter": null,
  "PrioritizeIvOverCp": true,
  "ProfilePath": "C:\\Users\\Aldonius Yoseph Jo\\Desktop\\Pokebot\\NecroBot-master - Copy\\NecroBot\\NecroBot\\PoGo.NecroBot.CLI\\bin\\Debug",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 100,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251

**Comment by ProfessorPoke** [comment]
"EvolveAboveIvValue": 5.0,
"EvolveAllPokemonAboveIv": true,

You are telling the bot to evolve anything with Iv higher than 5.0. Change this to 95.0 or false.

**Comment by guest136** [comment]
i have the same problem it is either evolving all or nothing, but doesnt use the evolve list


{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\Armenia\\Downloads\\Neuer Bot\\Alex\\PoGo.NecroBot.CLI\\bin\\Debug\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 38.57813,
  "DefaultLongitude": -121.48671,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 100
    },
    {
      "Key": "itemRevive",
      "Value": 30
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1300,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 80.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1200,
  "PokemonsNotToTransfer": [
    "graveler",
    "pidgeotto",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "doduo",
    "weedle",
    "nidorina",
    "rattata",
    "spearow",
    "ekans",
    "sandshrew",
    "oddish",
    "zubat",
    "paras",
    "diglett",
    "growlithe",
    "poliwag",
    "machop",
    "bellsprout",
    "weedle",
    "tentacool",
    "geodude",
    "ponyta",
    "magnemite",
    "shellder",
    "drowzee",
    "krabby",
    "voltorb",
    "cubone",
    "goldeen",
    "pidgey"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": true,
  "ProfilePath": "C:\\Users\\Armenia\\Downloads\\Neuer Bot\\Alex\\PoGo.NecroBot.CLI\\bin\\Debug",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}

**Comment by skyicon** [comment]
@ProfessorPoke i've use that setting with ver 0,17 and works but not in 0,18

**Comment by guest136** [comment]
"EvolveAllPokemonWithEnoughCandy": false,

that was my problem it has to be "true"
