### ISSUE TITLE
GPX Confirmer

### ISSUE THREAD

**Issue by Maynaards** [NecronomiconCoding/NecroBot#1016]
For a lot of people we dont know whether or not our bot has loaded the gpx file It would be brilliant if this was added

**Comment by ProfessorPoke** [comment]
I think I noticed a difference between my GPX bot and my wandering bot in that the wandering bot will list info when it finds the next Pokestop. The GPX bot doesn't list the info. Not sure why, but this is how I know my GPX is working. When I grabbed the wrong version of GPX, it threw tons of errors, so there's that.

**Comment by NhatL** [comment]
This is why it'd be great for the bot to print out a line with current GPS so that we can keep track of where it is.

**Comment by MrDingdong** [comment]
With a look at the ingress map it would alteady help if the pokestops could be named like in free mode.
