### ISSUE TITLE
RocketAPI needs to be updated problem with the filename Exceptions/PtcOfflineException.cs

### ISSUE THREAD

**Issue by psicrest** [NecronomiconCoding/NecroBot#1018]
Currently its PTCOfflineException.cs latest pull was changed to **PtcOfflineException.cs**
CSC: error CS2001: Source file `Exceptions/PtcOfflineException.cs' could not be found

**Comment by eLyiN** [comment]
Redownload the Api from FeroxRev

**Comment by fossum** [comment]
The current necrobot:master commit bac526f2f742bc40dd9f3f839c6b52c37a996fa7 uses FeroxRev commit c6d12b6 (which has the issue). Pulling the latest FeroxRev:master breaks a lot more than a File name case sensitivity.

**Comment by Diamondpact** [comment]
Is this related to the error 
logging in using google (in blue writing)
(Attention) make sure lat & long are right. Exit Program if not! (in green with my long and lat set up)

then the errors continue.
(ERROR) PokemonGo.RocketAPI , Exceptions , InvalidResponseException: Exception of type 'PokemonGo . RocketAPI . Exceptions . InvalidResponseException' was thrown.

then a bunch of other errors having exception was thrown

I would really appreciate the help as I really love pokemon  and just got into botting first time was in black dessert :D

Thanks in advanced to your insight
