### ISSUE TITLE
Login with google account

### ISSUE THREAD

**Issue by moredhel92** [NecronomiconCoding/NecroBot#1022]
![image](https://cloud.githubusercontent.com/assets/20690229/17191598/e22d6720-544a-11e6-8180-4638d76642a3.png)

i got 2 account when windows open, and i don't know how take the code

**Comment by TheBorna** [comment]
Select which account you want by clicking on it and after that it will ask you to enter the code which bot automatically copied for you, after that click accept.

After you enter it bot should work, if it doesn't try to restart it.

**Comment by moredhel92** [comment]
didn't work

**Comment by javilonas** [comment]
CTRL + V (The code is automatically copied to the clipboard)

**Comment by moredhel92** [comment]
ohohoh thanks, i'm stupid sorry
