### ISSUE TITLE
[Suggestion] Pokeball Priority

### ISSUE THREAD

**Issue by Maynaards** [NecronomiconCoding/NecroBot#1030]
> 1 You can set which pokeballs you want it to throw i.e pokeball ultra and great
> 2 If your bag is full and you get a ultra ball from a pokestop it will remove a lower ball for it's place

**Comment by starf** [comment]
Actually, the second problem can easily be solved by creating one parameter for "BallsToKeep", and it keeps the best balls. Same for potions, and has already been suggested somewhere.
For the first issue, there probably is some sort of algorithm in place that does a better job then the user no?
