### ISSUE TITLE
[Suggestion] Auto-close after first startup

### ISSUE THREAD

**Issue by Diablosito33** [NecronomiconCoding/NecroBot#1033]
## I would really like that to happen, so it wont use default map coordinates.
I get scared when I donwload V-0.1.8 and it was starting automaticly after setup,
when I changed coordinates, i saw your sistem counting up to 40 - Possible Softban.

**In a clear way:**
Bot could ask for:
_"Do you want continue with default coordinates *shows default coord*?"_
**If yes**, bot proceed
**if not**, bot shutdown simply.

**Comment by Nordiii** [comment]
Hm i will try to add this

**Comment by FreddyLIE** [comment]
Duplicate topic #793

**Comment by Diablosito33** [comment]
Sorry, i searched on very recent "issues" but didn't found, my bad, i should have searched more deeper.

**Comment by FreddyLIE** [comment]
Made the same mistake (#721) :-)

**Comment by Diablosito33** [comment]
Nice idea (just saw that #721), i can simply configure randomly at first startup, 
and then I'll edit with real configurations.

But there will be more people like me, falling on this and getting softbanned.
