### ISSUE TITLE
[Suggestion] Add Longitude / Latutude setting to first time startup

### ISSUE THREAD

**Issue by Evlow** [NecronomiconCoding/NecroBot#1041]
Not an issue, but a feature request.  On the configuration of a new compiled bot with no config, add a "Enter Longitude & Latitude" option where a user can enter the data and it start this out as the 1st point.

**Comment by titanbullet12** [comment]
Yup, right after google/ptc login, a "form" with longtitude and latitude plus a guide on how to see them would be nice. I should try to make this as a pull request.
