### ISSUE TITLE
PoGo.Necrobot.CLI - load failed

### ISSUE THREAD

**Issue by liam885** [NecronomiconCoding/NecroBot#1044]
PoGo.Necrobot.CLI coming up in studio with 'load failed' any ideas

**Comment by N3HL** [comment]
Same, something with the .csproj

**Comment by shejk0** [comment]
just remove this, or every other translation you don't need    
<None Include="Config\Translations\translation.tr.json">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>

**Comment by liam885** [comment]
o.NecroBot.CLI\PoGo.NecroBot.CLI.csproj : error  : The element <#text> beneath element <None> is unrecognized.  C:\Users\l\Desktop\necro\PoGo.NecroBot.CLI\PoGo.NecroBot.CLI.csproj

is full error, remove what sorry?

**Comment by N3HL** [comment]
@shejk0, removed all translations, now it loads fine, wp

**Comment by shejk0** [comment]
there are 2x "+", you just need to remove them :D didn't saw it earlier

**Comment by liam885** [comment]
How do i find them? sorry for being an idiot

**Comment by N3HL** [comment]
@liam885 open PoGo.NecroBot.CLI.csproj with Notepad++, VSCode, Atom, etc etc. Its like a XML file.

**Comment by liam885** [comment]
u the man, thanks so much!

**Comment by AppliedEllipsis** [comment]
Just place this file in \NecroBot\PoGo.NecroBot.CLI\
It's from the 5ec464c4ca3d622d3538a908eebda958f39348cf commit and just has the translations removed.
[PoGo.NecroBot.CLI.csproj.zip](https://github.com/NecronomiconCoding/NecroBot/files/387247/PoGo.NecroBot.CLI.csproj.zip)

**Comment by AppliedEllipsis** [comment]
Update: Line 139 and 140 need the "+" removed from the front.

**Comment by Resaec** [comment]
fixed https://github.com/NecronomiconCoding/NecroBot/commit/4bbc330e79da4d697254c09e0e270529f5d9e9a9
