### ISSUE TITLE
Auth code not showing up

### ISSUE THREAD

**Issue by UAVova** [NecronomiconCoding/NecroBot#1045]
Using latest release. No code to paste to devices page (google auth)
![image](https://cloud.githubusercontent.com/assets/11521441/17193463/c35624e8-545b-11e6-8cde-1299de122d30.png)

**Comment by Evlow** [comment]
did you try to press crtl+v and and see if it copied it to your clipboard like it says?  worked fine for me.

**Comment by UAVova** [comment]
@Evlow , Of course i tried that))

**Comment by wzx052266** [comment]
Getting the same issue here. Using Chrome and Google auth page pop up, but the program crash at the same time and nothing was copied to clipboard as try to crtl v to other places. Tried other PTC account works fine.

**Comment by airmaxxxx** [comment]
Yeah PTC works fine but I dont want to fucking login with PTC, that would made me start all over again.
