### ISSUE TITLE
[QUESTION] Not Catching Lured Pokemons

### ISSUE THREAD

**Issue by vcafezinho** [NecronomiconCoding/NecroBot#1052]
Just a question,

My bot is catching just normal pokemons ((PKMN) (CatchSuccess) | (Normal)) a long time that I do not catch any lured pokemons.

Did I miss any reversion or what is happening?

Thanks for your help.

**Comment by vcafezinho** [comment]
Someone?

**Comment by Ilses** [comment]
I'll take a look at latest master

**Comment by Ilses** [comment]
That's odd, I'm only seeing (Normal). I'll give it a while and check back.

**Comment by vcafezinho** [comment]
Ok, thank you very much @Ilses , that is really odd.

**Comment by Ilses** [comment]
I'm confirming lures are broken. Looking into a fix right now.

**Comment by Ilses** [comment]
This problem appears to be upstream. We'll have to wait for protos updates to come through.
