### ISSUE TITLE
Pokemons never evolving??

### ISSUE THREAD

**Issue by sepfire** [NecronomiconCoding/NecroBot#1053]
Bot isnt evolving anything for me what im doing wrong or is it a bug? heres my config 
http://pastebin.com/KYzL2S4R

and heres the image from bot that shows enough candies and still transfering drowzee's 

https://gyazo.com/ab4301879cb5dbd9481bbd96f8f3d0ca

**Comment by sepfire** [comment]
ok i found the fix in my Config i changed UseLuckyEgg option to False and kept everything the same and now it seemed to work alteast with the Rattata and Caterprie in that picture

https://gyazo.com/54776a5f4fb3f317feb6952593c788e1

**Comment by skupfer** [comment]
This is an ongoing issue. I experience the same even with an older version (pre merge) I am running myself. It works a few times but all of a suddon the bot stops autoevolving due to the settings are correct. Wasn't able to fix it yet. (toEvolve is filled with all pokemon who can evolve)

**Comment by Diablosito33** [comment]
I was having that issue...
I just filled my list with First Evolutions of Pokemon (excluding some)
and everything is going already, suddenly mande like 20evos, got a bunch of EXP, and good CP pokemons!

This is my config:
`{
  "AmountOfPokemonToDisplayOnStart": 250,
  "AutoUpdate": true,
  "ConfigPath": "*deleted*",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 41.147988915635857,
  "DefaultLongitude": -8.611040934920311,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 2000,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 500,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "ekans",
    "sandshrew",
    "nidoranFemale",
    "nidoranMale",
    "clefairy",
    "vulpix",
    "jigglypuff",
    "zubat",
    "oddish",
    "paras",
    "venonat",
    "diglett",
    "psyduck",
    "mankey",
    "poliwag",
    "bellsprout",
    "tentacool",
    "geodude",
    "magnemite",
    "doduo",
    "grimer",
    "shellder",
    "gastly",
    "krabby",
    "voltorb",
    "exeggcute",
    "koffing",
    "tangela",
    "horsea",
    "goldeen",
    "staryu",
    "eevee",
    "omanyte"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": false,
  "ProfilePath": "*deleted*",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 23.0,
  "WebSocketPort": 14251
}`

**Comment by Diablosito33** [comment]
Btw, that's a **CP focused config**, it's ignoring everything related with IV.

**Comment by thenextfreud** [comment]
new release solved evolutions
