### ISSUE TITLE
[BUG] Unable to Run PoGo.NecroBot.CLI after login and Lat/Lon input

### ISSUE THREAD

**Issue by CandyKeynes** [NecronomiconCoding/NecroBot#1054]
I have been running an older version (0.1.1.5) for a few days with no issues. Went to upgrade in order to have the incubator function. 

Had no problems with downloading .zip and extracting, and I logged in with my Google auth just fine. Got out of the bot to change the default lat and long before a soft-ban, and also changed a few other things in the Config file (evolve ratatas, min IV keep value). 

I go to load the bot and it will not load ("NecroBot has stopped working."). But I had no issues running it when I first downloaded (both the previous version and before I changed Lat/Long). Any ideas? 

I've attached my config file to see if I deleted something accidentally that was necessary. (The file is a .json in the folder, but I had to make a .txt copy in order to post it here.)
[config.txt](https://github.com/NecronomiconCoding/NecroBot/files/387289/config.txt)

**Comment by n1ghty** [comment]
"PokemonsToEvolve": [
 ...
"ratata"

Change that to "rattata".

**Comment by CandyKeynes** [comment]
Hah, I'm an idiot. Thanks, works now!
