### ISSUE TITLE
PoGo.NecroBot.CLI.exe is Missing

### ISSUE THREAD

**Issue by tunafish316** [NecronomiconCoding/NecroBot#1055]
Hey everyone! 

Just want to let you know that I followed the steps for the users who wanted to meddle around with the source code (developers option). 

I unzipped the RocketAPI and moved it to the FeroxRev folder as instructed. 

After opening the project in Visual Basic and then I right click on PoGo.NecroBot.CLI and select the option to "Set as Startup Project" the error occurs when I try to run it. 

This error pops up. https://gyazo.com/752aa2cf2734fee5fe864c2954fa1692

Secondly, I believe this is also another reason for why my problem occurs. 

If you look at the Solution Explorer, PokemonGo.RocketAPI shows up as unavilable even though I dragged the API folder into the FeroRev Folder.

https://gyazo.com/302600ead31a2af5625da2aa98497fcf

What steps should I take to properly run the program? Thanks

**Comment by Talamar1** [comment]
You tried to run the program without building it?

**Comment by tunafish316** [comment]
I will try to build it and then run it as you recommend. Sorry for that.

**Comment by tunafish316** [comment]
For people who ran into my problem. You have to build the project after you seet it as startup project. THanks Talamar1!
