### ISSUE TITLE
Suggestion: update README to fix changing DefaultLat & Long

### ISSUE THREAD

**Issue by gamelinchpin** [NecronomiconCoding/NecroBot#106]
Lat/Long coords come from`PokemonGo.RocketApi.Console\bin\Debug\Coords.txt` when running the app multiple times. Therefore changing coords inside `UserSettings.settings` means that the `Coords.txt` file must be destroyed in order for the app to adopt the UserSettings.

It appears that a `Clean Solution` or similar in VS2015 doesn't clear those files out.

**Comment by lauw** [comment]
Yeah this should be changed to work differently altogether, but for now a Readme adjustment could do.
You can also change the readme and submit a pull request if you want.

**Comment by ReddoKiddo** [comment]
Changed closing
