### ISSUE TITLE
[BUG]Not tranfering pokemon correctly

### ISSUE THREAD

**Issue by desfoi** [NecronomiconCoding/NecroBot#1060]
So, I'm using the last version (1.9) and I have set "TransferDuplicatePokemon": true, "KeepMinCp": 2000, "KeepMinDuplicatePokemon": 1, "KeepMinIvPercentage": 95.0 and "KeepPokemonsThatCanEvolve": false. I also have the "PokemonsNotToTransfer" list empty...
With this settings, the version 1.0 used to transfer everything perfectly, but this one just transfers one or two very occasionally. Other than this, I think the bot is perfect.
Thank you, btw

**Comment by GoodMonty** [comment]
Was trying to fix this myself. I have the same settings as you.

**Comment by Diablosito33** [comment]
Do not forget: *"PrioritizeIvOverCp"*

**Comment by Diablosito33** [comment]
My bot is doing everything corretcly, as i choosed to.
Evolving, trasnfer, keep....
Everything's ok.
Read the wiki about each configuration line.

**Comment by drappiro** [comment]
same issue here. 
PrioritizeIvOverCP is false...
My settings works in old version but not in this.

**Comment by desfoi** [comment]
Tried everything that I can, but as I don't understand that much about programming, just gave up and came for help...but would be nice a quick fix, because after 2/3 hours, the bot stops due to full PokemonInventory

**Comment by drappiro** [comment]
{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\Arkolys\\Desktop\\bot\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.785091,
  "DefaultLongitude": -73.968285,
  "DelayBetweenPokemonCatch": 3000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 20
    },
    {
      "Key": "itemGreatBall",
      "Value": 20
    },
    {
      "Key": "itemUltraBall",
      "Value": 63
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 10
    },
    {
      "Key": "itemHyperPotion",
      "Value": 100
    },
    {
      "Key": "itemMaxPotion",
      "Value": 100
    },
    {
      "Key": "itemRevive",
      "Value": 10
    },
    {
      "Key": "itemMaxRevive",
      "Value": 100
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 20
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 450
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 450
    }
  ],
  "KeepMinCp": 1650,
  "KeepMinDuplicatePokemon": 3,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": false,
  "ProfilePath": "C:\\Users\\Arkolys\\Desktop\\bot\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug",
  "RenameAboveIv": true,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}

**Comment by Diablosito33** [comment]
Try my config, at: #1053 
Read the "warnings" at start of config, dont forget to change those values.

**Comment by drappiro** [comment]
works, thanks

**Comment by drappiro** [comment]
Well. I found the problem, it's the KeepMinPokemon, we need to put to 1...

**Comment by drappiro** [comment]
Or 2. But 3 doesn't work..

**Comment by desfoi** [comment]
I have the same as him, and it doesn't work xD

**Comment by drappiro** [comment]
True. It only transfered one time 10 pokemons and now, don't transfer anything again

**Comment by Diablosito33** [comment]
Dudes?! It will transfer when needed, it will eventually works perfect, you dont want to do 1000actions in 10sec, and get insta ban, I guess they have a smart system, to do all actions human like, so it wont detect you used macros or bot to trasnfer or evolve...
For real tests, watch your bot for **MINUTES**; instead seconds and spamm this github xD
I mean, mine is working just perfect, I've been monitorizing and everything's great.

**Comment by desfoi** [comment]
Started with 140 pokemons, copied your settings, just as they were, after 20 minutes or so, I checked to see how things were. I had 210...that's worrying I think...just means it's not transferring xD

**Comment by Diablosito33** [comment]
Weird...

**Comment by Diablosito33** [comment]
Try to wait like 10-30min, and watch what happens.

**Comment by bad1dea** [comment]
there's logic broken somewhere, for the transferring of pokemon -- reverted back to old version and it worked fine.. ran for 4 hours.

**Comment by thenextfreud** [comment]
I didn't revert but it was working fine before and now isn't. I dont have all the reference directories or know the code well enough to help =(.
