### ISSUE TITLE
KeepPokemonsThatCanEvolve

### ISSUE THREAD

**Issue by ghry** [NecronomiconCoding/NecroBot#1062]
how to set it only keep pokemons in the "PokemonsToEvolve" list

**Comment by Dyzson** [comment]
Good idea.

**Comment by Navyguy330** [comment]
Agreed lol, and +100

**Comment by integriti** [comment]
Currently that setting keeps only the pokemon that you can actually evolve as per your current candy count. I think there should be an extra setting for this request.

If people want, I'll split the setting into two:
KeepEvolvablePokemonsWithEnoughCandy   (what the setting currently does)
KeepPokemonsInEvolveList   (as requested by ghry)

**Comment by Navyguy330** [comment]
I would rather it transfer everything other than the settings posted.  So
if I don't have enough candy and it doesn't meet the other cp or iv
requirements then out it goes, then if enough Candie and it's NOt on the do
not evovle list it evolves it.  Etc.  Or wait il it has 30 or so to evolve.
Pops an egg and goes off.

**Comment by GammaPaladin** [comment]
Yeah, this setting has issues. You have to set it, or it transfers your pokemon and never evolves them, but if you do set it, it keeps anything that it has enough candy to evolve, even if it has an IV of 5% and isn't on your "PokemonsToEvolve" list.

Worse, having it on means that things like Gravelers that can't even evolve get kept.

I toggled it to false and it finally transferred a whole ton of pokemon it had been keeping.

But if it run with it off, I lose a ton of xp I could be getting from evolving pidgeys and such :/

Plz fix.

**Comment by GammaPaladin** [comment]
Actually, no rush, already fixed this in my local copy, couldn't wait. So take your time.
