### ISSUE TITLE
[SUGGESTION] Renaming Pokemon

### ISSUE THREAD

**Issue by GTXMike** [NecronomiconCoding/NecroBot#1064]
The feature to rename Pokemon if its above set perfection level is fantastic as it helps to locate the best Pokemon in collection. As for now the rename process looks like PokemonID_%Perfection. What I would like to suggest is an option to choose in a config the way Pokemon is renamed. If bot could rename the Pokemon in this way: %Perfection_PokemonID for example: 100_Pikachu. That would be very helpful because if we would use A-Z sorting in the game, all the highest perfection Pokemons would be nicely sorted by level on the top of the list.

**Comment by drappiro** [comment]
+1 !

**Comment by Mewys** [comment]
+1

**Comment by Kuroah** [comment]
+1. It would be even better if there is a separated IV setting for naming feature. BTW, when I set my IV to 95%, the pokemon with exact 95% perfection rate won't be renamed. Is that a bug?

**Comment by GTXMike** [comment]
I believe the setting is >95% means it will actually mark 96%. If it would be >=95% it might mark from 95%.

**Comment by hakkotsu** [comment]
i made a PR[#1099](pull/1099) to fix condition check, but I'm not sure that putting number in a front of the name will be a good idea since during sort in app we will get it sorted by numbers and not by names/pokemons

**Comment by GTXMike** [comment]
Thats the point as it would be useful for many people and we talking here about an optional setting so everybody could choose what they like.

**Comment by hakkotsu** [comment]
Done. Submitting PR now
![img](http://i.imgur.com/rKICi28.png)

**Comment by Fenixxia** [comment]
Someone tested the rename to Evee? Is it possible its intended transformation into one of the three brothers, if the name is changed a second time?If First time using the bot. Maybe this "Easter egg" will not work when re-renaming. So we lose the target the transformation of Evee, if we use bot.

**Comment by hakkotsu** [comment]
Just don't put them to *PokemonsToEvolve* list and set
*EvolveAllPokemonAboveIv* and *EvolveAllPokemonWithEnoughCandy* to false

**Comment by hakkotsu** [comment]
@GTXMike give a look at #1115

**Comment by SUSANL61520** [comment]
Fenixxia the Evee renaming easter egg was removed in the last update of PoGo

**Comment by GTXMike** [comment]
That looks great 😁
