### ISSUE TITLE
[Suggestion] Upon running the program for the first time, ask for the locality to set as default

### ISSUE THREAD

**Issue by sloanja** [NecronomiconCoding/NecroBot#1065]
When you first run the program, it asks you to log into Google and do the token.  Either before that process or after, can we have the program prompt for the user's location (either in GPS coordinates, or a prompt to fill in the city and the program can look up the gps coordinates from Google)?

It makes more sense to prompt the user upon first startup to prevent softbans because we default currently to Paris, France.

It would also make sense to ask for language to set at the start instead of manually doing this modification.

**Comment by AppliedEllipsis** [comment]
I agree, but not sure about the Paris thing..
In the latest commit, it defaults to (52.379189 4.899431) Amsterdam.

**Comment by sloanja** [comment]
I stand corrected... :P  but still, need a configuration option for location so we don't default in AMSTERDAM (see, i can fix myself).
