### ISSUE TITLE
Not transfer correctly the pokemons

### ISSUE THREAD

**Issue by drappiro** [NecronomiconCoding/NecroBot#1066]
Anyone know what's the problem?

{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\Arkolys\\Desktop\\bot\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.785091,
  "DefaultLongitude": -73.968285,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 20
    },
    {
      "Key": "itemGreatBall",
      "Value": 20
    },
    {
      "Key": "itemUltraBall",
      "Value": 63
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 10
    },
    {
      "Key": "itemHyperPotion",
      "Value": 100
    },
    {
      "Key": "itemMaxPotion",
      "Value": 100
    },
    {
      "Key": "itemRevive",
      "Value": 10
    },
    {
      "Key": "itemMaxRevive",
      "Value": 100
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 20
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 450
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 450
    }
  ],
  "KeepMinCp": 1650,
  "KeepMinDuplicatePokemon": 3,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": false,
  "ProfilePath": "C:\\Users\\Arkolys\\Desktop\\bot\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug",
  "RenameAboveIv": true,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}

**Comment by Unentertained** [comment]
[http://stackoverflow.com/a/19176131](url) Might explain why.
Basically the code is seeing the backslash character in the profile path as a special character. Although i might be completely wrong.. 
But mine shows it as:
"ConfigPath": "C:\\Users\\Admin\\Desktop\\PoGo\\Bots\\Release\\Release\\config",

**Comment by Navyguy330** [comment]
Are you not supposed to leave profile path blank and it makes one by default? then edit that one?

You may need to escape the \  there are different methods for each some double '   (NOT " or double quotes but rather two single quotes)
