### ISSUE TITLE
Pokemon Inventory full 

### ISSUE THREAD

**Issue by UAVova** [NecronomiconCoding/NecroBot#1068]
I see message "PokemonInventory is Full.Transferring pokemons..." but nothing happens. It doesn't transfer pokemons...
[My config](https://gist.github.com/UAVova/93d9337efbc8b8e0fdeac022766f82e7)

**Comment by drappiro** [comment]
Same here.

**Comment by drappiro** [comment]
fix: You can't keep 4 pokemons. KeepMinPokemon = 2(max)..
