### ISSUE TITLE
Getting this message or close to it "No usable pokestops in the area..."

### ISSUE THREAD

**Issue by gfeijo** [NecronomiconCoding/NecroBot#1075]
Is the game servers down? I double checked and coords are correct.

**Comment by wind-raven** [comment]
Check your max travel distance in the config file.  If its set to short then you wont "Find" any pokestops

**Comment by gfeijo** [comment]
Nah, looks like Central Park was a little bit crowded.Tried the same bot with another account at another place and worked. Same bot worked for main account again back in the first place.

**Comment by padmanek** [comment]
I got this after roughly 4 hours of running the bot in the center of Copenhagen.  There's a ton of pokestops here so no idea why this happened. The bot should be able to recover from it, for example by returning to the default location when this error shows up.
