### ISSUE TITLE
V0.1.9 UseLuckyEgg Function does not work. 

### ISSUE THREAD

**Issue by Olympian69** [NecronomiconCoding/NecroBot#1076]
In the v0.1.9 the "UseLuckyEggsWhileEvolving": true, does not work. It worked great in v0.1.8.

If it's possible to add the option to check for lucky egg timer, and if not present activate one every 30 minutes?

**Comment by Diablosito33** [comment]
Checks this two variables:
**"UseLuckyEggsMinPokemonAmount"**
**"UseLuckyEggsWhileEvolving"**
at your config.json

**Comment by Olympian69** [comment]
I have this, and it was working good in v0.1.8, however it doesn't evolve or use the lucky egg,
**"UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": true,**

I thought my issue would be by not having enough pokemons to evolve, however it keeps transferring all potential Pokemon's instead of evolving them, even tho this seems right :+1: 

  **"KeepMinCp": 1500,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": true,**

**Comment by Diablosito33** [comment]
Do not forget this:
**"PrioritizeIvOverCp"**.

You can use: **"PokemonsTransferFilter"**
to keep specific pokemons.
Ex: Pideys and Zubats, for transfer later, when **"UseLuckyEggsMinPokemonAmount"** reached, right?

**Comment by Olympian69** [comment]
It seems that it fixed itself, however would it be possible to add a function to have the lucky egg activated every 30min?
Is it possible for the bot to activate the egg after it has checked if it has been  already activated or not?

**Comment by Diablosito33** [comment]
"UseLuckyEggsMinPokemonAmount": 1,
and if doens't work, try to change:
**"UseLuckyEggsWhileEvolving"** to false, it makes some sense xD

**Comment by Shroomzie** [comment]
Im guessing you just didn't have a lucky egg to use.

**Comment by Olympian69** [comment]
I didn't have 30 Pokemon's available

On Wed, Jul 27, 2016, 8:03 PM Shroomzie <notifications@github.com<mailto:notifications@github.com>> wrote:

Im guessing you just didn't have a lucky egg to use.

**Comment by Shroomzie** [comment]
Ahh i see, thankyou for clarifying the cause.
