### ISSUE TITLE
Option to disable catch pokemon// or catch wanted pokemon

### ISSUE THREAD

**Issue by bebar69** [NecronomiconCoding/NecroBot#1078]
I'am on top five player of my county...
i want farm pokeball and heal potion not XP and pokemon
Can you implement option to disabled pokemon catch?
Or an option for catch only wanted pokemon?

**Comment by Revuin** [comment]
There's a "PokemonsToIgnore" setting in the config file. Just put every pokemon in that list or ones you dont want. Also set "UsePokemonToNotCatchFilter" to true.

**Comment by lukftw** [comment]
can we have a list of pokemons?

**Comment by AldoFieuw** [comment]
@lukftw http://pastebin.com/raw/AyEwTBcT

I have placed "drowzee" in the "ConfigPokemonsNotToCatch.ini" but it's keep catching him.
Other pokemon on that list are being ignored.

My "ConfigPokemonsNotToCatch.ini" file: http://pastebin.com/raw/pEQddifq

**Comment by lukftw** [comment]
@AldoFieuw thanks

**Comment by lukftw** [comment]
This is the list without errors at start : http://pastebin.com/KcnkdLAt
