### ISSUE TITLE
Always catchflee

### ISSUE THREAD

**Issue by WEAREALLCORRUPT** [NecronomiconCoding/NecroBot#1080]
Every pokemon. Cant catch any. Whats my issue?

**Comment by sahil16** [comment]
possibly softban?

**Comment by gfeijo** [comment]
Use any of the "unbanning" bot available on the market

**Comment by WEAREALLCORRUPT** [comment]
where do i find that at?

**Comment by WEAREALLCORRUPT** [comment]
@gfeijo where may i find that

**Comment by lhzeng888** [comment]
just keep the code running, and it will be fine in 5 min.

**Comment by Talamar1** [comment]
Bot will unban you when it hits a pokestop.

**Comment by KurtCocain** [comment]
Does that work for long distance travels? Like say i would go from NYC to Sydney

**Comment by Talamar1** [comment]
Yes, there is currently only one kind of softban.
