### ISSUE TITLE
no pokemons get catched when the pokestop is empty

### ISSUE THREAD

**Issue by guest136** [NecronomiconCoding/NecroBot#1086]
Hello, if I go to Dratini City and run the bot it just catches the pokemon when the pokestops cooldown is resetted then it catches some pokemon nearby and emptys the pokestop and after that he waits untill the pokestops are resetted to empty it and catch some pokemon for about 5 sek. it seems to me that the bot needs enough pokestops to work.

**Comment by Ilses** [comment]
The bot wanders between available pokestops and catches pokemon in the process. If there are no pokestops off cooldown, it will sit in place looking for pokemon. Use a gpx route if you don't want this behavior.

**Comment by guest136** [comment]
ok cool i thought it will behave the same with gpx route. i will try thanks

**Comment by KurtCocain** [comment]
That or get a higher kmdistance from start position i guess
