### ISSUE TITLE
Step #4 Nothing to click on in Visual Studio 2015

### ISSUE THREAD

**Issue by MrTriForce** [NecronomiconCoding/NecroBot#109]
Step 4 states "on the right hand side, double click on UserSettings.settings" but I find nothing to click on the right hand side.

**Comment by lauw** [comment]
Press Ctrl + ; in case Solution explorer is hidden, then write UserSettings and see if you can find the file

**Comment by MrTriForce** [comment]
That worked perfectly, thank you.
