### ISSUE TITLE
[Feature] [Request] Pause after welcome warning

### ISSUE THREAD

**Issue by dually8** [NecronomiconCoding/NecroBot#1091]
It's difficult to catch the program before it starts you off in one place.  I think it'd be helpful to have a pause to wait for user input before continuing after seeing 

> Make sure Lat & Lng are right. Exit Program if not!

I was going to try and insert a system pause where
```
session.EventDispatcher.Send(new WarnEvent
            {
                Message =
                    session.Translations.GetTranslation(TranslationString.WelcomeWarning, session.Client.CurrentLatitude,
                        session.Client.CurrentLongitude)
            });
```
happens.  If there is a better way of doing this, please let me know.  I'm happy to contribute what I can.  Thanks.

**Comment by Skullmonkey** [comment]
+1 just got softbanned (hopefully) because i couldn't close out in time to make sure the co-ords were correct.

**Comment by Sasstraliss** [comment]
+1

**Comment by hakkotsu** [comment]
it was already fixed

**Comment by hakkotsu** [comment]
download and rebuild from source

**Comment by dually8** [comment]
Yeah. That's just on the first run though. This is for every run after that. I'd like to keep this open since at least a few people want this functionality.

**Comment by Naroko** [comment]
+1
