### ISSUE TITLE
ERROR : session.Client.Inventory.UpgradePokemon is not working

### ISSUE THREAD

**Issue by MonsterMMORPG** [NecronomiconCoding/NecroBot#1093]
Hello. I have tried to utilize session.Client.Inventory.UpgradePokemon

To upgrade my Pokemon. However the response is 

{{ "result": "ERROR_POKEMON_NOT_FOUND" }}

Can you fix it asap? Thank you

I am calling this as same as 

var evolveResponse = await session.Client.Inventory.EvolvePokemon(pokemon.Id);

So i can safely say that i have made no mistake.

**Comment by YannickFricke** [comment]
File it to the api, not a function of the bot i think

**Comment by MonsterMMORPG** [comment]
@YannickFricke  i guess you are right posted there
