### ISSUE TITLE
GPX error

### ISSUE THREAD

**Issue by Migflyway** [NecronomiconCoding/NecroBot#1096]
i got some error when i set gpx TRUE. version 0.1.9.
I got gpx file at https://github.com/NecronomiconCoding/NecroBot/wiki/Locations-&-GPX-Route-Files
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass1_0.<<Execute>b__1>d.MoveNext() C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: line 83

**Comment by KurtCocain** [comment]
Did you try bot comma and period?
If your language uses comma for coords like 40,13993 -73,23989823 use the comma one
if it does coords like this 40.13993 -73.23989823 use the period one

Had this problem too

**Comment by Migflyway** [comment]
yep. I tried both.  I delete some <ele>22</ele> and no error pop up, however cannot move.

**Comment by Navyguy330** [comment]
Make sure you are using the correct format, some use a decimal and some use a comma. Also capital may matter, use True, or true.

Another test would be to use a different GPX file, and also make sure the starting coords of your bot are the same as the start of the GPX.
