### ISSUE TITLE
Trying to catch a pokemon that spawned from incence throws an error and logs you out.

### ISSUE THREAD

**Issue by titanbullet12** [NecronomiconCoding/NecroBot#1100]
![image](https://cloud.githubusercontent.com/assets/8401124/17197616/e6a2596a-5476-11e6-9609-06668aa15985.png)

Nothing to be done about it, i need to wait till the incence is gone.

**Comment by Navyguy330** [comment]
Sorry I do not speak russian lol

**Comment by Ilses** [comment]
PR #1026 fixes this.
