### ISSUE TITLE
[Feature Request] Prioritize egg incubation by Distance

### ISSUE THREAD

**Issue by GRINSPANKER13** [NecronomiconCoding/NecroBot#1103]
I'd like to see the incubation process place the highest km eggs first.

**Comment by Fenixxia** [comment]
Не соглашусь. Яйцо-2км вылупляется быстрее, следовательно быстрее освободит слот под новое яйцо. А новое яйцо может быть яйцо-10км. Значит выгоднее использовать именно яйцо-2км. Но приоритетность использования яиц на выбор пользователя - это в любом случае выгодно.

**Comment by GRINSPANKER13** [comment]
I understand your point. My point is, with limited incubators and 10km eggs as rare as they are, I'd rather them have the highest priority. Maybe we could get an option in the config to specify which egg distance is the highest priority?

**Comment by gwtampan** [comment]
or maybe option or which incubator would we use.
