### ISSUE TITLE
Doubling lucky by changing time

### ISSUE THREAD

**Issue by KurtCocain** [NecronomiconCoding/NecroBot#1104]
Someone on OC said and I quote

`It seems that you can activate a lucky egg and change the phone's time, successfully doubling its time (the egg/incense timer can only be 60 minutes or it bugs). Has any bot added a functionality for it yet? `

Can someone confirm this? I can't try myself as my NOX is currently not working and I do not own a phone.

EDIT: And then if possible, add it to bot ^_^, kind of the point of this lol

**Comment by Owinger** [comment]
That's bullshit.

**Comment by ChenGaoYuan** [comment]
Sure???

**Comment by Navyguy330** [comment]
it don't work, old news, its locally and visual only

**Comment by Navyguy330** [comment]
who the f doesn't own a phone?  why are you playing pokemon go at all then? lol

**Comment by Ilses** [comment]
That's a client-side display bug. Not possible, please close.
