### ISSUE TITLE
[Help] Pokémon evolution (config)

### ISSUE THREAD

**Issue by Dyzson** [NecronomiconCoding/NecroBot#1105]
Hi, i need help.

This config is good: http://pastebin.com/S4Jykh6m
Unfortunately, evolve doesn't work.
I need evolve shit Pokémon for exp.
Evolution doesn't work at all.
I don't know why..

v0.1.9

**Comment by guest136** [comment]
it works for me with this - check it out:


{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\Armenia\\Downloads\\Neuer Bot\\Alex\\PoGo.NecroBot.CLI\\bin\\Debug\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 38.57813,
  "DefaultLongitude": -121.48671,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 100
    },
    {
      "Key": "itemRevive",
      "Value": 30
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1300,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1200,
  "PokemonsNotToTransfer": [
    "graveler",
    "pidgeotto",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "doduo",
    "weedle",
    "nidorina",
    "rattata",
    "spearow",
    "ekans",
    "sandshrew",
    "oddish",
    "zubat",
    "paras",
    "diglett",
    "growlithe",
    "poliwag",
    "machop",
    "bellsprout",
    "weedle",
    "tentacool",
    "geodude",
    "ponyta",
    "magnemite",
    "shellder",
    "drowzee",
    "krabby",
    "voltorb",
    "cubone",
    "goldeen",
    "pidgey"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": true,
  "ProfilePath": "C:\\Users\\Armenia\\Downloads\\Neuer Bot\\Alex\\PoGo.NecroBot.CLI\\bin\\Debug",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}

**Comment by Zerofy** [comment]
ye i got the same problem ;/ @guest136 do you have the latest build?

**Comment by integriti** [comment]
The linked config has these settings:
"UseLuckyEggsMinPokemonAmount": 30,
"UseLuckyEggsWhileEvolving": true,

With this, the evolution logic is blocked until you have at least 30 evolvable pokemon in your bag, regardless if you have a lucky egg or not.

**Comment by Dyzson** [comment]
Yes it's true
This config work: http://pastebin.com/SVq6nTFg

**Comment by srwgin** [comment]
how to set config
let me keep Duplicate pokemon piggy+zabat+rattata=30
then use lucky egg evolve them and Transfer

**Comment by Dyzson** [comment]
"EvolveAllPokemonWithEnoughCandy": true,
"KeepMinCp": 2000,      ; maybe less
"KeepMinDuplicatePokemon": 1,      ; maybe less or more
"KeepMinIvPercentage": 90.0,      ; maybe less
 "PokemonsToEvolve": [
    "piggy",
    "zabat",
    "rattata"
  ],
  "TransferDuplicatePokemon": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": true,

It's not a full config.
Only important settings, but I'm not 100% sure.

**Comment by srwgin** [comment]
but I see some in EvolveAllPokemonWithEnoughCandy (Value)
PokemonsToEvolve list will be evolved every 5 Pokestops limited by the number of Pokemon and candies you have
if I catch piggy+zabat+rattata=10 then pass 5pokestops
they evolve right？
so if pokestops too many and between them I catch less piggy+zabat+rattata
it will never use lucky egg？

**Comment by integriti** [comment]
If UseLuckyEggsWhileEvolving is true, then no evolution will happen until evolvable pokemon numer reaches UseLuckyEggsMinPokemonAmount value.

The question is whether or not KeepPokemonsThatCanEvolve is properly working to actually continue to accrue more pokemon, rather than transferring prematurely.
