### ISSUE TITLE
[Feature Request] Console title, change email to actual PTN username

### ISSUE THREAD

**Issue by Sasstraliss** [NecronomiconCoding/NecroBot#1106]
In the case of PTN account use, can the console window show the actual PTN username instead of the truncated email?

**Comment by dascione** [comment]
The console shows your 'display name' for your account.  If you haven't logged into the account with the app or site and set a display name, it will show the truncated email.  If you want it to show something specific, login and set a display name.

**Comment by Ilses** [comment]
If this is resolved, please close the issue.
