### ISSUE TITLE
[Feature Request] Break Timer

### ISSUE THREAD

**Issue by DRXOXO** [NecronomiconCoding/NecroBot#1109]
Not sure if possible, but it would be cool if the bot paused/ stopped at a set time -> waited for a set time -> opened at set time. The bot would have a more human feel this way; rather than grinding 50k+ XP/hr  24/7.

**Comment by Navyguy330** [comment]
Um no, rather it run 24/7   if you wanna pause it just close the damn thing.

**Comment by Navyguy330** [comment]
Oh want auto restart?  try a batch file. lol duh
