### ISSUE TITLE
Account not verified - exiting

### ISSUE THREAD

**Issue by NumberXer0** [NecronomiconCoding/NecroBot#1111]
I've been using this account to bot since the first release. Earlier today, mid run, it came up with the above error. Any subsequent attempt to run gives the same error. I tried erasing and starting from scratch, still the same error. Any idea why this error comes up all of a sudden? My other two bots are running fine, same exact files. I saw a few other issues about this but all were closed with no resolution.

**Comment by Navyguy330** [comment]
did you activate the account?  can you login online or on a phone?

**Comment by dascione** [comment]
Yeah, this is not a bot issue, you have to confirm your email address for your account.  Login to the PTC website and confirm your email address, after which the bot (and everything else) will login correctly.

**Comment by NumberXer0** [comment]
It's been activated for two weeks. I use the account every day. The bot was running with the account until it randomly errored.

**Comment by NumberXer0** [comment]
Doesn't make any sense, I log on fine and it says my account is activated. But if it's certain it isn't a bot issue, I'll attempt to figure it out on my own.
