### ISSUE TITLE
Transferring problems 0.1.9

### ISSUE THREAD

**Issue by Throw9984** [NecronomiconCoding/NecroBot#1116]
Is the bot supposed to keep an original Pokemon by default?

I set the option "KeepMinDuplicatePokemon" to a value of 0 and it transferred away Pokemon that I only had one of. When the value is set to 1, it keeps an original AND a duplicate no matter what CP or IV either one is (expected). So I thought changing it to 0 would be keeping only one of each Pokemon, again regardless of CP or IV, and then swapping it out if I got a better one. Is this logic wrong, or are my settings wrong?

"AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\jtroyer\\Desktop\\PGO\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 34.0086199479568,
  "DefaultLongitude": -118.498158979077,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1200,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew",
    "pidgey",
    "caterpie",
    "weedle"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "drowzee"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": false,
  "ProfilePath": "C:\\Users\\jtroyer\\Desktop\\PGO\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug",
  "RenameAboveIv": true,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}

**Comment by MattyO2** [comment]
I've noticed this as well, although I think saying originals and duplicates is a bit misleading

The bot -should- keep all pikachus above 1000 cp, all pikachus above 95% IV, and the strongest pikachu (default is the one with most CP but the "PrioritizeIvOverCp" probably makes it keep the highest IV pikachu instead)

but right now it keeps all above 1000, all above 95%, and the two strongest pikachus

**Comment by grantfree035** [comment]
> TransferDuplicatePokemon (Value)
> 
> When TransferDuplicatePokemon is set to true, any Pokemon that meets the below criteria is transferred:
> 
> Total number of that Pokemon species in your inventory is greater than KeepMinDuplicatePokemon
> Below the KeepMinIVPercentage value
> Below the KeepMinCP value
> Is not listed in your PokemonsNotToTransfer list
> Note that any of the first three criteria are global values and they CAN be overwritten by the Pokemon-specific settings in the PokemonsTransferFilter list.

^ to only keep 1 of each pokemon while _TransferDuplicatePokemon_ is true, _KeepMinDuplicatePokemon_ should indeed be set to one.

Now with your current config, it will keep any (regardless if they're duplicates) Pokemon whose CP is over 1500 or IV is above 90.
