### ISSUE TITLE
Google Unauthorized Response

### ISSUE THREAD

**Issue by Smok3r** [NecronomiconCoding/NecroBot#1117]
Wondered why I wasn't getting a code copied to the clipboard and a crash after it took me to the device page so I started debugging. It looks like an invalid response from google at least for me. I'll try making a PTC account and see if I can get around it.

![capture](https://cloud.githubusercontent.com/assets/20695592/17201212/4e9e352e-5441-11e6-8d67-33d6d179e44c.PNG)

keep up the good work

**Comment by Leetferret** [comment]
[21:29:32] (UPDATE) Perfect! You already have the newest Version 0.1.9
[21:29:32] (INFO) Logging in using Google
[21:29:33] (ATTENTION) Opening Google Device page. Please paste the code using
TRL+V
[21:29:38] (ERROR) Couldnt copy to clipboard, do it manually
[21:29:38] (ERROR) Goto:  & enter

Getting a blank AUTH code. Won't auto-copy to clipboard either.

**Comment by Ch3maa** [comment]
i have the same problem. 

![image](https://cloud.githubusercontent.com/assets/20695844/17201508/03116740-545d-11e6-82b3-ef24c4a43b8a.png)

**Comment by Smok3r** [comment]
Made a PTC account it works fine there, google has closed that loophole for me at least

**Comment by Opzon** [comment]
@Smok3r it isn't a loophole (at least I don't think so) I've used google login with another program and it worked fine. getting the same issue these guys are having :(

**Comment by olegtarasov** [comment]
Everything worked fine yesterday, but today I started to have the same problem.

**Comment by denniskai1234** [comment]
Same here.

**Comment by ugrkucuk** [comment]
I also have the same issue

**Comment by p3lonis** [comment]
I have this issue as well.

**Comment by lsf00txtp009** [comment]
same here as well, any possible way to solve it at this time?

**Comment by koukan118** [comment]
same...how to fixxx

**Comment by DnZ87** [comment]
Same issue today.. yesterday worked fine..

**Comment by rizardhis** [comment]
i also got this problem today, please someone help us 😲

**Comment by michaelliao5** [comment]
The original api creator shut down his client secret/id lol

**Comment by punkrocker250** [comment]
Had this issue also, I just used the auth config from the previous version.

**Comment by apurvakumar01** [comment]
Workaround:

Use any one of the previous code from _C:\Users\****\Desktop\Release\Config\auth_ from the previous version. Copy the code from this line "GoogleRefreshToken": **"1/MxqKS7JI3Q-*******************"** and paste it in the new version you downloaded.

**Comment by Leetferret** [comment]
When using said workaround and manually pasting the google code into the auth config. 
I get this... http://imgur.com/8UpcuWO

**Comment by ugrkucuk** [comment]
@Leetferret I also got the same message.

**Comment by Leetferret** [comment]
I fixed it (temporarily)... using " " around the Google code in auth.config 
![test](https://cloud.githubusercontent.com/assets/20695712/17205812/810dce3c-5461-11e6-8741-bc3f58d891e8.png)

**Comment by apurvakumar01** [comment]
Shouldn't have happened I think you copied something wrong in the file, please check the code again.

**Comment by Nightshaide** [comment]
is there a way I can get it to auth against another google API? 
like edit it and link it to my google account to get the key?

**Comment by adriantheplug** [comment]
@Leetferret you didn't use " " around the token.

**Comment by HZH1907** [comment]
How about a new google account? The reason why I find this is trying a new one.
The old one work fine.

**Comment by userix** [comment]
Getting the same issue.  It's not opening the webpage nor is it generating any code.  Just blank.

**Comment by E2155** [comment]
"AutoUpdate": false,

fix this issue in config.json

**Comment by koale** [comment]
Any idea for a guy who just wanted to start and never had this key created?

**Comment by romankessler** [comment]
I think this will help the developer. 
[http://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token](url)

**Comment by gearkill** [comment]
error in Newtonsoft.Json.dll or something related to it hope someone can solve
