### ISSUE TITLE
Add switch to allow for config.xml to be passed to exe

### ISSUE THREAD

**Issue by sh4t** [NecronomiconCoding/NecroBot#112]
Allow for a config.xml to be passed with the exe, eg:

pokemon-go-bot.console.exe -config=downtown.xml

where as downtown.xml and any other config.xml could contain a specific lat/lon, pokemon to keep/transfer etc

there was a precompiled version of one of the many variants of the bot on oc forum that had a user.xml that at least was in the folder that made it easy to have numerous locations defined (one per folder, one user.xml per folder) in my case.

**Comment by shejk0** [comment]
You've got "PokemonGo.RocketAPI.Console.exe.config", you still got it in debug/release folder after compiling and you can change these.
