### ISSUE TITLE
[Request]Check ban before catch pokemon

### ISSUE THREAD

**Issue by letuananh035** [NecronomiconCoding/NecroBot#1125]
[Request]Check ban before catch pokemon
Check pokestop if working => catch pokemon if not working unban

**Comment by windyair** [comment]
I think the bot can quickly fix the softban in minutes.

**Comment by starf** [comment]
Yes, but when spawning on top of a pokemon you want, it tries to cach the pokemon and it flees, goodbye snorlax, it's not coming back, even after the softban fix.
This can be fixed by going to a stop first (to check for ban), but the pokemon can then be out of reach.
Not easy i think.
