### ISSUE TITLE
no Google code or clipboard

### ISSUE THREAD

**Issue by bunnyx** [NecronomiconCoding/NecroBot#1126]
i start up PoGo.NecroBot but no Google AUTH code

Ver. 1.9 
![image](https://cloud.githubusercontent.com/assets/11628714/17202040/3c9b5a22-54c9-11e6-96a0-403ef892cb2c.png)

**Comment by RieTech** [comment]
Same too

**Comment by Hitsu91** [comment]
Same here

**Comment by proesd** [comment]
same here

**Comment by szychan** [comment]
there is already issue created here 
https://github.com/NecronomiconCoding/NecroBot/issues/1117

**Comment by lsf00txtp009** [comment]
same here

**Comment by Nomaan12345** [comment]
couldnt copy the device code to enter at google.com/device enter manually but cant see the device code in cmd window﻿ please help

![untitled](https://cloud.githubusercontent.com/assets/20672611/17202650/280b2d78-54b8-11e6-838a-9a0521a4a57e.jpg)

please help with the resolution of the cmd window too half of the words are cut

**Comment by Shroomzie** [comment]
As a temp fix have you tried running it as admin so it can gain control of the clipboard?

**Comment by lsf00txtp009** [comment]
It doesn't work by running it as admin

**Comment by ogAgliff** [comment]
The issue you're running into is because Pokemon Go servers are currently down.
Should be fixed soon.

**Comment by szychan** [comment]
why is it working on old version then ?

**Comment by lsf00txtp009** [comment]
http://ispokemongodownornot.com/  the server is
 good

**Comment by Shroomzie** [comment]
There's probably an app that's "locked" the clipboard. Try and work out what app has done that and close it. 

Try to restart your PC. Doesn't get more simple than that.

- Bug in an application: It acquired the clipboard and never freed it

- Windows ran out of memory a while ago and is now confused. It'll probably crash soon (blue screen).

- Virus

**Comment by ilhamazdi** [comment]
@szychan which old version are you mentioning ? I'm using both 0.1.8 and 0.1.9 release and it doesn't work too, unless you've authorized the copy of bot client, it should still work.

![capture](https://cloud.githubusercontent.com/assets/7246466/17203130/cc0e0ef4-54c7-11e6-8c57-7c3b74f680c4.JPG)

**Comment by michaelliao5** [comment]
The original api creator shut down his client secret/id lol

**Comment by ogAgliff** [comment]
Again, its because of Pokemon Go servers. 
You can't even log onto it on a device.

**Comment by xclusive707** [comment]
other bots runs but this one not so it can't be a server issue dude

**Comment by rizardhis** [comment]
@ogAgliff i dont think so bro, the server is OK in my country, and i can still logging in to the apps

**Comment by jonasbareiss** [comment]
I don't think he shut it down, but there is a user limit.
This is made by Google, no chance to change.

**Comment by michaelliao5** [comment]
unless that person upgrades the plan

**Comment by xclusive707** [comment]
can someone explain how to get the security code from app?

**Comment by Nomaan12345** [comment]
is there any solution to this where we could get the device code if not from cmd

**Comment by szychan** [comment]
@ilhamazdi v1.7 is running with no problems

**Comment by ilhamazdi** [comment]
@szychan just downloaded 0.1.7 release and it doesn't work either.

However, I second @jonasbareiss there's API limit usage

![capture](https://cloud.githubusercontent.com/assets/7246466/17203446/ca293cb0-54c9-11e6-9551-1d04594ed170.JPG)

**Comment by szychan** [comment]
just copy Your GoogleRefreshToken from auth.json to new version and it works ;) cheers !

**Comment by InnerFire** [comment]
@szychan I deleted it by mistake. Is there any way to retrieve the token again?

**Comment by lsf00txtp009** [comment]
its my first time, how can I get my GoogleRefreshToken @szychan

**Comment by koukan118** [comment]
im new...
i have no token key...

**Comment by crazynever** [comment]
szychan, within the auth file appears the following code:
`"GoogleRefreshToken": null,`

There should not be a token in this space?

**Comment by szychan** [comment]
Not sure how to retrive it. I got mine yesterday. but it seems as @ilhamazdi said there could be API limit usage. so sadly I dont know how to resolve it for ppl who deleted theirs token or are just starting with it.

**Comment by ilhamazdi** [comment]
However, some of my bots still running because I've cancelled the auto-update. Because enabling auto-update make you lose the GoogleRefreshToken and bot request new one.

**Comment by proesd** [comment]
@szychan suggest is only for who has older version I think, because if you new at this you need a fresh google auth.

**Comment by Sad0wl** [comment]
@szychan thanks man for the hint, its worked for me,

**Comment by Nothingst** [comment]
@szychan  do you get code ? how do you get it? and what do you mean by just copy Your GoogleRefreshToken from auth.json to new version

**Comment by Nothingst** [comment]
@Sad0wl hey man, would you tell me how to fix it?

**Comment by szychan** [comment]
@Nothingst I meant if someone was already using bot in older version for example they can use token generated there and move it to new release to make it work . dont know how to resolve issue for newcomers :(

**Comment by lisiorro** [comment]
my code from this auth.json.old is so freaking long, dunno what to do with it

**Comment by miraclesuki** [comment]
The old version cannot work as well. This is because the GoogleToken can not be retrieved correctly. You need to manually find the device code and paste to google device for authentication at this moment.  I've tried to use my previous GoogleToken and it works well. Maybe there is a fix on how to get the device code later on.

**Comment by InnerFire** [comment]
@miraclesuki How to find device code bro?

**Comment by Sad0wl** [comment]
i copy from old "auth.json" file, "GoogleRefreshToken", there wold be long link and past it to new "auth.json", or you can copy just "auth.json" file to new location

**Comment by lsf00txtp009** [comment]
@miraclesuki  do you know how to find the device code ?

**Comment by lisiorro** [comment]
Oh, it worked, thanks

**Comment by Nothingst** [comment]
@lisiorro what did u do?

**Comment by lisiorro** [comment]
just copied the "GoogleRefreshToken" from auth.json.old to auth.json

**Comment by baggiminsk** [comment]
"GoogleRefreshToken": null,

**Comment by Nothingst** [comment]
@lisiorro  where is auth.json.old  ? I only saw the auth.json

**Comment by lisiorro** [comment]
I got it from yesterday, if you dont have it, just wait, youre not able to do anything on your own.

**Comment by Nothingst** [comment]
@lisiorro  could u send to me?

**Comment by hyreduki** [comment]
or copy the code from an older release (GoogleAuth.ini) and paste it in auth.json.
"GoogleRefreshToken": ... => don't forget the " "

**Comment by rizardhis** [comment]
wow it work, now does someone know how to make it not 'auto-update' the google auth code while we open the program??

**Comment by Ryuzaki-L** [comment]
so how do i fix it? i have the same error with no google code

**Comment by aanjinx** [comment]
@lisiorro How do we fix it dude? thanks before

**Comment by lisiorro** [comment]
You can't if you dont have the old auth.json.

**Comment by Nomaan12345** [comment]
it works now ur awesome #hyreduki

**Comment by GammaV** [comment]
Just copy Google Refresh Token from old version to /Config/auth.json. It's working fine.
Ex: "GoogleRefreshToken": "1/mxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

**Comment by kousik93** [comment]
Tried getting auth token using the existing ClientId. Google says client is invalid. So the API creator must have deleted his credentials. Either you get a previously issued token in old auth.json(will expire sometime in the future) or get your own credentials ([link](https://developers.google.com/identity/sign-in/devices)) and compile the project yourself and run. 
![invalid](https://cloud.githubusercontent.com/assets/3846847/17204758/2a26c6c8-545c-11e6-8f18-aac3e6f7c02b.png)

**Comment by xclusive707** [comment]
can someone explain how to get new token

**Comment by kousik93** [comment]
Follow directions here - https://developers.google.com/identity/sign-in/devices

**Comment by aanjinx** [comment]
@Nomaan12345 dude how did u do it?

**Comment by antfuentes87** [comment]
@kousik93 I did get a new ClientId / ClientSecret and it allows me to use the Device Code, but then it errors: 

[02:44:56] (INFO) Exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' was thrown. from test

Not sure why it is saying Access Token Expired? Any ideas?

**Comment by kousik93** [comment]
@antfuentes87 Visual Studio has been installing for the past 3 hours. Will try it out once i get it up.

**Comment by Ryuzaki-L** [comment]
can someone link the release they used to pull the old auth code?

**Comment by Nomaan12345** [comment]
i previously used pokemon go rocket master api for example
(user drive where extracted the old bot)F:\Pokemon-Go-Rocket-API-master\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI.Console\bin\Debug\Configs this is the path file then doubleclick on googleauth file there u have it ur token code then u just have to follow these instructions
or copy the code from an older release (GoogleAuth.ini) and paste it in auth.json.
"GoogleRefreshToken": ... => don't forget the " "

**Comment by antfuentes87** [comment]
@kousik93 Damn three hours... crazy, mine installed less than 10 minutes. I sent you a email as well, you got Google Hangouts?

**Comment by the-spectator** [comment]
I am still getting this problem is @NecronomiconCoding is aware of this problem if yes do something man

**Comment by Nomaan12345** [comment]
just started getting this now 
![untitled](https://cloud.githubusercontent.com/assets/20672611/17207132/adc39cda-54d0-11e6-8ddc-7ce348ce616a.jpg)

**Comment by steffenbrem** [comment]
the google authentication process is just broken, simply use an older refresh token or fetch yourself a new one through google APIs...

**Comment by userix** [comment]
Can you let us know how we could get our own refresh token?

**Comment by the-spectator** [comment]
@steffenbrem  Just tell me how to fetch new one............

**Comment by rolandthewise** [comment]
![image](https://cloud.githubusercontent.com/assets/20701411/17210011/c1ed1e30-54f2-11e6-95a1-c32e8c635fad.png)
should recompile the file clear this problem?

**Comment by Dasdanet** [comment]
I created a new Google OAuth 2.0 client, wrote the secret and client id into code but still the same problem occurs.

**Comment by gearkill** [comment]
error in Newtonsoft.Json.dll or something related to it hope someone can solve
