### ISSUE TITLE
Next level and XP wrong for 39 to 40

### ISSUE THREAD

**Issue by CL24** [NecronomiconCoding/NecroBot#1127]
![image](https://cloud.githubusercontent.com/assets/20602322/17202121/8ab39e4a-5497-11e6-8b69-e1b7bef2ab2a.png)

I'm at 120.000/5.000.000

**Comment by tw88** [comment]
ot: What xp/h do you have?

**Comment by ChenGaoYuan** [comment]
Crazy! Lv 39......
