### ISSUE TITLE
[Feature Request] - Set Radius to check pokestops within

### ISSUE THREAD

**Issue by emwedk** [NecronomiconCoding/NecroBot#1129]
It seems to me that the bot just checks if there is a pokestop within the set distance and by theory it could end up 100km's away if left long enough - to farm Habitats it could be nice to be able to set a Radius to check pokestops within from the set LOC

**Comment by Ilses** [comment]
That's not how it works. You have a radius from the origin, outside of which pokestops are ignored. Please close.
