### ISSUE TITLE
[Question]how to stay with Lure poke stops

### ISSUE THREAD

**Issue by youxihuafeng** [NecronomiconCoding/NecroBot#1133]
Is there any way to set up conif that I can stay nearby poke stops without moving?

**Comment by hilycker** [comment]
Not at the moment. Anyway know that spawning time for lured pokémon while standing still is longer than while moving. Can't find anymore a link to a snippet of game code saying this

**Comment by ChenGaoYuan** [comment]
Good idea!

**Comment by TaylorZaneKirk** [comment]
Glad I searched before posting this as a suggestion! I second the motion for this to be a potential toggle command within the config file.  @hilycker  I heard the same thing, except as I understood it that only pertained to Incense. However if it is true, I imagine it would be possible to have the bot circle the lured PokeStop (probably would be easier to move in a 'square' around the lat/lon of the Stop, I would imagine)
