### ISSUE TITLE
Couldnt copy to clipboard, do it manually

### ISSUE THREAD

**Issue by RoSeawolf** [NecronomiconCoding/NecroBot#1135]
I got this issue

Couldnt copy to clipboard, do it manually
GOto:   & enter

what i can do ?

**Comment by proesd** [comment]
already have this issues #1126 #1117

**Comment by MrKubic** [comment]
So as someone else has found a solution by reading I did not see anything?

**Comment by Ilses** [comment]
close this, as it's a duplicate
