### ISSUE TITLE
[Feature Request] KeepPokemonsThatCanEvolve only if Pokèmon is on PokemonsToEvolve list

### ISSUE THREAD

**Issue by bignuts** [NecronomiconCoding/NecroBot#1137]
As title already says pokemon should be kept to evolve only if on Pokemon to evolve list!

**Comment by ChenGaoYuan** [comment]
I don’t think so！

**Comment by lnmtriet93** [comment]
I think it will be cool if we have an CatchOnlyPokemons list instead of keeping pokemon in evolve list

**Comment by bignuts** [comment]
not sure why u need a catchonlypokemon list, there is already pokemon filter list, just add there what u don't want to catch and u have the opposite logic of catchonly list..
My suggestion is for optimizing mass evolve under lucky egg, is it better to evolve 10 pidgey if u have 125 candy, and not 6 pidgeotto, that's why i don't want to keep pidgeotto over pidgey for that purpose.

**Comment by lnmtriet93** [comment]
About catchonlypokemon list, it seems easy for me to just add 10 pokemons instead of 141 others in notcatch list bro ^^
About your idea, I think you can do that by setting EvolveAllPokemonWithEnoughCandy to true and EvolveAllPokemonAboveIv to false, then put pidgey (not pidgeotto) to evolve list

**Comment by bignuts** [comment]
this is exactly my setting, but i keep getting pokemon like pidgeotto, the bot see enought candy to evolve it and keep it, then it does not evolve, but just occupy bag space
