### ISSUE TITLE
leaving 2 of the same kind

### ISSUE THREAD

**Issue by mich3lam** [NecronomiconCoding/NecroBot#1138]
for some reason when trasnfering it leaves 2 of every kind, the IV , CP exceptions should not effect these and I have the keepminduplicate=1 .. very weird. any ideas?

**Comment by ProfessorPoke** [comment]
Post your complete config?

**Comment by ChenGaoYuan** [comment]
It should work...

**Comment by mich3lam** [comment]
http://puu.sh/qhbMZ/20a3c094a1.json

This is my config.. I am always left with 2 of the same kind instead of 1

**Comment by vanillasteel** [comment]
are their cps above 1000? over cp over IP stop it from removing

**Comment by mich3lam** [comment]
@vanillasteel nop.. they are low cps
