### ISSUE TITLE
how to use the Translations file to change the language?

### ISSUE THREAD

**Issue by MiaoMFoo** [NecronomiconCoding/NecroBot#1140]
TKS..

**Comment by cqhtyi** [comment]
open folder：NecroBot\Release\Config\translations\
edit: NecroBot\Release\Config\config.json
  "TranslationLanguageCode": "en",
  "TranslationLanguageCode": "zh_CN",

**Comment by MiaoMFoo** [comment]
@cqhtyi  thank u very much!!!
