### ISSUE TITLE
needs best config . thanks

### ISSUE THREAD

**Issue by brama23** [NecronomiconCoding/NecroBot#1142]
master excuse me , I'm a beginner, I need a good config for my pogo bots . thanks :+1:

**Comment by Eduardox** [comment]
Exactly what do you need?

**Comment by brama23** [comment]
do you think best and right

**Comment by Dreamslol** [comment]
GitHub is not a forum, stop using it like that ffs.

**Comment by brama23** [comment]
sorry, I need config is right because I am very beginner .

The latter , sorry

**Comment by hakkotsu** [comment]
go to discord chat and ask there

**Comment by Ilses** [comment]
close this issue and go to #helpme

**Comment by lotusJDM** [comment]
Discord chat invitation link not working for me. Says its expired or doesn't exist.

Does anyone have a new one?
