### ISSUE TITLE
Exp grow too fast..

### ISSUE THREAD

**Issue by ChenGaoYuan** [NecronomiconCoding/NecroBot#1143]
Exp grow too fast..Is't OK？If our account will be locked?

**Comment by goodwind** [comment]
May be locked, may be not
At this time the only punishment is  softban - when you travel to fast from one end of the World to another, server making you unable to catch pokemons and gut pokestops for some time (from 30 minutes to 3 hours AFAIK)

**Comment by hakkotsu** [comment]
You are using bot = violating EULA = permanent ban sooner or later
If you don't want to get banned - don't cheat

**Comment by Ilses** [comment]
This post is not an issue, close this.

**Comment by goodwind** [comment]
@Ilses unfortunatelly, most of issues in this repo are not issues at all =(
