### ISSUE TITLE
run bot and nox at the same time

### ISSUE THREAD

**Issue by kayrol** [NecronomiconCoding/NecroBot#1144]
can i run bot and open nox player at the same time with same account? is that consider as multilogin? thanks.

**Comment by AdrianAlcGon** [comment]
A friend had the same idea and had a ban of more or less two hours. I think two authentications are generated, one for the app and another by the Nox and imagine that Google detects it as a "hack".

**Comment by d3s4st3r95** [comment]
For me it works all time.
Just turn off the location.

**Comment by hakkotsu** [comment]
You will get softbanned.

**Comment by Ilses** [comment]
This post is not an issue, close this.

**Comment by Niahm** [comment]
Disable GPS in nox, works fine.
