### ISSUE TITLE
[Suggestions] Resizable Window

### ISSUE THREAD

**Issue by spot88** [NecronomiconCoding/NecroBot#1148]
* Resizable Window under the release version. Now it's kinda small and can't do anything about it. 
* Add a delay before config files are generated and you go right into the bot. So people have the chance to read the text before they find out the bot is starting and they have not changed the cords. 

Something like: 
** Generating config files, remember default location is Central Park, cancel after generating files if you wan't to edit cordes **
** Delay 5 sec ** 
** Config files generated, starting bot ** 
** Delay 2 sec **

**Comment by hakkotsu** [comment]
- Your windows is not resizable because you are using cmd.exe. Try to install http://cmder.net/ and run bot in it
- Already implemented for first run and there is PR for other cases, see #1114

**Comment by spot88** [comment]
Thanks, awesome. Will try it out
