### ISSUE TITLE
possible to run on Linux

### ISSUE THREAD

**Issue by LoloLaurentiu** [NecronomiconCoding/NecroBot#1149]
hello
is it possible to make it run on linux ?
when I try to run it I get this error

mono PoGo.NecroBot.CLI.exe
Unhandled Exception:
System.MissingFieldException: Field 'PokemonGo.RocketAPI.Client.Login' not found.
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingFieldException: Field 'PokemonGo.RocketAPI.Client.Login' not found.

**Comment by txt3rob** [comment]
try mono to see if that works

**Comment by mosimo** [comment]
Did you do a full git clone with --recursive to download the submodules for the RocketAPI?

**Comment by LoloLaurentiu** [comment]
@mosimo no. How do I do that ?

**Comment by LoloLaurentiu** [comment]
can anyone help me with this error ?
