### ISSUE TITLE
Temporary Fix to Clipboard Problem

### ISSUE THREAD

**Issue by ALEX-PR** [NecronomiconCoding/NecroBot#1154]
For all of you getting the "couldn't copy to clipboard, do it manually error"  the way I fixed it was by copying my refresh token from a previous version of the pokemon go rocket api. The google refresh token can be found inside the google auth file at: PokemonGo.RocketAPI.Console\bin\Debug\Configs\ and should be pasted into the auth file at: PoGo.NecroBot.CLI\bin\Debug\Config\  Also the google refresh token should be written with quotation marks example "1addfkcjfokd"

**Comment by GamberroIbz** [comment]
So... If i downloaded just few minuts ago, and i dont have a google refresh token, is any way to generate this code?

**Comment by riven77** [comment]
![problem](https://cloud.githubusercontent.com/assets/20698746/17206203/e18b6e34-54ae-11e6-9098-cf291ce43e82.png)

**Comment by riven77** [comment]
: PoGo.NecroBot.CLI\bin\Debug\Config cant be found in the release.zip

**Comment by rokuon** [comment]
so, the console said that it copied the code to clipboard but when I ctrl+v or right click+paste theres no such thing as code in my current clipboard. I have a google refresh token from other type of bot, but I dont have the so folder called Config and file named auth. What should I do [http://prntscr.com/byivys](sir?[http://prntscr.com/byiv4v](url))

**Comment by ALEX-PR** [comment]
That's really weird. Since your device code was copied to the clipboard you should be able to paste it into google.com/device. I honestly don't know what to tell you.

**Comment by riven77** [comment]
okey for my case the code isnt even copied  and i dont see it

**Comment by ALEX-PR** [comment]
Riven I had same issue. I don't know of a way to fix it without the google token. I am pretty sure this will be fixed soon by the dev
