### ISSUE TITLE
"DelayBetweenPokemonCatch" Not being honoured

### ISSUE THREAD

**Issue by Oniftw** [NecronomiconCoding/NecroBot#1155]
Hi all

Sorry if this has been reported before i searched but didn't see that it had.

In my config i have this setting set as

"DelayBetweenPokemonCatch": 46512,

however in my logs im seeing catches that do not honour that time frame ( 46.5ish seconds )

EG.
[17:16:40] (CatchSuccess) | (Normal) Poliwag Lvl: 6 CP: (119/131) IV: 64.00%
[17:16:42] Looking for incense pokemon..
[17:16:43] Looking for pokemon..
[17:16:47] (CatchSuccess) | (Normal) Clefairy Lvl: 7 CP: (206/234) IV: 43.00% 

I have more examples but figure this is enough, can others confirm?

**Comment by dreamenginestudio** [comment]
Read through the source code. I think this mean the delay between the SAME POKEMON Catch.

**Comment by uhnduhrew** [comment]
edit the response between catches and your travel per KM/H
