### ISSUE TITLE
KeepMinDuplicatePokemon cann't working

### ISSUE THREAD

**Issue by letuananh035** [NecronomiconCoding/NecroBot#1156]
Set 1 but keep 2 (Cp < 1500 and IVs <95 config)

**Comment by letuananh035** [comment]
please fix

**Comment by Khayalan** [comment]
Please fix :+1:

**Comment by frees11** [comment]
For me it doesn't working at all. I have like 20 pidgeys in my backpack, here is my config


[config.txt](https://github.com/NecronomiconCoding/NecroBot/files/388385/config.txt)

**Comment by Victorsouza02** [comment]
Please fix
