### ISSUE TITLE
Is Bot dead now?? It was good while it lasted :)

### ISSUE THREAD

**Issue by Iluveulongtime** [NecronomiconCoding/NecroBot#1158]

**Comment by Dreamslol** [comment]
are you dumb?

**Comment by Eduardox** [comment]
Bot is fine, PTC servers are not.
http://ispokemongodownornot.com/

**Comment by Gratataa** [comment]
spamming? you seem upset

**Comment by Sylencer90** [comment]
Mine seems to be broken too, using google auth.

**Comment by MatkeMatke** [comment]
servers are fine, bot however logged me out and won't log back in

**Comment by holywend** [comment]
yeah, can not login with google account. but login from devices are okay

**Comment by thekjohn** [comment]
I can't even get a DeviceToken from google :(

**Comment by Sylencer90** [comment]
Ban wave :p?

**Comment by BSwazZ** [comment]
Bot is dead :8ball:

**Comment by adriantheplug** [comment]
So the google servers are up, I can log in from a device but I can't log in from the bot.

**Comment by yottabytez** [comment]
google logins are down right now

**Comment by yottabytez** [comment]
the bot isn't dead

**Comment by rokuon** [comment]
I can login from nox not from bot Ptc btw

**Comment by Eduardox** [comment]
Server are unstable/offline, chill out this isnt a bot issue lol
https://go.jooas.com/
http://ispokemongodownornot.com/

**Comment by H3RB4LS** [comment]
Calm down people. It just can't parse the hostname. https://gyazo.com/7d94381faad1089a2de8ae1d74351758

**Comment by themanwhocodes** [comment]
google login down as well?

**Comment by BSwazZ** [comment]
![gg](https://cloud.githubusercontent.com/assets/20690071/17207004/c53b2ee6-54b2-11e6-962b-96739710e0c0.PNG)

**Comment by MRLZRD** [comment]
![image](https://cloud.githubusercontent.com/assets/15700481/17207079/199879a8-54b3-11e6-8381-d641b954158c.png)
Its seems to be cool :D

**Comment by thekjohn** [comment]
**GoogleLogin.GetDeviceCode() returns an empty DeviceCodeModel, so there is no verification url inside**

**Comment by H3RB4LS** [comment]
It'll be resolved when login is back. Just chill out. Both Ptc and google are down atm.
http://ispokemongodownornot.com/
http://ispokemongodownornot.com/
http://ispokemongodownornot.com/

**Comment by holywend** [comment]
but login from device are okay.

**Comment by rokuon** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20699194/17207146/54e7f482-54dd-11e6-8e4d-6c82fabdd007.png)

**Comment by Eduardox** [comment]
PTC servers are more likely to go offline (taking incount that you can make mass acounts with no captchas), this ones are OFFLINE
Google servers are less likely to go offline because its harder to mass account and these are UNSTABLE (yeah, you are loggin in from device but youll eventually get kicked)
So no, we are not banned. And no, being able to log in from devices does not mean anything. For more information search "unstable" definition on google lol. 
https://go.jooas.com/
http://ispokemongodownornot.com/
https://go.jooas.com/
http://ispokemongodownornot.com/

**Comment by H3RB4LS** [comment]
Working again for me :D

**Comment by MRLZRD** [comment]
Its working guys!

**Comment by yottabytez** [comment]
...And the servers crashed again.

**Comment by H3RB4LS** [comment]
My one account is on, but the other can't make it quite yet lol. Servers being finicky. In due time

**Comment by yottabytez** [comment]
It's up-down right now for me. I'm watching server status on two devices and one is up, the other down.

**Comment by bjens39** [comment]
im new to all this, so i started the bot and got the unable to copy code error, is that due to the servers or my end? also how long are the servers normally up?

**Comment by Eduardox** [comment]
@bjens39 When servers get up, if you still get an error check #1152

**Comment by RZX6R** [comment]
Down again lol

**Comment by Ilses** [comment]
Bot isn't dead. Close this issue.

**Comment by FeiFogota** [comment]
It's working now

**Comment by thekjohn** [comment]
I still don't get a device code :(
