### ISSUE TITLE
Autoupdate clears config

### ISSUE THREAD

**Issue by fazzertron** [NecronomiconCoding/NecroBot#1160]
Autoupdating from 0.1.8 to 0.1.9 deletes the config files for 0.1.8, so they have to be redone. Is there a way to avoid this?

**Comment by sp1ti** [comment]
That's not entirely correct. It just renames the old one to .bak. Wouldn't be too hard to implement a XML update for common/unlikely to change attributes from the old one though.

**Comment by fazzertron** [comment]
Fair comment. For the amount that changes, it seems strange to create a whole new config though. Even just a check to see what JSON keys are missing and then adding them to the config would work?

**Comment by sp1ti** [comment]
Oh right, it's not an XML anymore. Should be fairly easy to do yes.

**Comment by tataMuminka** [comment]
Hi,

can you comment where .bak file could be found? It seems .bak is not inside /bin/Debug/Config at least in my case. Thanks in advance for that however I'm really interested in that feature :+1:

**Comment by fazzertron** [comment]
It's not actually a .bak file, but a .old instead.

**Comment by padmanek** [comment]
Omg. The old config was renamed and it's still in the folder. It simply had .old added to the end. Just edit it with notepad and you have your older config. Why do people make issues for stuff like this. It's not an issue. It's intended to work like this. The bot is under heavy development. Old config might not be compatible with the new version.

**Comment by fazzertron** [comment]
It's an issue because, if the auto-updater is enabled, suddenly your bot logs in with the default coordinates and you get soft-banned. Go figure.
