### ISSUE TITLE
0.19 Compiled Release, Evolve Issue On GPX Path.

### ISSUE THREAD

**Issue by Aristrine** [NecronomiconCoding/NecroBot#1161]
**Hi , i just wanted to ask,  I'm not sure if it's due to my Incompetence, but does the 0.19 compiled release still evolve pokemon when it is on a designated path by GPX? I had sufficient candy, yet it only evolved several pokemon at the start of the run, and nothing after that.**

**Comment by Shroomzie** [comment]
Can you tell us what settings you use for these?

`"UseLuckyEggsWhileEvolving": ?
  "UsePokemonToNotCatchFilter": ?
"KeepPokemonsThatCanEvolve": ?
"EvolveAllPokemonAboveIv": ?
  "EvolveAllPokemonWithEnoughCandy": ?`

Have you run the program in normal pathing mode to tell if it even has anything to do with GPX path?

**Comment by Gosurisor** [comment]
I have the same problem, bot is not evolving.
Config: 
"UseLuckyEggsWhileEvolving": true,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": true,
"KeepPokemonsThatCanEvolve": true,

**Comment by Shroomzie** [comment]
Right off the bat im thinking you dont have enough candies. Prolly due to this 

`"KeepPokemonsThatCanEvolve": true,`

**Comment by Aristrine** [comment]
"UseLuckyEggsWhileEvolving": false
"EvolveAboveIvValue": 95.0
"KeepPokemonsThatCanEvolve": false
"EvolveAllPokemonAboveIv": false
"EvolveAllPokemonWithEnoughCandy": true

I tried it while GTX Path was False. It shows signs of evolution even if it's slow.

However, for GTX Path=True, Pidgey candies were more than 50, yet there's no sign of Evolution.
