### ISSUE TITLE
Its possible to run it on MAC?

### ISSUE THREAD

**Issue by GamberroIbz** [NecronomiconCoding/NecroBot#1163]
Hello, i was looking for some issue about trying to work with mac.
Its possible to execute the bot in a mac (OS X)
Thanks

**Comment by rizardhis** [comment]
use bootcamp / virtual, and it works

**Comment by HZH1907** [comment]
yes
you can use crossover to run it. 
bootcamp &virtual is useless @rizardhis 
 it make you mac run frantically,getting hotter and hotter....

**Comment by goodwind** [comment]
I`m using parallels desktop for this

**Comment by HZH1907** [comment]
@goodwind some thing like wine,wineskin,playonmac and crossover is better
it make windows application run in your mac...
but wine,wineskin,playonmac have some bugs, can't install .net 4.0....
crossover work fine

**Comment by goodwind** [comment]
@HZH1907 I`m using parallels for other tasks too (Solid Works, for example). In coherence mode windows apps runs perfect. but crossover would be better for small apps like this but, I agree with you

**Comment by VanStorm** [comment]
You could also install windows into a virtual machine that you could create with virtualbox.
But i'd advise you to try crossover or playonmac first since it's a better solution than just creating a virtual machine for a small bot :laughing:

**Comment by bmsimons** [comment]
Try out the open source Mono .NET Framework. (Available for Windows, Mac OS and Linux)
Might also work for Linux.
