### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by oOFIREZOo** [NecronomiconCoding/NecroBot#1165]
Ausnahmefehler: Newtonsoft.Json.JsonReaderException: Error parsing comment. Expe
cted: *, got N. Path 'GoogleRefreshToken', line 3, position 26.
   bei Newtonsoft.Json.JsonTextReader.ParseComment(Boolean setToken)
   bei Newtonsoft.Json.JsonTextReader.ParsePostValue()
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject
(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty
member, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonR
eader reader, Object target)
   bei Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object
 target)
   bei Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, J
sonSerializerSettings settings)
   bei PoGo.NecroBot.CLI.AuthSettings.Load(String path) in C:\Users\tvgfx\Docume
nts\Pokemon Go Bot\PoGo.NecroBot.Logic\Settings.cs:Zeile 41.
   bei PoGo.NecroBot.CLI.GlobalSettings.Load(String path) in C:\Users\tvgfx\Docu
ments\Pokemon Go Bot\PoGo.NecroBot.Logic\Settings.cs:Zeile 278.
   bei PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\tvgfx\Documents
\Pokemon Go Bot\PoGo.NecroBot.CLI\Program.cs:Zeile 47.

get this everytime i want to start the bot.. what can i do?

**Comment by Kalashnikitty** [comment]
read the fkn other 20000000 issues - SERVERS ARE DOWN

**Comment by chewbyte** [comment]
Thanks for that wonderfully descriptive title.

**Comment by oOFIREZOo** [comment]
@ Kalashnikitty If the servers are down: why i can login with my phone? lol...

@chewbyte: your answere will help me alot...
