### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by mariiusx** [NecronomiconCoding/NecroBot#1167]
I keep getting this error when trying to launch up the bot. Any help?
http://imgur.com/DmLcjyL

**Comment by cpasmoi** [comment]
read first line

**Comment by freepr0xy** [comment]
https://go.jooas.com/

**Comment by wellon** [comment]
change from **,** to **.**

**Comment by anonemon** [comment]
If you can't seem to find the typo, why don't you paste the config instead of the error?

**Comment by mariiusx** [comment]
Config - http://imgur.com/a/iu0FC

**Comment by Shroomzie** [comment]
This is not a issue with this program, please close the thread. 200 issues and i bet you half are from scrubs. Who will be next.

**Comment by cpasmoi** [comment]
can't you 'both shroomzie and marrius) even read the FIRST line of the LOG ?!

and in wellon told you to change the , by . !!
