### ISSUE TITLE
Couldnt copy to clipboard

### ISSUE THREAD

**Issue by Xalk444** [NecronomiconCoding/NecroBot#1168]
![log](https://cloud.githubusercontent.com/assets/20630520/17207772/bc99f950-54be-11e6-99d1-8089ed4a5a3b.jpg)
![google](https://cloud.githubusercontent.com/assets/20630520/17207785/c483812c-54be-11e6-89f7-35863b27cacb.jpg)
What should I do?

**Comment by mpl1337** [comment]
Server DOwn

**Comment by Xalk444** [comment]
Oh sorry,i noticed

**Comment by bennextmitchell** [comment]
Servers are up now? 

http://ispokemongodownornot.com/

**Comment by bennextmitchell** [comment]
wait nevermind they just fell and died

**Comment by myo** [comment]
its an issue with google auth not pokego servers

**Comment by myo** [comment]
a fix here: https://github.com/NecronomiconCoding/NecroBot/issues/1169

**Comment by artganify** [comment]
#1169 is not a fix. Just a possible workaround. #1168 is duplicate, please close.

**Comment by Th3C0D3R** [comment]
[https://cdn.discordapp.com/attachments/206065340579315712/208159243495276555/unknown.png](url)
This is why

**Comment by myo** [comment]
@artganify any idea on the safety of using ur own google api creds? weren't we using niantic's before? lol

**Comment by Aqua3** [comment]
![image](https://cloud.githubusercontent.com/assets/20701126/17209469/18637a68-54b5-11e6-9cb4-88cbab49bf52.png)
