### ISSUE TITLE
Changing Lat and Long does nothing.

### ISSUE THREAD

**Issue by Tropicocity** [NecronomiconCoding/NecroBot#117]
Currently, After first running the bot and inputting my Lat and Long (not mine specifically but a location in the same city), the bot runs and works fine.

Any subsequent runs of the bot, regardless of what I enter in the DefaultLatitude/Longitude fields, still seems to start me back at my original location.

Wouldn't mind this too much as my chosen location seems to be full of pokemon, but it seems a bit too suspect when the bot stops x hundred metres away from the start, then is all of a sudden out of GPS contact, and restarts back at the first location (it seems like I've just teleported back in time) and to avoid this I'm currently waiting 5-10 minutes between each start.

Is there any way to update the Lat/Long coords without having to redownload the entire bot folder and re-register the 'device' with my google?

Thanks.

**Comment by salvaracer** [comment]
He stores the last position and takes it again.

**Comment by RoachxD** [comment]
I think he means at the point when it restarts (?)

**Comment by beautivile** [comment]
To fix this without redownloading, change the coordinates in the PokemonGo.RocketAPI.Console\bin\Debug\Coords file, seems to not being updated on recompile

**Comment by MrTriForce** [comment]
I have the same issue. I have modified the Lat and Long and it still remains the default instead of my chosen destination.

**Comment by Daylend** [comment]
Clear the coords.txt file.

**Comment by MrTriForce** [comment]
Where can I find the file?

**Comment by Daylend** [comment]
Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\bin\Debug\Coords.txt
