### ISSUE TITLE
Malware-Gen issue

### ISSUE THREAD

**Issue by Brovoz** [NecronomiconCoding/NecroBot#1170]
Getting up malware-gen when I try to download this release and my avast antivirus blocks it.

**Comment by myo** [comment]
its opensource compile urself and add to whitelist

**Comment by Shroomzie** [comment]
Uusally takes about 30 days for a AV company to whitelist a program. Its going to be pretty hard as this is changing daily.

**Comment by bmsimons** [comment]
I'm glad that I don't have Avast anymore on my computer....

It's very common that Avast detects freshly compiled C# code as malware.

The best option would be to uninstall that piece of shit virus scanner just like I did!

**Comment by Aristrine** [comment]
Put the file in the Exception list for now.

**Comment by Brovoz** [comment]
Fixed :) thanks everyone:)
