### ISSUE TITLE
Missing translation file

### ISSUE THREAD

**Issue by Zierk59** [NecronomiconCoding/NecroBot#1171]
I have "translation missing" warnings, even though I have this files in config/translations...

3 lines from logs:
[11:40:40] Translation for GotUpToDateVersion is missing
[11:40:40] Translation for LoggingIn is missing
[11:40:42] Translation for WelcomeWarning is missing

There is my config
http://pastebin.com/jZWk12VM

**Comment by emoisback** [comment]
Open config / translations delete every file inside translation folder then try to open bot again..

**Comment by Zierk59** [comment]
Works, thank you!
