### ISSUE TITLE
Google Token Problem

### ISSUE THREAD

**Issue by Joesilvpb4** [NecronomiconCoding/NecroBot#1178]
The app won't let me login, says enter manually, tried pasting "GoogleRefreshToken" but to no success has anyone found a solution to this?

**Comment by marmil** [comment]
Youre brain won't let you think, it ignores 15 other issues posted before. Try a book to solve this problem!

**Comment by Shroomzie** [comment]
Close the issue. you are the 20th person to post one like this. Why didn't you check first!!!

**Comment by Joesilvpb4** [comment]
Other threads did not provide a solution, can you point me in the right direction?

**Comment by GamberroIbz** [comment]
Maybe because atm there's no solution for ppl who dont have the google refresh token?

**Comment by Shroomzie** [comment]
@Joesilvpb4 Yolu're trolling right? or did you just wake up? Either way, we are trying to tell you that its a bad idea to duplicate post issues. it tends to piss the people off that are doing all the work for your!

Would you like to read through all this sht daily? No? I didn't think so!
Joesilvpb4 said quite clearly. "Try a book to solve this problem!"

**Comment by Joesilvpb4** [comment]
Is there a way to manually go into some file and input the username and password?

**Comment by Joesilvpb4** [comment]
Which book would I read?  Sorry if I seem like I'm trolling, I'm just trying to navigate these files without much background beforehand.  I just want to get this to work

**Comment by Shroomzie** [comment]
A book that takes time, so you come back and its working...

**Comment by Kalashnikitty** [comment]
@ #1169 

they are working on a solution. 

/close pls

**Comment by Bogenschuetze** [comment]
Is it that hard to read through the wiki?......
https://github.com/NecronomiconCoding/NecroBot/wiki/Compiled-Releases

**Comment by Joesilvpb4** [comment]
Ok I see, sorry guys. Ill wait

**Comment by Mattmdn** [comment]
man the rudeness is really uncalled for, all this back and forth when you could have just answered directly.

**Comment by skynetken** [comment]
Had to signup just to give my 2cents. God damn it man. ITS HAPPENING TO ALL OF US! 

Please read another issues,
