### ISSUE TITLE
[Suggestion] [TR] Turkish Language

### ISSUE THREAD

**Issue by Mormia** [NecronomiconCoding/NecroBot#1179]
{
  "TranslationStrings": [
    {
      "Key": "pokeball",
      "Value": "PokeBall"
    },
    {
      "Key": "greatPokeball",
      "Value": "GreatBall"
    },
    {
      "Key": "ultraPokeball",
      "Value": "UltraBall"
    },
    {
      "Key": "masterPokeball",
      "Value": "MasterBall"
    },
    {
      "Key": "wrongAuthType",
      "Value": "Config.json icerisinde bilinmeyen kimlik dogrulama!"
    },
    {
      "Key": "farmPokestopsOutsideRadius",
      "Value": "Bolgesel alanin disindasiniz! Yeniden hazirlaniyor ({0}m mesafe) 5 saniye icerisinde. Coords.ini icerisindeki ayarlariniz dogru mu?"
    },
    {
      "Key": "farmPokestopsNoUsableFound",
      "Value": "Bu alanda pokestop bulunamadi. Mesafeyi kisa mi girdiniz?"
    },
    {
      "Key": "eventFortUsed",
      "Value": "XP: {0}, Mucevher: {1}, Items: {2}"
    },
    {
      "Key": "eventFortFailed",
      "Value": "Toplama tamamlanamadi, muhtemelen softban yediniz. Yeniden deneniyor: {0}/40"
    },
    {
      "Key": "eventFortTargeted",
      "Value": "{0} , ({1}m) icerisindedir."
    },
    {
      "Key": "eventProfileLogin",
      "Value": "{0} Olarak oynaniyor"
    },
    {
      "Key": "eventUsedLuckyEgg",
      "Value": "Kullanilan Lucky Egg, kalan: {0}"
    },
    {
      "Key": "eventPokemonEvolvedSuccess",
      "Value": "{0} Tamamlandi. Kazanilan {1}xp"
    },
    {
      "Key": "eventPokemonEvolvedFailed",
      "Value": "Basarisiz {0}. Sonucunda : {1},  evolve islemi durduruluyor {2}"
    },
    {
      "Key": "eventPokemonTransferred",
      "Value": "{0}\t- CP: {1}  IV: {2}%   [En iyi CP: {3}  IV: {4}%] (Seker: {5})"
    },
    {
      "Key": "eventItemRecycled",
      "Value": "{0}x {1} kadar temizlendi."
    },
    {
      "Key": "eventPokemonCapture",
      "Value": "({0}) | ({1}) {2} Lvl: {3} CP: ({4}/{5}) IV: {6}% | Sans: {7}% | {8}m mesafe | beraberinde {9} ({10} kaldi). | {11}"
    },
    {
      "Key": "eventNoPokeballs",
      "Value": "Hic poketopunuz kalmamamis :( - Kacirdik! {0} CP'ye sahip. {1}"
    },
    {
      "Key": "catchStatusAttempt",
      "Value": "{0} Yakalama #{1} denendi"
    },
    {
      "Key": "catchStatus",
      "Value": "{0}"
    },
    {
      "Key": "candies",
      "Value": "Seker: {0}"
    },
    {
      "Key": "unhandledGpxData",
      "Value": "GPX dosyasi icerisinde islenmeyen veri bulunuyor. Atlanmaya calisiliyor."
    },
    {
      "Key": "displayHighestsHeader",
      "Value": "Pokemonlar"
    },
    {
      "Key": "commonWordPerfect",
      "Value": "Oraninda mukemmel!"
    },
    {
      "Key": "commonWordName",
      "Value": "ADI"
    },
    {
      "Key": "displayHighestsCpHeader",
      "Value": "En yuksek CP'ye sahip olanlar:"
    },
    {
      "Key": "displayHighestsPerfectHeader",
      "Value": "En mukemmel olanlar:"
    },
    {
      "Key": "displayHighestsLevelHeader",
      "Value": "En yuksek level'e sahip olanlar:"
    },
    {
      "Key": "welcomeWarning",
      "Value": "Kordinatlardan emin olunuz! (Lat & Lng) . Emin degilseniz, programdan cikin! Lat: {0} Lng: {1}"
    },
    {
      "Key": "incubatorPuttingEgg",
      "Value": "Incubator icerisinde bulunan yumurta'nin: {0:0.00}km kaldi."
    },
    {
      "Key": "incubatorStatusUpdate",
      "Value": "Incubator durumun guncellendi: {0:0.00}km kaldi."
    }
  ]
}

**Comment by hsizadam** [comment]
nice one thanks for effor.
eline sağlık ortak mailin varsa verir misin bi kaç bişey sorucam sana :)

**Comment by CtrlAltTR** [comment]
_**`Herkes Bot kulanıyor mk. :/`**_

**Comment by Mormia** [comment]
Mail : ca0sleider77@hotmail.com
