### ISSUE TITLE
Error: No Google Login Code

### ISSUE THREAD

**Issue by ghost** [NecronomiconCoding/NecroBot#1181]
`[13:00:57] (UPDATE) Perfect! You already have the newest Version 0.1.9`
`[13:00:57] (INFO) Logging in using Google`
`[13:00:58] (ATTENTION) Opening Google Device page. Please paste the code using C
TRL+V`
**`[13:01:03] (ERROR) Couldnt copy to clipboard, do it manually`**
**`[13:01:03] (ERROR) Goto:  & enter`**

_How to fix this? Please help me!_
![necrobot-google-login-error-coundt-copy-to-clipboard-do-it-manually-goto enter](https://cloud.githubusercontent.com/assets/20700260/17209487/eae8bcc2-54c5-11e6-9f46-ab928c104fbc.jpg)

**Comment by Aqua3** [comment]
Its happening to a lot of us. I believe its being worked on.

**Comment by Happymeal1887** [comment]
realy man ?
read the other 20million issue

**Comment by proesd** [comment]
Close this thread, please .

**Comment by artganify** [comment]
If I read an issue like this one more fucking time.. :rage:

**Comment by MadLluks** [comment]
#1169 Another duplicate .... close this

**Comment by Kalashnikitty** [comment]
cancer to all of u

**Comment by Bogenschuetze** [comment]
I hope its just a question of time when they close the Issue Tab... 215 Issues and most are dumb or duplicates..

**Comment by Joesilvpb4** [comment]
I'm under the impression that there is no known fix until the next release is that correct?

**Comment by cirk0** [comment]
might be the huge influx of people after getting such publicity i.e. The Register

**Comment by artganify** [comment]
@Bogenschuetze Yeah the main problem is that most people just come here to use the bot to speed up their game, not knowing what and how github/git/an issue tracker or even development in general is or works. Makes it really hard to see legitimate issues. 

This and there are way too few developers with administrative permissions on the issue tracker to filter out stuff actively.

**Comment by godofrayer** [comment]
the Google Rocket API project is at limit. There will be no more new device id for a while for google account. Try login with your PTC account or create a new one

**Comment by Joesilvpb4** [comment]
I have an existing pokemon go account, how do I convert it to a ptc account?

**Comment by artganify** [comment]
@godofrayer Really? That's the main issue? We did it!!!

**Comment by cirk0** [comment]
@Joesilvpb4 same issue and realised the only workaround is to create a new account

**Comment by Joesilvpb4** [comment]
Is it possible to use an existing account with a ptc login?

**Comment by MadLluks** [comment]
@Joesilvpb4 If you are using a Google account you can't convert it into a ptc, you could (maybe) create a new ptc account but PTC server are down.
http://ispokemongodownornot.com/

**Comment by godofrayer** [comment]
@Joesilvpb4 no you cant. hm, another workaround is someone forked this project then using their new freshly created Google API Project. And use the project number and secret key that google provided. then build the project. now u have your own google rocket api

**Comment by PassiveModding** [comment]
okay heres a pretty easy fix

If you still have a previous version of the bot that you've used to log in with google

1. go to the config folder of the older version
2. open auth.json
3. navigate to line 3
4. "GoogleRefreshToken": "COPY THE TOKEN IN HERE",
5. after copying the token go the the auth.json file in your newer bot directory
6. open auth.json
7. replace null in this like:  "GoogleRefreshToken": null, 
   with "GoogleRefreshToken": "YOUR TOKEN",

This should now allow you to log into your account with no issue

**Comment by coremaya** [comment]
@godofrayer how to do that

**Comment by GamberroIbz** [comment]
@PassiveModding yeah, thats a good solution if u already have the refresh token.
But the question is, what about accounts thats never used bot, how u log in? u dont have the token for these accounts

**Comment by PassiveModding** [comment]
@GamberroIbz not sure if this'd work but just download an older version log in and then go from there and copy the token over

**Comment by ereorrman** [comment]
i read, from other thread say he can solve this problem in a min
hope you can collaborate with him 
he name is spegeli
