### ISSUE TITLE
"Unable to connect to the remote server" error

### ISSUE THREAD

**Issue by denordin** [NecronomiconCoding/NecroBot#1184]
I'm getting the following error when launching NecroBot compiled version:

> Initializing Rocket logger at time 2016. 07. 28. 12:34:58...
> [12:34:58] Perfect! You already have the newest Version 0.1.9
> [12:34:58] Logging in using Google
> [12:34:59] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network [2a00:1450:400d:807::200d]:443
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
>    at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at PokemonGo.RocketAPI.Helpers.HttpClientHelper.<PostFormEncodedAsync>d__0`1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Helpers\HttpClientHelper.cs:line 21
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at PokemonGo.RocketAPI.Login.GoogleLogin.<GetDeviceCode>d__5.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__4.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 39
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:line 33
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__8.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 43

I've been having this problem for days, redownloaded and set up NecroBot countless times, but I can't seem to figure out what's causing this. Please advise.

**Comment by civisek** [comment]
Same problem... :+1:

**Comment by 0x1911** [comment]
`System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network [2a00:1450:400d:807::200d]:443`

- Get proper internet
- Wait for pokemonGo Servers to come back up

**Comment by denordin** [comment]
Thanks for the very helpful response, but my net is perfectly fine, I can load up any site normally, and as I said I've been having this issue for days now, so this is not related to PTC currently being down.

**Comment by Niahm** [comment]
Check the format of GPX file if used, i had the same problem.

**Comment by civisek** [comment]
yeah, i just find out that problem was at my coordinates. I wrote 70 instead of -70 ...

**Comment by denordin** [comment]
I can't even log in, I'm unable to do anything. This error comes up right after fresh start. I select Google login, and the error comes up right after. Literally not able to do anything at all. Just an error loop trying to log in.
