### ISSUE TITLE
No Evolving and no Softbanlift in GPX Mode

### ISSUE THREAD

**Issue by Gosurisor** [NecronomiconCoding/NecroBot#1185]
Bot is not evolving and dont even trys to lift softbans when running in GPX Pathing Mode.
Evolve-Config:

"UseLuckyEggsWhileEvolving": true,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": true,
"KeepPokemonsThatCanEvolve": true,

**Comment by Happymeal1887** [comment]
Same settings same issue here

**Comment by sickhipx** [comment]
same settings same problem, anyone?

**Comment by bastiflew** [comment]
in FarmPokestopsGPXTask.cs, bot enter in `while (pokestopList.Any())` juste once at start, after bot never enter again in this loop
