### ISSUE TITLE
Google Device

### ISSUE THREAD

**Issue by cyrsis** [NecronomiconCoding/NecroBot#1186]
I try to setup some new accounts, the Google device page is missing. and only available for android 

I guess Google just don't like non- android device.

**Comment by WinSCaP** [comment]
This is not a chatbox, this is not a forum. This is a bug tracker!

**Comment by MythHack** [comment]
@WinSCaP Even if the service is not up and running, what else to talk about? Service not up and running itself is not a bug it?

**Comment by MythHack** [comment]
@WinSCaP Find and solve problems is not correct? While many people are reached for the party.
