### ISSUE TITLE
How to set the coordinates ?

### ISSUE THREAD

**Issue by darkmanvale** [NecronomiconCoding/NecroBot#1188]
How to set the coordinates ?

**Comment by cpasmoi** [comment]
How to use a bug tracker ?

**Comment by salvob41** [comment]
Issues tab are not FAQ or Q/A, read the wiki!

**Comment by WinSCaP** [comment]
This is not a chatbox, this is not a forum, this is not helpdesk. This is a bugtracker, please behave accordingly.
