### ISSUE TITLE
 Unhandled exception

### ISSUE THREAD

**Issue by Zmazleci** [NecronomiconCoding/NecroBot#1191]
Any idea how to fix it? 

Unhandled exception: Newtonsoft.Json.JsonReaderException: Invalid JavaScript property identifier character: ,. Path 'DefaultLatitude', line 5, position 40.
   v Newtonsoft.Json.JsonTextReader.ParseUnquotedProperty()
   v Newtonsoft.Json.JsonTextReader.ParseProperty()
   v Newtonsoft.Json.JsonTextReader.ParseObject()
   v Newtonsoft.Json.JsonTextReader.Read()
   v Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   v Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   v Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   v Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   v Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   v Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   v Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   v PoGo.NecroBot.CLI.GlobalSettings.Load(String path) v C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.CLI\Settings.cs:řádek 126
   v PoGo.NecroBot.CLI.Program.Main(String[] args) v C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.CLI\Program.cs:řádek 46

**Comment by WinSCaP** [comment]
This is not a chatbox, this is not a forum, this is not helpdesk. 

**This is a bugtracker, please behave accordingly.** 

Also #1182

**Comment by cpasmoi** [comment]
how about reading at least the first line of the log ?

**Comment by agp89** [comment]
Guess you used a `,` instead of a `.`!

Make sure it looks like this:
![image](https://cloud.githubusercontent.com/assets/6398661/17211835/f2300822-54cb-11e6-9282-3aa06efcbbe5.png)

Please close issue if solved!

If there is any **JsonReaderException** you should validate your config with [a json validator](http://lmgtfy.com/?q=json+validator)
