### ISSUE TITLE
[FIX] (ERROR) Couldnt copy to clipboard, do it manually

### ISSUE THREAD

**Issue by Lastnet0709** [NecronomiconCoding/NecroBot#1192]
Copy your token from old version 

Then go to the directory for your Necrobot (v7 Bot):
PoGo.NecroBot.CLI > bin > Debug > Config

Open to the file in there with a text editor or VS

{
  "AuthType": "google",
  "GoogleRefreshToken": "PUT YOUR TOKEN HERE",
  "PtcPassword": null,
  "PtcUsername": null
}

Save > run bot ^_^﻿

**Comment by Spegeli** [comment]
uuhhh what a Fix...this is more a workaround in case you have a old token.

**Comment by Strike5221** [comment]
Only If I had my old version ;(

**Comment by proesd** [comment]
This solution only work if you have old version, not from fresh account. closed thread

**Comment by WinSCaP** [comment]
Temporary Fix to Clipboard Problem #1154

**Comment by korionz** [comment]
is the bot working properly  ?? Because when i use the newest bot i've stuck with the softbann , but when i used the older version it works fine, any solution  ?
is any other have the same problem ?

**Comment by WinSCaP** [comment]
This is not a chatbox, this is not a forum, this is not helpdesk. 

**This is a bugtracker, please behave accordingly.**

**Comment by FeiFogota** [comment]
It works！ 
![j3d 4s u fq0mj h15 2](https://cloud.githubusercontent.com/assets/20700916/17212031/34fed966-54ff-11e6-9dc7-26f50b69d4de.png)
