### ISSUE TITLE
Poke Stops farming just exp

### ISSUE THREAD

**Issue by m4c-4rthur** [NecronomiconCoding/NecroBot#1193]
![untitled](https://cloud.githubusercontent.com/assets/7851231/17211858/02564d74-54cc-11e6-91cf-546bee84b781.jpg)

I think it's not normal to only get xp from pokestops without any items

**Comment by edum995** [comment]
item inventory full?

**Comment by lnmtriet93** [comment]
Maybe because your bag is full

**Comment by WinSCaP** [comment]
This is not a bot issue. This is a clear PEBKAC issue.

**Comment by agp89** [comment]
Your inventory is full!
See #1183

Please Close.

**Comment by brama23** [comment]
can see your config ?
best config
