### ISSUE TITLE
Visual Studio errors

### ISSUE THREAD

**Issue by InfernalLag** [NecronomiconCoding/NecroBot#1197]
![error](https://cloud.githubusercontent.com/assets/20702908/17212208/3536c0aa-54ce-11e6-8bd9-70f12f789225.jpg)

The errors at the bottom say: files not found.
Can someone help me?

**Comment by WinSCaP** [comment]
This is not a chatbox, this is not a forum, this is not helpdesk. 

**This is a bugtracker, please behave accordingly.**

**Comment by artganify** [comment]
@WinSCaP Don't blindly copy that one everywhere. Some might be legitimate bugs. Ask the OP to provide more information about the problem and then decide before jumping to conclusions. Additionally, general requests for help are fine if a problem hasn't been answered before or isn't described in the wiki.

**Comment by artganify** [comment]
@InfernalLag To me it looks like some references haven't been built. Can you provide the output from your VS console?

**Comment by lnmtriet93** [comment]
Which version of visual studio do you use? It seems like can only compile with Visual Studio 2015, I have same errors when I tried yo compile with VS 2013.

**Comment by artganify** [comment]
@InfernalLag @Inmtriet93 Did you both also checked out the referenced submodule from the repo?

**Comment by TheFrozenOne** [comment]
WinSCaP is right though, this is NOT a helpdesk

**Comment by artganify** [comment]
@TheFrozenOne And this might not be necessarily a "help question". OP seems to have problems with building the project, so this could be e.g. related to a build environment (vs2013 for example) which isn't supported or a bug in the current branch. So first we need to figure out what the problem is and then we can react accordingly.

**Comment by InfernalLag** [comment]
@artganify yeah, i don't have that files, 'cause i dont have any bin folder
I downloaded everything from GitHub, first al the bot, after that the ForexRev folder...
I missed something?

**Comment by artganify** [comment]
@InfernalLag Ah, I see. Try to check out the repository using a git client with the `--recursive` flag, as described here: https://github.com/NecronomiconCoding/NecroBot/wiki/Source-Code#source-code-via-git-faster-always-up2date. That should fetch all necessary dependencies and submodules. :)

Please report back if that solved your problem and close the issue accordingly.

**Comment by lnmtriet93** [comment]
@artganify sorry, it doesn't work at all, I have used the --recursive flag during first try and I have downloaded the Rocket API during second try but no luck. But it works fine with VS 2015 :)

**Comment by InfernalLag** [comment]
@artganify yeah, now i have that files!
but ( following the Setup ) when I run the program it don't work ( ask me Google or PTC, mine is Google, and at the end...

[14:47:28] (INFO) Logging in using Google
[14:47:30] (ATTENTION) Opening Google Device page. Please paste the code using CTRL+V
[14:47:35] (ERROR) Couldnt copy to clipboard, do it manually
[14:47:35] (ERROR) Goto:  & enter

I failed?

**Comment by artganify** [comment]
@InfernalLag Nope, you did everything correctly! :smile: 

The problem you're having now is another bug everyone is struggling with. See for example here: #1181. Currently, there is no solution to it, except to wait. Devs are working on it.

**Comment by InfernalLag** [comment]
@artganify ok!
so, thank you so much!
i'll close the issue right now

**Comment by artganify** [comment]
@InfernalLag No, it's not. It's probably related to Google. Either they changed something with the client authentication (which we can react to), they have issues themselves (there are currently a lot of server problems in general) or they blocked certain stuff, for example the Niantic client id which the Rocket API currently uses (then we're pretty much out of luck). If someone else has more information with proof, they can correct me but I don't know anything else than that.

**Comment by InfernalLag** [comment]
@artganify close!
