### ISSUE TITLE
[Suggestion] Log lat/long of captures

### ISSUE THREAD

**Issue by hoopzbarkley** [NecronomiconCoding/NecroBot#1198]
I'd like to be able to use the bot to data mine spawn times and locations, as I'm seeing it capture a lot of stuff in my local area I've never encountered. It'd be great if the console could optionally output and log  the lat/long of each capture, such that I can generate heat maps to figure out the best hunting spots for use with my legit account.

**Comment by agp89** [comment]
This would be a bit to much information for the console output. The WebSocket interface is what you want to use.

[ Someone has build a visualizer which shows the captures on a map using the WebSocket interface](https://github.com/nicoschmitt/necrobotvisualizer)

**Comment by hoopzbarkley** [comment]
@agp89 that's incredibly helpful, thank you!
