### ISSUE TITLE
IV checker

### ISSUE THREAD

**Issue by godlesowned** [NecronomiconCoding/NecroBot#1204]
On start bot showing 10 best CP and 10 best IV
Is there option to check ALL pokemons IV? I need to evolve my best IV pokemons.

**Comment by emoisback** [comment]
config.json

change   "AmountOfPokemonToDisplayOnStart": 10, 

to   "AmountOfPokemonToDisplayOnStart": 100, 

bot will show 100 bect CP and 100 best IV

**Comment by McGuim** [comment]
Edit that line in config.json
  "AmountOfPokemonToDisplayOnStart": 50,
set 1000 or 9999 or 655535 anything bigger than your inventory
