### ISSUE TITLE
"Translation for IncubatorEggHatched is missing"

### ISSUE THREAD

**Issue by brama23** [NecronomiconCoding/NecroBot#1205]
"Translation for IncubatorEggHatched is missing"

solving problems like the dialogue that came out this how ? thank you

**Comment by artganify** [comment]
It seems like there is obviously a line missing in one of the translation files. What language did you set in your configuration?

**Comment by brama23** [comment]
Indonesia , the line to what do you think?

**Comment by nenko91** [comment]
Same even in english

**Comment by Zeraceee** [comment]
Delete the translation file you are using,

**Comment by brama23** [comment]
if removed translation file im using, what about this line ?  "TranslationLanguageCode": "id",
what is required at this line ?

**Comment by brama23** [comment]
@Zeraceee

**Comment by Zeraceee** [comment]
@brama23 delete the entire file and restart the bot, it will fix your problems.
