### ISSUE TITLE
Not transfering kept on walking... searching for pokestops.

### ISSUE THREAD

**Issue by artsy23** [NecronomiconCoding/NecroBot#1208]
can you update the bot its not auto transferring pokemon when pokeinventory is full.. it just kept on searching for pokestops... and not reseting the bot... to transfer...i've tested it

**Comment by Lauriy** [comment]
Have you checked if you have other limitations that prevent transferring? Like min IV?

**Comment by JohnyWlkr** [comment]
Also check KeepPokemonsThatCanEvolve...
