### ISSUE TITLE
Latest commit only evolving on login

### ISSUE THREAD

**Issue by ggouki** [NecronomiconCoding/NecroBot#121]
EvolveAllPokemonWithEnoughCandy only executes during PostLoginExecute, not after.

Can we get back evolving before transferring duplicates to maximize evolving with excess candy?

Thanks

**Comment by Shroomzie** [comment]
stats say that you will be better off not evolving and just bot. Then evolving in a bunch then get back to botting. Just sayin.

**Comment by OverlordQ** [comment]
Yeah, popping a lucky egg and evolving all at once will get you the most XP
