### ISSUE TITLE
I delelted the old one...

### ISSUE THREAD

**Issue by hei55555** [NecronomiconCoding/NecroBot#1210]
Could someone send me a used old version release please? I deleted mine...

**Comment by Bogenschuetze** [comment]
https://github.com/NecronomiconCoding/NecroBot/releases

**Comment by hei55555** [comment]
I mean the one that with the old token, not just the version.

**Comment by ZoleeHU** [comment]
@Bogenschuetze How to stop it from auto updating so i can actually login and take the GoogleRefreshToken from the auth file?
