### ISSUE TITLE
couple of issues inc incubator and non transfer

### ISSUE THREAD

**Issue by brooky325** [NecronomiconCoding/NecroBot#1214]
Hi first post and hope i can help you guys in future. 
First of all thanks everyone for the awesome work.

so onto issues. 
ive downloaded the latest release which boots up fine and runs, the issue i have is after a couple of hours im getting no more room for pokemon as i have like 20 weedle 20 pidgey 20 zubats etc the rest transfer fine but these seem to stay, i have the keep pokemon to only 2 so anything else should just be transferred?.

Also im not seeing anything about egg hatches.. do i have to set them going in bluestack/nox or my mobile or is the app supposed to auto incubate them?

**Comment by PandaWalz** [comment]
Is KeepPokemonsThatCanEvolve set to true? If you move it to false it should fix the transfer issue.

Did you turn incubation on in your config?
