### ISSUE TITLE
Initializing Rocket logger at time 2016-07-28 7:42:18 AM...

### ISSUE THREAD

**Issue by junweig** [NecronomiconCoding/NecroBot#1215]
anyone can help me with this problem? thanks

**Comment by WinSCaP** [comment]
And @junweig can you explain what the actual problem is? do you need help setting it up? (In that case, this is not te place to ask). Please show more than just a request for help. Otherwise people might think the problem is PEBKAC.

**Comment by junweig** [comment]
@WinSCaP 
Initializing Rocket logger at time 2016-07-28 7:42:18 AM...
Initializing Rocket logger at time 2016-07-28 7:43:25 AM...
Initializing Rocket logger at time 2016-07-28 7:44:55 AM...
Initializing Rocket logger at time 2016-07-28 7:45:13 AM...


i could run it before but now just showing this
