### ISSUE TITLE
Update for Language zh_CN added missing lines

### ISSUE THREAD

**Issue by MiaoMFoo** [NecronomiconCoding/NecroBot#1216]
进入脚本目录下Release\Config\Translations
用记事本打开translation.zh_CN.json文件
内容修改为
{
  "TranslationStrings": [
    {
      "Key": "pokeball",
      "Value": "精灵球"
    },
    {
      "Key": "greatPokeball",
      "Value": "高级精灵球"
    },
    {
      "Key": "ultraPokeball",
      "Value": "超级精灵球"
    },
    {
      "Key": "masterPokeball",
      "Value": "大师精灵球"
    },
    {
      "Key": "wrongAuthType",
      "Value": "登录错误"
    },
    {
      "Key": "farmPokestopsOutsideRadius",
      "Value": "您已经走出范围！5秒后返回起点(距离{0}米),请确认系统设置是否正确？"
    },
    {
      "Key": "farmPokestopsNoUsableFound",
      "Value": "附近没有补给站，请确认系统设置是否正确？"
    },
    {
      "Key": "eventFortUsed",
      "Value": "获得经验值:{0},金币:{1},道具:{2}"
    },
    {
      "Key": "eventFortFailed",
      "Value": "捕捉失败,可能被封号了,自动解封中...尝试次数:{0}/40"
    },
    {
      "Key": "eventFortTargeted",
      "Value": "{0}距离{1}米"
    },
    {
      "Key": "eventProfileLogin",
      "Value": "登陆账号{0}"
    },
    {
      "Key": "eventUsedLuckyEgg",
      "Value": "使用幸运蛋.剩余数量:{0}"
    },
    {
      "Key": "eventPokemonEvolvedSuccess",
      "Value": "成功进化{0}获得{1}经验值"
    },
    {
      "Key": "eventPokemonEvolvedFailed",
      "Value": " {0}进化失败,因为{1},已取消{2}"
    },
    {
      "Key": "eventPokemonTransferred",
      "Value": "{0}\t- CP值:{1}完美度:{2}%[已拥有CP值:{3}完美度:{4}%相同精灵]剩余糖果{5}"
    },
    {
      "Key": "eventItemRecycled",
      "Value": "{0}x {1}"
    },
    {
      "Key": "eventPokemonCapture",
      "Value": "{0}|{1}{2}等级:{3}|CP值:({4}/{5})完美度:{6}%|捕获几率:{7}%|距离{8}米|剩{10}个{9}|{11} "
    },
    {
      "Key": "eventNoPokeballs",
      "Value": "没有精灵球了,我们错过了一只CP值为{1}的{0}"
    },
    {
      "Key": "catchStatusAttempt",
      "Value": "{0}重试次数{1}"
    },
    {
      "Key": "catchStatus",
      "Value": "捕捉{0}"
    },
    {
      "Key": "candies",
      "Value": "糖果{0}"
    },
    {
      "Key": "unhandledGpxData",
      "Value": "GPX数据未成功处理,试图跳过."
    },
    {
      "Key": "displayHighestsHeader",
      "Value": "精灵"
    },
    {
      "Key": "commonWordPerfect",
      "Value": "完美度"
    },
    {
      "Key": "commonWordName",
      "Value": "名称"
    },
    {
      "Key": "displayHighestsCpHeader",
      "Value": "保留高CP值精灵"
    },
    {
      "Key": "displayHighestsPerfectHeader",
      "Value": "保留高完美度精灵"
    },
    {
      "Key": "displayHighestsLevelHeader",
      "Value": "保留高等级精灵"
    },
    {
      "Key": "welcomeWarning",
      "Value": "请确保坐标正确，否则请退出! Lat:{0} Lng:{1}"
    },
    {
      "Key": "incubatorPuttingEgg",
      "Value": ":{0:0.00}公里之后开始孵蛋"
    },
    {
      "Key": "incubatorStatusUpdate",
      "Value": "精灵蛋{0:0.00}公里后孵化成功"
    }
  ]
}

保存
返回上层Config目录
用记事本打开config.json编辑找到最下面"TranslationLanguageCode": "us",行us改为zh_CN

**Comment by nenko91** [comment]
there are missing lines in en too
