### ISSUE TITLE
[Feature Request] A feature to list all the pokemon in inventory.

### ISSUE THREAD

**Issue by InnerFire** [NecronomiconCoding/NecroBot#1217]
It will list all the stats of available pokemons so players can manually evolve pokemon based on their preference for each individual pokemon.

**Comment by WinSCaP** [comment]
@InnerFire This is implemented if you edit the config file to show all your pokemon instead of the best 10 or 20 ;)

**Comment by InnerFire** [comment]
I tried it. But it still only list top 10 pokemons on the list. Once CPvise and then IVvise.

**Comment by PandaWalz** [comment]
To do the manual evolution wouldn't you have to log in via Nox anyway?

**Comment by InnerFire** [comment]
@PandaWalz And how would I see IV stats in nox?
