### ISSUE TITLE
925 compile, but critical error on startup

### ISSUE THREAD

**Issue by GDlike** [NecronomiconCoding/NecroBot#1220]
[16:09:15] System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   en DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   en PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) en D:\Documentos\GitHub\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:línea 17
   en PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() en D:\Documentos\GitHub\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\**Login.cs:línea 30**
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() en D:\Documentos\GitHub\NecroBot\PoGo.NecroBot.Logic\State\L**oginState.cs:línea 33**
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() en D:\Documentos\GitHub\NecroBot\PoGo.NecroBot.Logic\State\**StateMachine.cs:línea 34**

**Comment by uhnduhrew** [comment]
Try switching to EN and see if the error persists.

**Comment by GDlike** [comment]
@uhnduhrew  the bot is in en the visual too .

**Comment by erfg12** [comment]
I added quotation marks to the GoogleUsername and GooglePassword json settings. That made the error go away, but I still don't get logged in.

**Comment by marksterxxx** [comment]
refresh token was safer IMO

**Comment by Cush1337** [comment]
You need to add your Google user/pass to auth.json now.

If you use 2 factor auth, you need to go to https://security.google.com/settings/security/apppasswords and generate an app password, then use that in place of your usual password in the auth file.
