### ISSUE TITLE
[Question] How to keep 3 dratinis

### ISSUE THREAD

**Issue by Niahm** [NecronomiconCoding/NecroBot#1222]
In my config.json i have
`"KeepMinDuplicatePokemon": 1`
but i want to keep 3 strongest Dratinis an 3 strongest Magikarps, how to do it ?

**Comment by StanleyDerLurch** [comment]
Noob!
Check ur conf file... the magic word is "filter"...

**Comment by agp89** [comment]
The answer can be found in the wiki: [PokemonTransferFilter (List)](https://github.com/NecronomiconCoding/NecroBot/wiki/Config#pokemontransferfilter-list)

Please close issue if solved!

**Comment by Niahm** [comment]
My bad i had an old release.
found it !

**Comment by agp89** [comment]
@Niahm please close the issue then ;-)
