### ISSUE TITLE
Failed to Copy to clipboard

### ISSUE THREAD

**Issue by iChaosWolf** [NecronomiconCoding/NecroBot#1227]
![bug](https://cloud.githubusercontent.com/assets/20685395/17216258/ee4f29b8-54ad-11e6-90ce-081b65d8bad4.png)
When first opening the program it shows me this error (shown in the file attached.

**Comment by Kalashnikitty** [comment]
....cancer

**Comment by bignuts** [comment]
close, this please, there are already hundred of this report

**Comment by agp89** [comment]
A simple search for [copy to clipboard](https://github.com/NecronomiconCoding/NecroBot/issues?utf8=%E2%9C%93&q=is%3Aissue%20Copy%20to%20clipboard) before opening yet another dublicated issue was to hard?
