### ISSUE TITLE
Pokestops/Pokemon Fleeing/GYM Battles

### ISSUE THREAD

**Issue by arose237** [NecronomiconCoding/NecroBot#1228]
Anytime I try to go to a pokestop nothing happens. When I try to catch a pokemon they always flee. Trying to battle gyms never works and always resets right before the battle. I am assuming this is due to softban but if anyone has any clue why these problems happen please let me know.

**Comment by Ambushed91** [comment]
Did you try lowering the walkspeed to 16.0 instead of 300.0

**Comment by cpasmoi** [comment]
there is a problem with this program ?

**Comment by aikoncwd** [comment]
Looks like you got softbanned.

**Comment by arose237** [comment]
These arent problems that the bot is having. These problems only occur when I try to go out and actually play the game.

**Comment by vekst** [comment]
Yeah, your currently softbanned. Wait a few hours and try again, you should be good.

**Comment by aikoncwd** [comment]
You bot was playing at africa and now you logged in in your country and you got softbanned. You need to wait 2hr penalty or use 40 pokestops (entrer pokestop, spin, go back to map) repeat that x40

**you can close this issue**

**Comment by arose237** [comment]
so turn off the bot for 2 hours and I should be good?

**Comment by aikoncwd** [comment]
what? You should *not* use your phone while bot is online!

**Comment by hsizadam** [comment]
dude you should pick someplace for play the game, bot's location or your location. 
if you do so, when close the bot, wait 2 hrs and open your phone, if you dont wait it will happen everytime you try.

**Comment by arose237** [comment]
ALRIGHT THANKS

**Comment by aikoncwd** [comment]
Close this issue then. Thanks
