### ISSUE TITLE
[Question] Possible Issue

### ISSUE THREAD

**Issue by KuschelCore** [NecronomiconCoding/NecroBot#1229]
the bot transfers pokemon/recycles items after exactly 5 pokestops. this sequence makes the bot easily detectable by a simple algorithm, right? wouldn't a randomized update of pkmn/items every 5-8 pokestops be much better?

I'm not an expert, just asking. and you do a great job, guys :)

**Comment by agp89** [comment]
FYI #808

**Comment by KuschelCore** [comment]
thank you, @agp89 . looks like I made a double post. sorry for that.
