### ISSUE TITLE
someone help pls

### ISSUE THREAD

**Issue by IXSharks** [NecronomiconCoding/NecroBot#1230]
i downloaded new version and after i said use google auth this error starts 
[16:31:32] (INFO) Logging in using Google
[16:31:32] (ERROR) System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   bei DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   bei PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\janni\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:Zeile 17.
   bei PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in C:\Users\janni\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:Zeile 30.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\janni\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:Zeile 33.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in C:\Users\janni\Desktop\NecroBot-master\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 34.
someone can help me pls ?

**Comment by cpasmoi** [comment]
:man_with_gua_pi_mao: :gun:
