### ISSUE TITLE
Don't use log4net, use NLog

### ISSUE THREAD

**Issue by igromanru** [NecronomiconCoding/NecroBot#1232]
log4net is nothing but a clone of log4j. It's made for lazy java developer who just want to made something fast in C# and the latest version is from 2015.
[NLog ](https://github.com/NLog/NLog) was made with love for C#, it's [faster ](https://www.loggly.com/blog/benchmarking-5-popular-net-logging-libraries/) and gets permanent updates.
If you need more reasons, just google for it.

**Comment by agp89** [comment]
NLog would be create! :laughing: 
- [ColoredConsole-Target](https://github.com/nlog/NLog/wiki/ColoredConsole-target )
- [File-Target](https://github.com/nlog/NLog/wiki/File-target)
- [Mail-Target](https://github.com/nlog/NLog/wiki/Mail-target) (e.g. Send a mail when a Mewtwo was catched :-P)

I'v never worked with log4net, but with NLog all this is done pretty easily!

**Comment by wind-raven** [comment]
@igromanru  Are there any issues you are seeing with log4net?  I use log4net in another project as well and see no issues that would be solved by a switch to NLog.

@agp89 log4net has an smtp appender which provides the mail sending functionality.  https://logging.apache.org/log4net/release/config-examples.html  Colored Console appender, rolling file appender, and smtp appender are what you would be looking for to find the same functionality.
