### ISSUE TITLE
[Feature Request] Starting lat lon based on GPX

### ISSUE THREAD

**Issue by cznoclaf** [NecronomiconCoding/NecroBot#1234]
Hi,
I have feature request / minor improvement suggestion - I think it might be useful when  "UseGpxPathing": true to ignore lat/lon in the config file and use first point from the GPX file (or have another flag for the user like "UseGPXAsStartingPoint")

br

**Comment by KurtCocain** [comment]
+1 on this. 
Using a lot of bots and just copy pasting one GPX file is 10x easier than changing 10x+ lat/long too
