### ISSUE TITLE
error, help, google 

### ISSUE THREAD

**Issue by EskimoLV** [NecronomiconCoding/NecroBot#1240]
https://gyazo.com/d417bcebbd54359c68277cdfb3aca838
and no copying, ???

**Comment by poutros** [comment]
I lost count of the issues oppenned because of this. Close this issue. Google changed a few things and devs are working.

**Comment by bignuts** [comment]
Little bit of research before posting please, close this.

**Comment by EskimoLV** [comment]
link pls :D

**Comment by poutros** [comment]
What do you mean? Just close the issue and wait.

**Comment by bignuts** [comment]
they are fixing it, close it ans wait
