### ISSUE TITLE
not working even after update

### ISSUE THREAD

**Issue by alwayzgame** [NecronomiconCoding/NecroBot#1242]
http://prntscr.com/bynvt2

**Comment by aikoncwd** [comment]
It works perfect for me. 0.20

**Comment by poutros** [comment]
Maybe delete your old config?

**Comment by alwayzgame** [comment]
i just downloaded the release.zip and edited auth.json anything im missing?

**Comment by KurtCocain** [comment]
You guys got the release? I only have the json 0.2.0. And It wont open cause missing API. :<

**Comment by aikoncwd** [comment]
They dropped the compiled-release. I was fast and I downloaded, also you can compile it from sources.

**Comment by alwayzgame** [comment]
can u guide mw how to do it that would be helpfull

**Comment by KurtCocain** [comment]
@aikoncwd I can't compile from source, it says its missing api, do I really have to install githubdesktop and clone it? I don't want to do that.

**Comment by namines** [comment]
I'm getting the same error, and now they've removed the compiled download link, so I guess we'll just need to wait until they fix it.

**Comment by Kartoffelbrust** [comment]
Hey I know this is stupid to ask but I am a complete beginner and have no clue what to do so can someone help me, please? 
Sorry for the inconvenience.

**Comment by KurtCocain** [comment]
So he rereleased but the version still crashes. Really?

**Comment by matthewryanparker** [comment]
Kurt, they're working on the fix. Calm yourself. If you don't know how to fix it then you're at their mercy, they're doing to a service and you have the nerve to complain? These people are geniuses and deserve our praise and some tips for their contributions, not whining and crying.

**Comment by aikoncwd** [comment]
1. Just download 1.9.0 again (clean version)
2. Execute it.
3. Wait 30 seconds
4. Select google auth
5. Wait 3 seconds again

It will be updated to 0.2.0, then close the bot and edit `auth.json` with yout username/password

**Comment by poutros** [comment]
They have rereleased it.

**Comment by kittaru** [comment]
put username and password in "" if using google. Will accept the string then if you were getting errors.

**Comment by hertn** [comment]
THe bot is working but Google auth is still not working.

**Comment by aikoncwd** [comment]
It works, just fill your name and password (using quotes "")

**Comment by KurtCocain** [comment]
@matthewryanparker I'm totally calm. I'm just confused on what happened. Maybe I was rude, but what I meant to ask was
Did he release twice the bad version? Or is it just not working for me?

I got lazy, it came out wrong and rude. I apologize.

**Comment by hertn** [comment]
@aikoncwd When using Google auth there is no password or username.

**Comment by aikoncwd** [comment]
@hertn are you serious?

```
{
  "AuthType": "google",
  "GoogleRefreshToken": null,
  "PtcUsername": null,
  "PtcPassword": null,
  "GoogleUsername": "yormail@gmail.com",
  "GooglePassword": "yourpass"
}
```

**Comment by hertn** [comment]
@aikoncwd WTF? Where did you get this? In my auth file there is only this:

`{
  "AuthType": "google",
  "GoogleRefreshToken": "",
  "PtcUsername": "username",
  "PtcPassword": "pw"
}`

**Comment by aikoncwd** [comment]
@hertn Update you damn bot!

**Comment by hertn** [comment]
@aikoncwd Ooops, I had so many "release" folders on my desktop I accidentally looked in the wrong one. Thanks mate!
