### ISSUE TITLE
Wrong names in pokestops (Russian lang)

### ISSUE THREAD

**Issue by golitsyn** [NecronomiconCoding/NecroBot#1245]
![image](https://cloud.githubusercontent.com/assets/7149397/17218625/7bd3076e-54f9-11e6-81df-599a2ec2aedf.png)

**Comment by Xalk444** [comment]
kak ti zapustil.shas zhe ne pashyt servera google

**Comment by golitsyn** [comment]
https://github.com/NecronomiconCoding/NecroBot/releases
