### ISSUE TITLE
can someone help with this ?

### ISSUE THREAD

**Issue by IXSharks** [NecronomiconCoding/NecroBot#1247]
help me pls with this error 
Unbehandelte Ausnahme: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: J. Path 'GoogleUsername', line 6, position 21.
   bei Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   bei Newtonsoft.Json.JsonTextReader.ReadAsString()
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   bei Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   bei Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   bei PoGo.NecroBot.CLI.AuthSettings.Load(String path) in C:\Users\janni\Desktop\NecroBot-master\PoGo.NecroBot.Logic\Settings.cs:Zeile 43.
   bei PoGo.NecroBot.CLI.GlobalSettings.Load(String path) in C:\Users\janni\Desktop\NecroBot-master\PoGo.NecroBot.Logic\Settings.cs:Zeile 283.
   bei PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\janni\Desktop\NecroBot-master\PoGo.NecroBot.CLI\Program.cs:Zeile 31.

**Comment by PhilippKeil** [comment]
Did you write your username and password in ""? Like this: "xxxx@gmail.com"

**Comment by Ry6er** [comment]
Same here i did use xxxx@gmail.com has to be something else

**Comment by IXSharks** [comment]
found my problem ..... forgot " " omg sry >.<

**Comment by IXSharks** [comment]
xD

**Comment by IXSharks** [comment]
thanks for ur help ^^

**Comment by alwayzgame** [comment]
what was the problem?

**Comment by Deske043** [comment]
Sharks could u send the code?  Without ur password & email obv

**Comment by IXSharks** [comment]
the problem was i forgot there " things i have to put like this "xxxx" and """""""" i forgot to put <.<

**Comment by Deske043** [comment]
I tried putting "MY_Username"  &  "My_Password" 
But it doesnt appear to help, could u send me ur 
Auth.jon code?  Without ur pass & email

**Comment by IXSharks** [comment]
"AuthType": "google",
  "GoogleRefreshToken": null,
  "PtcUsername": null,
  "PtcPassword": null,
  "GoogleUsername": "devnotmyemail@gmail.com",
  "GooglePassword": "Kappa1234"

**Comment by Deske043** [comment]
Thankyou!

**Comment by IXSharks** [comment]
np

**Comment by Deske043** [comment]
Remove that ur email and pass is in it

**Comment by Deske043** [comment]
Ow nvm xD

**Comment by kjmrmcdz** [comment]
@IXSharks  password with "" too? example id: "pokego" pw: "nice"

**Comment by IXSharks** [comment]
its nor my email and pas just troll :dancer:

**Comment by IXSharks** [comment]
yes i did and after it works

**Comment by IXSharks** [comment]
works now? @kjmrmcdz
