### ISSUE TITLE
Installing With Git Error?

### ISSUE THREAD

**Issue by bennextmitchell** [NecronomiconCoding/NecroBot#1248]
Hello I am trying to install using git for windows this time instead of the .zip files. I keep getting this error when I try to run the git fetch origin pull/ID/head  command. Error: C:\Users\Me\Desktop\here\NecroBot>git fetch origin pull/ID/head
fatal: Couldn't find remote ref pull/ID/head

**Comment by Eastrall** [comment]
Hi!

Try a `git clone` instead.

Or you can also donwload TortoiseGit here: https://tortoisegit.org/ install it, and then do a right click wherever you want to clone the repo and select the `Git clone...` option.

**Comment by wind-raven** [comment]
that is to pull a specific commit, pull/ID/head does not actually exist.  Check the git help page on how to check out a branch from a remote.  You will want to check out the master branch.

**Comment by bennextmitchell** [comment]
ahh ok so I don't need to run that command, I was just following the https://github.com/NecronomiconCoding/NecroBot/wiki/Source-Code gide, 


I don't need to do this step?

Pull specific commit or pull request
1.Ensure you are in Necrobot root directory
2.Run  git fetch origin pull/ID/head

**Comment by bennextmitchell** [comment]
I'm new to the whole git thing

**Comment by wind-raven** [comment]
@bennextmitchell no.  a clone of the repository should do it.

I would take a look at http://product.hubspot.com/blog/git-and-github-tutorial-for-beginners for a good intro to git

**Comment by bennextmitchell** [comment]
ok
so I can just open the NecroBot for Pokemon Go.sln file
and go from there?
