### ISSUE TITLE
How to tell bot after update to logg in with TrainerClub?

### ISSUE THREAD

**Issue by Snacktastic** [NecronomiconCoding/NecroBot#1250]
Hello,
after update the bot is asking for google auth. How can I change it to trainer club auth?
Thank you :)

**Comment by lukftw** [comment]
it doesnt work with google either

**Comment by fazzertron** [comment]
It gives you the option to select either google or PTC when you start it for the first time after an update. Either that, or edit the auth.json file again.

**Comment by voltized** [comment]
@fazzertron It doesn't do that. After deleting the auth.json it tells you to login with Google or edit the auth and it doesnt accept 'PTC' or the program crashes

**Comment by Lui-** [comment]
I did it like this and it works:

`{
  "AuthType": "ptc",
  "GoogleRefreshToken": "",
  "PtcUsername": "yourUsername",
  "PtcPassword": "yourPassword",
  "GoogleUsername": "",
  "GooglePassword": ""
}`

I hope it helps but its definitely a bug :/

**Comment by lukftw** [comment]
its in a loop now, i enter my credentials in the auth file and when i start it updates again and delete my credentials

**Comment by voltized** [comment]
@Lui- 
It crashes right after. Are you on 0.2.0

**Comment by JaLuBru** [comment]
you know that 0.2.1 is out right :D that versiopn works for me with lui's strategy!

**Comment by voltized** [comment]
@JaLuBru 
yes i have it still doesnt work

**Comment by voltized** [comment]
@Lui- 
works now, thanks
@JaLuBru 
copied it exactly and it works

**Comment by Lui-** [comment]
@voltized
Yes, i am. I downloaded the "vanilla" 0.1.9 Release, started it once and put in my PTC-Username/-Password. I edited the config.json and it didnt work. I edited the auth.json like above and it worked. The "" are just placeholders

**Comment by JaLuBru** [comment]
@voltized damn okay glad it works for you now as well! do you know what the "DumpPokemonStats" cammand does? command list isn't updated yet
