### ISSUE TITLE
Can someone help me, please?

### ISSUE THREAD

**Issue by Kartoffelbrust** [NecronomiconCoding/NecroBot#1253]
I am an aboslute beginner and have no clue how to configure the bot at all.
I would really appreciate it if someone helped me out.
Sorry for the trouble I may cause you.

**Comment by wind-raven** [comment]
please read the wiki or join the chat.  This is the bug tracker for issues or feature requests.

**Comment by Eastrall** [comment]
There is a wiki on this repo that tells you exactly how to configure the bot: https://github.com/NecronomiconCoding/NecroBot/wiki

There is the wiki to setup the bot: https://github.com/NecronomiconCoding/NecroBot/wiki/Compiled-Releases

**Comment by Kartoffelbrust** [comment]
Thank you and sorry for troubling you.
