### ISSUE TITLE
Project in inbuidable state.

### ISSUE THREAD

**Issue by Cyberek** [NecronomiconCoding/NecroBot#1254]
Currently this project cannot be builded. It throws over 80 errors when I'm trying to build unchanged master. 
Why are you adding so much new code without even checking the shape of the master branch?
Master should be always keep in buildable / releasable shape.

**Comment by bignuts** [comment]
maybe they'll need some help with developing and keep everything updated and functional, ii'll be glad to help them if i had the knowledge of C#!
