### ISSUE TITLE
v0.2.1 google auth

### ISSUE THREAD

**Issue by PepoelpepO** [NecronomiconCoding/NecroBot#1258]
I google auth does not work , I put my username and password does not work

**Comment by IXSharks** [comment]
u need to add "" like username: "xxxxxx@gmail.com" password: "1234"

**Comment by IXSharks** [comment]
than it shoud work

**Comment by DriveBy123** [comment]
same here

**Comment by IXSharks** [comment]
works now ?

**Comment by PepoelpepO** [comment]
works? This is your first start and the bot has generated the default config!
We will now shutdown to let you configure the bot and then launch it again.

**Comment by KevinBassaDevelopment** [comment]
Doesnt work for me. Stuck after "Logging in using Google".

**Comment by ryanwj9009** [comment]
me using ptc also stuck
