### ISSUE TITLE
Bot not farming when coordinates are too far away from a street

### ISSUE THREAD

**Issue by MoritzMiddendorf** [NecronomiconCoding/NecroBot#133]
Test it yourselves, it will just repeat the best pokemon list, your level and than starts over. This is because it seems like the bot only simulates walking through streets and because the bot doesnt find any streets it will get stuck in a loop. no proof for this theory though.

**Comment by CL24** [comment]
Sounds like you are farming in a rural area and every known Stop is already on CD.

**Comment by AdnanCukur** [comment]
Does it work at first, but after 30~ minutes it starts repeating the best pokemon list ?

**Comment by ReddoKiddo** [comment]
fixed? if not check FAQ in discord, if still not fixed then post a issue again pl0x
