### ISSUE TITLE
System.Runtime error after running the bot for 20-30 minutes - i have a google token

### ISSUE THREAD

**Issue by Arptastic** [NecronomiconCoding/NecroBot#135]
I'm using the most newest version of the bot and I'm getting this error after running it for 20-30 minutes 

https://gyazo.com/3559c215a3805402f5c5d29c5faf6025 there's more but I didn't take a picture of the rest.

And yes I have a google token.

**Comment by minhquangpm** [comment]
I get this issue too, but it doesn't affect the bot so I just ignore it. I guess it's when the Google token expires and refreshes.
