### ISSUE TITLE
[REQUEST] Automatically Power Up Pokemon

### ISSUE THREAD

**Issue by qaqsd123** [NecronomiconCoding/NecroBot#136]
Maybe add a feature that automatically powers up a Pokemon until you can't anymore. Maybe make is so that you have to favorite the Pokemon for it to detect it for power ups.

**Comment by TrajkovicB** [comment]
Yea. But if you catch Gastly with 500CP and you power him up to 700CP and then after few hours of leveling UP you catch 800CP Gastly you wasted all that stardust and candy..

**Comment by qaqsd123** [comment]
Lol. I would only power up my strongest Pokemon.
