### ISSUE TITLE
Pokemon name repeating

### ISSUE THREAD

**Issue by Biizzle** [NecronomiconCoding/NecroBot#137]
![pkmon](https://cloud.githubusercontent.com/assets/20605208/17075464/efa89e3c-508b-11e6-8c39-74d9629425e3.png)
 Has been working perfectly the last 4 or so hours, now it's decided the long&lat is NaN and is just repeating what's in the screenshot? Have tried restarting the programme and changing the co-ordinates aswell..

**Comment by AdnanCukur** [comment]
Delete your coords.txt file

check my possible fix at #118 to prevent it from happening again

**Comment by Biizzle** [comment]
My long & lat just set to 0 for both and I couldn't get it to change back after even after restarting it all so I just deleted and reopened a new file for it, changed a few settings back to how it was before and now it's running fine, thank you though :)
