### ISSUE TITLE
Route range

### ISSUE THREAD

**Issue by MarkHuangZ** [NecronomiconCoding/NecroBot#141]
I assigned coordination near sea in SF in order to capture Dratini, however the bot went to city. Is it possible to set a range so users can catch what they need?

**Comment by Lim-Dul** [comment]
I second this request. Would be very useful indeed.

**Comment by ReddoKiddo** [comment]
Implemented

**Comment by MarkHuangZ** [comment]
Could you tell me where you set the range? So i could customize it in future needs. Thank you.

**Comment by ReddoKiddo** [comment]
UserSettings.settings -> MaxTravelDistanceInMeters
