### ISSUE TITLE
Coordinates NEVER update.

### ISSUE THREAD

**Issue by CoordsDoNotUpdate** [NecronomiconCoding/NecroBot#145]
I have attempted to update coordinates in the app.config, UserSettings.settings, PokemonGo.RocketAPI.Console.exe.xml compiled settings file, AND cords.txt. (Yes I have deleted and re downloaded, including the past 10+ versions, same issue) Coordinates ALWAYS revert to the default. ALWAYS. This issues has been since the last 100+ commits including the original project. This hopefully is a huge problem that no one else sees or have posted yet, because this is causing me so many temp bans.

**Comment by dbfy** [comment]
That's Weird, I've never had that issue, but then again I'm compiling it on Ubuntu on a vps.
Um are you sure it's building properly? and You set the main project(Solution) as PokemonGo.RocketAPI.Console

**Comment by CoordsDoNotUpdate** [comment]
Yes, the project always build correctly and runs fine with the code. It just always outputs the incorrect lat and long when the bot begins. As well if its any help, I can send any logs or anything needed at all. Ill even screen record me changing all the files just to prove that this is happening. It's making my blood boil I cannot figure out why this is happening for the life of me. (Info: compiling on Windows 10 iso on a virtual machine within Ubuntu 14.04 dedicated server)

**Comment by CoordsDoNotUpdate** [comment]
@dbfy

**Comment by dbfy** [comment]
This Issue can be a lot of things, so the GEO location output is incorrect, Can you paste me the log of the output. I might do some tracking.

**Comment by dbfy** [comment]
OK Replace with this, it should output your current coords on the title bar, check to make sure it's the same as what you config.

> private async Task DisplayPlayerLevelInTitle(bool updateOnly = false)
        {
            _playerProfile = _playerProfile.Profile != null ? _playerProfile : await _client.GetProfile();
            var playerName = _playerProfile.Profile.Username ?? "";
            var playerStats = await _inventory.GetPlayerStats();
            var playerStat = playerStats.FirstOrDefault();
            if (playerStat != null)
            {
                var xpDifference = GetXPDiff(playerStat.Level);
                var message =
                    $"{playerName} | Level {playerStat.Level}: {playerStat.Experience - playerStat.PrevLevelXp - xpDifference}/{playerStat.NextLevelXp - playerStat.PrevLevelXp - xpDifference}XP Stardust: {_playerProfile.Profile.Currency.ToArray()[1].Amount} Latt : {_client.CurrentLat} Long : {_client.CurrentLng}";
                Console.Title = message;
                if (updateOnly == false)
                    Logger.Write(message);
            }
            if (updateOnly == false)
                await Task.Delay(5000);
        }

**Comment by gamelinchpin** [comment]
I had this issue and I couldn't understand why my changes had no affect. For me the solution was to use manually delete the `Debug` build directory, then simply update the `UserSettings.settings` file and rebuild & run (Ctrl+F5). The issue was the file `Debug/bin/coords.txt` over-rides any other settings you may make.

Ref: https://github.com/NecronomiconCoding/Pokemon-Go-Bot/issues/106

**Comment by OverlordQ** [comment]
`UserSettings.settings` only provides the **default** coordinates. If you've run the bot before, or are recompiling, anything in `Coords.txt` takes precedence.

**Comment by CoordsDoNotUpdate** [comment]
I deleted the bot completely and changed UserSetting & app.config to no success. After compile, attempted to edit the cords.txt (AND the xml file for running the compiled binary) and STILL nothing. The printed cords at the beginning of the script are wrong AND the pokestops are the ones located at the default coords. I verified. (As I also notice an immediate soft ban if I use the bot and then go to my location, so it is not a printing error. The coords are being parsed or read wrong somewhere)

**Comment by CoordsDoNotUpdate** [comment]
Here is the log. 
[log.txt](https://github.com/NecronomiconCoding/Pokemon-Go-Bot/files/379398/log.txt)

**Comment by aapikz** [comment]
same problem and i got 3hrs banned because of latitude and longitude not updating even i save it x100 T_T please fix it

**Comment by dbfy** [comment]
Are you running emulated?
> Requesting PlayerUpdateResponse
Idk why you have so many of those.

**Comment by Brewfasa** [comment]
Go here: Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\bin\Debug\Coords.txt and remove the coordinates in that file, save it, save the new coordinates in the VS, profit!

For some reason it doesnt update the coordinates in the debug file and the program priorities that

**Comment by CoordsDoNotUpdate** [comment]
@Brewfasa if you read my issue you'd see that I did do that as well with no success.

**Comment by CoordsDoNotUpdate** [comment]
@dbfy I set the walking speed to 3km, as 50 is extremely suspicious and 3 is the average human walking speed. That could be why it constantly looks for player response.

**Comment by ReddoKiddo** [comment]
Is this still issue? you basically shouldn't never modify Coords.txt, just delete it and change coords in UserSettings.Settings

**Comment by dbfy** [comment]
Also realize that the on screen output coords on startup, will be different due to Noise Variance 
`private void SetCoordinates(double lat, double lng, double altitude)`
Will make the origional coord different then what is outputed to 
<                Logger.Write(
                $"Make sure Lat & Lng is right. Exit Program if not! Lat: {_client.CurrentLat} Lng: {_client.CurrentLng}",
                LogLevel.Warning);
