### ISSUE TITLE
Nother little Enhancement For Item Enums

### ISSUE THREAD

**Issue by dbfy** [NecronomiconCoding/NecroBot#152]
[https://puu.sh/qbr3v/f4541b17de.png](https://puu.sh/qbr3v/f4541b17de.png)

Basically regex for better item on screen.

Find `private async Task CatchEncounter(EncounterResponse encounter, MapPokemon pokemon)`
add and replace teh code block with
[https://puu.sh/qbruU/262644a0d6.txt](https://puu.sh/qbruU/262644a0d6.txt)
then find `private async Task ExecuteFarmingPokestopsAndPokemons()` and replace with code below
[https://puu.sh/qbrzB/02f6be134f.txt](https://puu.sh/qbrzB/02f6be134f.txt)

And that's it.

**Comment by Lim-Dul** [comment]
I am getting build errors -
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'Regex' does not exist in the current context	PokemonGo.RocketAPI.Logic	Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs	59	Active
```

**Comment by dbfy** [comment]
at the top of Logic.cs add the reference 
`using System.Text.RegularExpressions;`

**Comment by Lim-Dul** [comment]
Cheers mate!

I figured it out immediately after posting. Noticed that Regex was underlined and the library was not loaded.

Now others will know that too. :)

**Comment by dbfy** [comment]
=)
