### ISSUE TITLE
(ERROR) Account not verified

### ISSUE THREAD

**Issue by Txger** [NecronomiconCoding/NecroBot#1534]
Today NecroBot updated to 0.4.0 as it started.
But as soon as i configured the auth.json and the config.json the Bot said that my Account wasn't verified if i start the bot.
It worked fine the days before....
and also what is the certificate for. Do i need to install it? If yes whats the password?

**Comment by NecronomiconCoding** [comment]
Your account was deleted because you haven't verified.

**Comment by Txger** [comment]
but i used it all day long... everyday since the release. It cant be just deleted. I even can play on the phone
