### ISSUE TITLE
[Off] NecroBot Fórum

### ISSUE THREAD

**Issue by dgateles** [NecronomiconCoding/NecroBot#1537]
Hey, its not better create an forum to comment all issues and suggestions or whatever ? :+1:

**Comment by Aneduna** [comment]
I do not see why it is needed. You can discuss issues and suggestions just fine on Github.

**Comment by dgateles** [comment]
Is not fine on Github, Github is for development only, not talk about whatever you want.

**Comment by cawk** [comment]
^^ this github does a good way of being able to have an issue option so its not needed maybe in the future if the Dev decides he wants one

**Comment by Aneduna** [comment]
You can Create a Label Improvement or something like that.
Also, pretty muc every Suggestion is Development related, even feature requests.
