### ISSUE TITLE
Is it possible to dissable Pokestops using the bot just to catch pokemons?

### ISSUE THREAD

**Issue by zaikar** [NecronomiconCoding/NecroBot#1539]
It would be nice to have an option to disable pokestops, and only using Necrobot to catch pokemons.

**Comment by NecronomiconCoding** [comment]
implemented already

**Comment by zaikar** [comment]
I'm sorry but I've been trying to fins out how to disable pokestpots and there's nothing on config that does that...
Is there an option to diable stooping at pokestops and just catch pokemons?

Many thanks
