### ISSUE TITLE
[Request] Option to ignore poke stops

### ISSUE THREAD

**Issue by Lim-Dul** [NecronomiconCoding/NecroBot#154]
I would like to have a setting that would allow for ignoring poke stops or visiting only every Xth stop.

The reason for that is - sometimes users want to farm very specific Pokemon and not level up suspiciously quickly.

This would go nicely with a "geofencing" feature as suggested here:

https://github.com/NecronomiconCoding/Pokemon-Go-Bot/issues/141

**Comment by ReddoKiddo** [comment]
Will keep in mind for something like "ignore pokestop if have enough of specific items", but that will be a feature for the future...
