### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by LeaklessGfy** [NecronomiconCoding/NecroBot#1540]
Hello,

Is there any documentation for the WebSocket ? How can I access it with an Angular API etc ?
I got the port (14251) and I suppose it's localhost but how to launch it (if it's not made by the Cli) and access it ? (credentials etc ...)

Thanks :D

**Comment by Triky313** [comment]
Yes, that would be great.
I look at the area also.

**Comment by NecronomiconCoding** [comment]
Example : https://github.com/yamashi/NecroUI
