### ISSUE TITLE
"AutomaticallyLevelUpPokemon": true crashing the app

### ISSUE THREAD

**Issue by RavenlordUA** [NecronomiconCoding/NecroBot#1542]
Hi There, I have the following issue with "AutomaticallyLevelUpPokemon": true 
The reference not set to instance of object appeared when bot trying to level up the pokemon. 
Would you please take a look on this? 

[21:01:01] (ERROR) System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PoGo.NecroBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__0.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\LevelUp
PokemonTask.cs:строка 39
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\FarmState.cs:стр
ока 26
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs
:строка 36

**Comment by NecronomiconCoding** [comment]
has been adressed already
