### ISSUE TITLE
DisplayHighestsCP keep repeating.

### ISSUE THREAD

**Issue by Vortonic** [NecronomiconCoding/NecroBot#155]
I am not sure what I'm doing wrong but right when I start the program, this appears. https://gyazo.com/894a8e2aaf2b91de89f5e915d56abae1

**Here is my settings.**
https://gyazo.com/6675aaa009078e464337a839fbddf37f

I read the previous threads and deleted the coords folder and everything.  I'm just getting this thing to pop up over and over right when I open it.

**Comment by BioMuell** [comment]
https://github.com/NecronomiconCoding/Pokemon-Go-Bot/issues/151

**Comment by gewoon** [comment]
Are you using the latest version? Oh and are you trying to set your location to Times Square? Because i think you'll need to put a '-' before the 73 :P

**Comment by Vortonic** [comment]
@gewoon That was exactly my problem haha, the - sign.  Do you have steam or skype? I may have a few questions lol. Thanks!

**Comment by gewoon** [comment]
You can add me on skype, it's Volremort.

**Comment by AdnanCukur** [comment]
Fix is coming meanwhile you can check my comment in #151
