### ISSUE TITLE
Doesnt Recycle Berries

### ISSUE THREAD

**Issue by Fazy5** [NecronomiconCoding/NecroBot#1552]
It doesnt recycle razzberries and neither have nay option about it in the configs..
Kindly add this. Ty

**Comment by RoseFlunder** [comment]
In the "ItemRecycleFilter" there is an entry for "{
      "Key": "itemRazzBerry",
      "Value": 50
    }"

Did you check this?

**Comment by Fazy5** [comment]
Oh Sorry, didn't see that part of the part.. 
Ill close this. Thanks !
