### ISSUE TITLE
Amount of Poke/Great/Ultra Balls to keep

### ISSUE THREAD

**Issue by Mineller** [NecronomiconCoding/NecroBot#1563]
Hey 

I have a short question.

Is it possible to set the amount of Poke/Great/Ultraballs to keep other than the "TotalAmountOfPokebalsToKeep" so you could set it seperately?

Thanks alot

**Comment by hioRR** [comment]
yeh thats what iam asking myself with the healthpotions :-/ i just want to store the max ones and not the lower ones :-(

**Comment by recon88** [comment]
I made a pull request which allows to fully customize the recycler again. Let's see if it gets accepted ;)
