### ISSUE TITLE
Google.Protobuf.InvalidProtocolBufferException on Login

### ISSUE THREAD

**Issue by Bestora** [NecronomiconCoding/NecroBot#1565]
> `Initializing Rocket logger at time 8/1/2016 4:11:48 AM...
> [04:11:48] This is your first start and the bot has generated the default config!
> [04:11:48] We will now shutdown to let you configure the bot and then launch it again.
> Initializing Rocket logger at time 8/1/2016 4:12:10 AM...
> [04:12:11] Perfect! You already have the newest Version 0.4.0
> [04:12:11] Logging in using Ptc
> [04:12:13] Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
>    bei Google.Protobuf.CodedInputStream.SkipLastField()
>    bei POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input)
>    bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:Zeile 67.
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__9`1.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:Zeile 44.
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:Zeile 110.
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:Zeile 65.
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\LoginState.cs:Zeile 36.
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 36.
> [04:12:13] Logging in using Ptc`

**Comment by recon88** [comment]
Don't run the Bot on a VPS or dedicated server. Niantic seems to have banned a range of server IPs.

**Comment by Bestora** [comment]
The VPS was the issue -.-
thanks
