### ISSUE TITLE
Throw berries missing

### ISSUE THREAD

**Issue by Linewalker** [NecronomiconCoding/NecroBot#1568]
Has someone an idea to put berry throwing in?

**Comment by RoseFlunder** [comment]
There is already some logic in the code when a berry should be thrown. but i don't know if it is bugged or sth. Are you sure there are no berries used?

**Comment by Linewalker** [comment]
I haven't looked at the souce, if something for this is in it. Therefore the bot never uses a berry (in my case) it seems there's a bug in the routine.

**Comment by RoseFlunder** [comment]
Ok I try to check it. Maybe I can explain what happens

**Comment by Linewalker** [comment]
It's here: (isLowProbability && isHighCp) || isHighPerfection), CatchPokemonTask. Perhaps the numbers are wrong.

**Comment by RoseFlunder** [comment]
Ok I am working on it

**Comment by Linewalker** [comment]
The "var berries" always returns "null".

**Comment by RoseFlunder** [comment]
I got it working and made a pull request: [https://github.com/NecronomiconCoding/NecroBot/pull/1584](url)

**Comment by Linewalker** [comment]
I saw this an just testing it :-)

**Comment by Linewalker** [comment]
After the change the "var berries" still returns "null" so the event "return"s.

**Comment by RoseFlunder** [comment]
Are you sure you have razz berries in your inventory then?
There was no problem for me getting the razz berries from the inventory.
The only error was related to how the event was handled by the CLI.

**Comment by Linewalker** [comment]
Yes, sure.
It's working. I tested it now for three times always making sure, having enough razz berries. Thanks for the fix.

**Comment by RoseFlunder** [comment]
Then you could this issue to keep the list of issues short :)
