### ISSUE TITLE
TransferDuplicatePokemon doesn't work

### ISSUE THREAD

**Issue by Reijka** [NecronomiconCoding/NecroBot#157]
Hey, I'm not very good at coding so I'm just going to point out that it doesn't matter if TransferDuplicatePokemon is True or False, it still keeps the pokemon that are both low CP and low IV because they're the only ones.

Or am I doing something wrong?

My settings + example:
KeepMinIVPercentage = "85"
KeepMinCP = "10000"
TransferDuplicatePokemon = "False"
Didn't put Pidgeot in ConfigPokemonsToKeep.txt

Yet it refuses to transfer my **only** pidgeot with these stats: CP = 1151, IV = 21%

**Comment by gewoon** [comment]
I think because the code only transfers double Pokémon, if you only have one pidgeot, it won't be transferred.

**Comment by giesti** [comment]
Also, to use this functionality, you need to have : TransferDuplicatePokemon = "True"

**Comment by gewoon** [comment]
Probably when TransferDuplicatePokemon it doesn't transfer any Pokémon at all, also no when they meet the criteria.

**Comment by Reijka** [comment]
I want it to transfer ALL of my pidgeots unless they're above above IV 85%.

I have tried with TransferDuplicatePokemon False and True.. it doesn't change anything. :/

**Comment by giesti** [comment]
The program does not contain that functionality (yet?)

**Comment by dbfy** [comment]
Man  was going to go to sleep too.

**Comment by gewoon** [comment]
Yes sorry Reijka, but it's just not very responsable for the bot to delete Pokémon if you only have on of them...

**Comment by dbfy** [comment]
Ok inside Logic.cs
Find Function `        private async Task ExecuteFarmingPokestopsAndPokemons()`
at the end after `                if (_clientSettings.TransferDuplicatePokemon) await TransferDuplicatePokemon();`
add so it looks like
>                if (_clientSettings.TransferDuplicatePokemon) await TransferDuplicatePokemon();
                await TransferUnwantedPokemon();

Add this function anywhere inside Logic.cs
>        private async Task TransferUnwantedPokemon()
        {
            var sadUnwantedPokemon = await _inventory.GetPokemons();
            foreach (var pokemon in sadUnwantedPokemon.Where(p => _clientSettings.PokemonsDontWant.Contains(p.PokemonId)))
            {
                if (CalculatePokemonPerfection(pokemon) >= _clientSettings.KeepMinIVPercentage ||
                    pokemon.Cp > _clientSettings.KeepMinCP)
                    continue;
                var transfer = await _client.TransferPokemon(pokemon.Id);
                _currentPokemonCount--;
                var bestPokemonOfType = await _inventory.GetHighestPokemonOfTypeByCP(pokemon);
                Logger.Write(
                    $"{pokemon.PokemonId} with {pokemon.Cp} ({CalculatePokemonPerfection(pokemon).ToString("0.00")} % perfect) CP (Best: {bestPokemonOfType.Cp} | ({CalculatePokemonPerfection(bestPokemonOfType).ToString("0.00")} % perfect))",
                    LogLevel.Transfer);
                await Task.Delay(500); 
            }
        }

Then go to Settings.cs and add this anywhere
>        public ICollection<PokemonId> PokemonsDontWant => new[]
        {
            //Add pokemon here
            PokemonId.Pidgey,
            PokemonId.Rattata
        };
Then go to ISettings.cs and add this anywhere
>        ICollection<PokemonId> PokemonsDontWant { get; }

Now that's it, I didn't test it so good luck. It's IV value and CP value is based off of
`KeepMinIVPercentage` and `KeepMinCP`

Change below if you only want the VI
>                if (CalculatePokemonPerfection(pokemon) >= _clientSettings.KeepMinIVPercentage ||
                    pokemon.Cp > _clientSettings.KeepMinCP)
K gl.

**Comment by mczee** [comment]
I noticed the same issue:

CP set to 1200
IV to 85%
Transfer True
Configs all stock no Pinsir in there

Why is it not transferring these Pinsirs?

[code]
[07:28:28] ====== DisplayHighestsCP ======
[07:28:28] Requesting GetInventoryResponse
[07:28:28] # CP 1312	| (43,33	% perfect) NAME: 'Golduck'
[07:28:28] # CP 1300	| (55,00	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1253	| (60,00	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1223	| (45,00	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1202	| (36,67	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1169	| (46,67	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1149	| (38,33	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1128	| (28,33	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1117	| (23,33	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1108	| (43,33	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1098	| (15,00	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1089	| (35,00	% perfect) NAME: 'Pinsir'
[07:28:28] # CP 1078	| (26,67	% perfect) NAME: 'Pinsir'
[/code]

**Comment by dbfy** [comment]
because
>      public ICollection<PokemonId> PokemonsDontWant => new[]
    {
        //Add pokemon here
        PokemonId.Pidgey,
        PokemonId.Rattata
    };

**Comment by mczee** [comment]
Fixed @build 169
