### ISSUE TITLE
<ERROR> JSON Exception

### ISSUE THREAD

**Issue by Xalk444** [NecronomiconCoding/NecroBot#1572]
![default](https://cloud.githubusercontent.com/assets/20630520/17278832/248ddc54-576f-11e6-9c46-2ea590b3f4bc.jpg)
![default](https://cloud.githubusercontent.com/assets/20630520/17278847/8abf9148-576f-11e6-984a-b13e92cf2526.jpg)
What did I do wrong

**Comment by recon88** [comment]
Out quotes around mail and password like that:
"mail@gmail.com",
"mypassword",

**Comment by Xalk444** [comment]
LOL:Dhahahahahah I week could not solve the problem :DDDDD
