### ISSUE TITLE
[PTC] Account not verified after update to 0.4.0

### ISSUE THREAD

**Issue by Syxxxx** [NecronomiconCoding/NecroBot#1577]
Hello, i have update to 0.4.0 but is not working, Necrobot say alway account is not verified.
My bot accout is realy verified and the old release is working.
Thanks

**Comment by Lim-Dul** [comment]
I was just told that this is an issue with the username/password config. Switch them around in your settings - out the password as the username and vice versa. Of course this should be fixed...

**Comment by Syxxxx** [comment]
Thanks, is working.
