### ISSUE TITLE
[REQUEST] Different way to walk and catch pokemons.

### ISSUE THREAD

**Issue by Naprosnia** [NecronomiconCoding/NecroBot#158]
Walk and catch all pokemons in the same way they appear on this map 
https://github.com/AHAAAAAAA/PokemonGo-Map/
.
Like use pokestops and catch pokemons within a given space.

Equal to this option in the previous application. 
" Additionally, you can change the 10 after -st to any number. This number indicates the number of steps away from your location it should look, higher numbers being farther. "

**Comment by MSAlih1** [comment]
:+1: we already list wildpokemons.
should we add to list and check if appeared or not ? (for unique pokemons)

**Comment by Naprosnia** [comment]
We should give priority to unique / rare / list of pokemons  to catch.
