### ISSUE TITLE
[REQUEST] PowerUP Pokemons doesnt work/broken

### ISSUE THREAD

**Issue by Brucelats** [NecronomiconCoding/NecroBot#1581]
On Compiled (Release) version powering up pokemons doesnt work. I did put this settings:

  "AutomaticallyLevelUpPokemon": true,
  "LevelUpByCPorIv": "iv",

  "UpgradePokemonCpMinimum": 3000.0,
  "UpgradePokemonIvMinimum": 98.0,
  "UseGpxPathing": false,

This setings should choos my IV pokemons over 98% and power them up every 5 pokestops since my GPX path is not set.

But it doesnt do anything. I tried also with GPX path and still same issue.

I tried evolving, and evolving worked. IT evolved my pokemons over 98%. Now it would be amazing if i could power them up also.

REMINDER: THIS IS FOR COMPILED VERSION !

**Comment by kirito-su** [comment]
But it worked for me; Compiled Version 0.4.0

[16:50:12] (INFO) Pokemon Upgrade Failed Not Enough Resources 

Is what I'll see when i don't have enough resources to Upgrade. 

[16:24:03] Pokemon Upgraded:Flareon:550

Is what I'll see when I do.  But I don't have a CLUE as to the complete logic of why it chooses a pokemon it cannot upgrade.

**Comment by keinPlan** [comment]
it is working but you have to set UpgradePokemonCpMinimum to  0

**Comment by Brucelats** [comment]
ohhh

**Comment by kirito-su** [comment]
{
  "AmountOfPokemonToDisplayOnStart": 10,
  **"AutomaticallyLevelUpPokemon": true,**
  "AutoUpdate": true,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 
  "DefaultLongitude": ,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 1700,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 89.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
.................omitted to shrink text.
  "KeepMinCp": 1250,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  **"LevelUpByCPorIv": "iv",**
  "MaxPokeballsPerPokemon": 8,
  "MaxSpawnLocationOffset": 10,
  "MaxTravelDistanceInMeters": 1000,
  "MinDelayBetweenSnipes": 120000,
  "MinPokeballsToSnipe": 48,
  "MinPokeballsWhileSnipe": 30,
  ............. omitted to save space   ],
  "PrioritizeIvOverCp": true,
  "RenameOnlyAboveIv": true,
  "RenamePokemon": false,
  "RenameTemplate": "{1}_{0}",
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "StartupWelcomeDelay": true,
  "TotalAmountOfPokebalsToKeep": 222,
  "TotalAmountOfPotionsToKeep": 90,
  "TotalAmountOfRevivesToKeep": 20,
  "TransferConfigAndAuthOnUpdate": true,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  **"UpgradePokemonCpMinimum": 1000.0,**
  **"UpgradePokemonIvMinimum": 92.0,**
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseGreatBallAboveCp": 610,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseMasterBallAboveCp": 1500,
  "UsePokemonToNotCatchFilter": false,
  "UseSnipeLocationServer": true,
  "UseTransferIvForSnipe": false,
  "UseUltraBallAboveCp": 1000,
  "WalkingSpeedInKilometerPerHour": 30.477,
  "WebSocketPort": 14251,
  "UseSnipeOnlineLocationServer": true
}

**Comment by kirito-su** [comment]
I wouldn't set it to 0 because then its wasting on upgrading like a CP 10 Pidgey, which in its on right would be a waste of resources, *Stardust*

**Comment by darkendvoid** [comment]
Mine was picking one mon at start and upgrading that once than stopping.

Also an issue on first load where if it doesn't know your stardust it throws an exception and won't work until you disable it on conf file.
