### ISSUE TITLE
[Suggestion] Auto restart when stuck

### ISSUE THREAD

**Issue by Brucelats** [NecronomiconCoding/NecroBot#1582]
If it's possible it would be great to make bot auto restart. A lot of times it just get stuck at some point and nothing happens. Also option for turning off (press any key to continue) in config file would be great, otherwise restarts wouldnt make any sense.

Spigeli bot is nice in this issue. He auto restarts so it can bot for ages.

Thank you !

**Comment by Sehereje** [comment]
You can already turn the message off in the config 
"StartupWelcomeDelay": false,

And i agree, something like restarting bot every x mins would be awesome, or re-open it if it crashes

**Comment by NorwegianVikings** [comment]
Just make a .bat that terminates the process every x minutes and relaunches process after x delay. It would launch on your config lng+lat though (just like closing and relaunching the bot). So implementing something into the bot that remembers last known lng+lat and relaunches the bot on those coordinates would be the better option.

**Comment by recon88** [comment]
This can be done with a batch file like described by @NorwegianVikings
