### ISSUE TITLE
Fastest bot ever !

### ISSUE THREAD

**Issue by mfron** [NecronomiconCoding/NecroBot#1583]
![sans titre](https://cloud.githubusercontent.com/assets/11887274/17279297/d452bfaa-5770-11e6-8c32-366b4cdf8f5e.png)

https://github.com/mfron/Pokemon-Go-Bot

**Comment by Dgc2002** [comment]
Wow, this ass isn't just posting this here, but in a ton of other projects' issue section.

**Comment by myo** [comment]
i wanna downvote but i like it lol

**Comment by mfron** [comment]
Get it ! ^^

**Comment by dgateles** [comment]
I will port the ui to NecroBot for personal use :P

**Comment by OuttaControlX** [comment]
i gotta be real here,, this is rude af, but thats the ideal GUI, ripping it and adding it to necro.
