### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by Texiqq** [NecronomiconCoding/NecroBot#1589]
![not working](https://cloud.githubusercontent.com/assets/10067661/17279498/f17b6112-576c-11e6-8078-ce963ea1ed78.png)

Anyone know what the issue is?

**Comment by RoseFlunder** [comment]
Maybe there is something in a wrong format in your config which could not be parsed?
The error says it is trying to parse something which should  be number but fails to do so.

**Comment by actislav** [comment]
you are trying to start very old application or just sample application with Forex api

**Comment by recon88** [comment]
Please download the latest version und don't mess up the config file.
