### ISSUE TITLE
[Request] Renaming Pokemon according to their IV percentage

### ISSUE THREAD

**Issue by Darkztar** [NecronomiconCoding/NecroBot#159]
It would be great if the bot would rename the caught pokemon and the pokemon you already have (at the start time of the bot), which have the IV over the KeepMinIVPercentage value in the setting with their actual IV percentage.

E.g.: "Eevee" becomes "Eevee_93_33" 

So you would see in game, on which pokemon you should focus to evolve etc. without comparing with the data in the bot.

It would be a very great feature :)

Thank you for your work!

**Comment by gewoon** [comment]
Hmm you know Eevee can evolve in 3 different Pokémons if you rename them, right? So renaming them to Eevee_x_x would defeat that whole purpose. But if you don't care about that, an opational feature like that wouldn't harm i guess.

**Comment by BioMuell** [comment]
I also was thinking about that I already named them manually "97 33" and so on.

**Comment by Darkztar** [comment]
Eevee was just an example. 

I know that renaming her you can decide which evolution it will be, but only for the first time of each evolution. After that it is randomly which evolution it will be, nevermind which nickname.

So this option would be great and of course optional for those people who doesn't have all 3 evolutions of Eevee already.

**Comment by zno3** [comment]
With that pattern isn't it easy to detect if a lots of ppl are using this?

**Comment by Darkztar** [comment]
Other people doesn't see your pokemon unless you put them into Arena and if you want that, you can rename it by you self, but you will know your best pokemon to evolve/power up.

And if you mean if Niantic will see that, then I doubt the nicknames of the pokemon will be relevant and they will look for it^^

If they will ban us then according to the heavy traffic outcome of the bot and GPS spoofing ^^

Would be still a great feature :)

**Comment by gewoon** [comment]
You don't know what they are going to use to ban you. It's very unlikely that someone would rename their Pokémon this exact way. So you and others botters stand out.

**Comment by Darkztar** [comment]
you can/could calculate the IVs by your self and rename your pokemon: https://www.reddit.com/r/TheSilphRoad/comments/4te6bn/improved_iv_calculator_automatically_calculate/

So this is really not a reason that renaming the pokemon is a security concern for beeing banned.

But a nice to have...
