### ISSUE TITLE
Stuck in 2-Step Authentication

### ISSUE THREAD

**Issue by juventusland** [NecronomiconCoding/NecroBot#1590]
I signed up the pokemon go account with an university email (supported by google) and it has a 2-fact authentication. When I tried to run necrobot.exe. It shows following:

[14:03:47] As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
[14:03:47] Opening Google App-Passwords. Please make a new App Password (use Other as Device)

Then a new browser open up. I signed in with university account and it brought to me the "App passwords" page, but with errors "The setting you are looking for is not available for your account". I have nowhere to create an app pwd, or bypass 2 step authentication.

Note: When I signed into Pokemon Go from smartphone, it automatically redirect me to the university login web to complete the 2-step authentication. Any suggestion?

**Comment by Dancanplay** [comment]
If there's no way to obtain the token by yourself, contact your admin at university.

**Comment by recon88** [comment]
As @Dancanplay said, you would have to contact someone at your university.
