### ISSUE TITLE
Always using lucky eggs when "UseLuckyEggConstantly": true??

### ISSUE THREAD

**Issue by kanfkasndklasdn** [NecronomiconCoding/NecroBot#1597]
Every minute: (Info) Used a Lucky Egg

**Comment by cawk** [comment]
what does it say about incense?

**Comment by kanfkasndklasdn** [comment]
It said exactly what I commented in first message: (Info) Used a Lucky Egg. I don't know if it's trying to use one new egg, cause I don't think that you can use various simultaniously

**Comment by cawk** [comment]
no what i am asking is what does it say about INCENSE not the egg since they run basically the same

**Comment by kanfkasndklasdn** [comment]
Oh, sorry. It said Incense already active.

**Comment by cawk** [comment]
yeah its an issue it will be resolved soon

**Comment by cawk** [comment]
this has been fixed so can be closed
