### ISSUE TITLE
wierd behavior, bot transferring pidgey, weedle even i have set it to evolve :(

### ISSUE THREAD

**Issue by aapikz** [NecronomiconCoding/NecroBot#1604]
why my bot transfering pidgey...even i set to EVOLVE?? :(
im pretty sure i have enough amount of candies.. wierd

![not evolving](https://cloud.githubusercontent.com/assets/14224262/17279896/2e7c1052-5736-11e6-994b-640a2f897635.png)

"EvolveAllPokemonWithEnoughCandy": true,   
"KeepPokemonsThatCanEvolve": true,
"EvolveAllPokemonAboveIv": false,
EvolveAboveIvValue": 1.0,

"PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey"
  ],

**Comment by recon88** [comment]
First of all, remove the " , " after pidgey

**Comment by aapikz** [comment]
yep lol there's rattata after pidgey i just clean it up for to post here..... 
but my problem is my evolve list contintue transfering, even i have enough canides

**Comment by recon88** [comment]
Set "EvolveAllPokemonAboveIv" to true

**Comment by aapikz** [comment]
wtf i set"EvolveAllPokemonAboveIv" true .. but it evolves ALL MY POKEMON  it completely ignores my evolve list.... rip 800cp eevee suposed to be named to rainier for vaporeon but becomes flareon wtf noooo "im crying*

**Comment by recon88** [comment]
Oh well, didn't know it would ignore your list, sorry for that.
Also KeepPokemonsThatCanEvolve needs to be false, that should be the proper fix to your issue.
