### ISSUE TITLE
IApiFailureStrategy could not be found

### ISSUE THREAD

**Issue by nicchristeller** [NecronomiconCoding/NecroBot#1611]
![image](https://cloud.githubusercontent.com/assets/16927923/17280163/624aed3e-57dd-11e6-8a7e-120afbc5d4d1.png)

A fresh download of the repository leaves me with this error in the class ApiFailureStrategy. Also not found is ApiOperation. I'm unsure what has gone wrong, or how to sort this. Could someone point out the problem?

**Comment by cawk** [comment]
use the forked api from yamashi not the ferox api one

**Comment by nicchristeller** [comment]
Aha, that makes a lot of sense. Thank you.

**Comment by deathart** [comment]
Api from yamashi is delete :/
