### ISSUE TITLE
Account no verified

### ISSUE THREAD

**Issue by suppoo** [NecronomiconCoding/NecroBot#1613]
Tried to login with ptc account and bot gives this error? account is activated thru email and works on the phone

**Comment by JamesHeshka** [comment]
Check that you're entering the Username in the username field.

Recent changes made the generated config populate the password before the username for PTC. 

eg
{
  "AuthType": "ptc",
  "GooglePassword": null,
  "GoogleRefreshToken": null,
  "GoogleUsername": null,
  "PtcPassword": "mypassword",
  "PtcUsername": "MyUserNameIsSecond"
}
