### ISSUE TITLE
v.5 changes the config to use great/ultra/master balls

### ISSUE THREAD

**Issue by lolcheat321** [NecronomiconCoding/NecroBot#1618]
Change your configs so that:

  "UseGreatBallAboveIv": 100000,
  "UseUltraBallAboveIv": 100000,

To keep the script from tossing your good balls at the pokemon.

**Comment by otong123** [comment]
thank you sir

so helpfull

it work

**Comment by ahmadsafar** [comment]
fix with this [https://github.com/NecronomiconCoding/NecroBot/pull/1619](url)
