### ISSUE TITLE
[Request] SLOW DOWN

### ISSUE THREAD

**Issue by Shroomzie** [NecronomiconCoding/NecroBot#1645]
Why is this master branch practically always broken. Please stop the mass merging without testing. thats what a test branch is for. you have enough people to test so why are you STILL merging and breaking a master branch. its so amateur am a ridiculous thing to do to devs who want to contribute.

Its a joke that you have everyone fixing your stupid jokes all the time instead of working on their own implementations! Sort your shit out or just don't even bother.

**Comment by septemus** [comment]
They're only human, alright bro? Calm down. Just `git reset HEAD~1` and you should be fine.

**Comment by Shroomzie** [comment]
@septemus Merging code to a master branch that breaks is a good thing? Back to codecadamy for you .

**Comment by septemus** [comment]
It's not like you're perfect man. These guys are doing everything for free, cut them some slack. Instead of complaining, maybe you could help fix it instead of whining?

**Comment by IsBoris** [comment]
+1 to close the issue

**Comment by Shroomzie** [comment]
septemus IsBoris  you two twits don't seem to understand because you don't actually belong here. it has nothing to do with time spent here or whatever scrub. Its about how to properly run this type of project. 

Meh, what am i doing bothering anyhow, looks like this project is full of thug wannabe cheerleaders chanting necro. when all he is doing now is making it 100% difficult for people to work on the project, because he dosn't even have a dev branch so he dosnt stop breaking the master. gj dickheads!

**Comment by septemus** [comment]
The recent breakage is my fault. Alright? No need to blame Necro. Sure, he merged it, but that's because I assured him it was working (even though it isn't. Maybe some quirk with my setup). Instead of complaining about a free, open-source project not working, maybe contribute to it? That way you can make it better and fix the issues that you have.

**Comment by dddbliss** [comment]
Your lack of coherent useful information in this issue @Shroomzie is amazing. Criticism never helps successfully solve any issue. Either offer useful input or don't offer any at all.

+1 to close.

**Comment by Shroomzie** [comment]
What you are not getting is merging code to a master that breaks it wastes everyones time. 

Because you keep arguing its not the problem and by doing it you are not wasting everyones time then im done here.

**Comment by Energex22** [comment]
Although, i have just tried compiling all the release source code's, and i cannot got one to compile without an error....

**Comment by IsBoris** [comment]
@Shroomzie ride a bike or something, you have some major issues...

**Comment by Shroomzie** [comment]
@IsBoris good job, i see you contributing nothing to the topic again but thuggery.

back to your circle jerk scrub project. see how far you get with it full of jerks like you. 

Im betting you haven't even donated to these guys, making you just some cheap leeching scumbag cheerleader who jerks everyone off. As tho thats payment for all the work gone into it.

**Comment by Energex22** [comment]
And the current last 2 builds and master i am getting this issue....
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'H:\Game Other\Poken.on Go bots\New Folder\NecroBot-master\PoGo.NecroBot.Logic\bin\Debug\PoGo.NecroBot.Logic.dll' could not be found	PoGo.NecroBot.CLI	H:\Game Other\Poken.on Go bots\New Folder\NecroBot-master\PoGo.NecroBot.CLI\CSC	1	Active
Error	CS2001	Source file 'H:\Game Other\Poken.on Go bots\New Folder\NecroBot-master\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs' could not be found.	PoGo.NecroBot.Logic	H:\Game Other\Poken.on Go bots\New Folder\NecroBot-master\PoGo.NecroBot.Logic\CSC	1	Active
`

**Comment by andrewda** [comment]
Not sure what you're not getting @Shroomzie, but the `master` branch is almost always unstable. If you want a stable build, go ahead and download one of the releases. Otherwise, stop complaining.

**Comment by septemus** [comment]
@Shroomzie I do hope you know, however, that reverting it will not fix anything. Yamashi deleted his API repo which we were using, so either way the API is broken.

**Comment by Shroomzie** [comment]
Thanks, you guys have 0 clue what you are saying. im out. good luck keeping anyone.
