### ISSUE TITLE
Upgrade to 5.0 caused some instability in config file - causing it to use ultra balls only

### ISSUE THREAD

**Issue by zimmey** [NecronomiconCoding/NecroBot#1648]
I know for me, it changed the 

  "UseGreatBallBelowCatchProbability": 0,
  "UseUltraBallBelowCatchProbability": 0,

This was causing the "using only ultra balls" problem.

I ended up removing my config and recreating it, then moving my changes over so it would work properly again.

**Comment by zimmey** [comment]
My suspicion is that during the auto-update, because there are some changes in the config file, that some of the new values aren't being set properly.

**Comment by jonesbones23** [comment]
I think the use of pokeballs is based off IV. I've changed "UseGreatBallAboveIv": and "UseUltraBallAboveIv": so im back to using pokeballs

**Comment by solusipse** [comment]
For me, upgrading to 0.5 completely replaced my old config file.

**Comment by rs1200** [comment]
This fixed it for me 

  "UseGreatBallAboveCp": 600,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 90,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.50,
  "UseUltraBallBelowCatchProbability": 0.20,
  "UseMasterBallBelowCatchProbability": 0.10,

**Comment by Aneduna** [comment]
Set rs1200 Values in the settings, happening because #1678
