### ISSUE TITLE
Auto favorite over IV is spamming

### ISSUE THREAD

**Issue by zimmey** [NecronomiconCoding/NecroBot#1650]
version 5.0

I'm not sure if it is continually favoriting, or if it is just announcing over and over, but every 5 pokestops it says the same pokemon are 'favorited'.

**Comment by Beltian** [comment]
Its not actually favoriting them, its trying over and over again to favorite them. I checked this while logged into nox aswell, and when i manually favorited them the messages went away.

**Comment by recon88** [comment]
Check #1650 for further updates
