### ISSUE TITLE
Number of caught pokemon is inaccurate

### ISSUE THREAD

**Issue by zimmey** [NecronomiconCoding/NecroBot#1651]
(INFO) Amount Of Pokemon Seen:106:151, Amount Of Pokemon Caught:106:151

This should be

(INFO) Amount Of Pokemon Seen:106:151, Amount Of Pokemon Caught:**105**:151

**Comment by Energex22** [comment]
mines correct....

**Comment by dddbliss** [comment]
See #1646 for pr to fix.

**Comment by zimmey** [comment]
Perfect, should I close this?

**Comment by dddbliss** [comment]
Only if PR is accepted.

**Comment by recon88** [comment]
This issue was fixed.
