### ISSUE TITLE
[Request] Periodic status note

### ISSUE THREAD

**Issue by zimmey** [NecronomiconCoding/NecroBot#1659]
Would be nice to have a periodic (every 5 minutes or something) update that showed total uptime, number of XP, how much till next level, number of xp/hr currently, number of pokemon caught per hour, number of high IV pokemon caught, something similar.

**Comment by dddbliss** [comment]
Doesn't this already show in the title bar of the window?

**Comment by Energex22** [comment]
Would be nice if the window could be bigger than 1/2 the screen or there about.... But that will come with a Gui, if one ever happens...

**Comment by zimmey** [comment]
For some reason, never saw it in the title bar. Might be nice to have it in the list, but isn't critical.
