### ISSUE TITLE
Search pokemon then pokestops

### ISSUE THREAD

**Issue by holyst4r** [NecronomiconCoding/NecroBot#166]
Hi, usually I try to open the bot on a location to catch a pokemon that spawned there. As I understand, the bot first try to get to a near pokestop and then do a search in the area for nearby pokemons. 
I think it would be better if the search for nearby pokemon starts as soon as it spawns. Also, there should be a short delay first (I noticed with an emulator that I had to wait 5-6 seconds before the pokemon I knew it was there would appear).

**Comment by AdnanCukur** [comment]
The bot finds nearest pokestop and walks to it from your location, after every step it takes, it looks around if there are any pokemon nearby.

**Comment by holyst4r** [comment]
Then why it can't see pokemon that I see on pokevision? While going there with nox make them spawn. Maybe it starts to walk too soon? 
Also I've noticed that the default walking speed is 50km/h ? Is it ok ?

**Comment by Aninokaze** [comment]
It doesnt see Lures

**Comment by holyst4r** [comment]
That's not the case. I used Nox, went to the exact same spot, waited 5-6 seconds and the pokemon I knew was there appeared and I was able to caught it.

**Comment by ReddoKiddo** [comment]
Might be incense pokemon from someone else, but this will be fixed in future version (as soon as ferox updates our api) so I will close it for now
