### ISSUE TITLE
Online Snipe is not working in the Compiled Release Setup

### ISSUE THREAD

**Issue by koubie** [NecronomiconCoding/NecroBot#1674]
![snapshot_2016-07-31_205745](https://cloud.githubusercontent.com/assets/20736025/17283104/9ce60b30-5761-11e6-902e-140465fdcbc5.png)
It was working great modified by @Tsuki on the v0.4.0 version yesterday by using Online Snipe http://pokesnipers.com/
now is not working no more with the v0.5.0. anyone can help please

**Comment by Cuuup** [comment]
I'm pretty sure everyone is having this issue. Just wait patiently for devs to fix.

**Comment by koubie** [comment]
@Cuuup  
yeah I thought they merged the pull request from @Tsuki on the v0.4.0 into the v0.5.0
It was working awesomely though by using Online Snipe Location Server since  the pokevision has been down.

**Comment by Tsuki** [comment]
The pr is loss in 0.5.0 without that logic

**Comment by chimichandra** [comment]
Its working with discord. Pokevision is down, so that option should be deleted

**Comment by koubie** [comment]
Pokevision has been down but @tsuki made it work yesterday on the v0.4.0 by using online location server provided by http://pokesnipers.com/ though

**Comment by AriSrijaya** [comment]
@Tsuki can you update it tsuki to 0.50 based?

**Comment by recon88** [comment]
Try:
"SnipingScanOffset": 0.003,
or higher
