### ISSUE TITLE
account not verified?

### ISSUE THREAD

**Issue by nignogasaurus** [NecronomiconCoding/NecroBot#1676]
idk what thats actually supposed to mean, i used necrobot a day or so ago with same account it was fine and redownloaded the new one tonight and set it all up in auth and config but get that error and it closes

**Comment by Lucifirius** [comment]
I had the same issue when I was using ptc as the login method. It was fixed
when I took a look at auth.json and noticed the parts for the username and
pass were reversed so try taking a look at that.

**Comment by nignogasaurus** [comment]
oh yupp 100% right haha password was my username and username password, thanks very much man

**Comment by dddbliss** [comment]
Tracking this in #1677

**Comment by konchim** [comment]
oh~yes, it XXXKing treat
