### ISSUE TITLE
Evolve does not continue even lucky egg time has not ended yet

### ISSUE THREAD

**Issue by caihongxu** [NecronomiconCoding/NecroBot#1680]
When UseLuckyEggsMinPokemonAmount is reached and lucky egg is triggered. It just evolved all the currently available ones. When new evolve becomes available it does not evolve, but wait for UseLuckyEggsMinPokemonAmount to be reached again, even the lucky egg time has not ended yet.

**Comment by rherartt** [comment]
after you evolve the currently available ones change this to "KeepPokemonsThatCanEvolve": false,

**Comment by caihongxu** [comment]
No I don't think it is related to that. I always have KeepPokemonsThatCanEvolve to set to true and did not have the same issue in older versions.

I actually just found out it is related to recently added EvolveKeptPokemonsAtStorageUsagePercentage. After I change it to something lower (it defaults to .9), it then continue to auto evolve.

What is this parameter for? It is really confusing to me.

**Comment by rherartt** [comment]
when I did what i told you it worked :)

**Comment by caihongxu** [comment]
I will close this one. Really hope someone can explain the use case of EvolveKeptPokemonsAtStorageUsagePercentage though.
