### ISSUE TITLE
Disconnect/Bot interruption "ERROR CURRENT OPERATION WAS CANCELED"

### ISSUE THREAD

**Issue by Mr-SoloSilver** [NecronomiconCoding/NecroBot#1683]
![bug2](https://cloud.githubusercontent.com/assets/20763544/17283799/8cad1e5e-5782-11e6-84fa-a1461a942375.PNG)

Forces you to hit "enter" key again, interrupts bots while i'm away.

**Comment by Aneduna** [comment]
When did you have to press Enter
Before or after the Error Message?

**Comment by Mr-SoloSilver** [comment]
After the error message.

Right after the error message the bot logs you into your google/ptc account all over again and forces you to press enter.

**Comment by Aneduna** [comment]
it might be the   "StartupWelcomeDelay": true, that is messing you up

try changing   "StartupWelcomeDelay": false in the config

**Comment by Earisu** [comment]
Can confirm, it's the "StartupWelcomeDelay": true that's causing the "enter key to continue".
It happens to me.
