### ISSUE TITLE
ATTENTION! You're outside of your defined radius! 

### ISSUE THREAD

**Issue by Mr-SoloSilver** [NecronomiconCoding/NecroBot#1684]
![bug3](https://cloud.githubusercontent.com/assets/20763544/17283863/4be89898-5783-11e6-83ec-f4dd5fedd645.PNG)

I've been experiencing this since the last update I believe,  forces me to restart the bot.

**Comment by Aneduna** [comment]
This might be related to the recent changes to Throttling Requests (looking at the 00:28:46 Error)

Also related might be the Sniper in the combination with the throttling (im not sure how the Sniper works)

**Comment by actislav** [comment]
if u using snipe i finally fix it in @ #1706

**Comment by recon88** [comment]
This should have been fixed. Download the latest version.

**Comment by Mr-SoloSilver** [comment]
@recon88 I am on the latest release 0.5
