### ISSUE TITLE
Keep Pokemons that Can Evolve

### ISSUE THREAD

**Issue by Fluxty** [NecronomiconCoding/NecroBot#1685]
Can there be a way to keep Pokemon that can evolve ONLY if they are on the Pokemon to evolve list?

**Comment by rherartt** [comment]
for me its working like that in this last version

**Comment by Fluxty** [comment]
Okay, I was just reading on the wiki and it didn't say anything about it (didn't actually test it). I'm trying to go to bed with the best settings possible and was worried my pokemon inventory would be full if it was keeping all the stuff not on my evolve list.

**Comment by actislav** [comment]
in commit [6ebbcbc] simplyphp added code which check is pokemon to keep in list to evolve
