### ISSUE TITLE
What is this? Keep poping and won't start.

### ISSUE THREAD

**Issue by AIphaz** [NecronomiconCoding/NecroBot#1686]
![wow](https://cloud.githubusercontent.com/assets/20764984/17283970/352a222e-5784-11e6-86ea-fb2e21cc4add.jpg)

I got this the whole time. Need patch or some sort of fix|?

Thx

**Comment by Zerofy** [comment]
it was just fixed update it.

**Comment by AIphaz** [comment]
thank you
