### ISSUE TITLE
Error while running self compiled bot.

### ISSUE THREAD

**Issue by jakerxiii** [NecronomiconCoding/NecroBot#1696]
I am unable to compile from source, I get this error when I run: 
![2016-08-01](https://cloud.githubusercontent.com/assets/19394044/17285433/8f1832b8-57ba-11e6-82ed-08b6c0478bab.jpg)

**Comment by Aneduna** [comment]
Is this the full error?

**Comment by jakerxiii** [comment]
Yes it is @Aneduna

**Comment by Aneduna** [comment]
Are you using a special Localisation (other language)?

**Comment by jakerxiii** [comment]
No, I'm running the default engilsh.

**Comment by antwa** [comment]
> I am unable to compile from source
your screen shoot  its log from compiled version not from VS IDE.
CMIIW

**Comment by jakerxiii** [comment]
@antwa 
Your right, I'm just stupid. Sorry, It is actually an error when running what I compiled, Thankyou.

**Comment by Aneduna** [comment]
Can you try making a break point in  GetPokeDexCount.cs in line 27? It seems like the data is somehow malformed

**Comment by jakerxiii** [comment]
http://pastebin.com/2spE66jU Is the GetPokeDexCount.cs file if that helps and I still get the same error.

**Comment by Aneduna** [comment]
My own compile isn't working at the moment, but i haven't been getting the error anyways.

After setting the breakpoint in that line, please run the program in vs and wait for the breakpoint to trigger (it should), then look in the lower left corner of vs and step through the program till you see the string translation. Then please post the translation.

**Comment by jakerxiii** [comment]
![image](https://cloud.githubusercontent.com/assets/19394044/17286110/2b4df88a-57bf-11e6-9999-1af22840565a.png)

What should i press?

**Comment by antwa** [comment]
move your cursor into 
`PokeDex.Count`
post value here

**Comment by Aneduna** [comment]
The Variables are under the Locals Tab in the bottom left corner

**Comment by jakerxiii** [comment]
![image](https://cloud.githubusercontent.com/assets/19394044/17286190/c8f423c0-57bf-11e6-8806-e56e6af38c23.png)

**Comment by brujah** [comment]
for (int i = 0; i < PokeDex.Count; i++)
            {
                if (PokeDex[i].ToString().Contains("timesCaptured")){
                    var CaughtPokemon = PokeDex[i].ToString().Split(new[] { "timesCaptured" }, StringSplitOptions.None);
                    var split = CaughtPokemon[1].Split(' ');
                    int Times = int.Parse(split[1]);
                    if (Times > 0)
                        timesCaptured++;
                }
                
            }

**Comment by brujah** [comment]
Fixes the problem

**Comment by jakerxiii** [comment]
![image](https://cloud.githubusercontent.com/assets/19394044/17286211/013fffce-57c0-11e6-9c52-f3818084f19b.png)
@Aneduna and trying your fix now @brujah

**Comment by Aneduna** [comment]
if you now click the icon with the little blue arrow pointing to the grey circle right to the run button that you clicked, you step 1 step further into the program and you can see what happens with the variables

**Comment by Aneduna** [comment]
@brujah if it works, thats nice. Consider making a pull request. or is it already fixed in the current build?

**Comment by brujah** [comment]
@Aneduna Not in the current build, will try and add a PR for it now

**Comment by jakerxiii** [comment]
![image](https://cloud.githubusercontent.com/assets/19394044/17286381/2e67d908-57c1-11e6-8978-126cb7ac42dc.png)
Is the error I get now after using @brujah's fix

**Comment by Aneduna** [comment]
Seems like the same error

**Comment by brujah** [comment]
Not sure but if you update Translations.cs to the following you can run the bot:

public string GetTranslation(TranslationString translationString, params object[] data)
        {
            try
            {
                var translation = _translationStrings.FirstOrDefault(t => t.Key.Equals(translationString)).Value;
                return translation != default(string)
                    ? string.Format(translation, data)
                    : $"Translation for {translationString} is missing";
            }
            catch (System.Exception ex)
            {
                return "Problem with translation!";
            }
            
        }

**Comment by brujah** [comment]
@jakerxiii  Yeah, someone who knows code better than me can fix the actual problem. You should be able to run the code now though.

**Comment by jakerxiii** [comment]
Thankyou so much, all of you. This is a really kind community.
