### ISSUE TITLE
Should I make "UseSnipeOnlineLocationServer" true if I ran PogoLocationFeeder.exe?

### ISSUE THREAD

**Issue by duanpingbo** [NecronomiconCoding/NecroBot#1700]
Whats the difference between "UseSnipeOnlineLocationServer" and "UseSnipeLocationServer"?

**Comment by slxdegrees** [comment]
SnipeLocationServer uses Discord while the other one uses sites like pokesnipers.com etc.

**Comment by duanpingbo** [comment]
@slxdegrees Can they be used both?

**Comment by slxdegrees** [comment]
@duanpingbo I am not sure. But since the wiki states explicitly to choose between either, maybe only 1 can be used at any time.

**Comment by duanpingbo** [comment]
@slxdegrees Got it. Thank U.
