### ISSUE TITLE
No Snipe

### ISSUE THREAD

**Issue by KraJinka** [NecronomiconCoding/NecroBot#1708]
Hi guys, my snipe setup is not working and I wonder what I did wrong. Can anyone share any working snipe setup with me? I already did requirements true and I am using pogolocationfeeder also

**Comment by W1-PopelierE** [comment]
"PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": -37.7651298,
        "Longitude": 145.3509665
      },
      {
        "Latitude": 52.936191,
        "Longitude": 4.726726
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],

But currently the scanner is offline (pokevision.com) since niantic fixed it.

**Comment by Rabelaiss** [comment]
Sniping with manual locations is not possible (pokevision down)
BUT sniping with automatic locations is possibile (its working for me right now)
Follow this guide https://github.com/NecronomiconCoding/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by Harachteh** [comment]
A good guide can be found here https://github.com/NecronomiconCoding/NecroBot/wiki/Sniping-Setup
