### ISSUE TITLE
Sniping via PokeVision

### ISSUE THREAD

**Issue by W1-PopelierE** [NecronomiconCoding/NecroBot#1712]
Sniping via Pokevision won't work anymore because niantic fixed the map and now pokevision can't view the pokemons on a map. 
This is the cause why Sniping isnt having any result

**Comment by WaRMacTep** [comment]
use this website http://pokesnipers.com/

**Comment by recon88** [comment]
The bot is currently using https://skiplagged.com/pokemon/
