### ISSUE TITLE
evolves with eggs not working when i have 30 pokemon. (it wont use the egg)

### ISSUE THREAD

**Issue by pacinoallstars** [NecronomiconCoding/NecroBot#1715]
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": false,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 0,
  "GetMinStarDustForLevelUp": 0,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1500.0,
  "UpgradePokemonIvMinimum": 90.0,
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 37.808966,
  "DefaultLongitude": -122.410153,
  "WalkingSpeedInKilometerPerHour": 19.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 0,
  "DelayBetweenPokemonCatch": 1000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "KeepPokemonsThatCanEvolve": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 0.9,
  "KeepMinCp": 1500,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,
  "PrioritizeIvOverCp": true,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": true,
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "TotalAmountOfPokebalsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 0,
  "UseUltraBallAboveIv": 0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "TransferDuplicatePokemon": true,
  "FavoriteMinIvPercentage": 0.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magikarp": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "magmar",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by mcdax** [comment]
Same problem here (since the last update)

**Comment by oebanez** [comment]
yeah me too. when i use last version

**Comment by erikeleria** [comment]
It's working. https://i.imgur.com/jG5SWN0.jpg

**Comment by mcdax** [comment]
In my case:
"(UPDATE) [Evolves] Potential Evolves: 67 | 60 required for mass evolving" and nothing happens.

Can we see your config?

**Comment by mcdax** [comment]
Even if I use the egg manually or set  "UseLuckyEggsWhileEvolving" to false,
it won't work.

**Comment by bittzz** [comment]
might have somthing to do with new implementation of "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,

wait and see if your inventory gets full

**Comment by alexeymalihin** [comment]
@bittzz is right. Changed "EvolveKeptPokemonsAtStorageUsagePercentage" to 0.1 - evolved 60 pokemons. Look at EXP/H :smile: 

![image](https://cloud.githubusercontent.com/assets/8103832/17292361/37a1a90a-57f2-11e6-9f60-2ed8f22d6d2f.png)
