### ISSUE TITLE
Standing still at lures

### ISSUE THREAD

**Issue by PumbaMelbye** [NecronomiconCoding/NecroBot#1720]
Is it possible to make the bot stand still at a/some lure(s)? In that way, the bot will only find pokemons from the lures?

**Comment by Aneduna** [comment]
It is currently not possible. I'm not even sure if it would be beneficial because you dont go to pokestops.

**Comment by sawirth** [comment]
you can set a GPX Path or a really small `MaxTravelDistanceInMeters` around the location of the lure pokestop but that is not a recommending config as @Aneduna mentioned

**Comment by Harachteh** [comment]
A lure will attract 5-7 Pokemon over 30 minutes. Is there any reason why you would prefer waiting?

**Comment by ShaggyHW** [comment]
there are 4 lure places that people constatly farm with nox/bluestacks, and with the right bot settings you could get 6/7 lures at the same time that could net a pokemon a minute if your lucky

**Comment by recon88** [comment]
As mentioned, use GPX Path
