### ISSUE TITLE
No recycling: Help me please

### ISSUE THREAD

**Issue by xdiablo1990** [NecronomiconCoding/NecroBot#1721]
![no recy](https://cloud.githubusercontent.com/assets/20770238/17291299/5b556a26-57e3-11e6-8bfa-3872d32b8a7b.png)

**Comment by Aneduna** [comment]
It is Recycling. Set   "VerboseRecycling": true, if you want to see what is recycled.

**Comment by xdiablo1990** [comment]
ty man work! :)

**Comment by xdiablo1990** [comment]
I want to see my inventory, that option is?

**Comment by Aneduna** [comment]
Balls are sometimes printed but anything else doesn't, Use https://github.com/nicoschmitt/necrobotvisualizer or something else (even an emulator or you phone) to visualize

**Comment by xdiablo1990** [comment]
before the upgrade I could see how many pokeball, great ball, Ultraball, all within the bot now does not leave me.

**Comment by xdiablo1990** [comment]
before the upgrade i could see how many pokeball, great ball and ultra ball i have left, but now its not showing it

**Comment by recon88** [comment]
Set ShowPokeballCountsBeforeRecycle to true
