### ISSUE TITLE
Multiple Incubators

### ISSUE THREAD

**Issue by DeOrthodox** [NecronomiconCoding/NecroBot#1724]
Is there anyway to make the bot use the other incubators? it seems like now its only using the infinite one? what about the 3 use ones?

**Comment by pacinoallstars** [comment]
if this is with the latest version it must be a bug, because i know it used all of the incubators (up to 6) in the past .

**Comment by Megurine** [comment]
https://github.com/NecronomiconCoding/NecroBot/issues/1718
