### ISSUE TITLE
no ConfigConfigPokemonsNotToCatch.ini file...

### ISSUE THREAD

**Issue by PlazmaDragon** [NecronomiconCoding/NecroBot#1726]
Im catching so many darn pidgeys and hating it. What do i do for the file to show?

**Comment by Aneduna** [comment]
It exists. 
"UsePokemonToNotCatchFilter":

**Comment by dddbliss** [comment]
To add to @Aneduna, it is part of your configuration file. It is not a separate file.

**Comment by dddbliss** [comment]
Tracked in #1759
