### ISSUE TITLE
suggestion for transtering pokemons

### ISSUE THREAD

**Issue by ozntyr** [NecronomiconCoding/NecroBot#1728]
Choosing between cp or iv is relly defficult because when a pokemon has high cp it has mid or low iv and seeing cp 900+ pokemons transferred because cp 10s is really annoying :D so I suggest to add a new filter for mixed check like;
a=0.9
b=0.5
a*lvl+b*iv=value
if value<currentmaxvalue transfer pokemon

example;
pokemon1: lvl=25, iv=80 => value=6.25
pokemon2: lvl=1, iv=98 => value=4.99
so keep pokemon1 
or;
pokemon1: lvl=25, iv=80 => value=6.25
pokemon2: lvl=17, iv=98 => value=6.43
so keep pokemon2

stardusts are the hardest thihgs to get so I'd rather keep lower iv pokemon instead of higher one

**Comment by Revoss** [comment]
Who cares about CP, IV is the most important imo. Use the bot a couple of days and keeping the highest IV one should be worth

**Comment by ozntyr** [comment]
well imo stardust is the most impertant :D

**Comment by jaypeeb0917** [comment]
You are already botting. Stardust is NOT A PROBLEM.

**Comment by bulubebek** [comment]
I have at least 300k unused stardusts on my running bot. :)
For CP/IP problems, bot able to make a good adjustment, just leave it run for a day or two with proper configuration.

**Comment by recon88** [comment]
Stardust really should not be a problem, if you let run the bot for a day or two. I'm swimming in millions of dust at level 36 ;)
