### ISSUE TITLE
Bot keeps recycling all of my pokeballs and other items

### ISSUE THREAD

**Issue by inSaiyanxo** [NecronomiconCoding/NecroBot#1729]
Hi, the bot keeps recycling all of my pokeballs and other various items even though I wrote in the config for it to keep a minimum 100 pokeballs.
![2151617](https://cloud.githubusercontent.com/assets/20771030/17292168/6d745396-582b-11e6-9448-8864d6e77f4f.png)

edit: This wasn't a problem in previous versions, it started happening in version v.0.5.0

**Comment by somani6** [comment]
Check the following settings:

```
"ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      **"Key": "itemPokeBall",**
      "Value": 225
    },
    {
      "**Key": "itemGreatBall"**,
      "Value": 100
    },
    {
      **"Key": "itemUltraBall"**,
      "Value": 200
    },
    {
      **"Key": "itemMasterBall",**
      "Value": 100
    },
```
If they are missing, what they might, just add them.

**Comment by inSaiyanxo** [comment]
Hi thanks for the reply, my settings for those are good.
I think I may have found the problem:

  "TotalAmountOfPokebalsToKeep": 150,
  "TotalAmountOfPotionsToKeep": 10,
  "TotalAmountOfRevivesToKeep": 20,

Does the 'pokebal' in that setting includes every single type of pokeball?

**Comment by inSaiyanxo** [comment]
My current settings:
 "TotalAmountOfPokebalsToKeep": 100,
  "TotalAmountOfPotionsToKeep": 10,
  "TotalAmountOfRevivesToKeep": 20,
[Omitted unneeded settings]
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 100
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 200
    },

Anything wrong with this?

**Comment by theloser** [comment]
You only need "TotalAmountOfPokeballsToKeep", there are no "Key: itemPokeBall" etc. settings anymore, I think.

And regarding your screenshot and your setting: you had TotalAmountOfPokeballsToKeep set to 100. And your screenshot shows you had 71 Pokeballs, 12 Greatballs and 173 Ultraballs. Because you got 71+12+173 in total (which is more than the 100 you want to keep), the bot recycles unwanted balls -- first Pokeballs, then Greatballs.

**Comment by somani6** [comment]
i think theloser is right. Just reviewed the code. No more individual Filters. If you have that much Ultraballs, just increase the TotalAmountOfPokeballstoKeep value or set it to 0 in this case there will no Balls recycled.

UltraBalls will never be recycled.

**Comment by inSaiyanxo** [comment]
Awesome, thanks guys! This never happened before so it was quite confusing for me.
