### ISSUE TITLE
pokeball, greatball and ultraball porblem

### ISSUE THREAD

**Issue by xdiablo1990** [NecronomiconCoding/NecroBot#1730]
before the upgrade i could see how many pokeball, great ball and ultra ball i have left, but now its not showing it

**Comment by somani6** [comment]
Set the following option in the config
"ShowPokeballCountsBeforeRecycle": true,

you may also set "VerboseRecycling": true, if you want to see what the bot recycles.

**Comment by xdiablo1990** [comment]
ty bro! this work
