### ISSUE TITLE
[ QUESTION ] How can i configure the logfile output ?

### ISSUE THREAD

**Issue by Rinkaku** [NecronomiconCoding/NecroBot#1734]
Hi Guys,

I want only 1 logfile per day and not 1 every hour.

Greetings
Rink4ku

**Comment by somani6** [comment]
You can't via settings, u can download the source an change line 22 in the Logger.cs
` $"NecroBot-{DateTime.Today.ToString("yyyy-MM-dd")}-{DateTime.Now.ToString("HH")}.txt"))`
to 
` $"NecroBot-{DateTime.Today.ToString("yyyy-MM-dd")}.txt"))`
and compile your own version.

**Comment by Rinkaku** [comment]
Thanks for the quick answer.
I`ll try it out.
