### ISSUE TITLE
Inaccurate Pokemon Names and Not Collecting Items From Pokestop

### ISSUE THREAD

**Issue by pulverized** [NecronomiconCoding/NecroBot#174]
Some Pokemon names aren't correct according to the actual Pokedex on pokemon.com
Here they are:
- Sandlash should be Sandslash
- Alakhazam should be Alakazam
- not sure about writing Farfetch'd

Also, I'm using the newest Bot and didn't seem collecting items from Pokestop, it just passing and giving (INFO) the Pokestop names.

**Comment by Probber** [comment]
Same by me here too

**Comment by sp1ti** [comment]
Sounds like you have been soft banned. Logout for the duration it would need a real person to get there.
