### ISSUE TITLE
Doesnt transfer duplicate pokemons.

### ISSUE THREAD

**Issue by agassparkle** [NecronomiconCoding/NecroBot#1740]
I keep getting error with full pokemon. I keep raising the CP to keep but i think i am making something wrong. 

  "TransferDuplicatePokemon": is set to true. 

Thanks in advance.

**Comment by somani6** [comment]
Whats in your 'PokemonsNotToTransfer' list?
And how is keepPokemonsThatCanEvolve set?

**Comment by agassparkle** [comment]
"PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],

"KeepPokemonsThatCanEvolve": false

as they are set in default. 
But i assumed that keeping duplicate number over writes this one.

**Comment by mich3lam** [comment]
@agassparkle no, these pokemons will NEVER be trasnfered

**Comment by pikachukaki** [comment]
If i remove all pokemons from this list "PokemonsNotToTransfer" it will keep only the ones above IV&CP? cause i have many low cp/iv pokemons that are in this list!

**Comment by agassparkle** [comment]
@pikachukaki nice question.

**Comment by Marsinator** [comment]
@pikachukaki yes

**Comment by mich3lam** [comment]
@pikachukaki yes, depends on how u confire ur iv and cp
