### ISSUE TITLE
[ QUESTION ] Where can i edit the cmd headline stats output ?

### ISSUE THREAD

**Issue by Rinkaku** [NecronomiconCoding/NecroBot#1741]
I want to paste the headline stats ( like EXP/H ) into the logs.

**Comment by Megurine** [comment]
I dont really understand your question.
If you want to change the window title : CLI.Program.cs (l 72)
If you want to change something into the logs : Logic.Logging.Logger.cs (change what you need)

**Comment by Rinkaku** [comment]
I want to write the window title into the logs or elsewhere, but ur answer helps me alot.
