### ISSUE TITLE
Sniping not working

### ISSUE THREAD

**Issue by havenofear** [NecronomiconCoding/NecroBot#1744]
[19:39:34] (SNIPER) Scanning for Snipeable Pokemon at 38.5568074864611,-121.238379478455...
[19:39:39] (ERROR) System.Net.WebException: Время ожидания операции истекло
   в System.Net.HttpWebRequest.GetResponse()
   в PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) в C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:строка 346

**Comment by sawirth** [comment]
skiplagged is currently having some issues

**Comment by recon88** [comment]
Hey @havenofear 
The Skiplagged API is currently having issues and answering slow.
https://skiplagged.com/pokemon/

There's nothing we can do about to except wait until they fix it.

**Comment by aapikz** [comment]
skiplagged website is having massive load right now lol resulting slow downs ...temporary fix is  go to your pogo.necrobot.logic > task >snipePokemonTask.CS..then ctrl+f ...find this line... 
"request.Timeout = 5000; "....you change it to 30sec or higher "request.Timeout = 30000;"
