### ISSUE TITLE
Help me ! how i can only catch pokémon ? not pokéstop

### ISSUE THREAD

**Issue by redpull** [NecronomiconCoding/NecroBot#1747]

**Comment by bulubebek** [comment]
bot need to visit and spin pokestops to obtain balls. you cant farm pokemons without balls in your bag.

**Comment by recon88** [comment]
Please visit our Discord server if you have issues configuring the bot: https://discord.gg/VXKxNFr

**Comment by redpull** [comment]
no but i have a lot of pokeball in my bag

**Comment by hilycker** [comment]
Can't do that at the moment, unless you compile bot from source editing lines needed to remove pokestops farming.
