### ISSUE TITLE
Ignore Pokemon is not always skipping

### ISSUE THREAD

**Issue by Gemori** [NecronomiconCoding/NecroBot#1749]
I've reached a point where I want to cut back on xp leveling and focus on farming particular pokemon. I'm making use of the ignore list. I've noticed that the bot is still catching pokemon I put on that list. It skips them sometimes, but not 100%. Can I get some guidance? I've attached my config file.
[mylog.txt](https://github.com/NecronomiconCoding/NecroBot/files/393825/mylog.txt)

**Comment by redpull** [comment]
Help me ! how i can only catch pokémon ? not pokéstop

**Comment by sawirth** [comment]
Is it a particular pokemon?

**Comment by hilycker** [comment]
I see you have sniping active and at least some pokemon from the ignore list are in the sniping list. Maybe sniping list takes precedence over ignore list. And check your logs, are those pokemon catched that should have been ignore, lured or incense pokemon?

**Comment by redpull** [comment]
you can join me on teamviewer please , i cant understund sorry

2016-08-01 15:23 GMT+02:00 hilycker <notifications@github.com>:

**Comment by Gemori** [comment]
hilycker helped me fix it. I had to remove the pokemon from the snipe list and add them to the ignore list. The snipe list does in fact override the ignore list.
