### ISSUE TITLE
Red Errors Are Popping Up As of Today

### ISSUE THREAD

**Issue by Gemori** [NecronomiconCoding/NecroBot#1750]
I ran the bot over night. Today I'm noticing endless lines of red code. Attached is a screenshot.
![redlines](https://cloud.githubusercontent.com/assets/20773175/17294860/4d02caa2-57c7-11e6-8f0b-3dc1da30dff2.png)

**Comment by recon88** [comment]
The skiplagged API server is having a bad time and not responding in time.
Just wait for them to fix it.
