### ISSUE TITLE
Saves up pokeballs but not greater and ultraballs

### ISSUE THREAD

**Issue by CakeHole83** [NecronomiconCoding/NecroBot#1752]
After the latest update I can't find a way to decide what amount to keep of each of the balls. Setting keep 200 pokeballs makes me have 150+ of the normal pokeballs while the others keep depleting and are barely over zero.

**Comment by GeMoo** [comment]
With the latest update the new options
`"UseGreatBallAboveIv": 0, "UseUltraBallAboveIv": 0,` lead the bot use Ultra Ball and Great Ball first.

Increase the thresholds like
`"UseGreatBallAboveIv": 50, "UseUltraBallAboveIv": 80,`

**Comment by recon88** [comment]
I'll try to implement a toggle to switch between combined recycler and separate recycler so you can decide again how much of each item you want to keep.

**Comment by recon88** [comment]
Continuing the discussion here #1702
