### ISSUE TITLE
GPX pathing skips pokestops if it doesn't hit them precisely, is that supposed to be the case?

### ISSUE THREAD

**Issue by SupaCURE** [NecronomiconCoding/NecroBot#1756]
I was creating a GPX path manually and it would seem that the pathing works great, that being said even when I try to get as close as possible to pokestops that I can remember it seems to just skip them on occasion, it seems to do it moreso if it's battling pokemon, which happens frequently at pokestops.

Am I just not using it properly, or is there a better way  to make GPX files at this time? I may be the one causing problems of course.

**Comment by nfettinger** [comment]
What is your walking speed?

**Comment by SupaCURE** [comment]
It's set to 13.2

**Comment by PhilPhonic** [comment]
can't reproduce. my bot does not skip stops he is passing

**Comment by SupaCURE** [comment]
Okay well thanks for helping out then Phil /s
