### ISSUE TITLE
  "KeepMinDuplicatePokemon": 1, not work for me

### ISSUE THREAD

**Issue by vipery** [NecronomiconCoding/NecroBot#1757]
Is not working for me. I have full bag of snorlaxx cp 800-100 with 80% IV

Snorlax isnot in PokemonsNotToTransfer,   "TransferDuplicatePokemon": true,   "KeepMinDuplicatePokemon": 1,
    "Snorlax": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
If i change value  "KeepMinIvPercentage": 90.0, it wil transfer but keep Snorlax in bag more than "KeepMinDuplicatePokemon": 1
Still have bunch of snorlax in bag. Same with Porygon

**Comment by Revoss** [comment]
Having same problem with Electabuzz

**Comment by koonon** [comment]
KeepMinIvPercentage means keep everything above that IV, so if you have Snorlax higher than 80% IV then it will keep it. Keep "Min"(not MAX) Duplicate is saying keep at least 1 of the Snorlax.
