### ISSUE TITLE
Account not verrified

### ISSUE THREAD

**Issue by TheLietuvis** [NecronomiconCoding/NecroBot#1761]
I'm using 5.0.0 version. I also had it on 4.0.0 version. I'm logging in with ptc account, but it says That Account isn't verified, but I verified it

**Comment by theloser** [comment]
Switch PtcUsername and PtcPassword for now:
```
  "PtcPassword": "your ptc username",
  "PtcUsername": "your ptc password"
```

**Comment by TheLietuvis** [comment]
Thank you sooooo much

**Comment by Oolaruu** [comment]
Feel free to close the issue if so.
@TheLietuvis
