### ISSUE TITLE
Bot doesn't snipe

### ISSUE THREAD

**Issue by jbadumm** [NecronomiconCoding/NecroBot#1764]
I set the configs up like in the wiki but it doesn't work for me.

https://github.com/NecronomiconCoding/NecroBot/wiki/Automatic-Locations-Sniping-Guide

![notsniping](https://cloud.githubusercontent.com/assets/20769174/17296568/31b01a76-5802-11e6-8bd5-4a3cf7625d11.PNG)

**Comment by ifbatmanwasreal** [comment]
"UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,

**Comment by nfettinger** [comment]
Have you asked for help in the Discord chat rooms yet (ask in room #helpme)?

**Comment by jbadumm** [comment]
Didn't change anything and I think it works now (caught Dratini)

![snipe](https://cloud.githubusercontent.com/assets/20769174/17296695/c58aa28e-5802-11e6-99c2-2812767deb38.PNG)

**Comment by ifbatmanwasreal** [comment]
I have a similar issue.. Anyone know how to fix this? 

![untitled](https://cloud.githubusercontent.com/assets/8885748/17296851/2bb9fa78-57d1-11e6-8aca-db3e5996c553.png)

**Comment by jbadumm** [comment]
I tried your settings and it I get the same error.
If I change those two, it works.
Looks like this:

"UseSnipeOnlineLocationServer": false,
"UseSnipeLocationServer": true,

**Comment by ifbatmanwasreal** [comment]
@jbadumm I thought this might be the issue too, so I copied OPs settings. Now it just doesn't snipe at all. Full configuration:

  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 30,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 30000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": true,

Am I doing something wrong?

**Comment by jbadumm** [comment]
Let the bot run for 5-10 minutes. Somehow it needs some time until it starts sniping.

**Comment by ifbatmanwasreal** [comment]
@jbadumm Still not sniping, clearly something in my config is wrong

**Comment by jbadumm** [comment]
I think you should open a new issue. I'll close this one. Thanks & good luck!

**Comment by jbadumm** [comment]
It stopped working for me but I changed the settings again to this and it works perfect. Try it:

 "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
