### ISSUE TITLE
Does sniping work at all anymore?

### ISSUE THREAD

**Issue by leights12321** [NecronomiconCoding/NecroBot#1765]

**Comment by ifbatmanwasreal** [comment]
Not working for me
![untitled](https://cloud.githubusercontent.com/assets/8885748/17296862/35ee906c-57d1-11e6-8c69-75f3f803d9a6.png)

**Comment by nfettinger** [comment]
Have you asked for help in the Discord chat rooms yet (ask in room #helpme)?

**Comment by nfettinger** [comment]
This is not an application error, but a configuration one. I suggest this issue be closed.

**Comment by ifbatmanwasreal** [comment]
Okay, my bad. And I can't really get into Discord right now. But thanks. I'll look into my config settings.

**Comment by NPP000** [comment]
How to fix it? I same too.

**Comment by recon88** [comment]
Sniping works perfectly fine. Skiplagged servers are just having a bad time. Either wait for them to improve their servers or pull and compile the latest source from Github which handles reponses that take longer better.

**Comment by roychross** [comment]
@recon88 could you tell me your config setup to make it work right?

**Comment by recon88** [comment]
Please visit our Discord server for general and configuration help: https://discord.gg/VXKxNFr
