### ISSUE TITLE
When the IV value is the same, can choose better CP?

### ISSUE THREAD

**Issue by yanrongmao** [NecronomiconCoding/NecroBot#1766]
Logs:
![image1](https://kejun.tk/data/2.png)
![image2](https://kejun.tk/data/1.png)

**Comment by Silverarrows1986** [comment]
Got the same: 
Snorlax	- CP: 2223  IV: 100.00%   [Best CP: 137  IV: 100.00%]

**Comment by yanrongmao** [comment]
@Silverarrows1986
so?

**Comment by Silverarrows1986** [comment]
now we need to wait. there is actually no way to set it. lets hope some of the great ppls can do a fix for it

**Comment by dddbliss** [comment]
Tracking #1772
