### ISSUE TITLE
Having Trouble Setting how much of each item i want

### ISSUE THREAD

**Issue by IAmIndra** [NecronomiconCoding/NecroBot#1773]
While looking at the code for version 5.0 (which is what I currently have), I am not seeing a way to set how many of each type of potion and pokeball I want. The current wiki says that I can't use the "ItemRecycleFilter" List to set that anymore, and the "TotalAmountOfPokeballsToKeep" and it's accompanying code do not allow for me to set how many pokeballs I want. I tried to set those values in the "ItemRecycleFilter" list however it didn't do anything. **I Want to Know how to set how many great balls I want, etc. and set a ceiling for regular pokeballs.** As well as do the same thing for potions. Starting off before I had version 5.0 I had 100 Max Potions and 150 Hyper Potions in my inventory. After setting Total Amount of Potions to Keep to 250, it ended up transferring all of my hyper and max potions and started filling my inventory with regular potions. That is stupid coding. Potions do nothing for me. It did the same thing for my Pokeballs, GreatBalls, and Ultraballs. I now have 500 pokeballs, which is worthless when I am catching pokemon above 550 CP. Please help, how do I set ceiling and recycle filters for these items??????? Please Help?????!!!!!!!

**Comment by nfettinger** [comment]
In the new configuration, you set how many total Pokeballs you want. When you go over this limit, the logic will automatically recycle the least valuable Pokeballs first, before moving up to the better ones. This  logic not only better keeps your inventory from being full, but also increases the likelihood of catching Pokemon when the Pokeballs to keep amount is set very low.

Here is the configuration option:
TotalAmountOfPokebalsToKeep

Next time, please ask for help in the Discord chat rooms first, before creating an issue.

**Comment by ThatAce** [comment]
Where can i find the value of the type of potion and pokeball and set it ?

**Comment by theloser** [comment]
config.json, look for "TotalAmountOfPokebalsToKeep". "TotalAmountOfPotionsToKeep" and "TotalAmountOfRevivesToKeep".

**Comment by ThatAce** [comment]
can i prioritize CP than Catch protability

**Comment by recon88** [comment]
See #1752
