### ISSUE TITLE
[Minor Bug] Bot becomes inactive on Windows 10

### ISSUE THREAD

**Issue by AuliaYF** [NecronomiconCoding/NecroBot#1774]
So i just reinstalled my PC to Windows 10, and the bot keeps going inactive unless i press random key on it.

Is it just me?

Thanks.

**Comment by theloser** [comment]
What is your "StartupWelcomeDelay" setting?

**Comment by AuliaYF** [comment]
It's on false, i have no problem on previous OS ( Windows 7 ). I'm downloading visual studio, hope i can fix this issue by myself.

Any other solution?

**Comment by theloser** [comment]
What are your settings on the console, do you have "QuickEdit" enabled? When QuickEdit is on, clicking on the console can by accident select a single character, and then the output (and the program itself) are "on hold" until you press a key to deselect. Turn QuickEdit off.

**Comment by AuliaYF** [comment]
Ah shoot, man you're the man, I'm new to Windows 10 ( idk if this OS related, lol ). Apparently this fixed the issue.

Big thanks, hope i can make a PR soon.
