### ISSUE TITLE
Issue with pokeballs

### ISSUE THREAD

**Issue by jordanmh96** [NecronomiconCoding/NecroBot#1776]
the bot is using ultra and great balls for things like a level 6 weedle and i've tried to fix it on the config page but it just keeps wasting ultra balls and great balls on bad Pokemon

**Comment by nfettinger** [comment]
This is a configuration issue. Please ask for help on Discord.

**Comment by theloser** [comment]
Post your   "Use___BallAboveCp", "Use___BallBelowCatchProbability" and "Use___BallAboveIv" settings, they may be the problem.

**Comment by jordanmh96** [comment]
Cheers

**Comment by jordanmh96** [comment]
yeah i had a look and someone put up a set of each that was working for them and it seems to work. thanks for the help.

**Comment by progz** [comment]
This is what someone tell me on discord to fix the configuration issue : 

>  "UseGreatBallAboveCp": 1000,
>   "UseUltraBallAboveCp": 1400,
>   "UseMasterBallAboveCp": 2300,
>   "UseGreatBallAboveIv": 80,
>   "UseUltraBallAboveIv": 90,
>   "UseGreatBallBelowCatchProbability": 0.3,
>   "UseUltraBallBelowCatchProbability": 0.1,
>   "UseMasterBallBelowCatchProbability": 0.01,
