### ISSUE TITLE
Auth  file issues

### ISSUE THREAD

**Issue by coryajackson** [NecronomiconCoding/NecroBot#1777]
Whenever I try and set up the auth file, it just keeps saying I need to enter the password and username. Does the same thing with both Google and ptc

**Comment by nfettinger** [comment]
This is not a development issue. Please ask for help in the discord chat.

**Comment by saint-luciferr** [comment]
@coryajackson please go to where to folder is extracted and in the search box please search auth.json

You'll then be able to edit your details to avoid this issue.

Many thanks,

Lucifer
