### ISSUE TITLE
Add a gitignore for the "Pokemon to keep" etc files?

### ISSUE THREAD

**Issue by TheCrimsonDevil** [NecronomiconCoding/NecroBot#178]
These files have been updated in a few of the latest commits, but aren't these up to each person's personal preference? For example, at one time, I wanted eevee to not evolve automatically, so I could rename it first and force the evolution. I also don't want to evolve pikachu, but I want rattata, pidgey, and a bunch of other commons to, after I use a lucky egg.

Is there a way we could add an "ignore" for those custom files, so that changing them doesn't require a commit/reverting before pulling them?

**Comment by ReddoKiddo** [comment]
Implemented on latest commit, when you build the bot it checks for external pokemon list and if they already exists it will not copy the default one
