### ISSUE TITLE
Program using Great/Ultraballs on crappy pokemon, despite config settings

### ISSUE THREAD

**Issue by Ptolemaio** [NecronomiconCoding/NecroBot#1785]
[log.txt](https://github.com/NecronomiconCoding/NecroBot/files/394100/log.txt)

[config.txt](https://github.com/NecronomiconCoding/NecroBot/files/394103/config.txt)

**Comment by bodnar07** [comment]
Change this:

"UseGreatBallBelowCatchProbability": 40.0,
"UseUltraBallBelowCatchProbability": 20.0,
"UseMasterBallBelowCatchProbability": 10.0,

To this:

"UseGreatBallBelowCatchProbability": 0.20,
"UseUltraBallBelowCatchProbability": 0.10,
"UseMasterBallBelowCatchProbability": 0.05,

**Comment by theloser** [comment]
Your config is crap. "UseGreatBallBelowCatchProbability": 40.0 -- you told the bot to use greatballs for every pokemon with a catch chance lower than 4000%. Try the default settings:

  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.2,
  "UseMasterBallBelowCatchProbability": 0.05,
