### ISSUE TITLE
Auth Issues

### ISSUE THREAD

**Issue by papzman** [NecronomiconCoding/NecroBot#1787]
I've inputted my info in the auth.json files. And yesterday it was working fine but today everytime i try to start it it says: 

Logging in using Ptc

and keeps on repeating that and it never gets to the "playing as (username)"

Any help please?

**Comment by theloser** [comment]
Ptc servers down? Missed the "" around your username/password?

**Comment by Andrerm124** [comment]
What does your Auth.json file look like? **(Replace Username/Password with XXX before uploading)**

**Comment by CL24** [comment]
Same here it's not just you, worked 10 hours ago, didn't change anything.

**Comment by Andrerm124** [comment]
Seems to be working for me using the PTC logins. You guys using that or Google Auth?

**Comment by GraspGG** [comment]
Same here (Germany) - no PTC login possible.

Using a smartphone with the same account doesn't work either. Seems to be a server issue.

**Comment by papzman** [comment]
My auth.json file looks like this. 

 "AuthType": "ptc",
  "GooglePassword": null,
  "GoogleRefreshToken": null,
  "GoogleUsername": null,
  "PtcPassword": "XXX",
  "PtcUsername": "XXX"

Although from everyones comments it seems to be a server issue.

**Comment by recon88** [comment]
PTC servers are having issues. Please be patient.
