### ISSUE TITLE
Config causing crash on startup - can't pinpoint errors

### ISSUE THREAD

**Issue by Dmn7D** [NecronomiconCoding/NecroBot#1788]
Hi I'm having some trouble getting the bot to run. It crashes (necrobot has stopped working) on startup and it's more than likely the config for that profile since I can get the bot running for a different profile using a semi-default config. I've gone through the config but can't seem to find the errors.

Here's config I'm having issues with - http://pastebin.com/tgBiKNk5

Much appreciated!

**Comment by AlexWelson** [comment]
what is the error?

**Comment by Andrerm124** [comment]
Your issue is that you've put **ninetails** somewhere instead of nine**tales**

**Comment by Dmn7D** [comment]
Wow, what a fail on my end lol 

Thanks so much xD

**Comment by Oolaruu** [comment]
You win an heart for reading the whole config seriously. Good Job!

**Comment by Andrerm124** [comment]
I didnt read it all hahaha. Ran the bot with his/her config through VS and it literally gave me the error "Cannot Parse 'ninetails'". I'll take the hearts though hahah.
