### ISSUE TITLE
Console character coding

### ISSUE THREAD

**Issue by sp1ti** [NecronomiconCoding/NecroBot#179]
Can we change the console encoding to Unicode? Some Pokéstops end up with "?????" otherwise. 

![Error message](http://i.imgur.com/hoeQBVD.png)

I would submit this as a pull but I have yet to find out where exactly to define this (without running into compile errors).

Thanks

**Comment by TheCrimsonDevil** [comment]
Can you give me a few strings to test? Names of the pokestops, for example.

**Comment by sp1ti** [comment]
Hey,
Sure:
* 扇町公園
* Императорская Академия Живописи
* 거대 손

**Comment by TheCrimsonDevil** [comment]
See #414, should fix it.

**Comment by sp1ti** [comment]
Thanks mate! Will close it as of now.
