### ISSUE TITLE
Over max item storage

### ISSUE THREAD

**Issue by refix** [NecronomiconCoding/NecroBot#1793]
1400/350, why does the bot care if we are over max item storage? There is no cap if you've never logged into the game....

**Comment by refix** [comment]
feels really stupid deleting 400 pokeballs, 200 max potions, 100 razz berries just to run the latest version when it works perfectly fine on the old one

**Comment by refix** [comment]
"TotalAmountOfPokebalsToKeep": 999,
  "TotalAmountOfPotionsToKeep": 1,
  "TotalAmountOfRevivesToKeep": 1,
  "RecycleInventoryAtUsagePercentage": 0.9,

maybe 0.9 should be lower?

**Comment by sniper85500** [comment]
seems there is no recycle routine in 0.5.0? My Bot dosen't recycle anything

**Comment by nfettinger** [comment]
Using the following commit, my build is able to recycle things correctly.
459511d41177175c09dc04487b7544e22de44e1f

If upgrading from a previous version, make sure you check your config.json for the new pokeball, potion, and revive changes.
