### ISSUE TITLE
[Request] Pokemon name translation (de, fr, ja, ko, zh)

### ISSUE THREAD

**Issue by GraspGG** [NecronomiconCoding/NecroBot#1794]
Somewhen after botting - the backpack is filled with pokemon - when real live spotting, catching and fighting at arenas starts, it would be helpful to have the pokemon have the correct interface language related names.

As far as i know, french, german, japanese, korean and chinese language pokemon names are existing beside english.

Autorename is a great bot feature, but gets useless and confusing as soon as one of the users is leaving the house and catches pokemon having non english names... Then the user has to run/autosort the bot before he has a clean backpack again.

It would be much easier and cleaner if the pokemon names could get autorenamed into the interface language corresponding names.

**Comment by recon88** [comment]
See #1794
