### ISSUE TITLE
Script updating config file sets 0 as default value to new settings

### ISSUE THREAD

**Issue by jasio77** [NecronomiconCoding/NecroBot#1799]
Script that is updating the config file sets 0 as default to new settings in 5.0.0 release. It's causing most of the time problem with pokeballs.

Workaround until script gets updated: To anyone, that has problem with pokeballs! Copy your config and auth files anywhere else, run .exe and then replace your values into new config.

**Comment by recon88** [comment]
See #1801 for detailed information

**Comment by sniper85500** [comment]
Bot always use Greatballs now - has anyone the original values from 0.4.0?
