### ISSUE TITLE
Auto level up crash

### ISSUE THREAD

**Issue by Zierk59** [NecronomiconCoding/NecroBot#1810]
Hi, I tried to turn on auto level up and I got a little problem. So I changed "AutomaticallyLevelUpPokemon" from **false** to **true** and I launched NecroBot. 
There is error message

`System.NullReferenceException: Object reference not set to an instance of an object.
   in PoGo.NecroBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__0.MoveNext() in E:\Users\Administrator\Desktop\source-pokemon-bot\PoGo.NecroBot.Logic\Tasks\LevelUpPokemonTask.cs:line 25
--- The end of the stack trace from the previous location where the exception occurred ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Users\Administrator\Desktop\source-pokemon-bot\PoGo.NecroBot.Logic\State\FarmState.cs:line 31
--- The end of the stack trace from the previous location where the exception occurred ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Users\Administrator\Desktop\source-pokemon-bot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36`

**Comment by recon88** [comment]
What did you "LevelUpByCPorIv" set to?

**Comment by Zierk59** [comment]
Null. What type of value adopts this variable?

**Comment by recon88** [comment]
Level up by highest "iv" or "cp". Whatever you prefer ;)
