### ISSUE TITLE
Not working with Mono

### ISSUE THREAD

**Issue by muschter** [NecronomiconCoding/NecroBot#1811]
I am trying to run this on my Ubuntu 16.04 VPS with the mono-runtime. I am able to run the program, but after it tells me to check if my Latitude and Longitude are right, it says the operation is cancelled. After that happens, it just keeps trying to log in with Google and gets nowhere.

Here is the output from my Terminal window:
```
[12:08:09] (UPDATE) Perfect! You already have the newest Version 0.5.0
﻿[12:08:09] (INFO) Logging in using Google
﻿[12:08:10] (INFO) Playing as muschter
﻿[12:09:50] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7851704565496 Lng: -73.9683308822439
﻿[12:11:30] (ERROR) Current Operation was canceled.
﻿[12:11:30] (INFO) Logging in using Google
[12:13:31] (INFO) Logging in using Google
```

**Comment by NecronomiconCoding** [comment]
Mono is not supported.
