### ISSUE TITLE
Bot transfers pokemons when KeepPokemonsThatCanEvolve set to false and UseLuckyEggsWhileEvolving set to true

### ISSUE THREAD

**Issue by jasio77** [NecronomiconCoding/NecroBot#1812]
Bot transfers pokemons when KeepPokemonsThatCanEvolve is set to false and UseLuckyEggsWhileEvolving set to true. It runs out of pokemons quicker that it can do mass evolve with Lucky Egg.

**Comment by recon88** [comment]
Check #1783
