### ISSUE TITLE
Multiple Error Messages?

### ISSUE THREAD

**Issue by Hesk98** [NecronomiconCoding/NecroBot#1815]
Not sure why this happens. The bot will work for a bit normally until these error messages keep popping up https://gyazo.com/ab0bbe8363942298f1217654cdab45cb 

Thanks.

**Comment by NecronomiconCoding** [comment]
This happens because RocketAPI doesnt handle the PtcOfflineException well, it just means that the PTC Servers are unstable.

**Comment by recon88** [comment]
You probably configured your auth file wrong or the auth servers are down. For a quick check visit our Discord server: https://discord.gg/VXKxNFr

**Comment by Hesk98** [comment]
Ok thanks, I'm on the chat right now. My user is @Hesk
