### ISSUE TITLE
[Feature Request] Prioritise egg types (2k, 5k, 10k) with incubators

### ISSUE THREAD

**Issue by xrhaomx** [NecronomiconCoding/NecroBot#1821]
An option that would allow the user to choose in preference order which km length eggs they want to put in the incubators

**Comment by Aneduna** [comment]
Something like that is already implemented.
Infinite Incubator uses eggs with lower km
Finite Incubator uses eggs with higher km

**Comment by recon88** [comment]
It's doing that automatically currently.
