### ISSUE TITLE
Feature Request Add a List for Pokemons to only use Pokeballs for

### ISSUE THREAD

**Issue by Aneduna** [NecronomiconCoding/NecroBot#1823]
Using Ultra balls for Zubats is a waste eventhough they have high cp & low Prob & high iv

**Comment by Aneduna** [comment]
Would be nice if you give the issue for the duplicate.

I don't want the ignore list, but a list for pokemons to not use ultraballs/greatballs only pokeballs

**Comment by recon88** [comment]
#1745
Requests a list "usePokeballFor". Should be exactly what you want, just the way around ;)
Feel free to extend that ticket with your thinkings.

**Comment by Aneduna** [comment]
Thank you, sorry
