### ISSUE TITLE
Transfer Pokemon by CP

### ISSUE THREAD

**Issue by Blackrider1887** [NecronomiconCoding/NecroBot#1825]
Hello, is there a possibilty to let the Bot transfer the Pokemon by CP instead of the IV?

For example if I have an Squirtle with 515CP and a Squirtle with 350CP.
If the Quirtle with 350CP has a higher IV it will transfer my Squirtle with 515CP.
I don't want this!

Is there a chance to change this?

**Comment by rherartt** [comment]
"PrioritizeIvOverCp": false, just use this and it will keep highest cp

**Comment by Aneduna** [comment]
If you have configuration questions, get on discord
