### ISSUE TITLE
Crash after longer disconnect

### ISSUE THREAD

**Issue by Aneduna** [NecronomiconCoding/NecroBot#1831]
![image](https://cloud.githubusercontent.com/assets/9990060/17302068/94140398-5844-11e6-98bb-8618f4ce404d.png)
I am currently in a place with so bad internet, that sometimes the connection is lost for about a minute.
This caused a crash. The expected behaviour would be to wait like 20s then try again like in the relog.

Visualstudio says this is a System.Net.Http.HttpRequestException in ApiFailureStrategy.cs in line 53.
`Fehler beim Kopieren von Inhalt in einen Stream.`

**Comment by recon88** [comment]
Please visit our Discord server for general help: https://discord.gg/VXKxNFr

**Comment by Aneduna** [comment]
This is a Exception which is not handled. It should be fixed. This is not a rare case as it could probably happen even with niantic server being down.

**Comment by Aneduna** [comment]
This is not
> general help

its an unhandled exception
