### ISSUE TITLE
Crash after some minutes

### ISSUE THREAD

**Issue by LeJ0ker** [NecronomiconCoding/NecroBot#185]
Server Offline or Bug ?

[14:34:42] Requesting GetInventoryResponse
[14:34:43] Unhandled exception: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei Google.Protobuf.JsonFormatter.IsDefaultValue(IFieldAccessor accessor, Object value)
   bei Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   bei Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message, TextWriter writer)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message)
   bei Google.Protobuf.JsonFormatter.ToDiagnosticString(IMessage message)
   bei PokemonGo.RocketAPI.GeneratedCode.PokemonData.ToString() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI\GeneratedCode\Payloads.cs:Zeile 10760.
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.Format(String format, Object[] args)
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 355.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 414.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 236.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\Program.cs:Zeile 22.
---> (Interne Ausnahme #0) System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei Google.Protobuf.JsonFormatter.IsDefaultValue(IFieldAccessor accessor, Object value)
   bei Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   bei Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message, TextWriter writer)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message)
   bei Google.Protobuf.JsonFormatter.ToDiagnosticString(IMessage message)
   bei PokemonGo.RocketAPI.GeneratedCode.PokemonData.ToString() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI\GeneratedCode\Payloads.cs:Zeile 10760.
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.Format(String format, Object[] args)
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 355.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 414.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\root\Desktop\34234\Pokemon-Go-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 236.<---

**Comment by Xomux** [comment]
Same problem here.

**Comment by dylanhall34** [comment]
Also have this :)

**Comment by walter853** [comment]
Me too ;p

**Comment by LeJ0ker** [comment]
i thinks its server problem now it works perfect. But why no auto restart ?

**Comment by dylanhall34** [comment]
For a temporary fix, change ConfigPokemonsToKeep.txt to this: https://gyazo.com/9de196f9d730820092b276ea361c8feb

I had to remove a few that were causing errors.

**Comment by LeJ0ker** [comment]
Dont work for me
