### ISSUE TITLE
Request: Disable movement option

### ISSUE THREAD

**Issue by Caydenz** [NecronomiconCoding/NecroBot#186]
There are some great spots with 4-5 pokestops where I think the efficiency will be higher if the bot is not moving.

**Comment by LeJ0ker** [comment]
Yea Great idea a new config would be nice

**Comment by ThomasSRL** [comment]
https://github.com/NecronomiconCoding/Pokemon-Go-Bot/pull/129

You'll have to wait untill someone adds this ^^^^

**Comment by blindreaper** [comment]
Untested: http://pastebin.com/V0eaYuh5

**Comment by ReddoKiddo** [comment]
Range is implemented and detecting lure/incense pokemons will be in the future
