### ISSUE TITLE
Changing Account

### ISSUE THREAD

**Issue by Azrael123123** [NecronomiconCoding/NecroBot#187]
How am i able to change my google account for the bot?

**Comment by sp1ti** [comment]
Remove your refresh token and start it again, then doing the device auth under said account.

**Comment by Azrael123123** [comment]
thx mate appreciate it.

**Comment by Lovebucket25** [comment]
the refresh token isn't showing up under app.config? Where else could I Locate it?

**Comment by iamD2** [comment]
like to know also how to reset it.

**Comment by Lovebucket25** [comment]
the refresh token I thought auto updated.

**Comment by Azrael123123** [comment]
hm its weird but its still using my old account, i cant change it to the new one.

**Comment by Lovebucket25** [comment]
I have deleted and downloaded a whole new version, and it is still logging me into my old one....

**Comment by Azrael123123** [comment]
yeah me 2 its weird. dont know how to change it.

**Comment by jessewhite007** [comment]
Yeah, it's getting cached somewhere else it's weird. I solved the problem by simply commenting out where it initially reads the value in for refresh token.

if (Settings.GoogleRefreshToken != string.Empty)
            {
                tokenResponse = await GoogleLogin.GetAccessToken(Settings.GoogleRefreshToken);
                AccessToken = tokenResponse?.id_token;
            }

In Client.cs

Comment the aboves lines out. Run and it'll let you change the account. Uncomment if you want to not have to log in every time. 

Once I figure out where it's actually getting the value from I'll submit a pull request

**Comment by jessewhite007** [comment]
Figured out the issue. Because settings is scoped to user it's actually getting stored in your user directory. Delete the file user.config file from the location
C:\Users\<yourusername>\AppData\Local\PokemonGo\<someappname>\1.0.0.0

Where <yourusername> is whatever name you used to log onto the computer
and <someappname> is the name of the app. Should be the only folder there.

**Comment by Lovebucket25** [comment]
My friend also said to log out of whatever account you're using on your Google browser. If these dont work I'll let y'all know

**Comment by Lovebucket25** [comment]
can't find appdata

**Comment by jessewhite007** [comment]
appdata is a hidden folder. Either type it in the address bar or turn on show hidden files/folders.
