### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by RaymondSchnyder** [NecronomiconCoding/NecroBot#197]
`Unhandled exception: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei Google.Protobuf.JsonFormatter.IsDefaultValue(IFieldAccessor accessor, Object value)
   bei Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   bei Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message, TextWriter writer)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message)
   bei Google.Protobuf.JsonFormatter.ToDiagnosticString(IMessage message)
   bei PokemonGo.RocketAPI.GeneratedCode.PokemonData.ToString() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\GeneratedCode\Payloads.cs:Zeile 10760.
   bei System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   bei System.String.Format(IFormatProvider provider, String format, Object[] args)
   bei System.String.Format(String format, Object[] args)
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 355.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 414.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 236.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei PokemonGo.RocketAPI.Console.Program.<>c.<Main>b__0_0() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Console\Program.cs:Zeile 22.
---> (Interne Ausnahme #0) System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei Google.Protobuf.JsonFormatter.IsDefaultValue(IFieldAccessor accessor, Object value)
   bei Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   bei Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message, TextWriter writer)
   bei Google.Protobuf.JsonFormatter.Format(IMessage message)
   bei Google.Protobuf.JsonFormatter.ToDiagnosticString(IMessage message)
   bei PokemonGo.RocketAPI.GeneratedCode.PokemonData.ToString() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\GeneratedCode\Payloads.cs:Zeile 10760.
   bei System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   bei System.String.Format(IFormatProvider provider, String format, Object[] args)
   bei System.String.Format(String format, Object[] args)
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 355.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 414.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in D:\Pokemon-Go-Bot-master (1)\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 236.<---

`

There is the exception stack. Hope it helps

**Comment by DanielSantoro** [comment]
This should be fixed in the latest version, had something to do with eggs when your account was full.
