### ISSUE TITLE
How to use the Club account login

### ISSUE THREAD

**Issue by 574939913** [NecronomiconCoding/NecroBot#200]
Gmail is blocked in my country, although I can connect to the server with VPN, but I want to use club account login.

**Comment by walter853** [comment]
You'll have to set it up in settings in Visual Studio, under the Console.

**Comment by wouter2203** [comment]
![image](https://cloud.githubusercontent.com/assets/8761962/17078316/f98b5034-50ef-11e6-9652-c1abdb61d2c4.png)

Just set the `AuthType` to `Ptc`

**Comment by 574939913** [comment]
Thank you. I'm so careless.
