### ISSUE TITLE
It stops after a minute

### ISSUE THREAD

**Issue by asdasdsadasdsadasdasda** [NecronomiconCoding/NecroBot#209]
[IMG]http://i67.tinypic.com/2re7a1c.jpg[/IMG]

After a minute, always the same error

**Comment by Antidote78** [comment]
In All 3 folders PokemonGo.RocketApi.* delete the bin and then recompile.
Let me know if it worked

**Comment by asdasdsadasdsadasdasda** [comment]
I can't prove it more now, but in 5 minutes it doesn't throw any erro. Thanks!

**Comment by cvax** [comment]
The crash seems like it might be triggered by {fortSearch.PokemonDataEgg} in the Logger.Write() string.

**Comment by pattythesleeper** [comment]
@Antidote78 how do i remove the bin and where do i find it?

**Comment by cvax** [comment]
@pattythesleeper Just update your repo. There was a temp fix commited https://github.com/NecronomiconCoding/Pokemon-Go-Bot/commit/acb4e0520cbc0fb1333ec9e13e8713f1624e4e59
