### ISSUE TITLE
Transfer of pokemon is duplicated

### ISSUE THREAD

**Issue by panzer168** [NecronomiconCoding/NecroBot#212]
https://gyazo.com/e91a6029f45f7965743bd33e9fe79eef

Transferring at 8:46:32  and another one at 8:46:47

**Comment by ilu01** [comment]
Had this issue too. I believe its just server side

**Comment by berbb** [comment]
Been getting this too. It's also happening with recycling for me.

**Comment by ReddoKiddo** [comment]
Fixed
