### ISSUE TITLE
[Request] Hatch eggs

### ISSUE THREAD

**Issue by praneeth101** [NecronomiconCoding/NecroBot#214]
Is it possible to hatch eggs using this? After the target it reached, the eggs just disappear.

**Comment by solenrus** [comment]
set ur speed to 10-12 km/h

**Comment by ilu01** [comment]
Do the eggs really disappear? I belived the Pokemons hatch and are added to your Pokemon List?

**Comment by praneeth101** [comment]
@ilu01 They don't show up in the journal either (I'm guessing they should). A few hours ago 4 10km eggs disappeared. I'm sure nothing got added to my list.

**Comment by praneeth101** [comment]
@solenrus Did that now. I'll post here with the results.

**Comment by praneeth101** [comment]
Happened again. A 2 km egg just disappeared after doing 2.0/2.0. No pokemon were added to the list nor there's anything about it in the journal.

**Comment by lorenzowalz** [comment]
I haven't had any luck with eggs either. I've seen some initiative to add the ability to re-incubate new eggs and perfect that feature...but I haven't seen it on this repo. Is someone working on that? I'd be happy to help.
