### ISSUE TITLE
Evolution isn't working?

### ISSUE THREAD

**Issue by HoratioSanchez** [NecronomiconCoding/NecroBot#215]
The bot will only evolve Pokemon when it starts up sometimes, but it will never attempt to evolve pokemon at all until another restart happens. Is there a way to make it evolve Pokemon and use up the candys for the exp? or maybe make it use a luckyegg when it can evolve 60 times.

**Comment by vcafezinho** [comment]
Yeah, a good way is before tranf the pokemon check if we can evolve. If yes evolve and tranf keeping the duplicates and high CP according to the configs.

**Comment by wouter2203** [comment]
Make sure this entry is set to `True`

![image](https://cloud.githubusercontent.com/assets/8761962/17078601/ac2b88d8-50f7-11e6-8207-e355aa929ebc.png)

**Comment by vcafezinho** [comment]
True is already selected, it is transfer all pokes at the beginning of the process however just that, if you catch a pokemon that is supposed to evolve (you have the candys) it will transf, we want to get the XP of evolution before transf.

**Comment by JoshYuen** [comment]
Would be nice to add in keep minimum number of certain pokemon types. This way we can farm up lets say 100 pidgeys and then just have them all evolve on the next start up with a lucky egg active.

**Comment by ReddoKiddo** [comment]
It will evolve once it is done farming all of the pokestop it detected when the first loop is ran
