### ISSUE TITLE
KeepMiniIVPercentage

### ISSUE THREAD

**Issue by Antazia** [NecronomiconCoding/NecroBot#220]
Hi, i'm not an English, please, what is a MiniIVPercentage?

**Comment by LasaFawkes** [comment]
It states the minimum IVs for the pokémons you catch to be kept. You can learn more about IVs here: https://www.reddit.com/r/TheSilphRoad/comments/4tzcmk/faq_on_ivs_info_megathread/

**Comment by Antazia** [comment]
Thanks, so if I understand good, the IVS if he is at 100%, the pokemon is PERFECT, and if it is at 50%, it will be 1/2 of the power of the perfect pokemon?

**Comment by ilu01** [comment]
No, this is not entirely correct. 
100% is a PERFECT Pokemon, yes. With all IVs +15
But: even a 50% Pokemon has the same base stats as a perfect pokemon but all IVs roughly +7,5. Making it inferior but not 50% . Basestats are in the range of hundreds.

**Comment by LasaFawkes** [comment]
Keep in mind that IVs also influence the max CP a pokémon can get, so even though at first it may seem trivial, at higher levels the difference between a 100% IV and a 30% IV start to become relevant, given that max CP also scales with the player level.

**Comment by Antazia** [comment]
Okay, so I put 1000PC min, and idk for the IVs. What do you have?
And, if I have, for exemple, a dragonite 1500PC 50IVs, and a dragonite 1000PC with 100 IVs, which will be deleted first? 
And I put KeepMinPokemon : 3, if I have a dragonite (exemple : 100PC and 10IVs, will it be keept if I only have one?)

Thanks for your help
