### ISSUE TITLE
[Request] Leveling with evolution of Pidgeys, Caterpies and Weeldes.

### ISSUE THREAD

**Issue by grouvie** [NecronomiconCoding/NecroBot#221]
The bot doesn't evolve while walking and transfers the Pokemon before evolving for XP. Is there a way to change that? Thx :)

**Comment by RainGK** [comment]
It's better to evolve them all at once as you can use a lucky egg with that, also it shouldn't be transferring before evolving.

**Comment by onewhoflies** [comment]
Check my issue. You can change that easily, but it will try to evolve the same Pokemon multiple times.

**Comment by ReddoKiddo** [comment]
It's a lot waste of time evolving everytime you catch... currently the bot evolves when it starts and when it finishes farming all the detected pokestop (when it first starts it scans for pokestops and goes through them one by one, after it is finish with the last one the loop starts again -> evolve and scan more)
