### ISSUE TITLE
[Doubt] What does the "KeepMinDuplicatePokemon" setting actually do?

### ISSUE THREAD

**Issue by LasaFawkes** [NecronomiconCoding/NecroBot#224]
Title.

**Comment by marksterxxx** [comment]
if you wan't 2 of each pokemon just so you can compare them later, set it to 2.
if you just wan't 1 of each, set it to 1.

**Comment by LasaFawkes** [comment]
Any tips on why this would be useful? I mean, they are already filtered with the min CP and IV settings, why would you need this one? I'm a bit confused, sorry :confused:

**Comment by ChainRythm** [comment]
I'm guessing it would be to compare Move sets.

**Comment by gewoon** [comment]
You can use this setting if you dont mind have two of the same Pokémon, or you just want to keep the pokemon to later on evolve and gain XP. 
So when this setting is 1, you will one save 1 of each pokemon. If there comes e.g. a Charizard but you already have one, the weakest Charizard will get transferred. Set it to two, and you'll save 2 Charizards (3rd gets transferred).

**Comment by LasaFawkes** [comment]
I think I get it now. This is just for the cases in which you want to keep one (or more, if we edit it) of each pokémon even if they are below your CP and IV thresholds, because anything above will be kept anyway. Thank you all :)

**Comment by gewoon** [comment]
It can be used in that way, yes.
