### ISSUE TITLE
Evolving is happening multiple times while farming and failing (only succeeding the first time)

### ISSUE THREAD

**Issue by onewhoflies** [NecronomiconCoding/NecroBot#227]
I want to evolve Pokemon with enough candy after every catch, but when I place 

`            await EvolveAllPokemonWithEnoughCandy(_clientSettings.PokemonsToEvolve);
`

after the RecycleItems task like so:

```
await Task.Delay(1000);
await RecycleItems();
await EvolveAllPokemonWithEnoughCandy(_clientSettings.PokemonsToEvolve);
 if (_clientSettings.TransferDuplicatePokemon) await TransferDuplicatePokemon();
```

it will apparently try to evolve the same Pokemon _n_ times equal to the number of stops visited in the farming task. Works the first time, obviously fails the rest of the times due to a "pokemon missing" error. How can I fix this?

Attached screenshot: https://anonmgur.com/up/f3869e9fd68a78efd8318d6230afe626.png
Recycling + transferring also seems to be duplicating.

**Comment by Hitsuomy** [comment]
Just rebuild with a newer version. Try again.

**Comment by ReddoKiddo** [comment]
Will assume to be fixed because no further comments on issue... if not then please open a new one
