### ISSUE TITLE
Use other balls if one is empty

### ISSUE THREAD

**Issue by gewoon** [NecronomiconCoding/NecroBot#230]
Sometimes i run out of Great Balls, but i really want to catch the Pokémon. Then this happens:
`[18:08:30] (PKMN) Venonat (465 CP) Chance: 0 | 100m distance CatchError | with ITEM_GREAT_BALL`
Because i don't have any Great Balls it will show an error (i think that's why). Maybe it's a good idea to check wether a Great Ball can be used and if not, use a better ball.

**Comment by goldxero** [comment]
pretty sure use best ball feature is already implemented, might be another problem that you are facing

**Comment by gewoon** [comment]
Yes i know, it uses different balls depending on (if think?) CP. But if that ball is empty, it gives an error and continues without catching the Pokémon.

**Comment by Cryslacks** [comment]
CatchError means that you have been softbanned. Just wait 10-20min and run it again, then it should work.

**Comment by gewoon** [comment]
Nop, it works for other Pokémon  just excellent, it's also not that the greatballs don't work. I'm just in an area where there are more Pokémon than Balls i get from Pokéstops.

**Comment by gewoon** [comment]
If you're softbanned, al the Pokémon will show CatchFlee and you won't obtain any XP from stops.

**Comment by CTDragon** [comment]
I just re-checked this logic. GetBestBall will use any ball where the current amount is more than 0 if it can't find one based on CP. The only time it won't be able to use a ball is if you don't have any.

However, the chance of catching that pokemon is 0%. It probably used all of your great balls and then couldn't throw anymore. There is currently a Pull request that says it fixes that issue of using all balls when chance to catch is 0%

**Comment by gewoon** [comment]
0% catch chance? That's bad... Thanks for explaining though.

**Comment by Tvman1231** [comment]
i have an idea, if the lower pokballs have run out and the cp of the pokemon your trying to catch is not worth that pokeball i.e use of ultra ball for rattata of 10 cp then ignore that pokemon and run away...? maybe?
