### ISSUE TITLE
Bot does not do anything

### ISSUE THREAD

**Issue by pattythesleeper** [NecronomiconCoding/NecroBot#232]
http://prntscr.com/bwkbg3

It have been like that for like 30 mins repeating saying that :/

**Comment by n3o999** [comment]
me too. delete all project folder etc. ccleaner. reboot pc. re download new version of bot, follow read me and insert a CORRECT coord (also "-" char) now work for me

**Comment by pattythesleeper** [comment]
@n3o999  mate thats too mutch work haha i did remove the project folder and made a new one and works great for me now  :)

**Comment by ghsi10** [comment]
its only coord... you should rewrite them.
