### ISSUE TITLE
[Bug] Transfering "Pinsir".

### ISSUE THREAD

**Issue by Cryslacks** [NecronomiconCoding/NecroBot#233]
It seems like the bot doesnt transfere the pokemon "Pinsir" well enough, my settings is "KeepMinDuplicatePokemon = 1" and still I have 20 (counted to be exact) of them in my bag. But yes it does transfere the pokemon "Pinsir" but not enough. 

Thanks in advance!

**Comment by lorenzowalz** [comment]
@Cryslacks What do you have the CP/IV settings set to? If they meet the requirements it might still be keeping them.

**Comment by Cryslacks** [comment]
You are absolutely correct, my Cp was set to 1k and all of them was above 1k. But if i change this to like 1.5k and my highest would be 1.4k would everyone get transfered except the 1.4k one, if i use the above settings?

**Comment by lorenzowalz** [comment]
@Cryslacks As long as it is near perfect enough I don't think it will discard it. This section needs to be more flushed out.

**Comment by razki** [comment]
Central park is full of pinsirs, I'd like to see it totally get rid of them all, possibly a pokemon blacklist

**Comment by Hitsuomy** [comment]
Probably about the IVs, one day running the bot on Central Park and now I have 690 Pinsir Candies, bot is transferring most of them but due to higher concentration it catches a lot of high IVs Pinsirs too.
