### ISSUE TITLE
[Request] Auto lucky egg, Auto Incense.

### ISSUE THREAD

**Issue by Cryslacks** [NecronomiconCoding/NecroBot#234]
If someone would be able to code in an Auto lucky egg and Auto incense, for even more profits.
You could have settings like: UseWhenReady and UseAfterDelay.

UseWhenReady would just use the egg and/or incense when ready (after 30min).
UseAfterDelay would use the egg and/or incense after x minutes.

Please consider this as it would be really good, thanks in advance.

**Comment by gewoon** [comment]
Asked this yesterday too. I'm looking forward to it.

**Comment by zerobcpp** [comment]
Bot does not detect pokemons being lured by incense/module.

**Comment by gewoon** [comment]
Oh so incense is not an option?

**Comment by ReddoKiddo** [comment]
auto incense and other efficiency increase feature will be looked in the future
