### ISSUE TITLE
[Request] multi account

### ISSUE THREAD

**Issue by Tadebu** [NecronomiconCoding/NecroBot#236]
optional chose to use multi account in same time without copy Files.
google and ptc same time. right now i use other open source to use 10 bots same time without copy folders with the source

**Comment by Zashuiba** [comment]
How? Which open source?

**Comment by Hitsuomy** [comment]
Whut? You want run multiple accounts on the same client? Doesn't make sense, just make copies and run the others.

**Comment by Tadebu** [comment]
nope the same client when i click ctrl + f5 , will change passwords and log in to other accounts

**Comment by Hitsuomy** [comment]
Well, I think it's unreasonable, so easy to create multiple folders and edit the conf file of each one at appdata, but, okay.

**Comment by Shroomzie** [comment]
It just needs to be something like running batch files pointing to the config folder of each account you want i guess
