### ISSUE TITLE
Route based on (rare) Pokemon

### ISSUE THREAD

**Issue by lolstatsguy** [NecronomiconCoding/NecroBot#237]
Lets say i want to farm a specific type(s) of pokemon. The function right now (as I understand) goes from Pokestop to Pokestop and looks for close pokemon on the way. You basicly have to rewrite the function ExecuteFarmingPokestopsAndPokemons() and change . But I am really bad at C#...anyone want to help? I think you need to change i.fort to i.catachable.pokemon.

**Comment by AdnanCukur** [comment]
It moves from pokestop to pokestop cause thats where we know 100% there may be pokemon. To do what you want we need logic to implement custom pathing for the bot. If it just walks randomly it will get lost.

**Comment by lolstatsguy** [comment]
I am working on it. My idea is. Search for nearby Pokemon on list. If nothing found go to pokestop. One problem I am having right now: Why does CatachablePokemons have a longitude latidue attr and NearbyPokemon not?

**Comment by joshk6656** [comment]
Nearby is what the radar populates based on. The distance shown is so the footprints work, which they do not right now. All distance is 200 because the server isn't working as intended (iirc)
