### ISSUE TITLE
[Question] Eggs

### ISSUE THREAD

**Issue by Paura91** [NecronomiconCoding/NecroBot#255]
There's a way to auto put eggs in the incubator?

**Comment by gewoon** [comment]
I dont think there is yet. nice suggestion though.

**Comment by lorenzowalz** [comment]
@Paura91 Why dont you help create one?

**Comment by Paura91** [comment]
@lorenzowalz Unfortunately i don't know nothing about that, was just wondering if there's is a way or have to do one, but as i see at moment we don't have.

**Comment by JonatanIsui** [comment]
its somewhat easy to program on C# but it might be complicated to learn how the API works

**Comment by Hitsuomy** [comment]
Not yet, the function will probably be added later on, for now priorities are to keep the bot running without problems. Latter more functions will be tested and added, please be patient.

**Comment by empulse75** [comment]
You can do that by spoofing your gps on your phone to the location you startet the bot and use them, close the app on the phone and profit ;) 
This way may require Root & exposed with the mock mock locations module installed and set up properly
