### ISSUE TITLE
Google Token

### ISSUE THREAD

**Issue by Tarfeite** [NecronomiconCoding/NecroBot#256]
would it be possible to have the token in its own text in the same manner as coords.text is as well as the texts in the Configs folder. i find it mighty usefull for running multiple bots on different accounts. thank you very much and a job well done.

**Comment by Hitsuomy** [comment]
User\Appdata\Local\PokemonGo
Look for the version you are using, edit the user.config. 
It's where it's auto saved.

**Comment by cvax** [comment]
Resolved via https://github.com/NecronomiconCoding/NecroBot/commit/014eed851329a4df38565485700a1a65bc211cc3
