### ISSUE TITLE
(Minor-ish) Pokeballs

### ISSUE THREAD

**Issue by Biizzle** [NecronomiconCoding/NecroBot#260]
I have no pokeballs left as the programme has used the lot and it very rarely seems to find them? It sometimes will go to pokestops but I only get 50/100xp and no items, so it tends to find Pokemon, but can't catch because I have no Pokeballs left to use and it's just not regaining me any from Pokestops, what should I do? - Location is set to Central Park.

**Comment by gewoon** [comment]
Go to a city where the concentration of Pokestops is higher. San Francisco has the most (not sure where exactly)

**Comment by lorenzowalz** [comment]
@Biizzle 

In Settings.cs you can set it to keep more Pokeballs - that way when it does find them you don't have any chance of discarding them.

I would change the 20 to 50, etc.

` new KeyValuePair<ItemId, int>(ItemId.ItemPokeBall, 20),`

**Comment by Biizzle** [comment]
@gewoon  I'll try san fran then :)

@lorenzowalz Already changed those settings :p

**Comment by Biizzle** [comment]
I've changed the co ordinates, but it's not sticking to them when I start it back up, did try restarting the programme too?

**Comment by gewoon** [comment]
Yes you need to also change the coords in Coords.txt But watch out, chaning Location too quick will most likely result in a softban (cant catch pokemon/earn XP). You should wait about 30 minutes+ before chaning from A to B.

**Comment by Biizzle** [comment]
Okay, I'll give it a bit, thanks :)

**Comment by gewoon** [comment]
Coords.txt is located in the bin/Debug folder btw ;)

**Comment by Biizzle** [comment]
Was just looking around confused then haha, thank you! :p

**Comment by Biizzle** [comment]
@gewoon do you know if and how I can focus the bot abit more on pokestops? I just keep getting the same messages.. 
![weird](https://cloud.githubusercontent.com/assets/20605208/17079847/76cdc472-5114-11e6-9378-026d7e1da207.png)

**Comment by ilu01** [comment]
@Biizzle Try an different spot. In the cities are enough pokestop in range that you will never run out of balls

**Comment by Biizzle** [comment]
@ilu01 It just doesn't even seem to try getting them I swear.. But yeah I'll shift it about some more

**Comment by Tvman1231** [comment]
have a look at your inventory, check if its sotring more items than the bag limit (its a bug)

**Comment by Biizzle** [comment]
It's not stopped at one Pokestop in 20 minutes

**Comment by ilu01** [comment]
@Biizzle Very strange behavior, you are reporting there. Have you tried rebuilding? Is anyone else seeing this?

**Comment by Biizzle** [comment]
I have no idea about of the technical parts of the programme to be honest, I just followed the tutorial and went straight with that.. (only just restarting the bot but that's generally all I get over almost an hour..)
![untitled](https://cloud.githubusercontent.com/assets/20605208/17080224/161e97ea-511f-11e6-9eda-6b20b96c82d8.png)

**Comment by fathey** [comment]
@Biizzle log in to your account (Pokemon Go App). Open your Items. Delete everything you don't need.

**Comment by Biizzle** [comment]
I only have 48 items.

**Comment by Biizzle** [comment]
Problem still here, downloaded the newest files.

**Comment by Tvman1231** [comment]
do you have any pokeballs actually left?

**Comment by Biizzle** [comment]
@Tvman1231 Nope, it cleaned me out of Pokeballs because it stopped trying to get more

**Comment by gewoon** [comment]
THe Pokestop information is coming through though... IDK what the prolbem could be...

**Comment by Biizzle** [comment]
I don't know how or why but it's fine now, Pokestops are working again o.O

**Comment by gewoon** [comment]
Oh better! Now i actually got a simular problem... It gets to the Pokestops and shows (INFO) ... but it takes a long time to get the rewards...

**Comment by gewoon** [comment]
Problem could be server related.

**Comment by Biizzle** [comment]
Yeah I on and off will still gets Items with 50/100xp but no balls, but only sometimes does it..
