### ISSUE TITLE
[BUG]Pinsirs not being transfered.

### ISSUE THREAD

**Issue by iBananaa** [NecronomiconCoding/NecroBot#266]
https://gyazo.com/58fef072cce1535153987740e4f9f89c
And no, i didn't add pinsir to exceptions. And i have max duplicates set to 2

**Comment by Cryslacks** [comment]
Change KeepMinCP.

**Comment by iBananaa** [comment]
What if i have a pokemon with lower CP that i don't want to be transferred?
