### ISSUE TITLE
Pokestops.

### ISSUE THREAD

**Issue by Biizzle** [NecronomiconCoding/NecroBot#269]
The bot isn't even attempting to go to Pokestops? If it does try, I don't get anything but 50/100xp? I've had it go for 3 stops in around 45 minutes..

**Comment by PocketMobsters** [comment]
Your bag is probably full if you're only getting xp

**Comment by Biizzle** [comment]
Only just noticed that, I have the 'GPS signal not available' in the way - thanks for that!

**Comment by Tvman1231** [comment]
maybe when bag is full or over capcaity (ive noticed that sometimes the bag stores more items than the limit, so when bag is full and you level up the rewards get stored) recycle the items to the levels set within, i think its the settings.cs in the console project directory
