### ISSUE TITLE
Error while debugging

### ISSUE THREAD

**Issue by GTXMike** [NecronomiconCoding/NecroBot#270]
![error in bot](https://cloud.githubusercontent.com/assets/20617212/17080140/ab3c6346-511c-11e6-89ea-96a3b3c2c71f.JPG)
![error in vs](https://cloud.githubusercontent.com/assets/20617212/17080141/ab3da846-511c-11e6-9b57-4171d8c62687.JPG)

**Comment by Hitsuomy** [comment]
Install latest Net Framework for x64 and x86, it's a dll that comes with the pack.

**Comment by GTXMike** [comment]
Already have latest NET Framework, didnt had any issues with bot last night today this happens but only via google logim, ptc works fine.

**Comment by Hitsuomy** [comment]
LoL, I meant about the building error, the dll is used on net framework, weird. Does this happen in the newest version too?

**Comment by GTXMike** [comment]
Yeah, and yesterday no problems at all was running bot all night without any crashes. PTC works fine.

**Comment by GTXMike** [comment]
And its not building error, this happens when bot asks me to authenticate with google using 8 digit code.

**Comment by Hitsuomy** [comment]
Try to clear the User\Appdata\Local\PokemonGo, maybe it's a conflict error with a file that is already there of config. And also try to normally login with your google account and see if asks for some kind of authentication, I was having some problems the day before yesterday when using my google account, when I tried to login in game it was asking for an authentication for my google e-mail, after the authentication everything was back to normal.

**Comment by GTXMike** [comment]
well i deleted the folder you mentioned, logged in to the google account in game on phone and in nox (works fine), new version came out in the meantime and the error still persists
![error 1](https://cloud.githubusercontent.com/assets/20617212/17080442/aa8d8550-5127-11e6-95a9-36c8edf15be8.JPG)
![error2](https://cloud.githubusercontent.com/assets/20617212/17080443/aa8d91f8-5127-11e6-9f3e-f7654513f75f.JPG)

**Comment by GTXMike** [comment]
why do they bother with this copying to the clipboard thing, i have a feeling that is the problem here, it was fine before to copy the code manually

**Comment by Hitsuomy** [comment]
Well, you can test it, the pasta on Appdata\Local\PokemonGo is where the user.config is auto saved, you can open and edit, put the token manually and try again.

**Comment by GTXMike** [comment]
well after i removed that folder its not longer there, just checked :/ not happy at all as i didn't had any problems with his bot since very beginning

**Comment by Hitsuomy** [comment]
LoL, after you removed the bot would created another one to keep the local conf, weird as f. Don't know, probably a bug on this version, hopefully they will fix it soon.

**Comment by GTXMike** [comment]
yeah, weird cos bot is running fine logged in via PTC and still no folder lol

**Comment by Hitsuomy** [comment]
Maybe they changed the location of the autosave in the newest version? Not sute, I was using yesterday, didn't update yet, will do some tests.

**Comment by Hitsuomy** [comment]
Well, running using google with the newest version, no errors, 4 accounts, all fine.

**Comment by GTXMike** [comment]
what windows you are running?

**Comment by Hitsuomy** [comment]
W10 PRO X64.

**Comment by GTXMike** [comment]
damn, same like mine, must be something wrong on my pc then... hmmmm

**Comment by ReddoKiddo** [comment]
If you guys can't get the bot to build, then there is something wrong somewhere beside the bot, because latest version can be built on our computer... especially if you could build the old version but not the latest...

All of the settings are being saved in bin\Debug\Configs

**Comment by cloudsstars** [comment]
i had the same problem the program will not give you the device code or copy the code to the clip board i got it to work once but as soon as you close the program the fix will not work and i have no clue how to open it back up . for the fix you go to line 62 clip board for device it will have a yellow bar by line 62 then you click   SetText(deviceCode.user_code)) and then move the mose over the little pop up and click thats the code you put in google and then it works again but as soon as you restart your computer  it wont work again and clicking SetText(deviceCode.user_code)) will not show the code so after that this program is use less because there is no way to get the code working again that i can find

**Comment by cloudsstars** [comment]
so after you do that dont restart your computer or close the program because it will never give you the icon to get the code again. and deleting and reinstalling the zip will not fix the problem and it will make other versions do this as well  after a restart. i hope this is fixed on the next version

**Comment by GTXMike** [comment]
I found a solution to my problem. I closed all the program running in tray and bot worked without a problem. After an update one of my programs must of collide with the bot. I didn't install any new programs and the list of programs that i closed is long :) Anyway now its working so Im going to run the bot with bat file to restart it every 25 minutes and leave it for the night,
