### ISSUE TITLE
DisplayHighestsPerfect | DisplayHighestsCP

### ISSUE THREAD

**Issue by decryptionz** [NecronomiconCoding/NecroBot#272]
http://i.imgur.com/YJOiApj.png

Those two are rotating in the new build

**Comment by prodredbull** [comment]
[log.txt](https://github.com/NecronomiconCoding/NecroBot/files/379977/log.txt)
my log i am getting..

**Comment by l3uddz** [comment]
having same issue as prodredbull

**Comment by l3uddz** [comment]
if it makes any difference, wasnt sure wat to set that new distance value to as didnt want to be limited to 1000m, so set it to 100, 000, but even with 1000m it still does this.

**Comment by ReddoKiddo** [comment]
Range doesn't matter if it doesnt find any nearby pokestop (there is a limit how much client can see) it will just loop the main loop and that will print... best way is to change spot with dense pokestops
