### ISSUE TITLE
Reset google device token

### ISSUE THREAD

**Issue by Naprosnia** [NecronomiconCoding/NecroBot#273]
how to manually reset google token/ google/device ?

**Comment by Hitsuomy** [comment]
The token is auto saved in User\Appdata\Local\PokemonGo
Look for the version you are using, edit the user config and done.
Myself I always build and leave a backup without account settings in place, I find this easier.

**Comment by Naprosnia** [comment]
Thanks ;)

**Comment by PureCS** [comment]
Can you please close this ticket if your issue is solved, thanks.
