### ISSUE TITLE
Other languages, or Translation function？

### ISSUE THREAD

**Issue by yanrongmao** [NecronomiconCoding/NecroBot#275]
I come from Japan, English is not my mother tongue, because all over the world for the name of the pocket monster is not unified (using their own language), thanks.

**Comment by Hitsuomy** [comment]
You will probably need to edit manually the names of the pokemons on your bot, for now priority is keep the bot running and without bugs, translations probably later.

**Comment by MichaelGatesDev** [comment]
日本語に翻訳しても、まだそんな機能がなくて、つもりがないと思う。
Even if you were to translate it, there is yet to be any translation feature nor plans for it I believe. 
でも、興味があるんだよ！

**Comment by ReddoKiddo** [comment]
we won't be supporting any translation or localization any time soon, maybe once the GUI is done we will consider it
