### ISSUE TITLE
[REQUEST]: NOT TRANSFER FAVORITE and AUTOMATIC EGG INCUBATOR

### ISSUE THREAD

**Issue by n3o999** [NecronomiconCoding/NecroBot#277]
Hi, it's possible add a function that use "KeepMinDuplicatePokemon =1 or 2" but not transfer only favorite pokemon for example i want 2 pikachu (one to evolve)

and

automatic egg incubator (or already exists)

thanks

**Comment by Hitsuomy** [comment]
Automatic egg incubator is a function not yet present, be patient, there's like 20 of this requests already here.
The bot will keep only the highest cp duplicate and any other with 85%+ Ivs, if you want the Pikachus to not be transferred just add it to the whitelist.

**Comment by n3o999** [comment]
For add in white list 

Config/configpokemontokeep? 

Right?

But so if i catch 30 pikachu, all not be transfer. I Want only 2. 

Or for example  3 pinsir. The favorite_not_transfer=true is a intresting feature

Thanks for all

**Comment by Hitsuomy** [comment]
Hm, I see, you want to be specific about the quantity of a pokemon. Well, not present in the moment, you can add to the whitelist and manually transfer the others or wait for a Higher IVs Pikachu, I think that putting in the white list is not that bad, not all days you will get a Pikachu, I only got one with the account I'm botting for the last 2 days, so, probably will never be 20 pikachus to transfer, in a good day you will catch 4 to 6, easy to transfer only this much while waiting for this function.

**Comment by n3o999** [comment]
How to add in white list ? Thanks a lot

**Comment by ReddoKiddo** [comment]
ConfigPokemonsNotToCatch.txt in bin\debug\configs
