### ISSUE TITLE
[request] Max Level

### ISSUE THREAD

**Issue by TheIEnd** [NecronomiconCoding/NecroBot#282]
hi,

requesting the ability to set a level cap for an account - meaning, you set level 20 in the config, and the bot will logout and stop leveling the account once it reaches that level

**Comment by PocketMobsters** [comment]
I can incorporate an option for this if this gets enough support.

**Comment by dbfy** [comment]
Isn't it just doing a check in the Logic loop, if char is over X level(grab it from Statistics) Exit console?

**Comment by blindreaper** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/350
