### ISSUE TITLE
Can't complete build

### ISSUE THREAD

**Issue by DelinquentIxO** [NecronomiconCoding/NecroBot#287]
![boterror](https://cloud.githubusercontent.com/assets/20617599/17080365/bf10b424-50f1-11e6-8205-65582a97e6d8.PNG)

When attempting to build, receiving the following error within the Settings.cs file.  

Direction would be appreciated to get me up and running.

Thanks!

**Comment by Caydenz** [comment]
Ctrl+H -> Replace ".Default." with "."

**Comment by ReddoKiddo** [comment]
delete the whole project folder and redownload, if the bot doesn't build we would have already noticed and reverted the update
