### ISSUE TITLE
[Request] Item recycle threshold on a separate file

### ISSUE THREAD

**Issue by kbm15** [NecronomiconCoding/NecroBot#288]
Like with the keep and evolve, another txt for those who want custom recycle thresold.
Thanks

**Comment by Caydenz** [comment]
Check the Settings.cs file. You can modify the values there.

**Comment by kbm15** [comment]
But anytime I upgrade the file goes nuts.
I don't want to lose my changes every update

**Comment by zstraken** [comment]
Unfortunate kbm15, but a big thanks to Caydenz on this! I was scratching my head trying to increase the threshold. :D 

Seriously I ain't programmed since 2001, so this whole process has been incredibly fun/incredibly frustrating.

**Comment by marksterxxx** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/305

**Comment by ReddoKiddo** [comment]
Will close coz of PR
