### ISSUE TITLE
"Bug" Next level in...

### ISSUE THREAD

**Issue by crack00r** [NecronomiconCoding/NecroBot#296]
cant be 0,66hours, shouldnt it be 0 h and 40min. ?

**Comment by Rawrlex** [comment]
It should be, yes. But the priority of this is not that high I guess. Since you can guess yourself how many time is approx. left.

**Comment by vingesus** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/317

There you go :)

**Comment by ReddoKiddo** [comment]
Close because PR request is made
