### ISSUE TITLE
[Bug] Console window can't be expanded to the right

### ISSUE THREAD

**Issue by Rawrlex** [NecronomiconCoding/NecroBot#298]
Well, title says everything. I can't see every information in the headline as well as some lines could be in 1 and not in 2 lines. I just can't increase it to the right or is this a fail by myself?

**Comment by gewoon** [comment]
Sometimes the edge of the window is a littlebit more to the right, try moving your mouse just a bit more to the right.

**Comment by Rawrlex** [comment]
The arow to shrink/enlarge the window is on the left and on the right, but nothing happens when I am rying to pull it. Only If I want to shrink it back.
