### ISSUE TITLE
[Suggestion] Split Branches

### ISSUE THREAD

**Issue by Tvman1231** [NecronomiconCoding/NecroBot#300]
Just a consideration, may be split the bot to 2 branches or modes, one for extreme most efficient farming and one for conservative human like mode.

**Comment by PocketMobsters** [comment]
These are all configurable in the settings, why would we make two branches of the same code with different default settings being the only difference?

**Comment by PureCS** [comment]
You could implement a method to modify settings without re-compiling, 'presets' or something similar. Then you could select which to use from the console.

**Comment by ReddoKiddo** [comment]
This is well... pretty not important so no, please do it yourself
