### ISSUE TITLE
Trash, Evolve, Transfer SPAM

### ISSUE THREAD

**Issue by CL24** [NecronomiconCoding/NecroBot#308]
Wouldnt it be enough to do that every 20 or 50 stops?  Here's what i'm testing right now but not sure if i'm missing something:

![image](https://cloud.githubusercontent.com/assets/20602322/17080737/12c7758c-513b-11e6-8756-ab73c16dcb9e.png)

**Comment by Daylend** [comment]
My latest PR should fix this. Basically the same thing. :+1: 

https://github.com/NecronomiconCoding/NecroBot/pull/312
