### ISSUE TITLE
[Minor] Getting rewards from Pokéstops...

### ISSUE THREAD

**Issue by gewoon** [NecronomiconCoding/NecroBot#309]
Since the update it takes a very long time before i've received my rewards. Take a look.
`[01:12:44] (INFO) Dukes Saloon in (49m)
[01:12:55] (POKESTOP) XP: 50, Gems: 0, Items: 1 x ItemRazzBerry, 2 x ItemGreatBall`
It took about 10secs here. It used to be instant. Is this like a new function or just an issue?

**Comment by Hitsuomy** [comment]
Probably server related, peak hours during weekend. In game the same thing happens.

**Comment by gewoon** [comment]
Ah thanks Hitsuomy!

**Comment by gewoon** [comment]
I hope this is a server issue, it works fine for my other bot. (Times Square, NY)
