### ISSUE TITLE
Repeating transfers and recycling

### ISSUE THREAD

**Issue by Naprosnia** [NecronomiconCoding/NecroBot#313]
the latest version is repeating the transfers and recycling.

![repeat](https://cloud.githubusercontent.com/assets/13961757/17080902/be913076-5139-11e6-8410-bcdce270cb10.png)

**Comment by marksterxxx** [comment]
Tried debuging this, caused by no pokestops detected. it seems some areas/servers not loading pokestops.... in some places still work.
![trs](https://cloud.githubusercontent.com/assets/2887363/17080832/fdfa459e-5171-11e6-9859-65cdff8f8ab6.PNG)

**Comment by Naprosnia** [comment]
here I do not have this problem ("No Nearby Pokestops").

**Comment by marksterxxx** [comment]
I added that line to check...
![capture](https://cloud.githubusercontent.com/assets/2887363/17080863/f8b11314-5172-11e6-8805-2f71f505f4fa.PNG)

**Comment by marksterxxx** [comment]
I tried deleting GoogleAuth.ini in configs file to relogin google, now bot finds pokestops

**Comment by Naprosnia** [comment]
I added that line and not had this problem.

**Comment by Shroomzie** [comment]
I have noticed it repeating for quite a few versions now

**Comment by PocketMobsters** [comment]
I'm looking into this but I don't think it's as easy as I think it might be.

**Comment by marksterxxx** [comment]
But for some accounts in different location it is not repeating..

**Comment by marksterxxx** [comment]
Update:
In client settings set MaxTravelDistanceInMeters to 0
Found out this causes the problem:
` ( // Make sure PokeStop is within max travel distance, unless it's set to 0.
                            LocationUtils.CalculateDistanceInMeters(
                                _clientSettings.DefaultLatitude, _clientSettings.DefaultLongitude,
                                    i.Latitude, i.Longitude) < _clientSettings.MaxTravelDistanceInMeters) ||
                                        _clientSettings.MaxTravelDistanceInMeters == 0
                            );`

**Comment by Dgc2002** [comment]
Yup just saw that myself. I'm not sure if I'm configuring my position incorrectly or what but it's comparing to the default values rather than where the bot is actually at:  
![](http://i.imgur.com/c0BEcKN.png)

**Comment by mrnitrate** [comment]
#337 I believe its caused by the inventory cache system its only setup to cache the gets and does nothing with sets.  

```
private async Task<GetInventoryResponse> getCachedInventory()
        {
            var now = DateTime.UtcNow;
            SemaphoreSlim ss = new SemaphoreSlim(10);

            if (_lastRefresh != null && _lastRefresh.AddSeconds(30).Ticks > now.Ticks)
            {
                return _cachedInventory;
            }
            else
            {
                await ss.WaitAsync();
                try
                {
                    _lastRefresh = now;
                    _cachedInventory = await _client.GetInventory();
                    return _cachedInventory;
                }
                finally
                {
                    ss.Release();
                }
            }
           
        } 
```

**Comment by ellm62** [comment]
![capture](https://cloud.githubusercontent.com/assets/20610048/17082996/aa419b3e-5188-11e6-8710-4f748c4ed2a2.PNG)
