### ISSUE TITLE
[QUESTION] Gym

### ISSUE THREAD

**Issue by pattythesleeper** [NecronomiconCoding/NecroBot#316]
It search for Gym. does it do anything on the gym? Thers 4 gyms close too me and whit my pokemons i should easily be ablee to take over those gym :)

soo my question is does the bot do anything at the gym?

**Comment by Shroomzie** [comment]
no

**Comment by gewoon** [comment]
No and the developer has no intention in adding such feature to not defeat the point of the game.

**Comment by Shroomzie** [comment]
remember to close the issue if you find a solution
