### ISSUE TITLE
Gmail freshtoken

### ISSUE THREAD

**Issue by MarkHuangZ** [NecronomiconCoding/NecroBot#319]
Would you mind to keep the token available as before? The token is relatively more convenient than log in using browsers. Otherwise, keep the token as the first login option, if the user choose to Gmail and token is empty, copy code to clipboard. Could you implement this feature? 

Btw, you guys awesome.

**Comment by gewoon** [comment]
It's now in the bin/Debug/Configs folder.

**Comment by Shroomzie** [comment]
remember to close the issue if you find a solution

**Comment by MarkHuangZ** [comment]
i will, searching for debug folder now.

**Comment by Shroomzie** [comment]
It should look like this C:\Users\YOUR\PATH\TO\YOUR\BOT\FOLDER\NecroBot-master\NecroBot-master\PokemonGo.RocketAPI.Console\bin\Debug\Configs
