### ISSUE TITLE
Problem - Exception System

### ISSUE THREAD

**Issue by welshman** [NecronomiconCoding/NecroBot#320]
My bot keeps showing this error ...

> [01:06:41] Logging in via: Ptc
> [01:06:42] Exception of type 'PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException' was thrown. from Pokemon Go Rocket API

After error shown it restarts and repeats this same error constantly in a loop

Bot Version 1.0.4.0 -  Commit: Merge pull request #314 from PocketMobsters/master 

Can any one help resolve this ? thinking might be some thing simple but cant work it out my self.

**Comment by PocketMobsters** [comment]
You may need to log into your Ptc account on their website, some accounts have needed to re-verify email. They only keep accounts open for 2 days unless email is verified, and some accounts have needed to re-verify.

**Comment by welshman** [comment]
ok thank you , going check that out now

**Comment by Shroomzie** [comment]
remember to close the issue if you find a solution

**Comment by TrYkeRm4N** [comment]
re-activate doesn't work this time, I try it.

I open the PTC account with a older version of other bot, it is working perfectly, but with our last version, nope. 

So I think something is broken with the PTC login of this project.
