### ISSUE TITLE
Eggs Informations

### ISSUE THREAD

**Issue by benda95280** [NecronomiconCoding/NecroBot#321]
I all,

i don't see anything about eggs ?
Can it say a message when an eggs open ?
Can it put an eggs into an incubator automaticaly ?
Can it Dump 2 Kms eggs when Eggs > 8 ?

Thanks

**Comment by PocketMobsters** [comment]
We do not have functionality in the API for adding eggs to incubators, and you can't drop eggs in the real game either. We're looking forwards towards adding egg functionality, and I'll look into listening for egg hatches too.

**Comment by gewoon** [comment]
There is a lucky egg functiontionality, right? If so would it be hard to implend?
