### ISSUE TITLE
Objects informations

### ISSUE THREAD

**Issue by benda95280** [NecronomiconCoding/NecroBot#322]
Can it use XP Eggs automaticaly to get more XPs ?
So somethings i think should be interesting is to stay with Encents and XPs Egg near a boosted Pokestop ?

Or if impossible, walking automaticaly with encent when have it ...

**Comment by gewoon** [comment]
There is no such feature yet. i'm hoping there will be soon. I also heard that the bot won't catch Pokemon that are lured (from e.g. boosted pokéstop).

**Comment by Shroomzie** [comment]
lure pokes and wild pokes apparently show as two different entities. 

xp eggs prolly best to keep for batch evolving.
