### ISSUE TITLE
[Transfering] Wrong Pokemon

### ISSUE THREAD

**Issue by Mquark** [NecronomiconCoding/NecroBot#328]
I just started the new version 1.0.4.0 with this settings and it just transfered 2 100% IV Pokemon.
I immediately closed it, what happened? :(

Is it an "and" condition between MinIV and MinCP? Because I thought when I set up 95% IV, the NO Pokemon with Higher than 95% will be transfered....

![screenshot_2](https://cloud.githubusercontent.com/assets/20614439/17081122/415bf286-514c-11e6-80b9-842e1d2fb28c.jpg)

**Comment by Shishiaha** [comment]
Hi.

https://github.com/NecronomiconCoding/NecroBot/issues/301#issuecomment-234748300

**Comment by CTDragon** [comment]
I found the problem. Someone removed a line of code somewhere. Probably a merge mistake. Putting it back. The check for cp and iv was gone completely.

**Comment by Shishiaha** [comment]
As said in ; https://github.com/NecronomiconCoding/NecroBot/issues/301#issuecomment-234748300

**Comment by CTDragon** [comment]
I missed your link.
