### ISSUE TITLE
Need KeepMinCPPercentage plus consider both CP% AND IV%

### ISSUE THREAD

**Issue by ggouki** [NecronomiconCoding/NecroBot#331]
Right now during transfer of duplicates the bot either considers high IV pokemon or high CP pokemon - we need a an option to have it consider both.

The best way to do that would be a KeepMinCPPercentage (that considers IV and the player level, given how current potential max CP of a pokemon depends on that) and if it meets a certain percentage keeps that pokemon - no matter what.

For example the max CP for Eevee at level 40 is 1077.20 (at 15/15/15 i assume). Let's round that to 1000 cp. 

If i set KeepMinCPPercentage to 80 - if it finds any Eevee below 800 CP it would trash it, even if it has high IV values and keep 800+ Eevee's if the bot isn't set to consider both CP & IV - otherwise it should be able to trash even 800+ Eevee's if they don't have high enough IV percentage (decided through KeepMinIVPercentage).

Lattest commits trashes everyone's high IV pokemon that don't meet the KeepMinCP and have PrioritizeIVOverCP set to false.

But if PrioritizeIVOverCP  is set to true it trashes everyone's high CP pokemon in favor of high IV ones.

Edit: Guess it was only a recent bug that high IV pokemon got trashed when PrioritizeIVOverCP  was set to false.

Still, a KeepMinCPPercentage plus it considering both CP and IV as an option would be neat.

**Comment by Shishiaha** [comment]
You are right. I think IV > CP no matter what. The best w

**Comment by solenrus** [comment]
IV>CP fuck the rest, bud

**Comment by ggouki** [comment]
IV is greater than CP. But I'm not gonna level a 15/15/15 Dratini to max CP and spend 200k+ dust.

We need at least an option to consider both to some degree. I myself definitely don't want a perfect IV pokemon if it's below 50% of it's max CP - that's me being reasonable. I'd probably place it more at 70-80%. Not gonna level anything below that for a few extra CP.

**Comment by PocketMobsters** [comment]
It will only remove your higher CP pokemon in favor of higher IV ones if you toggle PrioritizeIVOverCP to true in the settings, if you prefer CP just turn that to false, it will still keep any IVs over your minimumIV.

That's the whole point of PrioritizeIVOverCP. False = Top CP True = Top IV

**Comment by PocketMobsters** [comment]
Although I will ask the other devs if having acceptable ranges for both is something we should add.

**Comment by orangesuave** [comment]
I have this working. Not sure how to post commits here, but I'll give the logic in a future comment. (smoke break)

**Comment by orangesuave** [comment]
BaseStats baseStats = PokemonInfo.GetBaseStats(duplicatePokemon.PokemonId);
                var max_cp = PokemonInfo.CalculateMaxCPMultiplier(duplicatePokemon);
                var min_cp = PokemonInfo.CalculateMinCPMultiplier(duplicatePokemon);
                var cur_cp = PokemonInfo.CalculateCPMultiplier(duplicatePokemon);


                var maxCPPercent = ((cur_cp - min_cp) / (max_cp - min_cp)) * 100.0;

                if (PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >= _clientSettings.KeepMinIVPercentage || (duplicatePokemon.Cp > _clientSettings.KeepMinCP && maxCPPercent >= 0.8))
                    continue;

**Comment by orangesuave** [comment]
put this under the foreach (var duplicatePokemon in duplicatePokemons) loop

**Comment by ggouki** [comment]
@orangesuave That's exactly it.  Or you know

```
                if (PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >= _clientSettings.KeepMinIVPercentage || (duplicatePokemon.Cp > _clientSettings.KeepMinCP && PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >= 0.65))
                    continue;
```

and replace || with && to consider both.

Hopefully this makes it into a commit one day.
