### ISSUE TITLE
Algorithm of pokebot is inefficient

### ISSUE THREAD

**Issue by wetshrimp** [NecronomiconCoding/NecroBot#332]
I just logged on the phone after going thru 20 stops or so and im in a VERY high density area for stops. the Purple stops only span an intermittent line when there are literally dozens of stops surrounding me in each direction. maybe reached under 10% of them. 

However, when I look at my bot log ( i turned on distance notifications) it is attempting to go 200-700m away sometimes whereas theres probably 10 stops already in a 100m radius.

Just bringing it up to see if you can adjust it. perhaps using a local radius from initial GPS point and moving radially and returning? 

Thanks for all the help!

**Comment by JoshYuen** [comment]
There is a pathing version in the works where the user can draw a path and make the bot follow it. There is also current a radius setting in the current commit that allows you to only travel X meters away from the starting point.
