### ISSUE TITLE
[Q] Farming spots

### ISSUE THREAD

**Issue by pattythesleeper** [NecronomiconCoding/NecroBot#334]
Where is the best Farming spoot and good spoots to find good pokemons?

Ive been boting on 5 diffrent places at one time whit the bot for 6 hours now and i must say untill now Tokyo seems to be the best place. (I know i should not run it on 5 diffrent places at one time whit one account but yeah fast lvl and pokemons lol)

**Comment by pattythesleeper** [comment]
i know this may not belong here

**Comment by Shroomzie** [comment]
then close it

**Comment by Shroomzie** [comment]
http://lmgtfy.com/?q=top+hotspots+to+hunt+pokemon
