### ISSUE TITLE
HI I just couldn't change my account

### ISSUE THREAD

**Issue by regnar98** [NecronomiconCoding/NecroBot#335]
I tried to delete everything even pokemon in my appdata. But everytime it will automaticlly login my first account. I don't know why

**Comment by Shroomzie** [comment]
try looking closer to the program

C:\Users\YOUR\PATH\TO\YOUR\BOT\FOLDER\NecroBot-master\NecroBot-master\PokemonGo.RocketAPI.Console\bin\Debug\

**Comment by regnar98** [comment]
@Shroomzie .and now it's not working for transfer, my inventory is full again. I want it to transfer all pokemon except 100 perfection. So I set 100 and minCP 10000. But it transfer nothing...

**Comment by Shroomzie** [comment]
Where did you set "100"?
