### ISSUE TITLE
Inventory caching is causing the duplicate transfer and recycle messages

### ISSUE THREAD

**Issue by mrnitrate** [NecronomiconCoding/NecroBot#337]
The inventory cache does not invalid or update when items are recycled or pokemon transferred.

This causes the bot to attempt to transfer or recycle items/pokemon more than once until the cache refreshes (max 30secs) .

**Comment by JoshYuen** [comment]
Anyone know exactly why the inventory is being cached for 30s?

**Comment by ilu01** [comment]
it was implemented, because e.g. the pokeball search function called a new inventory search 4 times. Caching was a workaround for that matter.
