### ISSUE TITLE
ConfigPokemonsToKeep not working.

### ISSUE THREAD

**Issue by NumberXer0** [NecronomiconCoding/NecroBot#339]
I'm trying to configure the bot to keep all Pidgey, Rattata, Weedle and Caterpie so I can pop a Lucky Egg and have the bot mass evolve after I gather enough. However, the filter does not work. I added the Pokemon to the config file and even added the names to the Settings.cs but the game still transfers them anyway. I want to keep transferring every other duplicate, just not those four. Is this bugged or am I doing something wrong?

I haven't tried yet, but is evolving done the same way? Add the names to the ConfigPokemonsToEvolve file? Is there anything else that needs to be done?

**Comment by Akimata** [comment]
Yeah its not working properly,  go to bot folder\PokemonGo.RocketAPI.Console and copy whole configs folder to other place, then enter Visual Studio add folder, name it Configs copy files that u moved in last step to newly created folder in this location then go to VS again edit it and add pokemons u would like to keep then copy that file and paste it to  \PokemonGo.RocketAPI.Console\bin\Debug\Configs
