### ISSUE TITLE
QUESTION - 'Do not catch'

### ISSUE THREAD

**Issue by Biizzle** [NecronomiconCoding/NecroBot#343]
How do I filter out catching particular Pokemon? I'm tired of all the Pinsirs and Pidgeys.. I've found the do not catch txt file, just not sure how to writing thing out on and off the programme..

**Comment by Shroomzie** [comment]
This is not a issue. try the discord for help

**Comment by Biizzle** [comment]
@Shroomzie Yeah see, I don't know what that is..

**Comment by Shroomzie** [comment]
Its in the readme https://github.com/NecronomiconCoding/NecroBot
