### ISSUE TITLE
[Suggestion] Latitude / Longitude Coords.ini update on change

### ISSUE THREAD

**Issue by JoshYuen** [NecronomiconCoding/NecroBot#344]
I noticed that once you have run the bot once updating the user setting lat/lng coords doesn't do anything. What if instead if the user settings values differ by a large % from the ones saved in the coords.ini a prompt appears on the console. Basically the user is warned that: 
"Softbans may occur if you move too far from your last position. Are you sure you want to proceed?
Press [y] - yes use new coords [n] - no use last logged coords

**Comment by ismcalpi** [comment]
Second this, if your Coords.ini Lat/Long is further than MaxTravelDistanceInMeters compared to your Default Lat/Long then the bot doesn't find any pokestops and loops without attemping to move. Prevents us from moving even within a city without editing the .ini file.

**Comment by CTDragon** [comment]
This is a good idea. I was thinking of adding something to delete the logged coords and start from the beginning if the last modified time is greater than a certain time. I may incorporate a realistic distance/time aspect to it. I will start on this tomorrow if no one else has done it. Many times I will start on something then see a pull request for the thing I am working on. Ha.

**Comment by CTDragon** [comment]
Adding this now since pull requests were just cleared.

**Comment by CTDragon** [comment]
Almost done, testing

**Comment by CTDragon** [comment]
Had to move some stuff around. Done with testing. Merging, test once more, the I'll create a pull request.
