### ISSUE TITLE
Configs folder stll not showing up on visual studio

### ISSUE THREAD

**Issue by qaqsd123** [NecronomiconCoding/NecroBot#347]
The configs folder from PokemonGo.RocketAPI.Console including the files inside of it are no longer showing up in visual studio.

**Comment by iBananaa** [comment]
I was about to open an issue about this, ty. 
-> https://gyazo.com/d278f7b9d49797b7b12c4d941ea3fdc0

**Comment by PocketMobsters** [comment]
There may not be a config folder in your project explorer but if you go to your NecroBot-master\NecroBot-master\PokemonGo.RocketAPI.Console section and you should find it there. Alternatively it may also show up in that directories bin/debug folder.

**Comment by qaqsd123** [comment]
nah not showing up on either of those

**Comment by PocketMobsters** [comment]
Yes, the list still functions as usual.
