### ISSUE TITLE
[Question] Is EGG hatching supported?

### ISSUE THREAD

**Issue by RZeroFrost** [NecronomiconCoding/NecroBot#349]
Ive heard mixed answers, does lowering the 'walkspeed' param to being within the 20kmph limit let us hatch eggs, and what is this about pokemon not appearing from hatched eggs?

**Comment by Shroomzie** [comment]
It has come up a few times, there seems to be demand for it. currently there is not the option in this repo.

**Comment by PocketMobsters** [comment]
We're working on extending the API to provide this functionality. We'll get there man, just give us some time!
