### ISSUE TITLE
[ISSUE] I get this 2 errors when i try to start it .

### ISSUE THREAD

**Issue by iBananaa** [NecronomiconCoding/NecroBot#352]
https://gyazo.com/247f0ae93cbe10ac04df0402c38e4b97

->lines
https://gyazo.com/b4ff0d80e65de081a572ba06f1a92b0c
https://gyazo.com/e64f096aa19d6d029394f55773ff0ebc

**Comment by iBananaa** [comment]
print("Nevermind, i was missing a parenthesis  on line 41. I think i'm starting 2 learn how to code guys !"),
//This post will be deleted in 5 minutes !

**Comment by Shroomzie** [comment]
Like this?
`new KeyValuePair<ItemId, int>(ItemId.ItemPokeBall, 50),`

**Comment by iBananaa** [comment]
Exactly @Shroomzie
