### ISSUE TITLE
[ISSUE] Is there any other way 2 add pokemons to exceptions since the folder is missing?

### ISSUE THREAD

**Issue by iBananaa** [NecronomiconCoding/NecroBot#353]
https://gyazo.com/d278f7b9d49797b7b12c4d941ea3fdc0
No config folder, can i change the parameters directly on the code?
https://gyazo.com/41e93f23e3116d575c5595e84fc462e1
I only want to evolve my pidgeys, can i remove "Ratata" and "Zubat" directly from the code ?

**Comment by PocketMobsters** [comment]
There may not be a config folder in your project explorer but if you go to your NecroBot-master\NecroBot-master\PokemonGo.RocketAPI.Console section and you should find it there. Alternatively it may also show up in that directories bin/debug folder.

**Comment by CTDragon** [comment]
The config folder will be in Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\bin\Debug\Configs
It will not show up in your Solution Explorer

Also, yes, you can remove ratata and zubat from the code to only level the pidgeys based on the picture of the code you sent. However, if there is a config file, it will use the values from that instead, so make sure that that file doesn't already exist in the relative folder path that I provided above.

**Comment by iBananaa** [comment]
@PocketMobsters @CTDragon Alright, what i did was to open both "ConfigPokemonsToEvolve.txt" from
"NecroBot-master\NecroBot-master\PokemonGo.RocketAPI.Console/Configs" and " Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\bin\Debug\Configs" edit both files, then remove "Ratata" and "Zubat" on the code and it works like a charm. Thank you both for the help !

**Comment by CTDragon** [comment]
Note that in the latest version someone added them to the solution explorer and it will replace your config every time. To fix this, edit the config from the solution explorer or right click the file and change the setting that says Copy Always to Copy if Newer. Then it will never replace your file unless you update it from the solution explorer/ ide.
