### ISSUE TITLE
[BUG] Pokemons only evolve when the bot starts.

### ISSUE THREAD

**Issue by iBananaa** [NecronomiconCoding/NecroBot#354]
When the bot starts it evolves the pokemons set to evolve, after thet, if it catches more doesn't evolve them, also, i do have enough candies .
I checked that by restarting the bot and it's confirmed.

**Comment by pattythesleeper** [comment]
@iBananaa its the same for me it only evolve when i start the bot

**Comment by Hitsuomy** [comment]
It's not only when starts, it's just hat the INFO check of berries and everything occurs after a couple of hours, so you would need to wait a couple of hours before evolving again.

**Comment by bebar69** [comment]
I think Evolve before transfer can be better
