### ISSUE TITLE
Automatic restart

### ISSUE THREAD

**Issue by Smallinger** [NecronomiconCoding/NecroBot#358]
Hey, can you add an automatic restart or reconnect script if nothing doing after a time you can set ?

**Comment by dark0p** [comment]
i think it's already doing that

**Comment by Hitsuomy** [comment]
It's already implemented, you just need to wait a little but I saw this earlier yesterday happening, got a disconnect from my internet signal, bot connected automatically couple of minutes after the sinal was back, about 2min.
