### ISSUE TITLE
Running multiple bots at same time

### ISSUE THREAD

**Issue by squishy23456** [NecronomiconCoding/NecroBot#359]
Tried looking through issues and talking on chat but can't seem to find anything about running multiple bots. I'm not very good with programming and such so please give detailed explanation. How would I run a second bot using my 2nd google account? Current bot running in santa monica california. Want to run a second one in central park NY. 

Thanks.

**Comment by joshk6656** [comment]
Just make a copy of the folder and change the config file and run it

**Comment by Hitsuomy** [comment]
Edit the settings before building, make a backup copy, change the coords, run from the 2 different folders.
