### ISSUE TITLE
Transfer Pokemon dont work often for Pinsir's

### ISSUE THREAD

**Issue by trashbit** [NecronomiconCoding/NecroBot#367]
I wake up and my Hole Pokemon Space was full with Pinsir's

**Comment by Sylencer90** [comment]
You set the KeepMinCP too low, had the same issue.

**Comment by trashbit** [comment]
Was default on 1

**Comment by trashbit** [comment]
thx for you help

**Comment by n3o999** [comment]
@Sylencer90  i have a 20 pinsir. levev 1200 to 1400. keepMinCP set to 1000  if i set to 1300 hw appened? thanks
