### ISSUE TITLE
My bot is in amsterdam, not in Sweden Help!

### ISSUE THREAD

**Issue by Kaffetjuven** [NecronomiconCoding/NecroBot#374]
Hi, i dont know were else i can post. 

My coordinates are following, stating me to be in Sweden. But i've also got (Info) while bot is running "Sex Museum Entrance in 43m"
or Building "De Utrecht" in 1m
Which doesnt exist is Sweden were i want too be. Is Default Altitude the problem ? Suggestion

![i amsterdam](https://cloud.githubusercontent.com/assets/20623075/17083072/f9a2173e-5193-11e6-88ad-e965f9ff2c84.jpg)

![cords](https://cloud.githubusercontent.com/assets/20623075/17083065/b274eb98-5193-11e6-936e-c4f58870ea5d.png)

**Comment by Antidote78** [comment]
Change the lat and long and also delete Coord. Ini and recompile

**Comment by Kaffetjuven** [comment]
I changed the Latitude & Long too were i want to be by the guide that Necro did. But should i delete coord.Ini and recompile it ?

**Comment by djoey123** [comment]
Yes you need to delete coord.ini if you want a new location

**Comment by Kaffetjuven** [comment]
I did delete Coord.ini, and got new latitude & long into usersettings just incase. Started up the bot and once again i wind up in Amsterdam.

**Comment by Kaffetjuven** [comment]
Think i resolved it, Thanks for helping me guys.

**Comment by Antidote78** [comment]
What was the issue then ?
