### ISSUE TITLE
Since the last update, the bot stopped from farming pokestop and transfer duplicate

### ISSUE THREAD

**Issue by bronzeboy** [NecronomiconCoding/NecroBot#378]
Title, it just alert it but don't farm it!

It also don't trasfer pokemon anymore?

http://imgur.com/a/WrELH

**Comment by CL24** [comment]
softban

**Comment by Antidote78** [comment]
It looks like you forgot to change the location in the settings :)
Make sure you put the right location because the update might have overwritten your usersettings.setting and change the value of lat and long

**Comment by bronzeboy** [comment]
My bad then, thanks guys!
