### ISSUE TITLE
Updating without redownloading

### ISSUE THREAD

**Issue by NumberXer0** [NecronomiconCoding/NecroBot#379]
Is there a way to update the files without deleting everything and starting from scratch? A bot I used last week had a command you could input into the console to download the new files and automatically update. Just a question/suggestion. Not sure if it's already in place. It would just be much easier than having to redownload and do the config over and over. Especially if you run 2-3 bots, like myself.

**Comment by PocketMobsters** [comment]
Store copies of your config files, if a config update does happen, all you need to do is append the appropriate text.
