### ISSUE TITLE
[REQUEST] Evolving all Pidgeys?

### ISSUE THREAD

**Issue by salvaracer** [NecronomiconCoding/NecroBot#381]
Hey, i have now more then **2000 Pidgey Bombons.**.
I thrink a configuration for `PokemonThatShouldAlwaysEvolve` wouzld be useful?!

All other settings and configurations are quite good!

**Comment by AdnanCukur** [comment]
Exit the bot. Enter Pidgey in the PokemonsToKeep.txt config file. Let the bot run a while to catch loads of pidgeys. Exit the bot. Set EvolvePokemon to True in main config file. Write Pidgey in the PokemonsToEvolve.txt config file. Start bot, watch all pidgeys evolve..

**Comment by reflexx666** [comment]
Even if I only set pidgey in pokemonstoevolce txt file it evolves everything.

**Comment by NumberXer0** [comment]
This doesn't work. I posted an issue about it earlier. Even when added to the keep list, it transfers them anyway. Same thing with the evolve config, still evolves everything. The config files seem to be broken.

**Comment by kraizy** [comment]
+1 - Would be great to just let selected pokemons evolve

**Comment by Sylencer90** [comment]
Agreed with evolve only specific pokemons.

**Comment by carcerDunnit** [comment]
Adding to this also experience the ignore of config file involving evolve,  setting Pidgey in keep text still transfers.

**Comment by reflexx666** [comment]
It is changed now. There were 2 places of the config txt files. We edited the wrong one. New version deleted the wrong folder.
