### ISSUE TITLE
[Question] Transfering

### ISSUE THREAD

**Issue by marrcha** [NecronomiconCoding/NecroBot#386]
Is transfer quite working? 
The thing is I have put min IV to 40 and Min CP to 300, after a while I logged in and I had like 30 ratatas which most was around 10-100cp. Min duplicate is set to 1, what will happen when I get 250/250 poke?

**Comment by Kaffetjuven** [comment]
If you get 250/250 You cant catch any pokemon until you transfer someone

**Comment by reflexx666** [comment]
Min IV 40 is low. Maybe they are all above 40. Why would you want to keep any pokemon with IV below 80. I set it to 90.

**Comment by marrcha** [comment]
And could some one explain what is IV? In few words

**Comment by l3uddz** [comment]
Google....

**Comment by marrcha** [comment]
ok, thanks for your answers, put min IV much higher and all my lows was transfered :)

**Comment by reflexx666** [comment]
It is a calculation of the potential that your Pokemon has. The higher the IV the stronger your pokemon is (for that type). A 100% IV pokemon has the highest Def and attack possible for that pokemon. Keeping 40% pokemon is useless since they are weak.

**Comment by AdnanCukur** [comment]
In few words.. IV is hidden stats for your pokemon. IV in the bot is a percentage of how perfect those stats are.

In plenty words https://www.reddit.com/r/TheSilphRoad/comments/4tzcmk/faq_on_ivs_info_megathread/
