### ISSUE TITLE
Bot keeps restarting with exception

### ISSUE THREAD

**Issue by reflexx666** [NecronomiconCoding/NecroBot#388]
I keep getting an exception and the bot restarts in Ptc login. It is an "accountnotverifiedexceptoon". First I thought the Ptc servers were down, but they seem to be up.

**Comment by TheCrimsonDevil** [comment]
Did you do the email verification?

**Comment by reflexx666** [comment]
Thanks, that did the trick. For some reason I have been able to use the account for some days and now it got stuck. You would expect this issue to happen at first login.
