### ISSUE TITLE
can not get google device code copied to clipboard

### ISSUE THREAD

**Issue by LoYalHoly** [NecronomiconCoding/NecroBot#391]

**Comment by TheCrimsonDevil** [comment]
What happens? Does it give an error? What version of Windows are you using?

**Comment by LoYalHoly** [comment]
W10

**Comment by LoYalHoly** [comment]
(https://cloud.githubusercontent.com/assets/20624558/17083860/c07369b8-5161-11e6-8d47-d796930a1627.png) this is picture

**Comment by BoostingStore** [comment]
I checked on two computers WN10 and WN7 could not get a confirmation code device. Last night this worked.

**Comment by gewoon** [comment]
Are you all sure to press CTRL + V? Because the code doesn't show in the cmd on this build.

**Comment by BoostingStore** [comment]
lol, it works, I have not seen this in redmi. sry

24.07.2016, 16:02, "gewoon" <notifications@github.com>:
> Are you all sure to press CTRL + V? Because the code doesn't show in the cmd on this build.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Best Regards
Alexandr http://boosting.store

**Comment by gewoon** [comment]
Haha no problem!
