### ISSUE TITLE
ConfigPokemonsNotToCatch.txt

### ISSUE THREAD

**Issue by Denaz** [NecronomiconCoding/NecroBot#392]
Hi, i want to add some pokemons in "ConfigPokemonsNotToCatch" but it doens't work :/ can you help me

**Comment by trashbit** [comment]
Same Problem here

**Comment by makem2203** [comment]
Would you lads be able to check something.

In your: "Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\" folder- See if you find the following Configs Folder that contain: "ConfigPokemonsNotToCatch.txt, ConfigPokemonsToEvolve.txt & ConfigPokemonsToKeep.txt"

1.  "Pokemon-Go-Bot\PokemonGo.RocketAPI.Console\Configs"
2. "PokemonGo.RocketAPI.Console\bin\Debug\Configs"

Do you have both of those directories?

**Comment by Denaz** [comment]
yes i have

**Comment by trashbit** [comment]
thank you

**Comment by makem2203** [comment]
Ok, in that case @NecronomiconCoding needs to clear the 'old' directory.

As it seems everyone is editing the incorrect directory for their 'NotToCatch' filter. 

Just for now, ensure 'Pinsir' is in both locations. And give it go! :)

**Comment by Denaz** [comment]
ill try with Zubat :p

**Comment by Denaz** [comment]
its working :) but how i can add more than one? like this : "ZubatPidgey" ?

**Comment by makem2203** [comment]
@Denaz That is correct. That is the Syntax required for the Bot to read them. :)

Doing a 'clean' and 'build' of the  "PokemonGo.RocketAPI.Console" should remove the old directory that isn't being used anymore but it doesn't for some reason or another. Needs looking into, but I'm no Developer, so I'll leave it to the experts @NecronomiconCoding.

**Comment by JoshYuen** [comment]
Odd, so there is a commit where they added the creation of the NotCatch text file in the new Bin\Debugs\Configs folder. However the load/read of the actual text file is the Configs\ folder under Console. I believe you just need to modify that file for it to work, you can test it by having Zubat in one and not the other.
