### ISSUE TITLE
[Minor] Getting rewards from Pokéstops...

### ISSUE THREAD

**Issue by gewoon** [NecronomiconCoding/NecroBot#396]
Yesterday i had the same thing and it was said to probably be serverrelated. But now it's still happening.
I get the (INFO) output but then it takes sometimes up to a whole minute before the (POKESTOP) output comes and gives the reward. It's very annoying.

**Comment by ilu01** [comment]
The bot is walking to the point shown in the INFO. That's whats taking so long.

**Comment by gewoon** [comment]
But i've had it that INFO said it was only 1m, it still took pretty long (about 15/20 secs)
