### ISSUE TITLE
GPXPathin error

### ISSUE THREAD

**Issue by eLyiN** [NecronomiconCoding/NecroBot#399]
The values are in central park so, is a error or maybe i'm doing something wrong?

[15:07:39] Unhandled data in GPX file, attempting to skip.
[15:07:39] Requesting GetMapObjectsResponse
[15:07:39] The parameter value must be between -90.0 and 90.0.
Parameter name: Latitude from System.Device
[15:07:39] Got an exception, trying automatic restart..

**Comment by gewoon** [comment]
Are you familiar with GPX paths? I'm not and i don't know how one is supposed to look like but maybe you made a mistake in the file.

**Comment by gewoon** [comment]
Here's a premade GPX file (looping around Central Park) http://www.mapmyride.com/us/manhattan-ny/central-park-big-loop-route-140429217
You need te register to download it (free). See if that one works.

**Comment by eLyiN** [comment]
No i'm not familiar but i can understand how it works. I just removed the highlighted data. And the values are between -90.0 and 90.0

**Comment by crepito** [comment]
I have the same error. Followed instructions.

[14:34:07] (INFO) The value of the parameter must be from -90.0 to 90.0.
Parameter name: Latitude from System.Device
[14:34:07] (ERROR) Got an exception, trying automatic restart..
[14:34:07] (INFO) Awesome! You have already got the newest version! 1.0.4.0

**Comment by sappok** [comment]
same error here

**Comment by PocketMobsters** [comment]
Please post a pastebin.com link with your GPX files and I can fix them for you. This means the file is not properly formatted.

**Comment by PocketMobsters** [comment]
You can also PM them to me on Discord if you don't want them to be public.

**Comment by sappok** [comment]
send u on Discord, thanks man!

**Comment by PocketMobsters** [comment]
If you guys used WTracks remove the whole second line - it's the highlighted bit in the setup instructions!

**Comment by crepito** [comment]
Here it is my gpx file. I believe it is correct (as per instructions)
http://pastebin.com/x0DNaVBf

**Comment by PocketMobsters** [comment]
@crepito Please give this one a whirl http://pastebin.com/ixbwRXDy

**Comment by klurosu** [comment]
Any chance to change the values between -90 and 90??
I mean, sydney (per example) is -31 and 151 (if you know what i mean)

**Comment by jeroenkruis** [comment]
The solution is simple, change all . (dots) for , (commas) in the .GPX file.

**Comment by PocketMobsters** [comment]
There was a gpx uploaded and tested with a value out of that range.

https://github.com/NecronomiconCoding/NecroBot/wiki/GPX-Route-Files

**Comment by PocketMobsters** [comment]
Added a note about this in the setup instructions. Thank you @jeroenkruis

**Comment by Piottreck** [comment]
I replaced all "." with a "," and now it works! 
Thanks Jeroenkruis!

**Comment by klurosu** [comment]
For some extrange reason, it doesn't works OR show me trolling msg.
Take a look at this please:
http://i.imgur.com/fyz7NDm.png

**Comment by jeroenkruis** [comment]
Looks like it's working just fine. The `Your desired destination is (...)` means that it's picking up the file.

**Comment by klurosu** [comment]
I'll make a new route with closer spots... let's see

**Comment by klurosu** [comment]
Negative dude.. :(

same issue with attention msg (and i make veeery closer spots)

http://i.imgur.com/rideJ5C.png

**Comment by jeroenkruis** [comment]
Can you post your .GPX file?

**Comment by klurosu** [comment]
http://pastebin.com/kj7ZFD1V

**Comment by klurosu** [comment]
making a llop right now, i'll post more info in 5m

**Comment by jeroenkruis** [comment]
I think i've found out why the dot and comma problem is giving some people issues. The issue is localization. Consider the following snippet:

```csharp
double latitude = 52.370216;
double longitude = 4.895168;

Console.WriteLine(latitude.ToString(new CultureInfo("en-US", false)));
Console.WriteLine(longitude.ToString(new CultureInfo("en-US", false)));

Console.WriteLine(latitude.ToString(new CultureInfo("nl-NL", false)));
Console.WriteLine(longitude.ToString(new CultureInfo("nl-NL", false)));
```

Output:
```
52.370216
4.895168
52,370216
4,895168
```

We should enforce the correct (dot) notation. The following examples are valid coordinates based on format:

- 90.0, -127.554334
- 45, 180
- -90, -180
- -90.000, -180.0000
- 90, 180
- 47.1231231, 179.99999999

**Comment by klurosu** [comment]
Same issue.

http://i.imgur.com/eQstVLJ.png

http://i.imgur.com/0JEMjuq.png
