### ISSUE TITLE
how can i change razzberrys cp limit on usage

### ISSUE THREAD

**Issue by KiriharaSenpai** [NecronomiconCoding/NecroBot#410]
as a title

**Comment by ilu01** [comment]
in logic.cs:

`if` ((probability.HasValue && probability.Value < 0.35 && encounter.WildPokemon?.PokemonData?.Cp > **400**) ||
                    PokemonInfo.CalculatePokemonPerfection(encounter?.WildPokemon?.PokemonData) >=
                    _clientSettings.KeepMinIVPercentage)
                {
                    await UseBerry(pokemon.EncounterId, pokemon.SpawnpointId);
                }

**Comment by KiriharaSenpai** [comment]
oh thanks so much dude i appreciated it

**Comment by ilu01** [comment]
Remember to close issues once they are resolved

**Comment by KiriharaSenpai** [comment]
sorry
