### ISSUE TITLE
Please make Evolve before transfer if that pokemon in the list 

### ISSUE THREAD

**Issue by Luc4z** [NecronomiconCoding/NecroBot#413]
thanks if it possible

**Comment by Piottreck** [comment]
I would love that feature because right now I stacked so many bonbons but my inventory is almost full with pokemon I wanna keep. So at the moment a boost combined with a lucky egg is not that useful for me.

**Comment by vcafezinho** [comment]
Someone can give an Update about this topic? This is an important thing to improve.

**Comment by reflexx666** [comment]
It is changed now

**Comment by rewrew** [comment]
Is it possible to evolve pokemon with a certain IV value (and above)?
