### ISSUE TITLE
Looping anyone else?

### ISSUE THREAD

**Issue by ID10T107** [NecronomiconCoding/NecroBot#421]
![untitled](https://cloud.githubusercontent.com/assets/20619966/17084622/d23911c0-517f-11e6-8b93-24c10639a91d.png)

**Comment by sp1ti** [comment]
Just restarted, yes. Probably a server issue.

**Comment by ID10T107** [comment]
it continues to do this never does anything else for me even after restart or complete reset up

**Comment by l3uddz** [comment]
because your in a bad location with very little, if any pokestops. change location to somewhere better and it should be fine.  had this happen myself.

**Comment by ID10T107** [comment]
i moved to Las Vegas strip and no change : /

**Comment by sp1ti** [comment]
have you updated it only in the app config or also in the coords.ini?

**Comment by ID10T107** [comment]
Made user all was updated with new coords

**Comment by nrmodesto** [comment]
This doesn't happen to me.. are you using the most recent version?

**Comment by ID10T107** [comment]
Yes

**Comment by ID10T107** [comment]
now im getting (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by nrmodesto** [comment]
I think you have to increase your maximum distance.. it's 1KM by default..

You could try to change your location too,,
