### ISSUE TITLE
Crash at startup : System.FormatException

### ISSUE THREAD

**Issue by R1911** [NecronomiconCoding/NecroBot#431]
It says it failed to convert a string into a DateTime object. Haven't touched anything.

<img width="635" alt="capture d ecran 2016-07-24 a 18 27 25" src="https://cloud.githubusercontent.com/assets/16834379/17084982/e008c41a-51cc-11e6-9236-7a291f836da8.png">

**Comment by nrmodesto** [comment]
I think this is related to #430...

**Comment by R1911** [comment]
Two hours wasted trying different releases which all have annoying issues. Please try to fix stuff before adding features...
