### ISSUE TITLE
Help, I Can't change Default'sLong.and Altitude [FIXED]

### ISSUE THREAD

**Issue by caomeiketchum** [NecronomiconCoding/NecroBot#437]

**Comment by caomeiketchum** [comment]
FIXED by putting , instead of . 

thanks

**Comment by TheCrimsonDevil** [comment]
Is this a UK/US localization thing? I know in the US we do 42.32525, -23.3532 for example. Are there parts of the world that use commas instead?

**Comment by RaymondSchnyder** [comment]
@TheCrimsonDevil Yes, there are parts which use the comma. The bot crashed a few times till i recognized what im doing wrong
