### ISSUE TITLE
Can't even start the bot up?  IF NOT EXIST

### ISSUE THREAD

**Issue by CYCOABHI** [NecronomiconCoding/NecroBot#438]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "IF NOT EXIST "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs" (
MKDIR "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs"
)

IF NOT EXIST "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsNotToCatch.txt" (
COPY "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\Configs\ConfigPokemonsNotToCatch.txt" "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsNotToCatch.txt" /Y
)

IF NOT EXIST "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToEvolve.txt" (
COPY "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\Configs\ConfigPokemonsToEvolve.txt" "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToEvolve.txt" /Y
)

IF NOT EXIST "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToKeep.txt" (
COPY "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\Configs\ConfigPokemonsToKeep.txt" "C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToKeep.txt" /Y
)" exited with code 1.	PokemonGo.RocketAPI.Console

**Comment by TheCrimsonDevil** [comment]
Just for my curiosity, try running VS Studio as admin. Maybe it's a permissions thing? "Error" isn't very descriptive, Microsoft -_-

**Comment by razki** [comment]
@TheCrimsonDevil It is rather descriptive if you read it to be honest.

"Create three text files in your config folder called; ConfigPokemonsToKeep.txt, ConfigPokemonsToKeep.txt, ConfigPokemonsToEvolve.txt then rebuild"

**Comment by CYCOABHI** [comment]
@Razki I mean, I made it all false so do i even have to do that. Oh well, thanks

**Comment by TheCrimsonDevil** [comment]
@razki Oh, I saw #442 and thought it made them at runtime now, but it looks like this was created before that.

**Comment by CYCOABHI** [comment]
Wait where is the configs folder? I dont have one @TheCrimsonDevil @razki

**Comment by Sylencer90** [comment]
Fixed thanks, but why doesn't it auto create as before? Jesus can we please get a single rev without running into some bullshit issue? I just want a stable rev, fuck new features...

**Comment by CYCOABHI** [comment]
where is ur config folder @Sylencer90 ?

**Comment by TheCrimsonDevil** [comment]
There's already a PR to fix that. They're just working on the conflicts.

**Comment by TheCrimsonDevil** [comment]
@CYCOABHI You need to make the folder - C:\Users\XXXXX\Downloads\Pokemon Go Shit\NecroBot-master\PokemonGo.RocketAPI.Console\bin\Debug\Configs\
