### ISSUE TITLE
Missing configs folder

### ISSUE THREAD

**Issue by qaqsd123** [NecronomiconCoding/NecroBot#439]
Missing "PokemonGo.RocketAPI.Console\Configs" not sure if you guys meant to remove it. If so, where do i write down Pokemons To Evolve and Pokemons Not To Transfer?

Update: Got this error

`3>  The system cannot find the path specified.
3>  The system cannot find the path specified.
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: The command "IF NOT EXIST "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs" (
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: MKDIR "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs"
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: )
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: 
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: IF NOT EXIST "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsNotToCatch.txt" (
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: COPY "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\Configs\ConfigPokemonsNotToCatch.txt" "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsNotToCatch.txt" /Y
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: )
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: 
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: IF NOT EXIST "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToEvolve.txt" (
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: COPY "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\Configs\ConfigPokemonsToEvolve.txt" "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToEvolve.txt" /Y
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: )
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: 
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: IF NOT EXIST "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToKeep.txt" (
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: COPY "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\Configs\ConfigPokemonsToKeep.txt" "C:\Users\Czar\Desktop\pokemon\Pokemon\PokemonGo.RocketAPI.Console\\bin\Debug\Configs\ConfigPokemonsToKeep.txt" /Y
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: )" exited with code 1.`

**Comment by razki** [comment]
Create three text files in your config folder called; ConfigPokemonsToKeep.txt, ConfigPokemonsToKeep.txt, ConfigPokemonsToEvolve.txt then rebuild

**Comment by qaqsd123** [comment]
Thanks. BTW you said "ConfigPokemonsToKeep.txt" twice. There should only be 1, the other text file is ConfigPokemonsNotToCatch.txt
