### ISSUE TITLE
[Feature] JSON settings

### ISSUE THREAD

**Issue by yamashi** [NecronomiconCoding/NecroBot#493]
Save ClientSettings and LogicSettings in a json file.

**Comment by EasyAsABC123** [comment]
are you wanting this to replace all the .ini files and the userSettings files?

**Comment by kaeus** [comment]
Would probably be a good idea for both. It would be nice to not have to configure the UserSettings in an IDE, and would save the hassle of having to constantly exclude those settings from source control if we change it while testing.

**Comment by EasyAsABC123** [comment]
agreed, also would make sense to just include a settings.example.json so people can configure from there

**Comment by whalleyboi** [comment]
Making this right now. At the moment its 45% complete.

**Comment by whalleyboi** [comment]
Something like this?

{
  "NecroBot": {
    "ClientSettings": {
      "AuthType": "Google",
      "PtcUsername": "username2",
      "PtcPassword": "pw",
      "DefaultLatitude": 52.379189,
      "DefaultLongitude": 4.899431,
      "DefaultAltitude": 10.0,
      "GoogleRefreshToken": ""
    },
    "LogicSettings": {
      "KeepMinIvPercentage": 85.0,
      "KeepMinCp": 1000,
      "WalkingSpeedInKilometerPerHour": 50.0,
      "EvolveAllPokemonWithEnoughCandy": false,
      "TransferDuplicatePokemon": true,
      "DelayBetweenPokemonCatch": 5000,
      "UsePokemonToNotCatchFilter": false,
      "KeepMinDuplicatePokemon": 1,
      "PrioritizeIvOverCp": false,
      "MaxTravelDistanceInMeters": 1000,
      "GpxFile": "GPXFile.GPX",
      "UseGpxPathing": false,
      "UseLuckyEggsWhileEvolving": false,
      "EvolveAllPokemonAboveIv": false,
      "EvolveAboveIvValue": 95,
      "ItemRecycleFilter": [
        {
          "Name": "ItemUnknown",
          "ID": "0"
        },
        {
          "Name": "ItemPokeBall",
          "ID": "25"
        },
        {
          "Name": "ItemGreatBall",
          "ID": "50"
        },
        {
          "Name": "ItemUltraBall",
          "ID": "75"
        },
        {
          "Name": "ItemMasterBall",
          "ID": "100"
        },
        {
          "Name": "ItemPotion",
          "ID": "0"
        },
        {
          "Name": "ItemSuperPotion",
          "ID": "25"
        },
        {
          "Name": "ItemHyperPotion",
          "ID": "50"
        },
        {
          "Name": "ItemMaxPotion",
          "ID": "75"
        },
        {
          "Name": "ItemRevive",
          "ID": "25"
        },
        {
          "Name": "ItemMaxRevive",
          "ID": "50"
        },
        {
          "Name": "ItemLuckyEgg",
          "ID": "200"
        },
        {
          "Name": "ItemIncenseOrdinary",
          "ID": "100"
        },
        {
          "Name": "ItemIncenseSpicy",
          "ID": "100"
        },
        {
          "Name": "ItemIncenseCool",
          "ID": "100"
        },
        {
          "Name": "ItemIncenseFloral",
          "ID": "100"
        },
        {
          "Name": "ItemTroyDisk",
          "ID": "100"
        },
        {
          "Name": "ItemXAttack",
          "ID": "100"
        },
        {
          "Name": "ItemXDefense",
          "ID": "100"
        },
        {
          "Name": "ItemXMiracle",
          "ID": "100"
        },
        {
          "Name": "ItemRazzBerry",
          "ID": "50"
        },
        {
          "Name": "ItemBlukBerry",
          "ID": "10"
        },
        {
          "Name": "ItemNanabBerry",
          "ID": "10"
        },
        {
          "Name": "ItemWeparBerry",
          "ID": "30"
        },
        {
          "Name": "ItemPinapBerry",
          "ID": "30"
        },
        {
          "Name": "ItemSpecialCamera",
          "ID": "100"
        },
        {
          "Name": "ItemIncubatorBasicUnlimited",
          "ID": "100"
        },
        {
          "Name": "ItemIncubatorBasic",
          "ID": "100"
        },
        {
          "Name": "ItemPokemonStorageUpgrade",
          "ID": "100"
        },
        {
          "Name": "ItemItemStorageUpgrade",
          "ID": "100"
        }
      ],
      "PokemonToEvolve": [
        {
          "PokemonID": "Zubat"
        },
        {
          "PokemonID": "Pidgey"
        },
        {
          "PokemonID": "Rattata"
        }
      ],
      "PokemonsNotToTransfer": [
        {
          "PokemonID": "Dragonite"
        },
        {
          "PokemonID": "Charizard"
        },
        {
          "PokemonID": "Zapdos"
        },
        {
          "PokemonID": "Snorlax"
        },
        {
          "PokemonID": "Alakazam"
        },
        {
          "PokemonID": "Mew"
        },
        {
          "PokemonID": "Mewtwo"
        }
      ],
      "PokemonsNotToCatch": [
        {
          "PokemonID": "Zubat"
        },
        {
          "PokemonID": "Pidgey"
        },
        {
          "PokemonID": "Rattata"
        }
      ]
    }
  }
}

**Comment by PocketMobsters** [comment]
Added as of release version 0.1.3
