### ISSUE TITLE
[Suggestion]Add Family Candies to Transfer or Catch stats

### ISSUE THREAD

**Issue by kowzzz** [NecronomiconCoding/NecroBot#494]
It is already done in Spegeli but I prefer Necros movement and options. Was wondering if this could be added in easily because it gives a good idea when to stock up on certain pokemon to fully utilize the lucky egg buff.

**Comment by yamashi** [comment]
Don't really understand what you mean ?

**Comment by kowzzz** [comment]
http://i.imgur.com/NAM3lz7.png
At the end you can see family candies.

**Comment by yamashi** [comment]
So it's just a log change correct ?

**Comment by kowzzz** [comment]
Yes I believe so. I can go look into the code to see if I can find where it pulls it.

**Comment by yamashi** [comment]
It's fine, I understand the request, it will be done.

**Comment by kowzzz** [comment]
Thanks mate.
