### ISSUE TITLE
[BUG] Changing the AuthType Setting doesnt have any effect

### ISSUE THREAD

**Issue by crack00r** [NecronomiconCoding/NecroBot#497]
https://github.com/NecronomiconCoding/NecroBot/releases/tag/v0.1.1

When you set in config PTC, it allways try to open google with code to auth
not possible to use PTC

**Comment by DurtyFree** [comment]
We will take a look at that.
Next time please use a speaking title :)

**Comment by Vitriolize** [comment]
https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#getting-started
It does, follow the instruction, isn't the same as previous versions ^
