### ISSUE TITLE
[BUG]Changing Latitude and Longitude doesn't have any effect

### ISSUE THREAD

**Issue by proesd** [NecronomiconCoding/NecroBot#498]
I already setting my lat and long in PoGo.NecroBot.CLI.exe.config to sydney, but I can't get to there, still the initial value. Am i set wrong setting ?

**Comment by familoff** [comment]
Yes. I put the coordinates as they are not used.

**Comment by Degix** [comment]
Confirmed. CLI dont use the lat. and long. values. Realized late .... now i got a softban :dancers: ...
Fixed through updating the userSettings in VS before compiling.

**Comment by N3HL** [comment]
You have to change UserSettings.settings

**Comment by Skullmonkey** [comment]
Also cursed with this. Do I need to wait for a new release if I don't wanna mess with compiling?

**Comment by zno3** [comment]
does this only happen when you copy the older .config files? mine works fine by changing the cords inside the newly generated .config

**Comment by Skullmonkey** [comment]
This is from a fresh (like downloaded 10 mins ago) start. I am not seeing any UserSettings.settings file anywhere.

**Comment by proesd** [comment]
Close issued since last release already fixed this. cheers ^_^
