### ISSUE TITLE
[Suggestion] Add active counter of number of pokeballs next to (CatchSuccess)

### ISSUE THREAD

**Issue by danhsiu** [NecronomiconCoding/NecroBot#501]
Would be nice to have an active counter of the types of remaining pokeballs next to catch information
eg. [21:37:33] (PKMN) (CatchSuccess) | Rattata Lvl 28 (411/465 CP) (60.00% perfect) | Chance: 28.29% | 100m dist | with ITEM_GREAT_BALL **_(#Number of ITEM_GREAT_BALL)_**

**Comment by Fenixxia** [comment]
I have not long enough caps to display such information. I would prefer to have a periodic report during the program. it is important to understand, if I pokebolls and other item is to continue the route, or need to let go of the bot to float freely.

**Comment by PocketMobsters** [comment]
Added as of https://github.com/NecronomiconCoding/NecroBot/commit/0b35024b9ca5a347dc95d3db894a504c51f20330 closing now.
