### ISSUE TITLE
GoogleAuth.ini file not saving info

### ISSUE THREAD

**Issue by sloanja** [NecronomiconCoding/NecroBot#504]
Built the project and inserted the previously made GoogleAuth.ini from build 1.0.4.4, and it did not read from it.  Additionally, I permitted this 1.0.0.0 version to attach to my google account, and it did not save a new authentication cookie into the file.  Instead, it redid authentication with Google each time I restarted.

**Comment by N3HL** [comment]
Works fine now on my end now after a recent commit, delete bin and obj folders, then build again and get a new RefreshToken.

If not, delete all your bot folder and clone again the repo, I think thats what I did.
