### ISSUE TITLE
[BUG] GPX routes don't work

### ISSUE THREAD

**Issue by N3HL** [NecronomiconCoding/NecroBot#505]
Servers are a bit overloaded right now it seems (3 mins or more to complete a request) but GPX routes are not working. I tried to use [the central park loop 2](https://github.com/NecronomiconCoding/NecroBot/wiki/Locations-&-GPX-Route-Files#central-park) several times but the bot will just keep using berries and catching pokemons, it won't move, recycle or transfer.

Settings:
 * UseGPXPathing: true (obviously)
 * GPXFile: tried both CentralPark2_Comma.gpx and CentralPark2_Period.gpx, _comma now throws the "value must be between -90; 90" error due to a recent commit, but _period will just load fine, the thing its that it doesn't move.

**Comment by dually8** [comment]
I am getting this same issue as well.  Good work on the bot tho.  Quite handy.

**Comment by xDiglett** [comment]
Same issues

**Comment by yamashi** [comment]
It has been fixed for v0.1.4
