### ISSUE TITLE
what eggs will be used

### ISSUE THREAD

**Issue by Fenixxia** [NecronomiconCoding/NecroBot#507]
Waiting for the version with the choice of what eggs will be used at the moment (2, 5, 10 km)

**Comment by mario296** [comment]
not possible, you will end up with all 2/5km eggs

**Comment by Fenixxia** [comment]
I wish you could choose to use eggs 2 and 5 km. thus we maximize the chance of getting eggs 10 km as this will increase exping per hour. The eggs for 10 km, you can save and use at higher levels.Thank you.
