### ISSUE TITLE
the version of the release and does not work with PTC account

### ISSUE THREAD

**Issue by Fenixxia** [NecronomiconCoding/NecroBot#509]
I changed Auth type to Ptc but when i logged in, it keep open up the website google.com/device.

[08:09:15] Awesome! You have already got the newest version! 1.0.0.0
[08:09:17] Google Device Code copied to clipboard

**Comment by Ixath** [comment]
Same issue here. Tried editing everything I could find and it still won't let me use PTC.

**Comment by Revuin** [comment]
Same. I've changed the setting to "ptc" in both "PoGo.NecroBot.CLI.exe.xml" and "PoGo.NecroBot.CLI.vshost.exe.xml" and still didn't work.

**Comment by PocketMobsters** [comment]
AuthType for Google is "0" AuthType for Ptc is "1"

It's in the https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started

**Comment by TheCrimsonDevil** [comment]
Make sure you do "Ptc" and not "ptc" or "PTC".

**Comment by Revuin** [comment]
I got it to work now with the newest version based on PocketMobster's reply
