### ISSUE TITLE
Encounter Problem: PokemonInventoryFull

### ISSUE THREAD

**Issue by N3HL** [NecronomiconCoding/NecroBot#516]
![This](https://cloud.githubusercontent.com/assets/7317839/17124678/45345538-52c3-11e6-8414-793dba4f207e.png)

This has been happening a lot lately. Restaring the bot seems to fix it temporarily, since it transfers the worst pokemons on start, but **there should be a periodic check or event (when trying to catch a new pokemon)** (its up to you which one to implement) to transfer all the pokemons that match the settings criteria, so it won't stuck like this. In fact it should always prevent this from happening whether the user likes it or not, because if you get stuck here and leave, you'll run the bot for hours just for the pokestops.

**Comment by Navyguy330** [comment]
yeah at least before it would leave golbats and pincers etc lol

**Comment by Navyguy330** [comment]
I really only wanna keep REALLY good pokemon, and the good ones like garados, mew, legendairs, karps, dragonite, eevees etc

**Comment by ShawnHardwick** [comment]
There are plenty of settings to do exactly what you want @Navyguy330 

Also, there IS a periodic check to transfer and evolve pokemon.

**Comment by rayn21** [comment]
This is implemented.  You can break this if you configure it to keep too many Pokemon.
