### ISSUE TITLE
I have changed the location via the config file. Opened it and confirm the change but when I run the program it still uses the default lat & log.

### ISSUE THREAD

**Issue by ediaz369** [NecronomiconCoding/NecroBot#518]

**Comment by 5andr0** [comment]
Works for me. Are you using the correct locale? , <-> .

**Comment by ellenbroz** [comment]
@ediaz369 You have to set the location up in the settings that come up in Visual Studio. The config file you edited needs to be deleted every time you change the location in Visual Studio. It will write a new config file with the coords you enter into VB.

**Comment by Yeehawlerz101** [comment]
Change the .exe xml

**Comment by trashbit** [comment]
Same Problem here he taks the GlobalSettings over my Usersettings

**Comment by Ixath** [comment]
Same problem here. I had to edit the /Configs/Settings.ini for it to take hold.

**Comment by septemus** [comment]
Yep, seems like the bot doesn't check the XML settings (or something) and you need to start it up once to edit the Configs/Settings.ini.

**Comment by ediaz369** [comment]
Where can I find settings.ini

**Comment by trashbit** [comment]
NecroBot\PoGo.NecroBot.CLI\bin\Debug\Configs

**Comment by cvax** [comment]
The release.zip is boned in this regard because there is no \bin\Debug\Configs.

**Comment by ediaz369** [comment]
So No luck because of zip.?

**Comment by mijanx** [comment]
Use 0.1.2, should work better! The location and other settings are hardcoded initially with the json settings.

**Comment by Aristrine** [comment]
Which of the Versions would be considered a 'Stable release'?

**Comment by Vitriolize** [comment]
https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#installation--configuration

You're supposed to use the Configs/Settings.ini now
