### ISSUE TITLE
"No Pokeball" bug

### ISSUE THREAD

**Issue by nguyenvanduocit** [NecronomiconCoding/NecroBot#520]
Please take a look at the image. It show the bug very clearly. Thanks for the bot.
![screen shot 2016-07-26 at 10 36 06 am](https://cloud.githubusercontent.com/assets/1256953/17125479/f215eec4-531d-11e6-9b46-fd02ae7f6d1f.png)

**Comment by HagsterZx** [comment]
You have too many items !

**Comment by nguyenvanduocit** [comment]
No man, as you see, The bot said I had no Pokemon when it try to catch Eevee 1, then it use a ball to catch another eevee. So that, it's mean when it catch eevee 1, I have a ball.

**Comment by rayn21** [comment]
Have you seen this more than once? This looks pretty odd to me in code.

**Comment by NecronomiconCoding** [comment]
should have been fixed in https://github.com/NecronomiconCoding/NecroBot/commit/f7bcf39a170d9f1e35352337818d5b40657437a6
