### ISSUE TITLE
No pokemon transfer

### ISSUE THREAD

**Issue by werdna87** [NecronomiconCoding/NecroBot#522]
I have changed setttings.ini, and absolutely none of the pokemon are transfering

**Comment by tandematt** [comment]
I've yet to get this to work. I've tried nearly every setting combination I can imagine.

**Comment by werdna87** [comment]
There must be a bug in one of the transfer functions. If I had time I would
try to submit I fix, but I don't know the codebase and it's late

**Comment by iamhahnz** [comment]
"TransferDuplicatePokemon": true, <<< make sure this one change into True

**Comment by 5andr0** [comment]
I'm on a dratini gpx route without pokestops. It only transfers all the dratinis when it's restarting. I guess no pokestop = no transfer

**Comment by tandematt** [comment]
@iamhahnz I don't want to transfer duplicates, only the Pokemon that do not meet the CP / IV requirements I've specified. Is that setting still required?

**Comment by iamhahnz** [comment]
@tandematt mine is work fine now... it transfer all the poke that not meet the cp / iv req.

**Comment by tandematt** [comment]
@iamhahnz how do you stop it from transferring duplicates then?

**Comment by iamhahnz** [comment]
@tandematt  
"TransferDuplicatePokemon": true, << this one on setting change it into false  ... isn't it?

**Comment by rayn21** [comment]
Transfer duplicates should be set to true.  It will respect your keep criteria and save your good pokes

**Comment by reflexx666** [comment]
Keep min duplicates can not be set at 1 at this point. It is a bug, set it as 2.

**Comment by reflexx666** [comment]
Also make sure keeppokemonthatcanevolve is false.
