### ISSUE TITLE
Location not changing

### ISSUE THREAD

**Issue by xbtz** [NecronomiconCoding/NecroBot#523]
So i set my location to docklands in melbourne in the config tab, but when i load the bot up, it resorts to using the defaults, which is in Amsterdam. Just wondering if a fix has come out for this yet, I have downloaded the most recent release but it still is malfunctioning.

Thanks

**Comment by mijanx** [comment]
Use 0.1.2, the latest has the location hardcoded initially.

**Comment by HagsterZx** [comment]
https://github.com/NecronomiconCoding/NecroBot/releases
http://imgur.com/a/sn9GM
The last release work very well

**Comment by crixon** [comment]
nope is not working i have also the new version ... the 0.1.2 is not working too

**Comment by HagsterZx** [comment]
go here NecroBot-master\PoGo.NecroBot.CLI\bin\Debug\Configs and edit setting.ini and will work!
