### ISSUE TITLE
Not getting items from Pokestops

### ISSUE THREAD

**Issue by KicksDNA** [NecronomiconCoding/NecroBot#524]
I'm not getting any items from Pokestops anymore and therefore cannot catch any Pokemon.
![screenshot 25](https://cloud.githubusercontent.com/assets/20654748/17125767/6ab1b7b4-52c4-11e6-81af-636f6a52d39f.png)

**Comment by ediaz369** [comment]
Ban? Im sure you cannot collect when banned.

**Comment by HagsterZx** [comment]
You have +350 items in account

**Comment by KicksDNA** [comment]
Any way to set a limit to total items in bag so I don't go over the 350

**Comment by HagsterZx** [comment]
Go on nox and u will see,or open phone without gps on
