### ISSUE TITLE
Please add feature in user settings that allows you to choose an item limit of the bag so I don't go over the bag capacity.

### ISSUE THREAD

**Issue by KicksDNA** [NecronomiconCoding/NecroBot#526]
Often I go over the bag capacity and stop getting items from pokestops and eventually run out of pokeballs.

**Comment by cloudsstars** [comment]
in Settings.cs

**Comment by cloudsstars** [comment]
i have mine set to keep only the best stuff i only max because its set to keep 150 ultra balls

**Comment by phreaky1234** [comment]
so in the settings.cs, do the numbers represent how many you want to leave up at a time or how many you discard?
