### ISSUE TITLE
Low CP Pokemon not transferring. 

### ISSUE THREAD

**Issue by KAustin1** [NecronomiconCoding/NecroBot#527]
I just noticed that my low CP catches are no longer transferring. Also, my location (long/Lat) has reverted to the default although my setting show my current location.

**Comment by cloudsstars** [comment]
dont know if its the best way to do it but when i change locations i delete the debug and make a new one i can never find the coords file

**Comment by imtiax** [comment]
Make sure you update your KeepMinCP and KeepMinIV in your config file.

**Comment by KAustin1** [comment]
Deleting the debug file fixed the transferring issue. Havent figured out the long/lat issue. However, playing in Amsterdam gives me a chance at the region exclusive pokemon, bring on Mr Mime.

**Comment by iamhahnz** [comment]
i got the same problem. already setting the min cp and iv but still can't transfering the low cp
