### ISSUE TITLE
PokemonGo.RocketAPI (load failed)

### ISSUE THREAD

**Issue by Lovebucket25** [NecronomiconCoding/NecroBot#529]
The files don't exist in the newest download ?

**Comment by Hitsuomy** [comment]
Up for this, download size is now only 73kb, a lot of files are missing. WTF?

**Comment by Aristrine** [comment]
Hey, download the latest Rocket API and insert it in FeroxRev, and then proceed to Launch the Exe. For detailed instructions please refer to the Wiki.

**Comment by Hitsuomy** [comment]
/\ Already did this, still error.

**Comment by Aristrine** [comment]
Use the folder inside the folder, if it makes sense. If it doesn't work I have no other solution atm.

**Comment by Hitsuomy** [comment]
Okay, now it's working, was a name problem with the extracted folder. Thnks.

**Comment by Lovebucket25** [comment]
this is good to go thank you for your quick response!
