### ISSUE TITLE
Display Highest Perfect

### ISSUE THREAD

**Issue by oooorz** [NecronomiconCoding/NecroBot#531]
Hi all, 

It seems like in v0.1.3 it doesn't display highest perfect pokemon anymore. Just wondering if it is deleted intentionally or is a mistake?
By the way, is there anyway to make the it output more than ten in the older version? I want to see the other highest perfects so I can choose which to evolve and power up as well......  

Thanks for everything you guys have done!

**Comment by 5andr0** [comment]
Search for this: `var highestsPokemonPerfect = await _inventory.GetHighestsPerfect(10);` 10 means amount of pokemons to list. Hope it's coming back. Also this would be pretty helpful to check for pokemons: https://github.com/NecronomiconCoding/NecroBot/pull/462 
Soon there will be an http interface to check your pokeinventory etc.

**Comment by fenomeno96** [comment]
5andr0 sorry, I didn't catch the temporary fix to the problem... I can't find var highestPokemonPerfect on my project with Visual Studio 2015 :( Thankyou anyway for the answer :D

**Comment by Nordiii** [comment]
Working on this issue right know there will be a PR soon

**Comment by ridoknight** [comment]
Thank you @Nordiii ^^
