### ISSUE TITLE
Source with VS2012

### ISSUE THREAD

**Issue by WooAf** [NecronomiconCoding/NecroBot#533]
FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj : error  : The project file could not be loaded. Could not find a part of the path 'NecroBot-0.1.3\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj'.  NecroBot-0.1.3\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj

**Comment by WooAf** [comment]
http://i.imgur.com/bd9EWZU.png

**Comment by WooAf** [comment]
How I can build this source ? I want to play around with it

**Comment by MichaelGatesDev** [comment]
Download rocketapi and place it in the FoxRev folder... there's instructions on the wiki, linked on the readme page.
