### ISSUE TITLE
Appreciation For The Devs.

### ISSUE THREAD

**Issue by Aristrine** [NecronomiconCoding/NecroBot#534]
## Just thought that I'd get this out there,

As I feel that this is needed to be said at the least, a big thanks to the Devs for creating the Bot for a non-profit FOC Public Release, Quote on Quote, for Educational use.  As well as the Contributors through pull requests.

I may not be in-depth expertise on Coding up the repo for Pogo.

But I'll be sure to support the Devs until the Final Release of the Program through, (**Coughs**)

> Tip Jars

Well anyway,
_Cheers to the Community._

**Comment by MichaelGatesDev** [comment]
While I appreciate the devs as much as you all, I think they would prefer if you didn't open an issue for messages like this. Drop them a 'thanks' in the Discord or donate to them if you can. :)

**Comment by Aristrine** [comment]
Oh, alright, my bad, closing this Thread! :)
