### ISSUE TITLE
Gpx not farming Pokestops

### ISSUE THREAD

**Issue by 5andr0** [NecronomiconCoding/NecroBot#536]
I guess this is known, but no issue opened so far.

**Comment by aapikz** [comment]
use pokevision to view pokestop in map. and make sure gpx is walking to pokestop locations

**Comment by 5andr0** [comment]
I wouldn't open an issue if it wasn't tested and confirmed by others. So yea, i made sure that it's walking to pokestops

**Comment by johnz45** [comment]
Confirmed the same for me.

**Comment by XiCynx** [comment]
Can also confirm, made multiple GPX routes and none of them were grabbing the pokestops.  You can use this one as an example to test with.

[CentralParkPokestop_Loop.zip](https://github.com/NecronomiconCoding/NecroBot/files/383180/CentralParkPokestop_Loop.zip)

**Comment by aapikz** [comment]
edit: yea same for me.. my older bot gpx route is working fine..but the latest rev  stuck and not walking/farming pokestop

**Comment by killerciao** [comment]
Same for me :-1:

**Comment by bigzie** [comment]
Confirmed here too! Same for me.

**Comment by nguyenvanduocit** [comment]
Confirmed

**Comment by rrrds** [comment]
Use current Lat/Lon
`FarmPokestopsGPXTask.cs:138: LocationUtils.CalculateDistanceInMeters(
                                ctx.Client.CurrentLatitude, ctx.Client.CurrentLongitude,
                                i.Latitude, i.Longitude) < 40)`
