### ISSUE TITLE
latest rev is broken? missing API can't run the bot

### ISSUE THREAD

**Issue by aapikz** [NecronomiconCoding/NecroBot#537]
when i download the latest rev and deleted my old folder... 
it wont allow me to run .... it says pokemonGo.RocketAPI unavialable or missing
the project file cannot be found

![broken](https://cloud.githubusercontent.com/assets/14224262/17127699/69b3370a-52bc-11e6-90d3-2653a76405b4.png)

**Comment by g3ntzz** [comment]
download the api yourself.

**Comment by aapikz** [comment]
how??

**Comment by g3ntzz** [comment]
click FeroxRev @ de054ee, it brings you to another page download it. unzip in all into feroxRev folder.
but you might as well download the release ones, it's easier and now you have to change you settings in config folder settings.ini

**Comment by andrewfonseca** [comment]
Can't this be pulled recursively?

**Comment by gamelinchpin** [comment]
Solution for me was:
`git submodule update --remote --merge`

**Comment by ZzzKev** [comment]
Still a bit confused onto what to do. Maybe a bit of visual please?

**Comment by andrewfonseca** [comment]
Run the command above if you have git installed

**Comment by ZzzKev** [comment]
I apologize, I have never used Github nor visual studio, I have it opened up exactly like the picture above. My buddy was walking me through and realized i didn't have the same file as his. Then had to go to bed for work. I don't understand the Run command and where it is located.

**Comment by ZzzKev** [comment]
I downloaded his fails and ran it perfectly only to find out i was running his token and didn't know how to change it and later deleted it so i restarted fresh again.

**Comment by Shawak** [comment]
Same issue here, cloning the branch and executing the command dont work to get the api.

**Comment by ridoknight** [comment]
Why did they do this ? -_-

**Comment by andrewfonseca** [comment]
if you are having trouble you can clone the API repository manually into the FeroxRev folder.

Thy renamed a bunch of stuff. Don't forget to clean: git clean -fxd

**Comment by ridoknight** [comment]
Ty for answer but i really dont know this things. How can i clean this ?
