### ISSUE TITLE
Proper code for allowing enough pokeballs but not capping item inventory

### ISSUE THREAD

**Issue by phreaky1234** [NecronomiconCoding/NecroBot#542]
I need help modifying the settings.cs so that I can keep enough balls but not cap the inventory of 350 with revives, potions, berries, etc. If anyone has an example I would be really grateful. Thanks!

**Comment by SubstituteCS** [comment]
What would you define as "enough" pokeballs.

**Comment by phreaky1234** [comment]
like say only allow just 50 poke, 100 great, and 100 ultra and no revives or potions or berries

**Comment by SubstituteCS** [comment]
Like this?  
http://pastebin.com/hJZtLer3

**Comment by phreaky1234** [comment]
imma try this out! Thanks man! :)
