### ISSUE TITLE
Rocket API Error - Prevents it from catching pokemon

### ISSUE THREAD

**Issue by KaitoKid** [NecronomiconCoding/NecroBot#547]
http://imgur.com/2leroJc

Worked fine for several hours before this error appeared. Then it only spun Pokestops

**Comment by spot88** [comment]
I get Rocket API load fail in Visual Studio, new commit.

**Comment by spot88** [comment]
Some files that was in the FeroxRev folder, has been moved?

**Comment by HagsterZx** [comment]
Read [WIKI](https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#installation--configuration)

**Comment by KaitoKid** [comment]
Forgot to mention that I encountered this on the standalone client.

It came up once after running for several hours, and hasn't shown up again since then

**Comment by yamashi** [comment]
This happens when the pokego servers fail, not much we can do about it :(
