### ISSUE TITLE
no usable pokestops error

### ISSUE THREAD

**Issue by Thoraxa** [NecronomiconCoding/NecroBot#548]
i keep getting this error, even though it should be fine. I upgraded to the latest version and have had this problem, the previous beta version never had this issue, any reason it could occur?

**Comment by reflexx666** [comment]
In previous versions I have seen this error multiple times but then it was mostly cause people had the wrong long/latitude 118. instead of -118 or 70 instead of -70. Now this also seem to happen with the correct settings so my guess is the - is not handled correctly.

**Comment by MKWHosting** [comment]
i also keep getting the no usable pokestops error
