### ISSUE TITLE
Caught pokemon show no map location in-game

### ISSUE THREAD

**Issue by cvax** [NecronomiconCoding/NecroBot#549]
Are we missing something on our requests to get that info stored to account too?

**Comment by crixon** [comment]
nope it's not working atm! The hole settings will be set als default ... :/

**Comment by yamashi** [comment]
Don't understand the issue

**Comment by IsBoris** [comment]
When you catch a Pokemon in-game, it shows the location it was caught in the Pokemon Menu.

**Comment by cvax** [comment]
Yes, what IsBoris said. The bot catches pokemons, but leaves the map empty. This is critical. All the amount of hard work we put into silly things like human walking and delay catches are useless if Niantic can simply filter by accounts that have null maps on pokemons.

**Comment by PocketMobsters** [comment]
You do realise they disabled the catching map for EVERYONE right? Even my friends who I go out with and play legit with don't have maps in pokemon info. It's related to the 3-step-bug.

Chill out and actually research before opening an issue next time, please and thank you.
