### ISSUE TITLE
Necrobot doesn't copy the google device code to clipboard on macOS

### ISSUE THREAD

**Issue by Razzile** [NecronomiconCoding/NecroBot#550]
Running necrobot on mac using mono seems to work fine, with the only problem being that the google device code generated isn't copied to the clipboard when a browser window opens.

It would be useful if this code was also printed out to enter manually.

There may be other problems using mono too but so far this is all i've encountered

**Comment by crixon** [comment]
in my case its working - i'm on a mac :)

**Comment by Razzile** [comment]
@crixon hmm strange. for me it says copied to clipboard but it hasn't *actually* copied it to the clipboard

**Comment by yamashi** [comment]
Mac is shit
