### ISSUE TITLE
Bot doesn't load settings correctly

### ISSUE THREAD

**Issue by crixon** [NecronomiconCoding/NecroBot#551]
The bot doesn't load the settings... if started the settings are set to default.

**Comment by reflexx666** [comment]
What version are you using? Release.zip with exe or source code?

**Comment by HagsterZx** [comment]
on source code edit it from here C:\Users\al3xa\Downloads\NecroBot-master\PoGo.NecroBot.CLI\bin\Debug\Configs settings.ini

**Comment by crixon** [comment]
i tried both versions!

**Comment by crixon** [comment]
thx HagsterZx

**Comment by reflexx666** [comment]
The problem is that it has "public double DefaultLatitude => GlobalSettings.DefaultLatitude;" instead of "public double DefaultLatitude => UserSettings.Default.DefaultLatitude"
