### ISSUE TITLE
doesnt show properly highest cp and highest perfect

### ISSUE THREAD

**Issue by KiriharaSenpai** [NecronomiconCoding/NecroBot#553]
Hi sir thanks for all of your works i want to ask a question today i updated bot to last version but on the last version highest cp and iv dont work i mean dont show in bot screen

**Comment by ridoknight** [comment]
Do you want to see ====== DisplayHighestsPerfect ====== list right ? I want it back too!

**Comment by KiriharaSenpai** [comment]
yea sometimes i catch some rare pokemons and check them with bot >DD

**Comment by Gawdor** [comment]
It would be great to have it generate a new log, and immediately print the top pokemon lists, this way all people need to do is check the top of each log file for the best pokemon each hour.

**Comment by Majamulli** [comment]
It would be even better if it showed all pokemon and not just the top list. At least in a log file or something. So we can decide which (for example) Zubat to upgrade even though we have 20 perfect IV Dratinis. With just the top showing I wouldn't see those Zubats.

**Comment by rayn21** [comment]
I have just checked in some display highest code to my fork, but I don't know if I like how often it displays.  Need some feedback.

https://github.com/rayn21/NecroBot/commit/924d629c743bf64e0fbcf424210312270466235a

**Comment by Nordiii** [comment]
My branch got already merged into master no need to work on this anymore!
Can be closed

**Comment by yamashi** [comment]
@Nordiii it doesnt display anything with your PR.

https://images-2.discordapp.net/eyJ1cmwiOiJodHRwczovL2Rpc2NvcmQuc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9hdHRhY2htZW50cy8yMDYwNjUzMjY4MjYzMjM5NzAvMjA3NTE3NDk1OTAzNTE4NzI2L0NhcHR1cmUuUE5HIn0.eks6imv7Jbk92YVyyfwIyXD8LQo.PNG

**Comment by Nordiii** [comment]
@yamashi lol...
http://imgur.com/a/OQoTA


Works fine for me... i will look into it

**Comment by MaxGriot** [comment]
Actually config issue

**Comment by yamashi** [comment]
Settings issue, if it's set to 0 it shouldn't display the titles at all.

**Comment by rayn21** [comment]
@Nordiii Damn, how did I miss your change!? I was working on something similar.

https://github.com/rayn21/NecroBot/commit/3a0d6d4e910cdc8083f2d056ac513ad2cab05cd1
