### ISSUE TITLE
how to update necrobot and why pokemons dont transfer?

### ISSUE THREAD

**Issue by novpokcom** [NecronomiconCoding/NecroBot#558]
Hello, I have 0.1.0 version of necrobot and how to update it to 0.1.3?

**Comment by yonosokote** [comment]
How about reading the README file?

**Comment by novpokcom** [comment]
i can't open it!!!!!

**Comment by novpokcom** [comment]
i opened it,  but there is no info about how to update bot! HELP me please!

**Comment by novpokcom** [comment]
why u dont want to help me?

**Comment by yamashi** [comment]
GitHub issues are only for bug reports, features, no help with config files or usage will be provided here.
