### ISSUE TITLE
[Suggestion]Remove Softban

### ISSUE THREAD

**Issue by Artarex** [NecronomiconCoding/NecroBot#564]
hey I found in the internet this method to remove softbans and it works pretty well.
Click pokestop
spin it
exit pokestop
spin the same pokestop again
repeat around 40 times.
I am just not 100% sure if it has to be a pokestop on your old "working" location or if it can be a pokestop at your new location. But I think that doesent matter.

Takes around 3-5 minutes and the softban is lifted.
Maybe its possible to implement this. If catchflee --> do this

**Comment by yamashi** [comment]
Actually it's probably a coincidence, a softban doesn't last very long
