### ISSUE TITLE
Last merge doesn't load properly App.conf or settings.settings

### ISSUE THREAD

**Issue by kanfkasndklasdn** [NecronomiconCoding/NecroBot#568]
I've to manualy edit settings.ini to make the bot charge my data correctly. Deleting the file and rebuilding the proyect with the App.conf and settings.settings well configured still generates a default and uncorrectly settings.ini.

**Comment by KiriharaSenpai** [comment]
yes u re right even if delete the debug file and rebuild doesnt seem to work
