### ISSUE TITLE
Google Device Code on Ptc?

### ISSUE THREAD

**Issue by PaDo90** [NecronomiconCoding/NecroBot#570]
Hey, i follow all steps from the instructions. When i start the project with CTRL + F5 the console is opnenig and a google page for the device code is opening... but in the Usersettings.settings i chosed "Ptc" in the first line ... what is wrong? :D

**Comment by KiriharaSenpai** [comment]
#568 same problem it applies defaul conf so open project with visual studio and change def settings

**Comment by PaDo90** [comment]
Sorry i don't know what is to do :/
