### ISSUE TITLE
Update Wiki to Explain settings.ini

### ISSUE THREAD

**Issue by FloThinksPi** [NecronomiconCoding/NecroBot#571]
Would be great do document in WIKI which settig does what and work together with other settings and what are possible values. E.g,   
```
   "KeepPokemonsThatCanEvolve": true,
  "TransferDuplicatePokemon": true,
```
How do these Options Influence each other, Does the 1. overwrites rules of the 2. or does 1. option alone transfer the pokemons that cant be evoved without the need of the 2, option. ;)

**Comment by yamashi** [comment]
Wiki has been updated
