### ISSUE TITLE
Ptc not Working

### ISSUE THREAD

**Issue by PaDo90** [NecronomiconCoding/NecroBot#573]
Sorry for new Issue but i don't know what i can to do... Why closed my old issues?

Hey, i follow all steps from the instructions. When i start the project with CTRL + F5 the console is opnenig and a google page for the device code is opening... but in the Usersettings.settings i chosed "Ptc" in the first line ... what is wrong? :D 

sorry for my bad english :/

**Comment by FloThinksPi** [comment]
have you  `"AuthType": 1,` in settings.ini ?

**Comment by Xore** [comment]
Why is the Cli.exe.config not loaded / used as template for settings.ini?

**Comment by MattTheHuman** [comment]
I don't understand why we've moved away from using the config and also why there is a need to have an enum for the AuthType. "Ptc" and "Google" were working perfectly fine and were easy to understand for people not so up on coding.
