### ISSUE TITLE
"KeepPokemonsThatCanEvolve": true is causing errors

### ISSUE THREAD

**Issue by TriadHS** [NecronomiconCoding/NecroBot#576]
Whenever you  mark  "KeepPokemonsThatCanEvolve" as true in Configs/Settings.ini you recieve the following errors on a loop

> [13:51:44] (INFO) Successfully loaded your Settings.ini file
> [13:51:47] (INFO) Awesome! You have already got the newest version! 1.0.0.0
> [13:51:50] (INFO) Playing as -----
> [13:51:50] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat:
> 40,772076 Lng: -73,973776
> [13:51:53] (INFO) Loading File: Configs\ConfigPokemonsToKeep.ini
> [13:51:54] (ERROR) System.AggregateException: One or more errors occurred. --->
> System.DivideByZeroException: Attempted to divide by zero.
>    at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext
> ()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
> Exceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
> tion)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.Execute(Context ctx
> , StateMachine machine)
>    at PoGo.NecroBot.Logic.State.FarmState.Execute(Context ctx, StateMachine mach
> ine)
>    at PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context
> ctx)
> ---> (Inner Exception #0) System.DivideByZeroException: Attempted to divide by z
> ero.
>    at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__7.MoveNext
> ()<---

My settings.ini

> {
>   "AuthType": 0,
>   "PtcUsername": "username2",
>   "PtcPassword": "pw",
>   "DefaultLatitude": 40.772076,
>   "DefaultLongitude": -73.973776,
>   "DefaultAltitude": 10.0,
>   "KeepMinIvPercentage": 85.0,
>   "KeepMinCp": 1000,
>   "WalkingSpeedInKilometerPerHour": 50.0,
>   "EvolveAllPokemonWithEnoughCandy": false,
>   "KeepPokemonsThatCanEvolve": true,
>   "TransferDuplicatePokemon": true,
>   "DelayBetweenPokemonCatch": 5000,
>   "UsePokemonToNotCatchFilter": false,
>   "KeepMinDuplicatePokemon": 4,
>   "PrioritizeIvOverCp": true,
>   "MaxTravelDistanceInMeters": 1000,
>   "GpxFile": "GPXFile.GPX",
>   "UseGpxPathing": false,
>   "UseLuckyEggsWhileEvolving": false,
>   "EvolveAllPokemonAboveIv": false,
>   "EvolveAboveIvValue": 95.0
> }

Log files:
[NecroBot-2016-07-26-13.txt]
(https://github.com/NecronomiconCoding/NecroBot/files/383730/NecroBot-2016-07-26-13.txt)

**Comment by yamashi** [comment]
This has been fixed for 0.1.4
