### ISSUE TITLE
Bot is still not spining near pokestops with gpx

### ISSUE THREAD

**Issue by OverCraftX** [NecronomiconCoding/NecroBot#579]
I checked last update but the bot still do not spin nearest pokestop with gpx.

For example, very easy to check, in Santa Monica pier, the pier its full of pokestop and the bot uses 0 of them.

GPX made walking into the pokestops:
[santamonica.gpx.txt](https://github.com/NecronomiconCoding/NecroBot/files/383756/santamonica.gpx.txt)
![pokestops](https://cloud.githubusercontent.com/assets/20661590/17137768/398908d0-533d-11e6-8637-12093b6df9d2.jpg)

**Comment by killerciao** [comment]
Confirmed.
GPX Track with markers in every near pokestop and this is the result:
![image](https://cloud.githubusercontent.com/assets/20577624/17137976/5f44a448-533e-11e6-9e4c-8f9c5dfc7bd2.png)

**Comment by yamashi** [comment]
Try v0.1.4

**Comment by taufikhdyt99** [comment]
gpx seem to be working with last release, still running the bot right now
