### ISSUE TITLE
Project not loading

### ISSUE THREAD

**Issue by Sholyhit** [NecronomiconCoding/NecroBot#582]
Am I missing some certain program or do I need to do something specific? the older version (1 day ago) was working fine then I downloaded this but the project cannot be found.

![ddddd](https://cloud.githubusercontent.com/assets/20662783/17138430/eb809868-5348-11e6-8133-4b6c2ec3ca74.png)

**Comment by spot88** [comment]
Unzip the RocketAPI so the folder structure matches NecroBot\FeroxRev\PokemonGo.RocketAPI\

**Comment by spot88** [comment]
Read Wiki - Close this Issue
