### ISSUE TITLE
[Feature Request] Star (Favorite) high IV pokemon

### ISSUE THREAD

**Issue by DanielSantoro** [NecronomiconCoding/NecroBot#587]
When opening the bot it tells us which Pokemon are high IV, but looking through them on the device there isn't any indication. If the bot could favorite those with high IV, then we would know which to focus on and evolve.

**Comment by kaeus** [comment]
I've got code setup at the moment with a toggle to rename pokemon with their "Name_IV" as the format. It helps a lot when I go to manually evolve. I'm working on adding it in but have to make sure the settings work with the new setup.
