### ISSUE TITLE
Pokemon Inventory Full

### ISSUE THREAD

**Issue by KAustin1** [NecronomiconCoding/NecroBot#589]
An issue I am seeing a lot. 

KeepMinIVPercentage is 85, KeepMinCp is 1000 and KeepMinDuplicatePokemon is 1 . 

However, The bot is not transfering Pokemon with IV Percentage over 85 regardless of CP. I have to manually clear them and most have very low CPs. 

Can the bot be adjusted to transfer duplicates if CP is below the CP threshold regardless of IV percentage?

**Comment by solenrus** [comment]
just set ur ivpercentage to 90-99?

**Comment by mich3lam** [comment]
Meaning they are above 85% iv, just change the value to something higher .. @KAustin1

**Comment by KAustin1** [comment]
Didnt work. I will work on it later. Time for RL duties. 
I may have done something wrong, most likely as I still cant get the bot to leave Amsterdam even though my settings say I am elsewhere.

**Comment by Sylencer90** [comment]
Transferring seems to be broken, doesnt work for me as well, using latest release.

**Comment by KAustin1** [comment]
I had to try again real quick with a clean install of the "release" It did not work. Still not transferring.

**Comment by yamashi** [comment]
Paste config files if you want help

**Comment by Sylencer90** [comment]
{
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 34.010205,
  "DefaultLongitude": -118.495774,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1200,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 3500,
  "PrioritizeIvOverCp": true,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": true,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 50
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 20
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 5
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 100
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore": [
    "zubat",
    "rattata"
    ],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
	"pidgey",
    "mew",
    "mewtwo"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata"
  ]
}

**Comment by yamashi** [comment]
GitHub issues are only for bug reports, features, no help with config files or usage will be provided here.

**Comment by N3HL** [comment]
"post your config file if you want help" remember?

**Comment by Sylencer90** [comment]
Idk whats wrong with you yamashi, you tells us the post our config...
and it is a bug since it wasn't happening with the old config system.
