### ISSUE TITLE
No useful pokestops in your area.

### ISSUE THREAD

**Issue by Xomux** [NecronomiconCoding/NecroBot#592]
Settings are located in Santa Monica Pier. Good job. It doesn't work properly.

**Comment by Sylencer90** [comment]
Had the same issue. Just wait 10 more mins and this issue gets closed without seeing any fixes.

**Comment by yamashi** [comment]
Not able to repro, no config files posted, closing.

**Comment by iamD2** [comment]
i had the same problem actually i just made my walk distance to 2000 instead of the regular 1000 where by earlyer version it worked topnotch
