### ISSUE TITLE
[Bug] Transfers highest cp pokémon when higher iv pokémon is available

### ISSUE THREAD

**Issue by Rawrlex** [NecronomiconCoding/NecroBot#597]
Wouldn't it be nice to keep both? Sold my Gyarados with 2100 CP (92% perfect) for a one with 1400 CP (100% perfect).

**Comment by solenrus** [comment]
it's not a bug, just Gyarados to your nontransferlist

**Comment by padmanek** [comment]
And then it's not going to transfer all the low % low cp ones, not smart.

**Comment by pavelmoulisjr** [comment]
What was your KeepMinCP value?

**Comment by mich3lam** [comment]
Welp, it's not like you catch a Gyarados every 2 seconds lol.. @padmanek

**Comment by padmanek** [comment]
@mich3lam It's just an example, applies to all the pokemons.

**Comment by rayn21** [comment]
Can't you do this in config? I have keep cp = 1500 and keep iv = 88. I don't transfer any pokemon that have over 1500 OR over IV 88 - so I do keep both.

**Comment by Rawrlex** [comment]
Thanks for all the comments but I want to keep highest CP of all pokemon + highest perfect of all pokemon.

**Comment by ShawnHardwick** [comment]
This is not a bug. If you would like, you can submit an idea as a feature request, but the config is able to handle that scenario if configured properly.
