### ISSUE TITLE
Cant LogIn with Ptc. AccountNotVerifiedException

### ISSUE THREAD

**Issue by Volevanya** [NecronomiconCoding/NecroBot#602]
But my account verified.
`[16:39:43] Awesome! You have already got the newest version! 1.0.0.0
[16:39:44] System.AggregateException: Произошла одна или несколько ошибок. ---> PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException: Выдано исключение типа "PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException".
   в PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() в D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() в D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:строка 51
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в PoGo.NecroBot.Logic.State.LoginState.Execute(Context ctx, StateMachine machine) в D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:строка 17
   в PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx) в D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:строка 50
---> (Внутреннее исключение #0) PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException: Выдано исключение типа "PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException".
   в PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() в D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() в D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:строка 51<---
`

**Comment by yamashi** [comment]
GitHub issues are only for bug reports, features, no help with config files or usage will be provided here.

**Comment by Volevanya** [comment]
Using v0.1.5
