### ISSUE TITLE
Where did the .API go??

### ISSUE THREAD

**Issue by KicksDNA** [NecronomiconCoding/NecroBot#605]

**Comment by dgateles** [comment]
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/

**Comment by DrDelay** [comment]
Instead of manually downloading and unpacking like it states in the wiki this should probably work aswell:
``` bash
$ git submodule init
$ git submodule update
```

**Comment by KicksDNA** [comment]
![screenshot 27](https://cloud.githubusercontent.com/assets/20654748/17142085/c723bfbc-531c-11e6-9828-bbd789765231.png)

**Comment by StrangeClown** [comment]
I have the same problem, any solution yet?
