### ISSUE TITLE
 No Pokeballs all the time

### ISSUE THREAD

**Issue by thomasmoors** [NecronomiconCoding/NecroBot#612]
The log all of the sudden alway shows " No Pokeballs -  We missed a [Pokemon]. Why doesn't it just go collect balls at pokestops?

**Comment by instantwolf** [comment]
Same here.
Farming with 2 Accounts: One at Santa Monica Pier , the other one in central park (using GPX from Repo)
Hardly any Pokestop is collected while farming

**Comment by Maynaards** [comment]
Hi Guys,

You're not collecting pokeballs from pokestops because your bag is filled with other items such as potions, I suggest you remove all of those and restart the bot.

Also instantwolf, Santa Monica Pier is broken I advise against botting there currently.

Hope I can help!
