### ISSUE TITLE
missing files for main download 

### ISSUE THREAD

**Issue by cloudsstars** [NecronomiconCoding/NecroBot#617]
this is all that is in the main download for NecroBot-master\PoGo.NecroBot.CLI as well as when i download the main file it will not download NecroBot-master\FeroxRev has to be added manual from downloadinf from https://github.com/FeroxRev/Pokemon-Go-Rocket-API/tree/de054eecea6b551c65301782010ac78ea38c54db
if you download the zip from the page its missing alot of the files and programs and you have to add them your self as it wont add files from the https://github.com/NecronomiconCoding/NecroBot/releases
this is all it adds from NecroBot-master\PoGo.NecroBot.CLI
Config	Added a websocket interface	an hour ago
Properties	Rename folders to fit new name	21 hours ago
App.config	Added a websocket interface	an hour ago
ConsoleEventListener.cs	Spelling Mistake	32 minutes ago
ConsoleLogger.cs	code cleanup & fix code issues	21 hours ago
PoGo.NecroBot.CLI.csproj	accidentally changed the path to the API to my path	an hour ago
Program.cs	Added a websocket interface	an hour ago
Settings.cs	Merged again	41 minutes ago
WebSocketInterface.cs	Legacy clean up	an hour ago
packages.config	Added a websocket interface	an hour ago
supersocket.cmd	Added a websocket interface	an hour ago
supersocket.sh	Added a websocket interface	an hour ago

**Comment by yamashi** [comment]
Works as designed.

**Comment by Somberland** [comment]
you have to initialize the submodules (Pokemon-Go-Rocket-API):
Way 1 (detailed):
```
$ git clone https://github.com/NecronomiconCoding/NecroBot.git
$ git submodule init
$ git submodule update 
```

Way 2 (fast):
``` $ git clone --recursive https://github.com/NecronomiconCoding/NecroBot.git
` ``

**Comment by cloudsstars** [comment]
@Somberland im kinda new at this how do i do that where do i add this code its not in the wiki

**Comment by Somberland** [comment]
@cloudsstars  sadly I can't edit the wiki but: https://github.com/NecronomiconCoding/NecroBot/issues/618#issuecomment-235323195
