### ISSUE TITLE
Wiki needs Update

### ISSUE THREAD

**Issue by hioRR** [NecronomiconCoding/NecroBot#618]
Hey,

the Wiki for "Working with the source code" say:

"6. On the right hand side, double click on **UserSettings.settings.**"

Whats the **replacement** for it on the newest RocketAPI and could you please **edit the Wiki**?
An no, not everyone just wants to work with the release. some people **prefer the source** :)

Thanks!

**Comment by agp89** [comment]
In `Settings.cs` ([AuthSettings](https://github.com/NecronomiconCoding/NecroBot/blob/master/PoGo.NecroBot.CLI/Settings.cs#L22)/[GlobalSettings](https://github.com/NecronomiconCoding/NecroBot/blob/master/PoGo.NecroBot.CLI/Settings.cs#L128))

...after u build it you can change the two files auth.json and config.json which are located in `\bin\Debug\config`

**Comment by Somberland** [comment]
Sadly I can't update the wiki but here you go:

## Working with the source code
### Downloading necessary files
Download and Install [Visual Studio 2015](https://go.microsoft.com/fwlink/?LinkId=691979&clcid=0x409).

#### source code as zip-files
1. Get the current source code from [Code](https://github.com/NecronomiconCoding/NecroBot/archive/master.zip).
2. Get the current version of the RocketAPI we use from [RocketAPI](https://github.com/FeroxRev/Pokemon-Go-Rocket-API/archive/master.zip)
3. Unzip the source code for NecroBot
4. Unzip the RocketAPI so the folder structure matches `NecroBot\FeroxRev\PokemonGo.RocketAPI\`
	
#### source code via git (faster)
1. open your terminal (you should have [git for windows](https://git-for-windows.github.io) installed)
2. change to the folder where you want to clone the files to and typo into terminal
3. `git clone —recursive https://github.com/NecronomiconCoding/NecroBot.git`
	
### Setup
1. Open `NecroBot for Pokemon Go.sln`.
2. Press `CTRL + F5` and close the window asap
3. Open the `config.json` located at `NecroBot\PoGo.NecroBot.CLI\bin\Debug\config` with your favourite text-editor
4. Enter the *DefaultLatitude* and *DefaultLongitude* which can be found [here](http://mondeca.com/index.php/en/any-place-en) or via googleMaps.
5. change the other settings as you need them
6. if you want to change the AuthType to PTC Open the `auth.json` located at `NecroBot\PoGo.NecroBot.CLI\bin\Debug\config` with your favourite text-editor and change AuthType to `ptc` for Pokémon Trainer Club and add your login credentials
7. Right click on `PoGo.NecroBot.CLI` and click on `Set as Startup Project`.
8. Press `CTRL + F5` and follow the instructions.
9. Have fun!
