### ISSUE TITLE
[Bug ]KeepMinIvPercentage value possibly not being read correctly.

### ISSUE THREAD

**Issue by padmanek** [NecronomiconCoding/NecroBot#621]
using Release Necrobot v0.1.6.

I have 2 pokes:
[POKEMON]   [ATK]  [DEF]  [STA]     [CP]     [IV]
Eevee          15      9     15       78   86.67%
Hypno          14     12     14      225   88.89%

And my config is set to:  
"KeepMinCp": 1000 
"KeepMinIvPercentage": 90.0 
"KeepMinDuplicatePokemon": 0

and the bot won't transfer them. 
Eevee and Hypno are NOT on "PokemonsToEvolve" list either.

Full config: http://pastebin.com/Y1GELy2Y

**Comment by mario296** [comment]
It will keep them if they are the single one of it's kind that is  the highest perfect

**Comment by padmanek** [comment]
Theya re not, I have 100% Eevee too with higher CP.

**Comment by padmanek** [comment]
`Eevee          15     15     15      369  100.00%
Weepinbell     14     15     15      127   97.78%
Paras          13     15     15      412   95.56%
Venomoth       14     15     14      535   95.56%
Krabby         14     14     15      469   95.56%
Gloom          13     15     14      324   93.33%
Drowzee        14     13     14      206   91.11%
Hypno          14     12     14      225   88.89%
Golbat         13     11     15     1234   86.67%
Hypno          14     10     14     1222   84.44%
Venomoth       14      6     14     1250   75.56%
Gloom          13      3     13     1051   64.44%
Fearow         12     12      4     1074   62.22%
Fearow         11      0      2     1019   28.89%
Weedle          2      2      3       33   15.56%
------------       Other Pokemon        ------------
[POKEMON]   [ATK]  [DEF]  [STA]     [CP]     [IV]
Eevee          15      9     15       78   86.67%`

**Comment by padmanek** [comment]
Eevee          15     15     15      369  100.00%
Weepinbell     14     15     15      127   97.78%
Paras          13     15     15      412   95.56%
Venomoth       14     15     14      535   95.56%
Krabby         14     14     15      469   95.56%
Gloom          13     15     14      324   93.33%
Drowzee        14     13     14      206   91.11%
**Hypno          14     12     14      225   88.89%**
Golbat         13     11     15     1234   86.67%
**Eevee          15      9     15       78   86.67%**
Hypno          14     10     14     1222   84.44%
Venomoth       14      6     14     1250   75.56%
Gloom          13      3     13     1051   64.44%
Fearow         12     12      4     1074   62.22%
Fearow         11      0      2     1019   28.89%
Weedle          2      2      3       33   15.56%

**Comment by padmanek** [comment]
I've used bold on 2 pokes that should be transfer. Ignore the Weedle..my bot is running :)

**Comment by NecronomiconCoding** [comment]
do you have KeepMinCP activated?

**Comment by padmanek** [comment]
@NecronomiconCoding Activated? I dont see anywhere to see true flag to it: It's set to 1000.
"KeepMinCp": 1000,

You can see my full config: http://pastebin.com/Y1GELy2Y

**Comment by onlylove943** [comment]
Is 0.1.6 display ATK DEF HP stats or it's your own code?

**Comment by padmanek** [comment]
@onlylove943
Not my own, from this github https://github.com/imoutits/pgoapi
There's thread on OC about this tool http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/563472-iv-based-evolve-transfer-tool.html

**Comment by C0wLuminous** [comment]
Hello. How did you make the bot display your perfect% pokemon? Sorry I'm new thanks.

**Comment by padmanek** [comment]
@C0wLuminous read the comment above, I'm using another tool for that.

**Comment by onlylove943** [comment]
Do u use python 2.7 or 3.5? I see ppl recommend 2.7 but in that OC thread, OP use 3.5 :/

**Comment by padmanek** [comment]
@onlylove943 2.7 but I dont think that matters. Something is flawed with Bot's logic.

**Comment by onlylove943** [comment]
Thx for information. I'm using that tool to check my pokemon's IV. 1 more question, i have to manually use lucky egg or this tool will do it?

**Comment by Artud** [comment]
@onlylove943 The bot uses the egg.

@padmanek Is the issue fixed? It should keep highest CP or highest IV

**Comment by padmanek** [comment]
@Artud it's not fixed.

**Comment by padmanek** [comment]
Figured out the problem here #696, see comments.
