### ISSUE TITLE
Error with authenticated proxy

### ISSUE THREAD

**Issue by JaEdmuva** [NecronomiconCoding/NecroBot#622]
Hi, I'm trying to run the bot, but I get a console full of errors and the log file indicates it's because I'm behind an authenticated proxy (see the log bellow). May you define a configuration section for proxy data? Thanks.

[10:56:00] System.AggregateException: Se han producido uno o varios errores. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   en System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Helpers.HttpClientHelper.<PostFormEncodedAsync>d__0`1.MoveNext() en D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\HttpClientHelper.cs:línea 21
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Login.GoogleLogin.<GetDeviceCode>d__5.MoveNext() en D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs:línea 29
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__4.MoveNext() en D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:línea 39
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   en PoGo.NecroBot.Logic.State.LoginState.Execute(Context ctx, StateMachine machine) en D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:línea 26
   en PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx) en D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:línea 50
---> (Nº de excepción interna 0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Error en el servidor remoto: (407) Se requiere autenticación del proxy.
   en System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   en System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Helpers.HttpClientHelper.<PostFormEncodedAsync>d__0`1.MoveNext() en D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\HttpClientHelper.cs:línea 21
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Login.GoogleLogin.<GetDeviceCode>d__5.MoveNext() en D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs:línea 29
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__4.MoveNext() en D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:línea 39<---

**Comment by NecronomiconCoding** [comment]
This is currently not planned. I am sorry
