### ISSUE TITLE
[Suggestion] Removal Of The Pokemon Show Upon Start

### ISSUE THREAD

**Issue by Maynaards** [NecronomiconCoding/NecroBot#625]
In a previous build when the bot loaded up it showed your best pokemon and their IVs, this was a great feature and I think it should be readded!

Thanks,

Maynaards

**Comment by padmanek** [comment]
would be nice if it showed their ATT/DEF/STA too :)

**Comment by rayn21** [comment]
That was merged in this morning.

**Comment by starf** [comment]
What was merged in? The removal of the list? I don't see the logic in that.

This point of this issue is to have the list **shown**.
+1 for this.

**Comment by rayn21dev** [comment]
No, the list showing was merged in from a pull request. Should be included in next release.

**Comment by starf** [comment]
Big kiss

**Comment by ShawnHardwick** [comment]
Added in 0.1.7.
