### ISSUE TITLE
Cannot compile since last night commits

### ISSUE THREAD

**Issue by yonosokote** [NecronomiconCoding/NecroBot#627]
PokemonGo.RocketAPI shows "load failed"

and console has some references about missing PokemonGo.RocketAPI.csproj

**Comment by cawk** [comment]
Add this 
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/tree/de054eecea6b551c65301782010ac78ea38c54db
to the feroxrev folder

**Comment by yonosokote** [comment]
What am I doing wrong? http://i.imgur.com/pLDab98.png

**Comment by cebuladeals** [comment]
I have the same problem
http://imgur.com/a/AHbjn
C:\NecroBot-master\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\NecroBot-master\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj'.  C:\NecroBot-master\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj

**Comment by wouter2203** [comment]
Just download a release at https://github.com/NecronomiconCoding/NecroBot/releases

<small>I assumed you didn't edit the source code yourself, if so ignore this post.</small>

**Comment by NecronomiconCoding** [comment]
read the wiki next time
