### ISSUE TITLE
Lucky eggs are used before 30 min

### ISSUE THREAD

**Issue by ricoxor** [NecronomiconCoding/NecroBot#629]
The BOT don't wait 30 min before use the Lucky eggs 

1 - http://puu.sh/qfaXj/fd004e4752.png
2 - http://puu.sh/qfaZg/e5055f7947.png

**Comment by LasaFawkes** [comment]
I'm pretty sure that's just a visual bug. It happened to me yesterday as well but the egg was still there on my inventory.

**Comment by NecronomiconCoding** [comment]
https://github.com/NecronomiconCoding/NecroBot/commit/90c1743e93b245e200bb55aadd429e8d3435106d
