### ISSUE TITLE
Need new section in config for Only keep one of this pokemon

### ISSUE THREAD

**Issue by EasyAsABC123** [NecronomiconCoding/NecroBot#633]
This section will allow you to list pinsir, which you only want one of...but might be above your IV and CP limit...

I end up with too many pokemon because of this

**Comment by KurtCocain** [comment]
+1
I put IV value to 90 and max cp to 1800
Yet I have around 25 pinsirs. Idk what to do lol

**Comment by EasyAsABC123** [comment]
to fix this temporarily:
```
"UsePokemonToNotCatchFilter": true,
```

```
"PokemonsToIgnore": [
    "pinsir"
  ],
```

these settings make the bot ignore pinsirs

**Comment by ShawnHardwick** [comment]
Sounds like a AlwaysTransfer list.

**Comment by ShawnHardwick** [comment]
See #492
