### ISSUE TITLE
Unable to compile from Master

### ISSUE THREAD

**Issue by lgndz** [NecronomiconCoding/NecroBot#634]
Getting an error "Pokemongorocket.api is unavailable" so I cant change the usersettings.

**Comment by EasyAsABC123** [comment]
you need to get all submodules...

inside the folder in git bash run
```
git submodule update --init --recursive
```

**Comment by Navyguy330** [comment]
how do you do that?  it was fine a min ago now what?>

**Comment by EasyAsABC123** [comment]
@Navyguy330 literally you just need to delete the whole folder... Git clone then run the above listed command

**Comment by NecronomiconCoding** [comment]
read the wiki..

**Comment by EasyAsABC123** [comment]
@NecronomiconCoding actually it appears the wiki is wrong now that the code doesn't use usersettings...also it doesn't mention sub-modules

**Comment by Navyguy330** [comment]
that part is not on the wiki

**Comment by Navyguy330** [comment]
you changed so much the wiki is shot.  no user settings nothing.  doesnt compile etc.

**Comment by EasyAsABC123** [comment]
```
Download and Install Visual Studio 2015.
Get the current source code from Code.
Get the current version of the RocketAPI we use from RocketAPI
Unzip the RocketAPI so the folder structure matches NecroBot\FeroxRev\PokemonGo.RocketAPI\
```

**Comment by Artud** [comment]
The wiki is good, user settings are in config.json use the release in https://github.com/NecronomiconCoding/NecroBot/releases

**Comment by lgndz** [comment]
This was concerning getting the MASTER copy to run, since you do not update
releases near as fast as the master for people who hawk Git or have a local
SVN up.

Just saying

**Comment by Navyguy330** [comment]
Yup I don't wait for releases I use the master.  Just saying what ever was
changed since last release broke it.
