### ISSUE TITLE
Not evolving 0.16

### ISSUE THREAD

**Issue by KurtCocain** [NecronomiconCoding/NecroBot#635]
It's not evolving the pokemons to evolve but it DOES keep them, so I get inventory full in 20 seconds and then it just afks and do 5k exp/hour trying to catch pokemon and sometimes a pokestop here and there.

{
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.778835,
  "DefaultLongitude": -73.968917,
  "DelayBetweenPokemonCatch": 1000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1600,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 1600,
  "PrioritizeIvOverCp": true,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": true,
  "WalkingSpeedInKilometerPerHour": 350.0,
  "RenameAboveIv": true,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore": [
    "pinsir"
 
  ],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
    "weedle",
    "spearow",
    "caterpie"
  ]
}

It's not evolving the pokemons to evolve but it DOES keep them, so I get inventory full in 20 seconds and then it just afks and do 5k exp/hour trying to catch pokemon and sometimes a pokestop here and there.

**Comment by KurtCocain** [comment]
Even after restarting bot, it wont evolve or transfer any of them

https://gyazo.com/728db2cbc8826113779e4e99aa680461.png

**Comment by EasyAsABC123** [comment]
i'm also having this bug

**Comment by KurtCocain** [comment]
it'd be cool if we had an option to just farm pokestop. I don't need more pokemon and i'm pretty sure with the customizable walking speed we could get higher exp/h without soft ban just doing pokestops.

**Comment by EasyAsABC123** [comment]
temporary fix:
```
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
```

make sure your settings are like the above

**Comment by lgndz** [comment]
confirmed above worked

**Comment by KurtCocain** [comment]
https://gyazo.com/d44595ef3ac84b6c9d8f9037b0abd630
Can confirm too, thanks
