### ISSUE TITLE
(request) rare pokemon sniping method without being softban

### ISSUE THREAD

**Issue by aapikz** [NecronomiconCoding/NecroBot#636]
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/563391-guide-avoid-softban-while-sniping-pokemons-nox-app.html 

confirmed I tested it  and works perfectly jumping continent to continent around the world without bans
would be possible to add the bot to automate this ?

**Comment by NecronomiconCoding** [comment]
not planned right now / postponed
