### ISSUE TITLE
add a RazzBerryMode.

### ISSUE THREAD

**Issue by ghry** [NecronomiconCoding/NecroBot#637]
first,thanks for this greatest work.
can u add something like this.

cp Mode: Use RazzBerry when Pokemon is over setting's value.
pobability Mode: Use Razzberry when % between 0 and 1 of catching is under setting's value.

thanks again.

**Comment by PocketMobsters** [comment]
We already use Razzberries based off of catch probability, catch probability is more or less linked to CP and type so it's near pointless for a CP only mode.

**Comment by Artud** [comment]
Closed as current catch probability method is optimal.
