### ISSUE TITLE
1 or more projects didnt open correctly

### ISSUE THREAD

**Issue by PokemonCoOwner** [NecronomiconCoding/NecroBot#639]
when i open this it says PokemonGo.RocketAPI (Load Failes)

**Comment by GDlike** [comment]
Read wiki.

**Comment by NecronomiconCoding** [comment]
read the wiki

**Comment by EasyAsABC123** [comment]
https://github.com/NecronomiconCoding/NecroBot/issues/634

**Comment by Navyguy330** [comment]
You need to get the Rocket API and place it in the FeroxRev folder.

**Comment by EasyAsABC123** [comment]
just run
```
git submodule update --init --recursive
```
inside the base folder for NecroBot

**Comment by Navyguy330** [comment]
Run it in what? CMD?

**Comment by Navyguy330** [comment]
git isnt a recognized command

**Comment by EasyAsABC123** [comment]
@Navyguy330 git bash as this is a git command...you will need to have git installed...

if you are downloading the zip files then you really aren't following GitHub properly...you should 

1. [Install Git ](https://git-scm.com/downloads)
2. run `git clone https://github.com/NecronomiconCoding/NecroBot.git` from your folder you want NecroBot folder to be created in example ~/Documents/Code
3. run `git submodule update --init --recursive` from the NecroBot folder
4. to get the latest code run `git pull` from the NecroBot folder

**Comment by Navyguy330** [comment]
thank you did not know that

**Comment by Navyguy330** [comment]
thats cool does that make it so i do not need to constantly change all the freaking settings again and again?
meaning it only pulls the changes?? god I hope so I will love you forever lol

**Comment by EasyAsABC123** [comment]
@Navyguy330 understandably...it isn't explained in the wiki and if you are new to github how would you know.

Yes, you simply run `git pull` and the latest will be pulled.  As long as config\* isn't included in the source code via the .gitignore file then you don't have to worry about those contents

**Comment by Navyguy330** [comment]
I do not follow the last part.

**Comment by Navyguy330** [comment]
do I need to change the git ignore or something then? or ?? I just wouldn't mind not having to re enter all my credentials, the pokemon to evolve etc etc etc

**Comment by EasyAsABC123** [comment]
@Navyguy330 because the config folder is ignored in the .gitignore file (YOU DONT NEED TO DO ANYTHING HERE) when you run `git pull` it will just update the code not the config files

**Comment by Artud** [comment]
@Navyguy330 http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/563371-how-update-your-bots-keep-your-changes-locally.html follow that tutorial if you are new to GitHub.

**Comment by Navyguy330** [comment]
so anything NOT in git ignore it wil lover right, so like when I change how many pokeballs I want it to keep or delays etc those WILL be EVEN if they were NOT changed?


also the problemI am having is:  http://prntscr.com/bxt7r1

NOT an issue with getting ferox fork etc

**Comment by Navyguy330** [comment]
its got no reference to some weird PROTO thats grayed out and gives 500 errors lol

**Comment by Navyguy330** [comment]
125 errors sorry

**Comment by EasyAsABC123** [comment]
Yeah that must be the latest code, I don't have that issue as I haven't gotten latest in ~4 hours
