### ISSUE TITLE
Wiki incorrect  cannot compile

### ISSUE THREAD

**Issue by Navyguy330** [NecronomiconCoding/NecroBot#641]
Has lost usersettings and will not compile,  numerous errors

**Comment by EasyAsABC123** [comment]
This isn't true the wiki is now correct
```
Download and Install Visual Studio 2015.
Get the current source code from Code.
Get the current version of the RocketAPI we use from RocketAPI
Unzip the RocketAPI so the folder structure matches NecroBot\FeroxRev\PokemonGo.RocketAPI\
```

**Comment by Artud** [comment]
Use the release here https://github.com/NecronomiconCoding/NecroBot/releases and follow this steps: https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started

**Comment by Navyguy330** [comment]
I have done that, have used this since it was out. I am saying the newest
commits broke it.  That release is over 3 hours old there were like 20
commits since then

**Comment by cloudsstars** [comment]
im having the same problem i do this then get 15 errors and then it stops
 Open NecroBot for Pokemon Go.sln.
Right click on PoGo.NecroBot.CLI and click on Set as Startup Project.
Press CTRL + F5 and close the window asap
now i have 15 erros 
Open the config.json located at NecroBot\PoGo.NecroBot.CLI\bin\Debug\config with your favourite text-editor there is no such file as config

**Comment by Artud** [comment]
@Navyguy330 If you pull a Git after a lot of changes where made, either locally or on the repo then is better to clean install to not get issues.
