### ISSUE TITLE
There is no UserSettings.settings.

### ISSUE THREAD

**Issue by cebuladeals** [NecronomiconCoding/NecroBot#643]
There is no UserSettings.settings. on the right hand side
https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#installation--configuration

>  6. On the right hand side, double click on UserSettings.settings.

Where is it?

**Comment by EasyAsABC123** [comment]
This was removed in the latest version in favor of json settings in:
config\auth.json
config\config.json

**Comment by Artud** [comment]
Wiki is already updated.
