### ISSUE TITLE
Running out of Pokeballs

### ISSUE THREAD

**Issue by noobz123** [NecronomiconCoding/NecroBot#644]
Hi I'm having trouble with running out of bagspace. The potions aren't being recycled.

My item config file says: 
ItemUnknown 0
ItemPokeBall 25
ItemGreatBall 50
ItemUltraBall 75
ItemMasterBall 100
ItemPotion 0
ItemSuperPotion 0
ItemHyperPotion 10
ItemMaxPotion 75
ItemRevive 25
ItemMaxRevive 25
ItemLuckyEgg 200
ItemIncenseOrdinary 100
ItemIncenseSpicy 100
ItemIncenseCool 100
ItemIncenseFloral 100
ItemTroyDisk 100
ItemXAttack 100
ItemXDefense 100
ItemXMiracle 100
ItemRazzBerry 50
ItemBlukBerry 10
ItemNanabBerry 10
ItemWeparBerry 30
ItemPinapBerry 30
ItemSpecialCamera 100
ItemIncubatorBasicUnlimited 100
ItemIncubatorBasic 100
ItemPokemonStorageUpgrade 100
ItemItemStorageUpgrade 100

Yet when i log into Nox the bad i filled with just all potion of regular, super, hyper and max types
I get messages like this now:
[18:26:28] (PKMN) No Pokeballs - We missed a Magikarp with CP 110
[18:26:34] (PKMN) No Pokeballs - We missed a Goldeen with CP 480

Any way i can get the bot to recycle the potions?

**Comment by Artud** [comment]
Can you please do a fresh install of the bot, it should fix the issue.
