### ISSUE TITLE
PokemonInventoryFull while still have to select starter deadlock. #facepalm

### ISSUE THREAD

**Issue by thomasmoors** [NecronomiconCoding/NecroBot#645]
I can't log in on my phone because I still have to choose a starten, but my pokemon inventory is full. I also can't tranfer a pokemon because I can't select that option before selecting a starter. Please let the application first transfer all low lvl pokemon.

**Comment by EasyAsABC123** [comment]
wow, you botted from the get go...interesting *claps*

you likely will need to buy the "more pokemon space" item from the shop

**Comment by thomasmoors** [comment]
could we not just force the application to do the transferring first?

**Comment by KurtCocain** [comment]
^ I have 5 un named account I have never once logged into on an application before and they are lvl 32 now, I haven't found a problem were I could not transfer.

**Comment by Cazs03** [comment]
Inventory full is bug?

**Comment by thomasmoors** [comment]
@Cazs03 well it makes the game in deadlock state. I bought the bag upgrade because of the experiment, but it really can be fixed in this app by evolving or transferring first.

**Comment by Artud** [comment]
You need to wait for new releases with evolving/transfering first.

**Comment by rayn21** [comment]
I never selected a starter and I have always been able to transfer....
