### ISSUE TITLE
PoGo.NecroBot.CLl.exe" is missing

### ISSUE THREAD

**Issue by PokemonCoOwner** [NecronomiconCoding/NecroBot#650]
When i try to execute the bot it gives me that error and when i go to the folder to check it that exe file is there and its not missing, i tried it again and gives me the same error. please help

**Comment by parameciaCx** [comment]
I can't find it either, and running it through NecroBot for Pokemon Go.sln like before doesn't work as it gives the error saying The project file could not be loaded. Could not find a part of the path PokemonGo.RocketAPI.csproj

**Comment by Artud** [comment]
Updated wiki with PogoProto Fix: https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started
