### ISSUE TITLE
[feature request] not deleting "favorited" pokemons

### ISSUE THREAD

**Issue by starf** [NecronomiconCoding/NecroBot#651]
an option to NOT delete "favorited" pokemons
or is this already by default?
thanks for all the hard work.

**Comment by Artud** [comment]
It won't delete the Max CP or Best IV of each type pokemon, depends on your settings.

**Comment by padmanek** [comment]
@Artud If I have:
"KeepMinCp": 1000 
"KeepMinIvPercentage": 90.0 
"KeepMinDuplicatePokemon": 0

And 2 Eevees, 96% IV and 93% IV, is it going to delete one of them?
In other words, which rule is **stronger** KeepMinIV or KeepMinDuplicate ?

**Comment by starf** [comment]
I understand, but still it would be nice to be sure the "favorited" pokemons will never ever get deleted.

**Comment by emoisback** [comment]
nice suggest, its will be help us to transfer highest cp or precentage without transfer our favorited pokemons..

**Comment by starf** [comment]
@emoisback 
Perfect, thanks.

@padmanek 
**KeepMinCp** seems to be always respected, it keeps all your pokemon that have a higher CP then this value.
**KeepMinDuplicatePokemon** keeps X amount of pokemons on top of your best pokemon.
And you decide in parameter **PrioritizeIvOverCp** in what order the pokemon are ranked before transferring the remaining ones.
