### ISSUE TITLE
[Suggestion] Auto to use incubator to Hatch egg and auto to use incense

### ISSUE THREAD

**Issue by kel899** [NecronomiconCoding/NecroBot#652]
I hope that these two functions can be developed in the future =]
I also suggest that function about gym (training...etc.) can be considered in the future!
Thank you all=]!

**Comment by Artud** [comment]
Auto use incubator to be added in future updates.

Gym taking won't be added.

**Comment by jakesteele** [comment]
The incubator one is already developed its lower down on https://github.com/NecronomiconCoding/NecroBot/issues/521 by Bogenschuetze

Dont think the logic includes which incubator to use on which egg so be warned.
