### ISSUE TITLE
PogoProtos

### ISSUE THREAD

**Issue by cebuladeals** [NecronomiconCoding/NecroBot#654]
> NOTE: If PogoProtos is missing: Its in the packages folder, just right click the CLI -> Add Reference -> Browse (tab) -> Browse (button) -> go to the packages folder in the root directory and find the PogoProtos

I cant find PogoProtos, Where is it?

**Comment by EasyAsABC123** [comment]
follow: https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#installation--configuration

**Comment by hawkagent** [comment]
Necrobot/packages/POGOProtos.1.3.0/lib/net45

**Comment by cebuladeals** [comment]
I dont have folder packages

**Comment by Navyguy330** [comment]
what do i do with those?
