### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by sammuelsgs** [NecronomiconCoding/NecroBot#657]
"One or more project on your solution were not loaded correctly. Please see the output windows for details"

"C:\Users\Sammuel\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Sammuel\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj'.  C:\Users\Sammuel\Desktop\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj
"

i think there's a file missing in this zip﻿

**Comment by mich3lam** [comment]
https://github.com/NecronomiconCoding/NecroBot/issues/646
