### ISSUE TITLE
Can't Compile -- POGOProtos 

### ISSUE THREAD

**Issue by GDlike** [NecronomiconCoding/NecroBot#660]
The referenced component 'POGOProtos' could not be found.	PoGo.NecroBot.CLI			

Could not locate the assembly "POGOProtos". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PoGo.NecroBot.CLI			

The type or namespace name 'POGOProtos' could not be found (are you missing a using directive or an assembly reference?)	PoGo.NecroBot.CLI	

Settings.cs
ConsoleEventListener.cs	

How to fix this?

**Comment by mich3lam** [comment]
Add the proto as refference

**Comment by Artud** [comment]
Follow https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#installation--configuration

**Comment by onlylove943** [comment]
I did follow that guide. I have the same error while compile source code via git.
