### ISSUE TITLE
TransferDuplicateIV

### ISSUE THREAD

**Issue by Welshpride** [NecronomiconCoding/NecroBot#663]
Our inventory are getting full with IV over the 85% and its holding multiple IV% of the same Pokemon We only keep the Highest IV% TransferDuplicateIV under the top IV%

**Comment by Maynaards** [comment]
Change your MinIV to about 95% and fixed

**Comment by rbnbrls** [comment]
"KeepMinDuplicatePokemon": 1,
  "PrioritizeIvOverCp": true,

would also help I assume

**Comment by Welshpride** [comment]
@rbnbrls  that is the way my config is.

@Maynaards I would still have multi-Pokemon IV over 95%

**Comment by padmanek** [comment]
@rbnbrls 
I have:
"KeepMinCp": 1000 
"KeepMinIvPercentage": 90.0 
"KeepMinDuplicatePokemon": 0
"PrioritizeIvOverCp": true

And it still keeps 86% 75CP Evee and 88% 250CP Hypno and won't transfer it no matter what. No idea why.

**Comment by cloudsstars** [comment]
i have min set to 95% iv and cp over 1200 as well as rename pokemon iv on and i have 30 drowzees that are undeer 1200 and only one above 90% iv

**Comment by emoisback** [comment]
KeepPokemonsThatCanEvolve: true?

if its true, so that's is the problem your pokemon is can be evolve so bot didnt transfer it, just make it false, your pokemon under your setting will gone.

**Comment by padmanek** [comment]
@emoisback mine is false and it still doesn't transfer ;/

**Comment by cloudsstars** [comment]
it was a my bad had keep pokemon on thought it would evolve the last two pokemon im trying to add to my list cant find them anywhere in my city lol was hopping bot would find them

**Comment by emoisback** [comment]
@padmanek 

Do you use lastest code...

**Comment by padmanek** [comment]
@emoisback I use the latest release, 0.1.6.

**Comment by emoisback** [comment]
Your pokemon is not mark as favorite right?..

but its wierd, still doesnt transfer.

**Comment by padmanek** [comment]
@emoisback They are not marked as favourite. 
I know it's weird. It's 100% a bug and I've been looking on the logic in the code but could not find any issues myself.

**Comment by emoisback** [comment]
@padmanek  may i see your entier config without username and password..

yeah i looking on the logic but your setting should be running well..

**Comment by padmanek** [comment]
@emoisback 

{
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 45.030151,
  "DefaultLongitude": -93.31931,
  "DelayBetweenPokemonCatch": 0,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 0,
  "KeepMinIvPercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000,
  "PrioritizeIvOverCp": true,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 150.0,
  "RenameAboveIv": true,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore": [],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
	"weedle",
	"caterpie",
	"oddish",
	"drowzee",
	"spearow",
	"nidoranfemale",
	"nidoranmale",
	"bellsprout",
	"venonat"
  ]
}

**Comment by padmanek** [comment]
@emoisback And the pokemon list:

**Comment by emoisback** [comment]
its not transfered, console didnt show  notice about transfering your pokemon??..

because sometimes inventory cache not refreshed automaticly.

**Comment by padmanek** [comment]
@emoisback Nope, I've restarted the bot multiple times. Checked it manually in NOX. They are still there.

**Comment by Hardell** [comment]
The reason why it doesn't transfer them is because it doesn't count the pokemon above the thresholds as duplicate. For example, if your threshold is 90% IV, it will keep all pokemon above that threshold AND 1 duplicate below the threshold.

Setting the IV threshold above 100 will most likely make it only keep 1 pokemon with the highest CP.

**Comment by padmanek** [comment]
@Hardell my "KeepMinDuplicatePokemon": is 0

**Comment by padmanek** [comment]
@emoisback They are still here, screenshot from NOX http://imgur.com/O3pzgUM
