### ISSUE TITLE
Need better Pokemon transfer.

### ISSUE THREAD

**Issue by KicksDNA** [NecronomiconCoding/NecroBot#665]
My settings are set to the following yet I always get "(ATTENTION) Encounter problem: PokemonInventoryFull"

{
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 34.00924,
  "DefaultLongitude": -118.49760,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1500,
  "KeepMinDuplicatePokemon": 0,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 1000,
  "PrioritizeIvOverCp": false,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "RenameAboveIv": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 5
    },
    {
      "Key": "itemGreatBall",
      "Value": 10
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 0
    },
    {
      "Key": "itemMaxPotion",
      "Value": 50
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 25
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore": [
    "zubat",
    "pidgey",
    "rattata"
  ],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata"
  ]
}

**Comment by Maynaards** [comment]
You're filled with too many pokemons with IVs above 85%
"KeepMinIvPercentage": 85.0,

I advise you put this up to about 95.

Hope I can help,
Maynards

**Comment by Welshpride** [comment]
this is why we need this
https://github.com/NecronomiconCoding/NecroBot/issues/663

**Comment by KicksDNA** [comment]
@Maynaards but if I have "KeepMinCp": 1500, shouldn't everything under 1500 be transferred

**Comment by emoisback** [comment]
your PrioritizeIvOverCp is false?.

**Comment by KicksDNA** [comment]
@emoisback yes it is...so shouldn't CP be the only filter it pays attention to

**Comment by Welshpride** [comment]
PrioritizeIvOverCp true KeepMinCp 1700 and it will still keep multiple IV% over 85% as they are under the 1700CP and obeying rule KeepMinIvPercentage

**Comment by KicksDNA** [comment]
@Welshpride I have "PrioritizeIvOverCp": false, so shouldn't anything under "KeepMinCp": 1500, be transferred

**Comment by emoisback** [comment]
@KicksDNA everything under 1500CP will be transfered..do you still have pokemon with CP under 1500??

**Comment by KicksDNA** [comment]
@emoisback yes, plenty...that's why I keep hitting the Pokemon limit...I currently only have 10 or less above the 1500

**Comment by padmanek** [comment]
#621 Sound similar like my issue. KeepCP is 1000, KeepIV is 90 and it still keeps some pokes that are 86, 88% and much lower than 1000, so should definitely be transfered.

**Comment by KicksDNA** [comment]
@padmanek we definitely need this issue fixed

**Comment by padmanek** [comment]
@NecronomiconCoding  replied to my issue with a weird question but never got back there ;/

**Comment by Welshpride** [comment]
@KicksDNA "PrioritizeIvOverCp": false is not what i want to do as i want High IV not high CP

**Comment by KicksDNA** [comment]
@Welshpride I see...your're problem is different than mine...I have mine set to false and yet I still get Pokemon under my min CP

**Comment by emoisback** [comment]
"KeepPokemonsThatCanEvolve": true,

That's the problem, bot keep your pokemon because your pokemon can be evolve..

**Comment by KicksDNA** [comment]
@emoisback THANK YOU

**Comment by tomy91** [comment]
Yup. I encountered the same problem and there are 2 solutions:
1) set "KeepPokemonsThatCanEvolve" to FALSE
2) set "EvolveAllPokemonAboveIv": false and "EvolveAllPokemonWithEnoughCandy": true
I recommend combining this with "UseLuckyEggsWhileEvolving": true so it will give a nice XP boost.

Just don't forget to list all pokemons You are willing to auto-evolve like this:
`  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
	"doduo",
	"drowzee",
	"weedle",
	"metapod",
	"spearow",
	"oddish",
	"poliwag",
	"bellsprout",
	"magnemite",
	"krabby",
	"voltorb",
	"goldeen",
	"staryu",
	"pinsir"
  ]`
