### ISSUE TITLE
Namespaces not found

### ISSUE THREAD

**Issue by Mathijs1994** [NecronomiconCoding/NecroBot#666]
I just downloaded a copy with git but when i build It cant find the namespace POGOProtos and some other that are related i guess

**Comment by mich3lam** [comment]
https://github.com/NecronomiconCoding/NecroBot/issues/660

**Comment by Artud** [comment]
Follow https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#installation--configuration
