### ISSUE TITLE
Bot is not catching pokemon anymore, and inventory is full warning

### ISSUE THREAD

**Issue by CaptainFabulouss** [NecronomiconCoding/NecroBot#668]
I'm not very good when it comes to stuff like this, I have no idea what I am supposed to do.
The problem is that the bot has been doing **[this](http://imgur.com/a/aeF6i)** for the past 60 minutes. As you can see it is no longer catching pokemon and it keeps saying the inv is full, even though it does still loot some pokestops. 

Any help would be greatly appreciated. 
Thanks in advance.

**Comment by Artud** [comment]
Change your settings to discard pokemon.

**Comment by rbnbrls** [comment]
Pokemon inventory is your inventory of pokemon, not items which you get of pokestops. 
Alter your settings

**Comment by CaptainFabulouss** [comment]
Thanks for the help, I didn't realize that.
