### ISSUE TITLE
All your errors when trying to compile

### ISSUE THREAD

**Issue by Navyguy330** [NecronomiconCoding/NecroBot#670]
Edit

**Comment by padmanek** [comment]
All your answers are in the Wiki in the Installation Section on the bottom https://github.com/NecronomiconCoding/NecroBot/wiki/Getting-Started#installation--configuration

**Comment by padmanek** [comment]
> NOTE: If PogoProtos is missing: Its in the packages folder, just right click the CLI -> Add Reference -> Browse (tab) -> Browse (button) -> go to the packages folder in the root directory and find the PogoProtos

**Comment by Navyguy330** [comment]
fixed it thanks

**Comment by dually8** [comment]
I never found a packages folder.  It's not in the repo anywhere.

**Comment by dually8** [comment]
Nevermind.  You have to build first to get the Nuget packages.
