### ISSUE TITLE
Too much candies. 

### ISSUE THREAD

**Issue by MarkHuangZ** [NecronomiconCoding/NecroBot#678]
Is there a way to create an option that user can choose to evolve pokemons in evolve list after it got caught? I got 2.5k Pidgey candies and Zubat candies and I cant eat them... So i would like to think whether there is a better way to spend all those candies into exp. 

You guys are awesome. Great work!

**Comment by zno3** [comment]
yeah the bot prioritizing transfer over evolve, after caught pidgey, it check for cp and iv, then transfer, maybe if its over the iv to evolve, it might evolve

**Comment by Artud** [comment]
#677
