### ISSUE TITLE
Rocket API project failed to load in VS

### ISSUE THREAD

**Issue by MarkHuangZ** [NecronomiconCoding/NecroBot#679]

**Comment by zno3** [comment]
do you mean missing?

**Comment by Artud** [comment]
Please provide a description next time you open an issue.

**Comment by MarkHuangZ** [comment]
My apologies. I download the latest version of the code and I didnt see the RocketAPI folder exist in the solution directory, and I noticed names of folders are changed. So I tried to open the sln file in VS and VS showed me an error which is "One or more projects in the solution were not loaded correctly" and "\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj : error  : The project file could not be loaded. Could not find a part of the path" because the FeroxRev folder is empty.
