### ISSUE TITLE
default lat long in config.json after first compile

### ISSUE THREAD

**Issue by smiLLe** [NecronomiconCoding/NecroBot#683]
Hey guys, i am no C# Guru but from what i understand, as soon as the cli gets compiled for the first time it automatically creates the config.json with its default values. 
however wouldnt it make sense to set the default long and lat to 0.0 and if the main program starts and both values equal 0.0, then an exception should be thrown.
The reason is, if i have forgotten to change them i might start in a different country or continent and this is kinda suspicious.

**Comment by Navyguy330** [comment]
I agree just a failsafe nice little touch, or when running ask for coords, or even better link it to some google maps api ask for city state (country etc) and grab coords from there,   if you are anywhere in the same city you are usually fine no matter how fast you went to that spot from somewhere else  (I guess depends on city size but less "obvious"

**Comment by kanfkasndklasdn** [comment]
Please, I think this would be a great feature

**Comment by Sylencer90** [comment]
agreed.

**Comment by ShawnHardwick** [comment]
Reference #793. It will be the hub for consolidating this request/issue.
