### ISSUE TITLE
Upgrade high IV or CP pokemons with candies

### ISSUE THREAD

**Issue by kanfkasndklasdn** [NecronomiconCoding/NecroBot#685]
Is posible to add the feature to give candies to pokemons that accomplish one of this requirements (with a txt filter is possible), every time the bot starts?

**Comment by Navyguy330** [comment]
I think it is already in there

**Comment by kanfkasndklasdn** [comment]
I only see how to evolve

**Comment by Navyguy330** [comment]
Value IV over CP in config.json

**Comment by kanfkasndklasdn** [comment]
This is for comparing pokemons when transfering. What I want is to upgrade (not evolve) pokemon with high IV. I've 2 100% lvl1 with a lot of candy

**Comment by Navyguy330** [comment]
Oh ok

**Comment by JesusLopezSanchez** [comment]
You will burn a lot of Stardust to up your level 1. Do you really want the bot to do that?

**Comment by kanfkasndklasdn** [comment]
yes

**Comment by ShawnHardwick** [comment]
See #659
