### ISSUE TITLE
(INFO) in ... (spamming)

### ISSUE THREAD

**Issue by ilikesomething** [NecronomiconCoding/NecroBot#686]
Got 6 bot running great for about 30mins and now all i have is this :

![ssddf](https://cloud.githubusercontent.com/assets/13218000/17153081/12ee429c-537b-11e6-93e6-5e5db9e20ef1.png)

any ideas?

**Comment by Sylencer90** [comment]
Santa monica pier? Try different location, im on venice beach and it works fine.

**Comment by Navyguy330** [comment]
weird, gpx file? maybe bad data point info?

**Comment by ilikesomething** [comment]
i started at the middle of central park

**Comment by Artud** [comment]
It's due to location, some places are getting this error.

**Comment by Navyguy330** [comment]
Does it mess it up though? What is causing it?  Closing a major issue like
this before fixing it is odd.

Does it still work but no output? Or?

**Comment by ilikesomething** [comment]
i just get these "(INFO)" thing spamming and after a while i got an error saying: 

No usable PokeStops found in your area. Is your maximum distance too small?

I started at https://www.google.fr/maps/place/Central+Park/@40.7709338,-73.9752739,18z/

And when i relaunch, its always the same prob

**Comment by ilikesomething** [comment]
For information, after waiting 20 min it began to find something again..
But as i said i started from central park so..

**Comment by Navyguy330** [comment]
I have no problem there. I think maybe your size is too small, there is a
five min wait period on when you an use a pokestop again so maybe if too
small it will not have enough time pass before it tries that one again?
