### ISSUE TITLE
Feature Request: Dump Pokemon List via button combo

### ISSUE THREAD

**Issue by JesusLopezSanchez** [NecronomiconCoding/NecroBot#688]
Add capability to dump list of pokemons with stats into text file that can be parsed in excel. Some columns to inclide:
- Pokemon ID
- Pokemon Type
- Pokemon Name
- CP
- Level
- IV

**Comment by Sylencer90** [comment]
Yeah would like to have the as well.

Like a list - e.g. magikarp 100% IV, 105 cp.
easier to recall which to evolve manually.

**Comment by ilu01** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/462

**Comment by Knulen** [comment]
It's the same I'm looking for: #638

**Comment by ShawnHardwick** [comment]
As #638 came first I am closing this as a duplicate. Continue any discussion there about reimplementing PR #462
