### ISSUE TITLE
[Need info] Anyone can teach me (or add to Wiki) how to keep translations after pull?

### ISSUE THREAD

**Issue by GDlike** [NecronomiconCoding/NecroBot#692]
As tittle says, (I know is not the site, sorry) I have everything translated, but when pull new commits every changed file is overwrited, can you please show me any way to keep translates and be able to receive new commits?

**Comment by DurtyFree** [comment]
You should consider creating an issue for multilanguage support, where we actually seperate messages from the code, into translation files.

**Comment by ShawnHardwick** [comment]
I believe there is an ongoing effort for translation now.
