### ISSUE TITLE
File not loaded correctly?

### ISSUE THREAD

**Issue by PokeToby** [NecronomiconCoding/NecroBot#693]
The output box says this when i open the "Necrobot for Pokemon Go" 
C:\Users\Allan\Downloads\NecroBot-master\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Allan\Downloads\NecroBot-master\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj'.  C:\Users\Allan\Downloads\NecroBot-master\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj

Can any of you guys help me out here, the program has been working fine the past few days..

**Comment by MarkHuangZ** [comment]
You need to download the Rocket API here https://github.com/FeroxRev/Pokemon-Go-Rocket-API/tree/c6d12b6dfbcf51c96457788d6755708373c3d48e
That's the updated API NecroBot is using. Download the API and put everything under the Pokemon-Go_Rocket-API folder and you will be fine.

**Comment by PokeToby** [comment]
@MarkHuangZ I dragged the PokemonGo.RocketAPI into the NecroBot-master map and tried to launch but it dosent open the same way as it did like a day ago? Did i do something wrong?

**Comment by MarkHuangZ** [comment]
No, they changed the way to login. Its much better than before. Now you can type your ptc account and pw in the console. Back to 2 days ago, you need to change config file to add your account and pw and save it and run. It's much better now.

**Comment by ShawnHardwick** [comment]
Instructions are always being updated on the Wiki Getting Started page. Follow those instructions. If you still have trouble, join the Discord chat. We prefer this area be left for widespread issues and feature requests.

https://github.com/NecronomiconCoding/NecroBot/wiki/Source-Code
