### ISSUE TITLE
[Feature] Use pokeminer's db.sqlite for Rare Pokemon Hunting

### ISSUE THREAD

**Issue by Cyberek** [NecronomiconCoding/NecroBot#694]
It would be nice to be able to add a configuration to connect with user generated pokemon locations (pokeminer's db.sqlite) just to hunt for rare or missing pokemons.
It was already implemented in this project:
https://github.com/MonsterMMORPG/Pokemon-Go-Bot.git
but the problem is that the other project uses older version of NecroBot as a base. 
It would be nice to have such functionality in NecroBot itself.

BTW, great work guys.

**Comment by Zubinexu** [comment]
Yep , this would be an awesome idea  to implement.

**Comment by IsBoris** [comment]
Already accepted as a milestone feature
https://github.com/NecronomiconCoding/NecroBot/issues/495
Close the issue please :)
