### ISSUE TITLE
[Bug] [Critical] [IV% not calculated properly]  Not transferring all Pokemons. Debugger screenshots in comments.

### ISSUE THREAD

**Issue by padmanek** [NecronomiconCoding/NecroBot#696]
Using release **[0.1.6](https://github.com/NecronomiconCoding/NecroBot/releases/tag/v0.1.6)**

My most important settings:
"EvolveAllPokemonWithEnoughCandy": true,
"KeepMinCp": 1000,
"KeepMinDuplicatePokemon": 0,
"KeepMinIvPercentage": 90.0,
"KeepPokemonsThatCanEvolve": false,
"PrioritizeIvOverCp": true,
"TransferDuplicatePokemon": true,

My Pokemons:
[POKEMON] [ATK] [DEF] [STA] [CP] [IV]
Eevee 15 15 15 369 100.00%; IV over 90, ok
Weepinbell 14 15 15 127 97.78%; IV over 90, ok
Paras 13 15 15 412 95.56%; IV over 90, ok
Venomoth 14 15 14 535 95.56%; IV over 90, ok
Krabby 14 14 15 469 95.56%; IV over 90, ok
Gloom 13 15 14 324 93.33%; IV over 90, ok
Drowzee 14 13 14 206 91.11%; IV over 90, ok
**Hypno 14 12 14 225 88.89% <- SHOULD BE TRANSFERED**
Golbat 13 11 15 1234 86.67%; CP over 1000, OK
**Eevee 15 9 15 78 86.67%; <- SHOULD BE TRANSFERED**
Hypno 14 10 14 1222 84.44%; CP over 1000, OK
Venomoth 14 6 14 1250 75.56%; CP over 1000, OK
Gloom 13 3 13 1051 64.44%; CP over 1000, OK
Fearow 12 12 4 1074 62.22%; CP over 1000, OK
Tauros 3 2 13 1032 40.00%; CP over 1000, OK
Fearow 11 0 2 1019 28.89%; CP over 1000, OK

As you can see, Hypno and Eevee should be transfered according to settings.
But they are not. Restarted the bot multiple times. Double checked all the settings. Asked for help on discord. Nobody could explain. I've checked manually on Nox, those 2 pokemons are still there. It's not just a display issue.

My full config.json can be found here http://pastebin.com/UcD8uNNd

I'm listening to advices.

**Comment by nfettinger** [comment]
Does the "KeepMinCp" mean that it will keep the duplicate Pokemon that are above that threshold, no matter the other setting to transfer?

**Comment by padmanek** [comment]
@nfettinger Well, wiki answered your question. Please keep this thread clean from questions not directly related to the problem I'm showing above. There's a support chat on [Discord](https://discordapp.com/channels/206065054846681088/207190051703095300) you can ask all the questions you want about the bot and get answers immediately.

**Comment by padmanek** [comment]
Okay, I've downloaded the version used for 0.1.6 release, debugged it and fount the problem.
CalculatePokemonPerfection(PokemonData poke) is incorrectly calculating %IV.
For that 14, 12, 14 Hypno the result it gives is 90.015438033300057 instead of 88.888(8)
For that 15, 12, 15 Eevee the result it gives is 90.1688384227154.
Here's a screenshot from debugger: 
http://i.imgur.com/TAH18MN.png

**Comment by padmanek** [comment]
Function that checks IV perfection is very simple: (atk+def+sta)/45*100% and that's what everyone uses.

**Comment by padmanek** [comment]
I can see that the bot is using a weird formula for perfect IV that weights ATK twice so a  15/9/15 poke suddenly is 90% IV therefore it won't be transferred. All online calcs like poke assistant.com or Pokedexcel show this poke as 86.7%% and that's why I thought it should be transferred.

**Comment by padmanek** [comment]
And because of that I've closed the issue.

**Comment by ShawnHardwick** [comment]
See attached image.

http://i.imgur.com/YPVPGov.png
