### ISSUE TITLE
Feature Request: interface/db for 2D map.

### ISSUE THREAD

**Issue by OverCraftX** [NecronomiconCoding/NecroBot#701]
Im not saying that you could add a 2D map, but I will like to see an interface, dll, or database with all the pokemons and pokestops that the bot see, and the actual position and walking position.

So any other github project will be ready to make a 2D map usefull to connect with that info. Usefull for the people who want to see the bot in action in a 2D map and it will help too to understand the bot movements to create better GPX files and maybe to improve the bot IA.

**Comment by adriendomoison** [comment]
I would love to work on that, any body already on it?

**Comment by 5andr0** [comment]
please use the websocket for gui

**Comment by adriendomoison** [comment]
I am done, I use greatMap :) Can I do a merge request?

**Comment by ThePotato97** [comment]
https://github.com/spikeone83/Pokemon-Go-Bot

**Comment by ShawnHardwick** [comment]
I believe this is a WIP.

**Comment by adriendomoison** [comment]
Okay actually I have the map and it move as the bot move, are we doing quality before all (then I am not ready to merge) or do we just want the feature and we'll upgrade it with time?

**Comment by adriendomoison** [comment]
Would that work?

![pokemap](https://cloud.githubusercontent.com/assets/9092210/17202371/bb13a3ae-544d-11e6-9d6c-775b7329cf40.PNG)

**Comment by adriendomoison** [comment]
I went directly for the interface in it, idk if it is helpful lol

![pokemap](https://cloud.githubusercontent.com/assets/9092210/17202871/cc0ecc58-5450-11e6-845d-330dbcef18f5.PNG)
