### ISSUE TITLE
Pokemon Inventory Full & Wrong Window-Title "Item Recyled"

### ISSUE THREAD

**Issue by FreddyLIE** [NecronomiconCoding/NecroBot#702]
**Pokemons not getting Transfered**

After 30min runtime only 1 Pokemon get Transfered.

I logged in on Andriod and Transfered my Self.
After another 20min Runtime only ~15 got Transfered.
And poke Inventory is Full again.

**Console is Spamming:**
(ATTENTION) Encounter problem: PokemonInventoryFull

(See Sreenshot)

---
**Window-Title: Items Recycled - Calculating wrong**

The Console Window-Title "Items Recycled" is Calculating wrong.
In 2 min about 20 Items getting recycled.
But...
After 30min runtime the Console Window-Title only says:
Items Recycled: 35

(See Sreenshot)

---

**My Config:** (in bold the Lines i changed)

"DefaultAltitude": 10.0,
"DefaultLatitude": 52.379189,
"DefaultLongitude": 4.899431,
"DelayBetweenPokemonCatch": 2000,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": false,
"GpxFile": "GPXPath.GPX",
**"KeepMinCp": 1500,**
"KeepMinDuplicatePokemon": 1,
**"KeepMinIvPercentage": 90.0,**
"KeepPokemonsThatCanEvolve": true,
"MaxTravelDistanceInMeters": 1000,
"PrioritizeIvOverCp": true,
"TransferDuplicatePokemon": true,
"UseGpxPathing": false,
"UseLuckyEggsWhileEvolving": false,
"UsePokemonToNotCatchFilter": false,
**"WalkingSpeedInKilometerPerHour": 70.0,**
"AmountOfPokemonToDisplayOnStart": 10,
"RenameAboveIv": false,
"EnableWebSocket": false,
"WebSocketPort": 14561,
[...]

![pokeinventoryfull](https://cloud.githubusercontent.com/assets/611848/17155615/1cc9b49e-5386-11e6-8036-2161f5241adf.jpg)

**Comment by emoisback** [comment]
KeepPokemonsThatCanEvolve make it false

Maybe your pokemon not transfered because your pokemon ready to evolve

**Comment by SwordStroker** [comment]
i'll make a pr now.If your PokemonInventory is full it'll begin to transfer pokemons if TransferDuplicatePokemons is true in settings.

**Comment by Rabelaiss** [comment]
I'm having the same problem of FreddyLIE

**Comment by FreddyLIE** [comment]
@emoisback Thanks.

`"KeepPokemonsThatCanEvolve": false`

**Comment by SwordStroker** [comment]
#705

**Comment by FreddyLIE** [comment]
The "Items Recycled" in the window Title is not the amount of recycled items...
It is the counter how often Items was recycled right?

5x Pokeball
2x Potion
1x Revive
= Items Recycled: 3

Maybe rename or change to the actual amount of items
