### ISSUE TITLE
A good idea.

### ISSUE THREAD

**Issue by Xomux** [NecronomiconCoding/NecroBot#704]
Could you guys implement a favorite system? I mean, if i mark a pokemon as a favorite, the program doesn't transfer him.

**Comment by emoisback** [comment]
If i look at code logic its already exclude your favorite pokemon..

**Comment by nwg5817** [comment]
And can you please respect the hub? [Request] FavoritePokemonTransfer = false?

**Comment by PocketMobsters** [comment]
We already automatically exclude favorited Pokemon.
https://github.com/NecronomiconCoding/NecroBot/blob/master/PoGo.NecroBot.Logic/Inventory.cs#L64-L65
