### ISSUE TITLE
[PROBLEM] FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj : error

### ISSUE THREAD

**Issue by n3o999** [NecronomiconCoding/NecroBot#706]
How to fix this error to startup

"more project not be loaded"

thanks

last version

**Comment by spot88** [comment]
https://github.com/NecronomiconCoding/NecroBot/wiki/Source-Code

**Comment by spot88** [comment]
-- Close this

**Comment by PocketMobsters** [comment]
Thanks @spot88
