### ISSUE TITLE
Enhance recycle items

### ISSUE THREAD

**Issue by nfettinger** [NecronomiconCoding/NecroBot#707]
It would be nice if instead of transferring items based on their per unit limits, you set a limit per type or class. 

For example, I would like to keep 150 balls at most (dont care the type). The logic should recycle the least valuable balls first, then work its way up the chain when the limit is reached. In this case, great balls would only be recycled if there are no more pokeballs to recycle, and there are more than 100 balls in the inventory.

**Comment by starf** [comment]
nice suggestion there, it can replace all the other ball settings
guess it's the same for potions

**Comment by nfettinger** [comment]
I would say it should work the same way for potions. Any idea when this will get implemented, I am not seeing a milestone.
