### ISSUE TITLE
Need help with settings.

### ISSUE THREAD

**Issue by onlylove943** [NecronomiconCoding/NecroBot#708]
What settings should i use if I want to only keep pokemon that >95% IV and Zubat (or Pidgey, etc) that i'll evolve later to maximize the use of lucky egg?

**Comment by FreddyLIE** [comment]
Add them to the Filter "PokemonsNotToTransfer" in the config
(not tested)

**Comment by ShawnHardwick** [comment]
Questions belong on the Discord server under the #settings or #helpme channel.
