### ISSUE TITLE
pm name in config.json

### ISSUE THREAD

**Issue by ericjwg** [NecronomiconCoding/NecroBot#709]
a few pokemon names contain speical char like:
"Farfetch'd",
"Mr. Mime",

if they occur in the json, the program will crash.

or they need to escape?

**Comment by timelf123** [comment]
Have you observed this crash? That is valid JSON:

```
"Farfetch'd"
```

**Comment by FreddyLIE** [comment]
I think they called: Farfetchd & MrMime

**Comment by ericjwg** [comment]
oh.... so no special char like nidoran

**Comment by timelf123** [comment]
Either way, those characters would be escaped with double quotes, and nidoran is called nidoranFemale or something

**Comment by ShawnHardwick** [comment]
Questions belong in Discord server.
