### ISSUE TITLE
Pinsir dont transefed.

### ISSUE THREAD

**Issue by braum123** [NecronomiconCoding/NecroBot#710]
Hey guuys i have alot of pinsirs and they dont get transfered.
What i can do? 
Im sure most of the pinsirs are transfered but i have still about 30 or more.
ty

**Comment by FreddyLIE** [comment]
Can you post your config ?

**Comment by braum123** [comment]
{
  "AuthType": 0,
  "PtcUsername": "username2",
  "PtcPassword": "pw",
  "DefaultLatitude": 40.77278,
  "DefaultLongitude": 	-73.96817,
  "DefaultAltitude": 10.0,
  "KeepMinIvPercentage": 85.0,
  "KeepMinCp": 1000,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "EvolveAllPokemonWithEnoughCandy": false,
  "KeepPokemonsThatCanEvolve": false,
  "TransferDuplicatePokemon": true,
  "DelayBetweenPokemonCatch": 5000,
  "UsePokemonToNotCatchFilter": false,
  "KeepMinDuplicatePokemon": 1,
  "PrioritizeIvOverCp": false,
  "MaxTravelDistanceInMeters": 1000,
  "GpxFile": "GPXFile.GPX",
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAboveIvValue": 95.0
}

**Comment by braum123** [comment]
ahh i see keep min 1000 sry close it xd

**Comment by kn0cturnal** [comment]
@braum123 What did you change the 1000 to? I have multiple tangelas and electrodes and i don't know why. Especially when I specified that i didn't want to keep dupes.

**Comment by FreddyLIE** [comment]
@kn0cturnal 

These are the important settings:

`"KeepPokemonsThatCanEvolve": false`
`"KeepMinCp": 1000`
`"KeepMinIvPercentage": 85.0`
`"KeepMinDuplicatePokemon": 1`

**Comment by ShawnHardwick** [comment]
Questions belong in the Discord server.
