### ISSUE TITLE
It wont transfer low cp pokemons

### ISSUE THREAD

**Issue by PokemonCoOwner** [NecronomiconCoding/NecroBot#713]
the bot wont transfer low cp pokemons and it takes up the inventory

**Comment by fathey** [comment]
change this line in the config:
"KeepPokemonsThatCanEvolve": true,
set it to false

**Comment by zno3** [comment]
maybe your low cp have high iv

**Comment by bastiflew** [comment]
I think you're right, in Inventory.cs :
                        if (amountPossible > amountToSkip) should be if (amountPossible < amountToSkip)

It works without problem with this modification

**Comment by JoshYuen** [comment]
It keeps pokemon that meet your IV requirements or CP requirements. This means if they statisfy either or they are kept. If you really don't want the high IV low CP pokemon then just make the IV requirement something high like 95%.

**Comment by ShawnHardwick** [comment]
https://github.com/NecronomiconCoding/NecroBot/wiki/FAQ/#why-are-some-pokemon-not-being-transferred

Also, follow up in #helpme channel on the Discord server for further questions.
