### ISSUE TITLE
Magikarp & Ekans transfer

### ISSUE THREAD

**Issue by clicknetcafe** [NecronomiconCoding/NecroBot#720]
transfering higher cp
![magi 2](https://cloud.githubusercontent.com/assets/19372226/17158211/4f885bce-53c7-11e6-94f5-fa6482e968cd.png)
![magi 1](https://cloud.githubusercontent.com/assets/19372226/17158210/4f7f174e-53c7-11e6-8c38-5b29b945de83.png)
![ekans](https://cloud.githubusercontent.com/assets/19372226/17158212/4f904924-53c7-11e6-9540-c4f820044800.png)

**Comment by Owinger** [comment]
What's the question?

**Comment by FreddyLIE** [comment]
Mindreading ON; 
His question is:
Why get Pokemon with CP higher then my best CP Pokemon transfered ?

**Comment by FreddyLIE** [comment]
The answer to this is, the Pokemon you have got better IV percentage.

**Comment by clicknetcafe** [comment]
ohh, thanks. I realized that "PrioritizeIvOverCp" is true

**Comment by ShawnHardwick** [comment]
General questions and issues should be asked in the Discord #helpme channel.
