### ISSUE TITLE
(ERROR) Failed to start WebSocketServer on port : 14251

### ISSUE THREAD

**Issue by Cazs03** [NecronomiconCoding/NecroBot#729]

**Comment by BioHazard1999** [comment]
The same [01:41:28] Failed to start WebSocketServer on port : 14251

**Comment by Maiux92** [comment]
If you have downloaded the program from the releases, just download cert.pfx from the "PoGo.NecroBot.CLI" folder in the repository and put it inside your main folder.

**Comment by sensityy** [comment]
@Maiux92 May I ask what the WebSocket does?

**Comment by Maiux92** [comment]
I guess that it's used to receive the response from the TLS connection, but I'm not sure.

**Comment by Maiux92** [comment]
It is used for the user interface. if you go to https://127.0.0.1:14251/ you will see the it. (you must accept the certificate)

**Comment by BekirUzun** [comment]
Bot continues working even if this error happens. Do we really need a WebSocketServer?

**Comment by ShawnHardwick** [comment]
WebSocketServer is the framework for implementing a GUI. Ignore this error.

Also, next time we need more information in the description. This is the third time you've submitted an issue with no details.

**Comment by huhjess** [comment]
hey, I had the same problem. And I downloaded the cert.pfx as suggested above, however It still says Failed to start WebSocketServer on port : 14251. 

does this have to do with the mac I'm using?
