### ISSUE TITLE
MAC OS not coping code to clipboard and not creating config files

### ISSUE THREAD

**Issue by z06jaz** [NecronomiconCoding/NecroBot#731]
Any idea what to do next? It's opening up fine using terminal mono but now I am stuck.

**Comment by z06jaz** [comment]
got the config files working. Just need to figure out the copy code to clip board

**Comment by JoshYuen** [comment]
Just type it out because this is a C# binary and this is a windows native program. I don't think we planned on supporting other OSes.

**Comment by z06jaz** [comment]
I would actually love to type it out but I am unable to figure out where to retrieve the code?

**Comment by JoshYuen** [comment]
Look at the console it should have printed it did it not? If not then I just suggest you get a windows VM to run the app.

**Comment by z06jaz** [comment]
I'm running dual boot. On neither consoles is the code printed on there. I understand you guys only made it for windows, but using mono it's really simple to run if I an figure out this one small problem. I just rather run it on mac OS and not run both OS.

**Comment by MikeLund** [comment]
"Mac is shit", yes very good reason for closing. It's a C# project, so it's not difficult to target Linux/OSX (especially because it's mostly a console app/no platform-specific bullshit).

Anyways, the paths issue was fixed by https://github.com/NecronomiconCoding/NecroBot/pull/864

About the Google code, you will need to use wine instead of mono. Because it is using Clipboard.SetText, which depends on Windows.Forms, which mono doesn't support very well. Afterwards, you can rerun it with mono. Or just keep using wine, because it works fine with wine after the changes above.

**Comment by DaniilSokolyuk** [comment]
For clipboard on mac you can use method like this
` public static void Copy(string textToCopy)
    {
        try
        {
            using (var p = new Process())
            {
                p.StartInfo = new ProcessStartInfo("pbcopy", "-pboard general -Prefer txt");
                p.StartInfo.UseShellExecute = false;
                p.StartInfo.RedirectStandardOutput = false;
                p.StartInfo.RedirectStandardInput = true;
                p.Start();
                p.StandardInput.Write(textToCopy);
                p.StandardInput.Close();
                p.WaitForExit();
            }
        }
        catch (Exception ex)
        {
            Trace.WriteLine(ex.Message);
        }
    }
`

**Comment by MikeLund** [comment]
So replacing a platform-specific method (winforms) with a different platform-specific call (pbcopy).

**Comment by ShawnHardwick** [comment]
If the Devs do notwant support Mono, I agree that at the least the device code should be printed in the console window.

**Comment by timelf123** [comment]
It apparently should be printed, but it is not working on mono

**Comment by GodLesZ** [comment]
Just add a simple output after
https://github.com/NecronomiconCoding/NecroBot/blob/master/PoGo.NecroBot.CLI/Program.cs#L24 :
`Logger.Write($"Usercode: {usercode}", LogLevel.Info);`

Helps..
