### ISSUE TITLE
(ATTENTION) Encounter problem: Lure Pokemon NotAvailable

### ISSUE THREAD

**Issue by Cazs03** [NecronomiconCoding/NecroBot#735]

**Comment by Ilses** [comment]
Missed this one -- it's not a bug. See #746.

**Comment by UntilSunrise** [comment]
I developed the lure feature.

If a pokestop is lured, i can always see which pokemon will spawn next time but the spawn rate has an intervall. If the intervall isnt expired you will get a lure pokemon NotAvailable message.
Sadly we cant know how long this intervall is....

**Comment by ShawnHardwick** [comment]
Added to the FAQ. Closing this.
