### ISSUE TITLE
[Request] command to display inline PokemonAboveIV and KeepMinCp

### ISSUE THREAD

**Issue by Cazs03** [NecronomiconCoding/NecroBot#737]

**Comment by JoshYuen** [comment]
Assuming you set these values why should it be displayed? Just open your settings file.

**Comment by Cazs03** [comment]
This appears when you start the BOT, but what if I want to see if there are new changes in the Pokemons?
Suppose that after 1-2h want to see pokemon new high CP or IV have.
Without removing the bot, and re-start

**Comment by JoshYuen** [comment]
Wait, you mean the highest table? This prints whenever the bot has nothing to print.

**Comment by Cazs03** [comment]
Perhaps I did not explain well.
I look for when running, to ask the bot to show me the table

**Comment by ShawnHardwick** [comment]
This request will be redundant if an GUI is every implemented and you can view it in near-realtime.
