### ISSUE TITLE
[Request] (PKMN) (CatchEscape) in color RED pls

### ISSUE THREAD

**Issue by Cazs03** [NecronomiconCoding/NecroBot#738]

**Comment by rwrwrwrwrw** [comment]
and CatchFlee too maybe?

**Comment by hakkotsu** [comment]
What for? You cant do anything about it. If you need this data just view or parse log file. Something like `cat logfile |grep CatchEscape`

**Comment by Talamar1** [comment]
Because if you see a lot of these, it means you were softbanned and should stop for a while.

**Comment by hakkotsu** [comment]
Maybe you should not exaggerate with settings in a first place? Don't be greedy.

**Comment by ShawnHardwick** [comment]
I believe the devs want to leave red for terminating errors like exceptions. We already get tons of responses about every single yellow and red response people get. I'm sure we dont want to start receiving messages about this.
