### ISSUE TITLE
PokemonDoTransferList

### ISSUE THREAD

**Issue by MarkHuangZ** [NecronomiconCoding/NecroBot#742]
Is that possible to have a PokemonDoTransferList? I turned the KeepPokemonsThatCanEvolve and EvolveAllPokemonWithEnoughCandy to true. It evolves all Pidgeys and other pokemons in Evolvelist; however, the bot left all second stage pokemons in the inventory... So I am thinking whether players need those second stage exp pokemons in their inventory or just transfer them all. If it is possible to have a PokemonDoTransferList, players can add pokemons in the list,  and call TransferDuplicatedPokemonTask. It would be so great to have.

Forgive me my poor grammar...

**Comment by kingchenc** [comment]
+1

**Comment by ShawnHardwick** [comment]
I'm not positive, but I believe that NecroBot should transfer the second stage pokemon as duplicates as long as they are under the CP and IV values.
