### ISSUE TITLE
Software ban new scean

### ISSUE THREAD

**Issue by MarkHuangZ** [NecronomiconCoding/NecroBot#744]
If players got banned, the character went to a new world with nothing. NOTHING. So the bot start to warn console with no usable pokestops. I tried to change Walking speed and MaxRange, it helps a bit but not that much. First time with DelayBetweenPokemonCatch = 2000; got banned in 5 mins. Second time with DelayBetweenPokemonCatch = 5000; in 30 mins(might be evolve too much or transfer too fast. Not sure how server checks). If there are no pokestops should throw an exception.

**Comment by Shroomzie** [comment]
Did you just use a translator because i really don't have a clue what you just said!

**Comment by MarkHuangZ** [comment]
You can think that way. I got software banned... And if player got software banned, the scean they see are different, with nothing in that world.

**Comment by ShawnHardwick** [comment]
Softbans are indicated by being unable to spin pokestops and every Pokemon fleeing. You are seeing a server issue.
