### ISSUE TITLE
[Feature Request] Setting to prioritize XP or Evolves

### ISSUE THREAD

**Issue by Talamar1** [NecronomiconCoding/NecroBot#755]
Have a setting that you toggle between optimize evolves for XP or evolves.  When set to XP, lower cost evolves take priority over higher evolutions (Weedles go first, then Kakunas), when set to Evolves, the higher evolves go first and what is left goes to lower evolves, thus producing more higher level evolves but a slower XP growth.

**Comment by Shroomzie** [comment]
Its somewhat a interesting suggestion/request, however, when it takes 1-2 days to reach level 30 does that even matter?

**Comment by Talamar1** [comment]
I think what it would affect is what pokemon you have when you hit 30, using Evolve first you would have more final evolutions where using XP first would leave you with a lot of possible second tier evolutions and fewer 2rd tier (for those who have 3 evolves).

**Comment by ShawnHardwick** [comment]
I would call this EvolutionPriority with a "high" or "low" value. If set to "high", the higher evolutions take priority when determining evolution order based on the number of candies. Opposite for "low.
