### ISSUE TITLE
[Bug] MultiProfile is not working for auth.json

### ISSUE THREAD

**Issue by sub7even** [NecronomiconCoding/NecroBot#760]
https://github.com/NecronomiconCoding/NecroBot/pull/667#issuecomment-235455250

ProfilePath is not working for auth.json
Only config.json is loaded from CurrentDir<Profile>\Config
The function AuthSettings() still checks for auth.json from CurrentDir\Config (without Profile)

**Comment by 5andr0** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/749

**Comment by sub7even** [comment]
didn't see that - sry
