### ISSUE TITLE
[Error] Login Ptc

### ISSUE THREAD

**Issue by crazykenvn** [NecronomiconCoding/NecroBot#762]
`There is no argument given that corresponds to the required formal parameter 'username' of 'Login.DoPtcLogin(string, string)'	
PoGo.NecroBot.Logic	
D:\WebOutSource\PokemonGo\trunk\PoGo.NecroBot.Logic\State\LoginState.cs	23`

hey, someone plz check this plz, i can't login with Ptc? tks lots

**Comment by 5andr0** [comment]
Yes plz! pull the latest commit. If that doesn't work, delete your clone and reclone

**Comment by siddmon** [comment]
locally fixed it:
await ctx.Client.Login.DoPtcLogin(ctx.Settings.PtcUsername, ctx.Settings.PtcPassword);

**Comment by crazykenvn** [comment]
i got it, fixed, thanks
