### ISSUE TITLE
Auto Evolve question?

### ISSUE THREAD

**Issue by punkrocker250** [NecronomiconCoding/NecroBot#763]
I suggest adding an option to evolve everything without having to add them all to the list, instead of just whitelisting certain ones to evolve. 

With that, I also suggesting creating a blacklist so that it evolves everything except whatever is in the list, kind of an inverse option.

**Comment by ShawnHardwick** [comment]
Implemented in 0.1.8 with PR #870.

An empty PokemonsToEvolve list evolves all eligible pokemon

**Comment by romanalexander** [comment]
@ShawnHardwick PR #870 does not respect EvolveAllPokemonWithEnoughCandy if the filter is empty. Perhaps an additional setting is necessary to force evolving for XP farming.
