### ISSUE TITLE
[Request] Option to randomize throw accuracy

### ISSUE THREAD

**Issue by Maximum-throwaway** [NecronomiconCoding/NecroBot#764]
9000 perfect throws in a row has to look fishy in analytics if Niantic starts to look.

I've implemented a bit of a hack on my local copy to randomize throw accuracy between "nice" and "perfect" (1.000 and 1.950) as well as turning off curveball, unless it's a high IV, then I let it throw a bullseye.

I'm pretty sure my implementation of it is a hack, so if somebody else more familiar with the accepted programming practices for this project and code base has a proper implementation in mind, go for it.

**Comment by DjKiDD** [comment]
I like this

**Comment by Sasstraliss** [comment]
Seconded

**Comment by BHollowell** [comment]
+1

**Comment by ShawnHardwick** [comment]
Submit your changes as a pull request and a dev will look at it and commit it.
