### ISSUE TITLE
[Bug] candies all showing as {0} on caught pokemon 0.1.7 release

### ISSUE THREAD

**Issue by tj1627** [NecronomiconCoding/NecroBot#765]
Candies still accurately show on transferred pokemon, but show as {0} on the CatchSuccess line.  See screenshot: https://snag.gy/cgpqVK.jpg

This started happening with the 0.1.7 release, was fine with the 0.1.6 release.  Let me know if there are any logs/screenshots/files that I can provide to help.

**Comment by timelf123** [comment]
Reproduced with both account types

**Comment by Shawak** [comment]
This is already fixed in 9ef85f3c13183b21dbcde0c973fe02288cf3348b

**Comment by ShawnHardwick** [comment]
See duplicate #847
