### ISSUE TITLE
Farming without pokestops

### ISSUE THREAD

**Issue by barr0ck** [NecronomiconCoding/NecroBot#766]
Hey there,
I've found a pretty crazy spot in my area I'm unable to farm due the lack of pokestops. I already have an area to farm items with many pokestops, but the pokemons appearing there are not really worth it.
So, I've been thinking about farming first the pokestops area then move to the good pokemons area.
It's that somehow possible? Once you're on that area (it's surrounded by the sea, however it's still mostly land) id like the bot to farm nonstop until it runs out of pokeballs, then just moving back to the pokestops area and repeat.

Any answer will be very appreciated,
Have a nice day and thanks!

**Comment by onlylove943** [comment]
I think you can setup a path. See it in wiki

**Comment by nguyenvanduocit** [comment]
I think you have to make the points's distance more far. To make sure the bot have not to move change to other point to fast.

**Comment by Sekioh** [comment]
I've been trying to do something similar for a different reason. Right now the code looks for pokestops, then wanders toward them one by one catching pokemon on-the-way. But if there's no stops it stands still basically unless pokemon are within that distance.

Personally I'm trying to catch pokemon with better IV and NOT get exp. So I don't want to hit stops unless below X pokeballs so if I have a stockpile, I don't want it to hit any stops. For that, I need to make some randomness for wandering around area while ignoring stops. So I'll consider some random wander-in-range possibility while at it.

But @onlylove943 is correct, you're probably better taking a guess at how long you would have pokeballs and doing a manual gpx point path file, do a line through all the stops and then just do path to the other location and like 20 circles overlapping in the points, so it does the cycle through the area and then end the last point atop the start point, then it will go around the loop again.
