### ISSUE TITLE
Not transfering some Pokemons. Bag is full.

### ISSUE THREAD

**Issue by redongreen** [NecronomiconCoding/NecroBot#767]
I have Min to keep IV to 95% / CP to 2000. My console keeps saying that my bag is full, I log in to my account to see that I have over 30 eevees and 50 magikarp. I dont believe that this is working as intended.

**Comment by Nordiii** [comment]
You probably have enabled KeepPokemonToEvolve

**Comment by FuckItAll** [comment]
https://github.com/NecronomiconCoding/NecroBot/issues/745

**Comment by whalleyboi** [comment]
Can we add a confirm or warning message for the people that dont fully understand the settings..
This setting will continue to cause problems if we dont notify them.

**Comment by whalleyboi** [comment]
Even if we put it under the PokemonInventoryFull add a line saying "KeepPokemonToEvolve set to TRUE can prevent transfers" or something along that line.

**Comment by rayn21dev** [comment]
I think that if your bag is full and you have KeepPokemonsThatCanEvolve set to true, that should trigger an evolve event.  (Unless the expectation is that you will manually do it?)

**Comment by ShawnHardwick** [comment]
Post added to FAQ about this common occurence. Also #870 might help alleviate this.
