### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by punkrocker250** [NecronomiconCoding/NecroBot#771]
Lure Problem? Didnt have this issue in 1.6

Screenshot:
https://i.gyazo.com/5bd2fcc6f1a5c05e87282168815050d5.png

It constantly is going through the console

**Comment by timelf123** [comment]
`[Bug] Encounter problem: Lure Pokemon NotAvailable` should be the title

**Comment by onlylove943** [comment]
#746

**Comment by Ilses** [comment]
I don't think this is an issue -- see my response in #746

**Comment by UntilSunrise** [comment]
I developed the lure feature.

If a pokestop is lured, i can always see which pokemon will spawn next time but the spawn rate has an intervall. If the intervall isnt expired you will get a lure pokemon NotAvailable message.
Sadly we cant know how long this intervall is....

**Comment by ShawnHardwick** [comment]
Added to the FAQ. Closing this.
