### ISSUE TITLE
Is there a better way to run multiple profiles at once?

### ISSUE THREAD

**Issue by KicksDNA** [NecronomiconCoding/NecroBot#777]
I currently run 20 different ptc profiles by duplicating the unzipped file, changing the config auth then running the exe (repeat for each account). There has to be a better way. If, not is there any way to add this.

**Comment by MythHack** [comment]
Yes, but it is unstable, occasionally disappear without exception, transfer pokemon function will fail.

**Comment by KicksDNA** [comment]
@MythHack ok cool...I'll stick to my current process until something more stable is created
