### ISSUE TITLE
Suggest  for duplicated pokemons

### ISSUE THREAD

**Issue by yashine59fr** [NecronomiconCoding/NecroBot#783]
Is it possible to make the bot keep 2 of each pokemon , one of them with highest cp and other with highest IV ?

**Comment by Navyguy330** [comment]
yes it already has that setting it's in .json

**Comment by yashine59fr** [comment]
idk how you can do this

**Comment by reflexx666** [comment]
No not possible. It will keep 2 duplicates and transfer all that do not meet your min IV or min CP (if you got transfer on true). You can not let it keep 1 High IV and 1 High CP and transfer the other high IV and CP.
