### ISSUE TITLE
[Bug]Custom config path failed

### ISSUE THREAD

**Issue by MythHack** [NecronomiconCoding/NecroBot#785]
I use the command line to run"PoGo.NecroBot.CLI.exe config\mythhack"
The following is a directory structure

C:\USERS\test\DESKTOP\NECROBOT-MASTER\POGO.NECROBOT.CLI\BIN\DEBUG\
├─config
│  ├─mythhack
│  │  └─config
│  │      │  auth.json
│  │      │  config.json
│  │      │
│  │      └─translations
│  │              translation.en.json
│  │
│  ├─test2
│  │  └─config
│  │      │  auth.json
│  │      │  config.json
│  │      │
│  │      └─translations
│  │              translation.en.json
│  │
│  └─test3
│      └─config
│          │  auth.json
│          │  config.json
│          │
│          └─translations
│                  translation.en.json

But the command is not performed correctly, because there are no modifications made in the following code
internal class AuthSettings
    {
        public AuthSettings()
        {
            if (File.Exists(Directory.GetCurrentDirectory() 
                + Path.DirectorySeparatorChar +"config"
                + Path.DirectorySeparatorChar + "auth.json")) return;

**Comment by mich3lam** [comment]
All you need to do is PoGo.NecroBot.CLI.exe mythhack oO

**Comment by MythHack** [comment]
@mich3lam 
No matter how kind of program will be to 
Please choose your AuthType
(0) for Google Authentication
(1) for Pokemon Trainer Club

**Comment by MythHack** [comment]
@mich3lam  The program will not go to a custom directory reads the configuration file

**Comment by Ilses** [comment]
Use forward slashes instead of backslashes if you're specifying a path.

**Comment by ShawnHardwick** [comment]
Please close if this fixes your issue.

**Comment by mich3lam** [comment]
@MythHack i dont get it.. what do you want lol
