### ISSUE TITLE
(ATTENTION) Encounter problem: PokemonInventoryFull

### ISSUE THREAD

**Issue by Brayen31** [NecronomiconCoding/NecroBot#786]
I've tried everything and nothing ..

{
  "AutoUpdate": false,
  "TranslationLanguageCode": "en",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 34.009162,
  "DefaultLongitude": -118.497011,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 3,
  "KeepMinIvPercentage": 98.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 1500,
  "PrioritizeIvOverCp": false,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "AmountOfPokemonToDisplayOnStart": 10,
  "RenameAboveIv": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore": [
    "zubat"
  ],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata"
  ]
}

**Comment by MythHack** [comment]
"KeepPokemonsThatCanEvolve": true, 
Try modifying false?

**Comment by yashine59fr** [comment]
it happened to me and i turn off "KeepPokemonsThatCanEvolve"

**Comment by Brayen31** [comment]
[02:40:16] (ATTENTION) Encounter problem: PokemonInventoryFull


It worked only a few hours and happened again

**Comment by Tufky** [comment]
"KeepMinDuplicatePokemon": 3,
Make this 1, if you insist you can make it 2 but it will eventually clog your box.

**Comment by AndroidPhoneix** [comment]
"KeepMinCp": 1200,
  "KeepMinDuplicatePokemon": 1,

and error : Encounter problem: PokemonInventoryFull

try a
  "KeepMinCp": 1600,

and error going, pokemons transfered
