### ISSUE TITLE
[Feature Request] Save/Load Coordinates

### ISSUE THREAD

**Issue by GRINSPANKER13** [NecronomiconCoding/NecroBot#787]
I'd like to put in a request to have your coordinates stored every x meters.
Then have the bot, load those (which should be within your default coordinates and distance.)
That way, if you reopen the bot multiple times, you don't have to worry about teleporting.
I believe the older builds had this feature, maybe it's still active.
When the bot reconnects, does it revert back to your default coordinates?

**Comment by ShawnHardwick** [comment]
The bot used to support dynamic coordinates, but it was removed during hte refactor since it was more painful than useful. Necrobot starts at the default location on startup. Teleporting should not be an issue unless your max distance is set too far.

See #623. Marked as duplicate and closing.

**Comment by GRINSPANKER13** [comment]
#623 is for dumping the coordinates in the log file. It's similar, but not the same.
This is more of implementing current coordinates rather than default coordinates.
