### ISSUE TITLE
[Bug?] AmountOfPokemonToDisplayOnStart doesn't seem to work

### ISSUE THREAD

**Issue by Talamar1** [NecronomiconCoding/NecroBot#794]
On start I only see a list of the top 20 CP and IV pokemons, I set this to 200 to see everything in my inventory and I still only see the top 20.  Is this not what it is for?

**Comment by Syntrace** [comment]
You can see it?
I have searched the list but hopless. (Version: 0.1.6)

**Comment by emoisback** [comment]
Its printed twice...
Just scroll to top...

The second print always print 20 the first print depend on your setting

**Comment by emoisback** [comment]
I hope they write it to file and always updated when bot running.

**Comment by Talamar1** [comment]
It isn't written to the log, which is where I was looking, nor is it in the backscroll in my window.

**Comment by ShawnHardwick** [comment]
I can confirm this didn't work in 0.1.7. Can you see if it works in 0.1.8?

**Comment by Talamar1** [comment]
This is fixed in 0.1.8
