### ISSUE TITLE
config.json and .ini

### ISSUE THREAD

**Issue by srwgin** [NecronomiconCoding/NecroBot#795]
in config.json we can see blew
"ItemRecycleFilter": [],
  "PokemonsToIgnore": [],
  "PokemonsNotToTransfer": [],
  "PokemonsToEvolve": []
is these the same functions as The following files
ConfigItemList.ini
ConfigPokemonsNotToCatch.ini
ConfigPokemonsToKeep.ini
ConfigPokemonsToEvolve.ini

**Comment by MythHack** [comment]
yes
