### ISSUE TITLE
Catch pokemon always with perfect states.

### ISSUE THREAD

**Issue by Syntrace** [NecronomiconCoding/NecroBot#796]
I think its not human like to catch all pokemon with a curve ball and perfect throw. (210 exp)
Is it possible to add a bool flag in the configfile to randomize the catch behaviour?

**Comment by KevinBassaDevelopment** [comment]
Yes pls :)

**Comment by ShawnHardwick** [comment]
Duplicate of #764. Please follow up there, closing this entry.
