### ISSUE TITLE
[Bug] Console Log getting spammed from log-in failing

### ISSUE THREAD

**Issue by DidUknowiPwn** [NecronomiconCoding/NecroBot#797]
Accidentally left the tool running while my internet died and well I got this:
http://i.imgur.com/TROJ6OC.png

http://i.imgur.com/nBFES4m.png

Maybe include a limit of retrying?

**Comment by hirschmann** [comment]
Or maybe just limit the logfile size.
Just configure log4net like this: http://stackoverflow.com/a/641268

**Comment by ShawnHardwick** [comment]
I don't think this is an issue but we can also have others argue that they want the bot to keep retrying until successful (if the internet was down for a short time).
