### ISSUE TITLE
[Feature request] Gym train

### ISSUE THREAD

**Issue by nguyenvanduocit** [NecronomiconCoding/NecroBot#798]
I think Gym attack and Gym train is the good feature. Only that way can help us to farm pokecoin.

Description: 
1. The bot find the best gym to attack or provided by user
2. Attack the gym.
3. Train gym. Auto farm Pokestop if leak of revive

Please vote and help to implement this feature.

**Comment by crazykenvn** [comment]
why do you play pokemongo boy???

**Comment by Anyrainel** [comment]
If it comes out, I can imagine soon there will be many reports to Niantic, and bot accounts die faster.

**Comment by nguyenvanduocit** [comment]
Don't worry about the report, It alway happens. We are here to hack 'em all. Not for fear.

**Comment by starf** [comment]
maintainers have stated this won't be added in and that's a good thing

**Comment by crazykenvn** [comment]
bot do everything, not funny.
