### ISSUE TITLE
Problem ?! Ini kenapa ya ? kok sering muncul?

### ISSUE THREAD

**Issue by grldinside** [NecronomiconCoding/NecroBot#800]
![13872394_10154418488599533_1602558273_n](https://cloud.githubusercontent.com/assets/20676123/17165126/657b69ea-53f8-11e6-9f35-9ec3d257dc1f.png)

Ini kenapa ya ? kok sering muncul ini di ver 1.2
`

**Comment by bulubebek** [comment]
selamat siang,

1. its seems you're not using necrobot. :)
2. ensure your connection is stable

**Comment by reflexx666** [comment]
Not latest version of necrobot.
