### ISSUE TITLE
check pokemons moves for trasnfer

### ISSUE THREAD

**Issue by mich3lam** [NecronomiconCoding/NecroBot#801]
http://pastebin.com/JJHSwBFz

don;t mind the names etc.. the number insde the ( ) are the best moves each pokemon should have.. numbers taken from proto ofc.. hopefully we can implement some logic with these numbers ?

let's say 2 snorlax, same iv, same cp or w/e but 1 of them has better move then trasnfer the other one.. etc

**Comment by reflexx666** [comment]
Make a Pull request please
