### ISSUE TITLE
[QoL Request] Truncate Pokemon CatchSuccess Distance Decimal Places

### ISSUE THREAD

**Issue by basdxz** [NecronomiconCoding/NecroBot#802]
As an example, when I catch a pokemon I get
[06:56:20] (PKMN) (CatchSuccess) | (Normal) Pinsir Lvl: 17 CP: (921/1030) IV: 33.00% | Chance: 21.79% | 98.125055064455m dist | with a PokeBall (21 left). | Candies: {0}
Is it possible to round off everything after the decimal point as it serves no purpose other than to fill the console with junk? On top of that my candies aren't showing but that's besides the point.

**Comment by Brumotti** [comment]
Candy does not show too

**Comment by ShawnHardwick** [comment]
Candy issue can be seen here: #765

Edited the title to reflect the issues better.

**Comment by ShawnHardwick** [comment]
Added in 0.1.8
