### ISSUE TITLE
[Feature Request] Only farm pokestops

### ISSUE THREAD

**Issue by bdmew** [NecronomiconCoding/NecroBot#803]
Is it possible to get the bot to only farm pokestops to replenish our items? I set a path for the bot to walk and I would like it if it can ignore the pokemon. I understand that this would be a low priority issue, but I just wanted to put this out there.

**Comment by XiCynx** [comment]
You can do this already by adding all 151 pokemon to the Do Not Catch List and making sure that list is set to true for the bot to use it.

**Comment by nimaid** [comment]
True, but that's a major hassle. It would be nice to add a switch for just pokestop farming,

**Comment by AileenLumina** [comment]
Maybe we can make three modes like in PokemonGoF's bot; A mode where it focuses solely on pokestops, one where it focuses solely on pokemon, and the default mode. I think this would make a lot of sense.

**Comment by ShawnHardwick** [comment]
I agree. I'll leave this up as a feature request, but in the meantime, go to the FAQ wiki to find out how to implement it with the current release as a workaround.

**Comment by anonemon** [comment]
So nothing new on this?
