### ISSUE TITLE
Catch Dist meters displayed as a floating number

### ISSUE THREAD

**Issue by ArmsAsuncion** [NecronomiconCoding/NecroBot#806]
Do we really need to see what's the exact distance for catch? It's just making the logs longer. And I believe it's not the case for 0.1.6, only the latest 0.1.7.

**Comment by AileenLumina** [comment]
I agree, either round it to maybe two digits after the comma or just use an integer (which really is enough for us in my honest opinion).

**Comment by AileenLumina** [comment]
It was already committed but it didn't make it to the 0.1.7 release: https://github.com/NecronomiconCoding/NecroBot/commit/9ef85f3c13183b21dbcde0c973fe02288cf3348b

**Comment by ShawnHardwick** [comment]
Added in 0.1.8.
