### ISSUE TITLE
[Question] About IV display

### ISSUE THREAD

**Issue by kiz9yup** [NecronomiconCoding/NecroBot#812]
Is it possible to get a list or a full list of all your pokemons IV's/Perfection
sorted by highest to lowest cp?

the newest version doesn't display anything, would be nice with a list on the command prompt or a notepad.

**Comment by srwgin** [comment]
export to excel is better

**Comment by spot88** [comment]
Agreed export to excel.

**Comment by tpauwels** [comment]
Yeah, would also love an export to excel feature.

**Comment by rbnbrls** [comment]
so #829 ?

**Comment by ShawnHardwick** [comment]
There are multiple pull requests that implement this in some fashion but have not been merged for one reason or another. Closing this since it is a duplicate of #638.
