### ISSUE TITLE
Lure pokemon not available

### ISSUE THREAD

**Issue by crixon** [NecronomiconCoding/NecroBot#814]
After a short time i've get a encounter problem: Lure pokemon not available ... from then no lure pokemon was catched anymore..

**Comment by Ilses** [comment]
Duplicate of #771, #746, #735, and not a bug,

**Comment by crixon** [comment]
but why are only the first pokemon catched from lure and after the error shows up only normal pokemon are catched for 2 hours now? :D sorry but i think it's a bug

**Comment by UntilSunrise** [comment]
I developed the lure feature.

If a pokestop is lured, i can always see which pokemon will spawn next time but the spawn rate has an intervall. If the intervall isnt expired you will get a lure pokemon NotAvailable message.
Sadly we cant know how long this intervall is....

**Comment by crixon** [comment]
ah okey but thx for the info! Hopefully it will work sometimes :) maybe there is a way to find out the rate

**Comment by ShawnHardwick** [comment]
Added to the FAQ. Closing this.
