### ISSUE TITLE
[Bug]EvolveAllPokemonAboveIv flag does not work

### ISSUE THREAD

**Issue by bamoida2** [NecronomiconCoding/NecroBot#816]
"EvolveAllPokemonAboveIv": flag does not work, it only evolves Pokemons on the "PokemonsToEvolve": [] list

This is probably why there is many issues reported of Pokemon not evolving, the PokemonsToEvolve list should be used to evolve Pokemon for XP regardless of IV and the EvolveAllPokemonAboveIv should be used to evolve all top tier Pokemon, but right now I have to evolve top tier Pokemon manually and have the "EvolveAboveIvValue" set to 0.1 to evolve Zubats, Pidgeys etc

**Comment by lorenzowalz** [comment]
@bamoida2 What if there were two Evolution lists - the current one (PokemonsToEvolve) but also one based on IV (PokemonsToEvolveAboveIV) or something similar?

Could rename PokemonsToEvolve to be PokemonsToEvolveEXP, etc.

Have to be careful not to split down too many paths or it all becomes convoluted.

**Comment by ShawnHardwick** [comment]
Please check and see if #870 which was implemented in 0.1.8 alleviates this @bamoida2 and @PandaWalz

**Comment by bamoida2** [comment]
The Evolve all above IV seems to work now, but it is still ignoring the PokemonsToEvolve it seems.
It evolved multiple Pokemon over 95% IV but is still not evolving my pidgeys, zubats etc

relvant settings:
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": false,
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,

  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
    "weedle",
    "caterpie",
    "spearow"
  ],
