### ISSUE TITLE
Crash consistanly

### ISSUE THREAD

**Issue by tuningman9790** [NecronomiconCoding/NecroBot#820]
Hello, I tried changing some stuff to the config but it keeps on crashing, does anyone know what's wrong?
{
  "AutoUpdate": false,
  "TranslationLanguageCode": "en",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 52.36202597430918,
  "DefaultLongitude": 4.8854827880859375,
  "DelayBetweenPokemonCatch": 200,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 4000,
  "PrioritizeIvOverCp": true,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "AmountOfPokemonToDisplayOnStart": 20,
  "RenameAboveIv": true,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore":[],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo",
"Growlithe",
"slowpoke"",
"exeggcute",
"lapras",
"eevee"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
	"weedle",
	"Caterpie"
  ]
}

**Comment by Ilses** [comment]
...and what's the actual crash message? This isn't helpful.

**Comment by tuningman9790** [comment]
I can't copy the crash from the CLI, it just says it stopped working

**Comment by tuningman9790** [comment]
Initializing Rocket logger at time 27/07/2016 9:12:31...
Initializing Rocket logger at time 27/07/2016 9:13:34...
Initializing Rocket logger at time 27/07/2016 9:14:14...
Initializing Rocket logger at time 27/07/2016 9:16:09...
Initializing Rocket logger at time 27/07/2016 9:19:13...
Initializing Rocket logger at time 27/07/2016 9:27:54..., 

further then this inst in the logs

**Comment by tuningman9790** [comment]
![image](https://cloud.githubusercontent.com/assets/20615221/17168869/02e842de-53e5-11e6-830d-e28485eb46d0.png)

**Comment by SubstituteCS** [comment]
You have invalid JSON, check it here:  
http://jsonlint.com/  
Here is your config fixed
http://pastebin.com/raw/VT92yR9U

**Comment by SubstituteCS** [comment]
@tuningman9790 please close the issue if it's been resolved.
