### ISSUE TITLE
[Feature] Add a delay between pokemons Transfer.

### ISSUE THREAD

**Issue by Cyberek** [NecronomiconCoding/NecroBot#826]
It seems that currently few pokemons can be transferred in same second. 
I think it would be better to be able to set a value of delay not only for pokemon catching but also for pokemon releasing (or actually maybe one delay between any action, so for example after a pokemon is caught, wait 5 seconds, release a pokemone, wait 5 seconds, farm pokestop, wait 5 seconds, catch a pokemon etc).

**Comment by lorenzowalz** [comment]
@Cyberek You could write a delay function similar to what you're asking and throw it into the logic for transferring. Give it a shot and if you get it to work do a PR!

**Comment by Cyberek** [comment]
@PandaWalz I will try to do it as soon as the servers will be back online.

**Comment by ShawnHardwick** [comment]
If you do this, make sure you have the default behavior mimic the current behavior.

**Comment by Cyberek** [comment]
To be honest, I'm pretty new to C# coding, I got stuck on providing my new:
```
Utils/DelayingUtil.cs
```
to be available in
```
CatchPokemonTasks.cs
```
with use of:
```
DelayingUtils(ctx.LogicSettings.DelayBetweenPlayerActions, 2000);
```
(its commented out there). It seems it is not visible as other Utils elements (when I type Utils, it doesnt show in autocomplete same way as LocationUtils, JitterUtils, PoGoUtils and StrinUtils shows)

If you can point me into the right dirrection, I would be able to repalce all current "duplicated" delays with this utility function.

https://github.com/Cyberek/NecroBot/commit/4cc276cc5d2d331d87af74b0e4141b36a98c6555

**Comment by z06jaz** [comment]
Also instead of a constant 5 seconds everytime maybe you can do a random number between 4 and 7 seconds.

**Comment by Cyberek** [comment]
The randomization is there, it uses 30% of provided "delay" value:
https://github.com/Cyberek/NecroBot/commit/d7d4db297aceb5b14b789c12224aa8e4749c07d3
@PandaWalz, @ShawnHardwick, do you want to check this implementation, or should I do a PR and we will review the code there?

**Comment by Cyberek** [comment]
I have added PullRequest for this feature.
@PandaWalz, @ShawnHardwick you can verify it and accept it.

**Comment by PandaWalz** [comment]
I can't accept but I can verify that it is valid this afternoon. 

Either way I would suggest a PR.
