### ISSUE TITLE
[REQUEST]  Random Offset for 1) Wait Times  2) Langitude/Latitude  3) Starting Position

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [NecronomiconCoding/NecroBot#827]
It would be really nice to have the option for a random offset to be more non-computer like.

1) Time Delays:  +-20%  (or any other number)

2) Langitude/Latitude while walking:  +-0.0005 (or maybe even bigger while not at the final destination)

3) Starting Position: Maybe a random start position +-300 Meter (= +-0.01 long/lat) so that the shortest path is always different

These things would be really nice features :)

**Comment by KevinBassaDevelopment** [comment]
4) as someone else already mentioned: random pokeball throw "perfectness" -> do not always throw a perfect ball

**Comment by VanStorm** [comment]
Awesome ideas for improving the bot! Could make detection much more complicated.

**Comment by Valmere** [comment]
None of this matters until proper device spoofing is in place

**Comment by agp89** [comment]
If there is non device spoofing in place atm. Why is it still working :D Wouldn't it be easy for them to block non Android/iOs devices?

**Comment by ShawnHardwick** [comment]
Please see  #808 and #764. Post your randomization ideas there in #808. Closing since it is a duplicate.
