### ISSUE TITLE
[REQUEST] Randomize ball throw parameters

### ISSUE THREAD

**Issue by thekjohn** [NecronomiconCoding/NecroBot#836]
As said in title. I looked around everywhere but didn't find any information about normalizedRecticleSize or normalizedHitPos. hitPokemon should have some chance to be false, and other parameters shouldn't be fixed as well. Throwing perfect balls will result a banhammer very soon.

**Comment by l3uddz** [comment]
Using the bot will result in a banhammer regardless of how it 'throws' balls.

**Comment by ShawnHardwick** [comment]
Please see #808 and #764. Post your randomization ideas there in #808. Closing since it is a duplicate.
