### ISSUE TITLE
[PROBLEM]: transfer not work. POKEMNON INVENTORY FULL

### ISSUE THREAD

**Issue by n3o999** [NecronomiconCoding/NecroBot#838]
I have this problem. zubat not transfer, pinsir not transfer, and some pokemon not transfer, why? i set config to 1450 keepmincp and not transfer pokemon with 200-300, 1354 etc

why? thanks

![cattura](https://cloud.githubusercontent.com/assets/20614870/17170004/779a9f64-53ea-11e6-9c92-070f8da841c8.PNG)

```
{
  "DefaultAltitude": 10.0,
  "DefaultLatitude": -33.86882,
  "DefaultLongitude": 151.2093,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1450,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 1600,
  "PrioritizeIvOverCp": true,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": true,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "AmountOfPokemonToDisplayOnStart": 10,
  "RenameAboveIv": false,
  "EnableWebSocket": false,
  "WebSocketPort": 14561,
  "ItemRecycleFilter": [
  "PokemonsToIgnore": [
    "zubat",
    "pidgey",
    "pinsir",
    "rattata"
  ],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo",
    "pikachu",
    "gyarados",
    "lapras"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata"
  ]
}
```

**Comment by ilu01** [comment]
same problem here too

**Comment by srwgin** [comment]
try  "KeepPokemonsThatCanEvolve": false,

**Comment by starf** [comment]
"KeepPokemonsThatCanEvolve": true
set to false
please close this thread

**Comment by Valmere** [comment]
"EvolveAllPokemonWithEnoughCandy": false,
"KeepPokemonsThatCanEvolve": true,

there's your problem. not that hard

**Comment by n3o999** [comment]
but pinsir is not possible to evolve, why not transfer? 

if I set this to false transfer all evee, bulbasaur ivysaur (i want to evolve but I don't have enough candy)
KeepPokemonsThatCanEvolve: false

thanks

**Comment by StealthyXor** [comment]
If you want to specifically keep certain pokémon, put it in your config.json under "PokemonsNotToTransfer".

**Comment by Aerosyth** [comment]
Pinsir does not evolve, so everyone saying it's the "KeepPokemonsThatCanEvolve" line are wrong. People can be such jerks and be completely wrong at the same time. Puzzles me. 

I don't see how no one has pointed out the "Pokemonstoignore" line. You have both Pinsir and Zubat in that string of code. Take them out and it should transfer them. Let me know if this works.
