### ISSUE TITLE
[PROBLEM] - Can't catch pokemons

### ISSUE THREAD

**Issue by lolpop25** [NecronomiconCoding/NecroBot#839]
Downloaded NecroBot, works fine except that every pokemon keeps getting away.
Can't seem to catch anything.
Any suggestions??

**Comment by Valmere** [comment]
You're either out of pokeballs or didn't change your location in the config and got softbanned.

**Comment by spot88** [comment]
Softban, wait 30 min and try again.

**Comment by spot88** [comment]
Read the guide aswell: https://github.com/NecronomiconCoding/NecroBot/wiki
-- Close this.
