### ISSUE TITLE
[REQUEST] Rename all pokemons with their IV.

### ISSUE THREAD

**Issue by Xomux** [NecronomiconCoding/NecroBot#840]
Hi, yesterday i set the PrioritizeIvOverCp to true. Sometimes some pokemons  are so close to be 85% perfect, eg 84,43%.

 And sometimes i would like to see the IV value to know what pokemons should i evolve manually.

**Comment by basdxz** [comment]
Line 24 of the config:  "RenameAboveIv": true,

Already implemented I'm pretty sure, works for me anyway.

**Comment by rbnbrls** [comment]
Works already, _(percentage) is added to the name of the pokemon.

**Comment by Xomux** [comment]
I say All pokemons, not only aboveIV.

**Comment by GamespikeYT** [comment]
then just put bove iv to 0

**Comment by FreddyLIE** [comment]
Need settings like:
KeepMinIvPercentage: 85
RenameToIV: true

Keep all min IV 85, Rename ALL pokemons to see IV.

"remove/change" -> RenameAboveIv

**Comment by jordanlthompson1714** [comment]
so what do we rename "RenameAboveIV" to have all pokemons name with IV. other wise it only renames pokemon with an IV of 85 because of KeepMinlvPercentage: 85.
If you set that to 0 then you can get all pokemons renamed but then the client will no longer transfer pokemon and your box is full.

**Comment by FreddyLIE** [comment]
Yes Change the function of `RenameAboveIV` to `RenameWithIV`
So the rename is no longer bound to the `KeepMinlvPercentage` setting.
