### ISSUE TITLE
[REQUEST] Auto Unbanner (softbans)

### ISSUE THREAD

**Issue by swc-tine** [NecronomiconCoding/NecroBot#841]
Requesting an auto unbanner function to get rid of softbans (aka spin a pokestop until unbanned)
Checked by not catching pokemons and receiving xp at stops.

**Comment by StealthyXor** [comment]
How do you propose people should be unbanned?
Automatically text-message a volunteer to go visit Niantic and ask them to unban you?

**Comment by dark0p** [comment]
i think he means that the bot will detect a soft ban and stop catching pokemons (they run away) and just go for pokestops untill the ban is gone.

**Comment by swc-tine** [comment]
.... you can get unbanned by spinning the pokestop for 40 times in a row. Don't be sarcastic if you don't know anything about this.
There are already bots out there that can do this.

**Comment by StealthyXor** [comment]
Nothing wrong with sarcasm. You can't expect everyone to know weird glitches.
Be more specific in your requests.

**Comment by swc-tine** [comment]
Well I said "(aka spin a pokestop until unbanned)"
I thought this was common knowledge amongst botters by now

**Comment by StealthyXor** [comment]
Just seemed like a way to pass time while banned.

**Comment by swc-tine** [comment]
hehe, Well it works, confirmed. so it could be useful to implement.

**Comment by TheBorna** [comment]
#840

**Comment by TheBorna** [comment]
Simple fix, can be improved in future #850

**Comment by ShawnHardwick** [comment]
Implemented in 0.1.8 I believe
