### ISSUE TITLE
config.json  and web socket

### ISSUE THREAD

**Issue by oho911** [NecronomiconCoding/NecroBot#842]
ijust find this code on config.json after execute .exe fie `

> AutoUpdate": false,
>   "TranslationLanguageCode": "en",
>   "DefaultAltitude": 10.0,
>   "DefaultLatitude": 52.379189,
>   "DefaultLongitude": 4.899431,
>   "DelayBetweenPokemonCatch": 800,
>   "EvolveAboveIvValue": 75.0,
>   "EvolveAllPokemonAboveIv": true,
>   "EvolveAllPokemonWithEnoughCandy": false,
>   "GpxFile": "GPXPath.GPX",
>   "KeepMinCp": 1500,
>   "KeepMinDuplicatePokemon": 1,
>   "KeepMinIvPercentage": 85.0,
>   "KeepPokemonsThatCanEvolve": true,
>   "MaxTravelDistanceInMeters": 100000,
>   "PrioritizeIvOverCp": false,
>   "TransferDuplicatePokemon": true,
>   "UseGpxPathing": false,
>   "UseLuckyEggsWhileEvolving": false,
>   "UsePokemonToNotCatchFilter": false,
>   "WalkingSpeedInKilometerPerHour": 50.0,
>   "AmountOfPokemonToDisplayOnStart": 10,
>   "RenameAboveIv": false,
>   "WebSocketPort": 14251,
>   "ItemRecycleFilter": 

`

based on https://github.com/NecronomiconCoding/NecroBot/wiki/Config
 i can find in my config i can't find UseEggIncubators
and how to use websocket ?

just type localhost:14251 on my web browser ? but it doesnt work on me

**Comment by GamespikeYT** [comment]
eggs are not yet in de newest release since they are not working fully properly yet, websocket i do't know, was trying to figure it out myself but haven't been able to use it

**Comment by agp89** [comment]
Probably has something to do with the Web UI they are developing.
I'd love some more info on that...

**Comment by StealthyXor** [comment]
Websocket is a work in progress for a GUI.
It does not handle requests at this time, only listen on the port.

**Comment by ShawnHardwick** [comment]
Common questions belong on the Discord server. Closing this entry.
