### ISSUE TITLE
PokemonsNotToTransfer 

### ISSUE THREAD

**Issue by crixon** [NecronomiconCoding/NecroBot#843]
public ICollection<PokemonId> PokemonsNotToTransfer => _settings.PokemonsNotToTransfer;

Where is the option to use this? I dont want to tranfer all pokemon? 

There is no option to set it to false or true

**Comment by StealthyXor** [comment]
In /Config/config.json ... 

This is not a support section. 
Find references, walk through the code, learn it.

**Comment by crixon** [comment]
Thanks!
