### ISSUE TITLE
cannot transfer low cp pokemon

### ISSUE THREAD

**Issue by hughyuen** [NecronomiconCoding/NecroBot#845]
"AutoUpdate": false,
  "TranslationLanguageCode": "en",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 20.331001,
  "DefaultLongitude": 113.153353,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 900,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 99.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000,
  "PrioritizeIvOverCp": false,
  "TransferDuplicatePokemon": false,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": true,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "AmountOfPokemonToDisplayOnStart": 5,
  "RenameAboveIv": false,
  "WebSocketPort": 14251,

please help!

**Comment by bulubebek** [comment]
set TransferDuplicatePokemon to true. 
please read wiki before you ask, its already documented on wiki.
