### ISSUE TITLE
Cannot start bot

### ISSUE THREAD

**Issue by esreveReverse** [NecronomiconCoding/NecroBot#846]
When I open it, it continuously spams red text
http://puu.sh/qg5VG

**Comment by ziffan** [comment]
you should check config...

**Comment by esreveReverse** [comment]
I have but i couldnt find anything wrong with it 
{
  "AutoUpdate": false,
  "TranslationLanguageCode": "en",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 35.716273,
  "DefaultLongitude": 139.77446,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "KeepMinCp": 1500,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 1000,
  "PrioritizeIvOverCp": false,
  "TransferDuplicatePokemon": true,
  "UseGpxPathing": false,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 17.0,
  "AmountOfPokemonToDisplayOnStart": 10,
  "RenameAboveIv": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 20
    },
    {
      "Key": "itemGreatBall",
      "Value": 20
    },
    {
      "Key": "itemUltraBall",
      "Value": 60
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 0
    },
    {
      "Key": "itemMaxPotion",
      "Value": 0
    },
    {
      "Key": "itemRevive",
      "Value": 0
    },
    {
      "Key": "itemMaxRevive",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 0
    },
    {
      "Key": "itemXDefense",
      "Value": 0
    },
    {
      "Key": "itemXMiracle",
      "Value": 0
    },
    {
      "Key": "itemRazzBerry",
      "Value": 20
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsToIgnore": [],
  "PokemonsNotToTransfer": [
    "dragonite",
    "charizard",
    "zapdos",
    "snorlax",
    "alakazam",
    "mew",
    "mewtwo",
    "kangaskhan",
    "tauros"
  ],
  "PokemonsToEvolve": []
}

**Comment by ziffan** [comment]
try to use this:

{
"AutoUpdate": false,
"TranslationLanguageCode": "en",
"DefaultAltitude": 10.0,
"DefaultLatitude": 35.716273,
"DefaultLongitude": 139.77446,
"DelayBetweenPokemonCatch": 2000,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": false,
"GpxFile": "GPXPath.GPX",
"KeepMinCp": 1500,
"KeepMinDuplicatePokemon": 1,
"KeepMinIvPercentage": 85.0,
"KeepPokemonsThatCanEvolve": true,
"MaxTravelDistanceInMeters": 1000,
"PrioritizeIvOverCp": false,
"TransferDuplicatePokemon": true,
"UseGpxPathing": false,
"UseLuckyEggsWhileEvolving": false,
"UsePokemonToNotCatchFilter": false,
"WalkingSpeedInKilometerPerHour": 17.0,
"AmountOfPokemonToDisplayOnStart": 10,
"RenameAboveIv": false,
"WebSocketPort": 14251,
"ItemRecycleFilter": [
{
"Key": "itemUnknown",
"Value": 0
},
{
"Key": "itemPokeBall",
"Value": 20
},
{
"Key": "itemGreatBall",
"Value": 20
},
{
"Key": "itemUltraBall",
"Value": 60
},
{
"Key": "itemMasterBall",
"Value": 100
},
{
"Key": "itemPotion",
"Value": 0
},
{
"Key": "itemSuperPotion",
"Value": 0
},
{
"Key": "itemHyperPotion",
"Value": 0
},
{
"Key": "itemMaxPotion",
"Value": 0
},
{
"Key": "itemRevive",
"Value": 0
},
{
"Key": "itemMaxRevive",
"Value": 0
},
{
"Key": "itemLuckyEgg",
"Value": 200
},
{
"Key": "itemIncenseOrdinary",
"Value": 100
},
{
"Key": "itemIncenseSpicy",
"Value": 100
},
{
"Key": "itemIncenseCool",
"Value": 100
},
{
"Key": "itemIncenseFloral",
"Value": 100
},
{
"Key": "itemTroyDisk",
"Value": 100
},
{
"Key": "itemXAttack",
"Value": 0
},
{
"Key": "itemXDefense",
"Value": 0
},
{
"Key": "itemXMiracle",
"Value": 0
},
{
"Key": "itemRazzBerry",
"Value": 20
},
{
"Key": "itemBlukBerry",
"Value": 10
},
{
"Key": "itemNanabBerry",
"Value": 10
},
{
"Key": "itemWeparBerry",
"Value": 30
},
{
"Key": "itemPinapBerry",
"Value": 30
},
{
"Key": "itemSpecialCamera",
"Value": 100
},
{
"Key": "itemIncubatorBasicUnlimited",
"Value": 100
},
{
"Key": "itemIncubatorBasic",
"Value": 100
},
{
"Key": "itemPokemonStorageUpgrade",
"Value": 100
},
{
"Key": "itemItemStorageUpgrade",
"Value": 100
}
],
"PokemonsToIgnore": 
[""],
"PokemonsNotToTransfer": [
"dragonite",
"charizard",
"zapdos",
"snorlax",
"alakazam",
"mew",
"mewtwo",
"kangaskhan",
"tauros"
],
"PokemonsToEvolve": [""]
}

**Comment by esreveReverse** [comment]
now it has this error http://puu.sh/qg6YJ

**Comment by Welshpride** [comment]
Check your Auth.json

**Comment by esreveReverse** [comment]
I cant even get to the point of authing my google account because of it crashing

**Comment by Welshpride** [comment]
@esreveReverse  

"PokemonsToIgnore": 
[""],

"PokemonsToIgnore": 
[],

**Comment by esreveReverse** [comment]
Hey there we go, thanks so much for your help

**Comment by Welshpride** [comment]
please close ticket =)
