### ISSUE TITLE
(CatchedSuccess) - Candies: {0}

### ISSUE THREAD

**Issue by PokeG** [NecronomiconCoding/NecroBot#847]
Every time it catches a pokemon the Candies-Counter shown {0}.
Only if the pokemon is transfered it will show the correct counter.

[12:02:53] (CatchSuccess) | (Normal) Drowzee Lvl: 12 CP: (333/368) IV: 56,00% | Chance: 43,22% | 92,1615052940171m dist | with a GreatBall (31 left). | Candies: {0}

**Comment by bulubebek** [comment]
already reported, I believe it will be fixed soon.

**Comment by stribor14** [comment]
This happens only in release. I compiled code myself and number shows correctly.

**Comment by ShawnHardwick** [comment]
See #765. Marking as duplicate and closing.
