### ISSUE TITLE
[BUG] GetPokemons() doesn't return the right count of pokemon

### ISSUE THREAD

**Issue by bastiflew** [NecronomiconCoding/NecroBot#851]
in Inventory.cs 
`var myPokemon = await GetPokemons();` return only 168 pokemons, but I have 176 pokemons in my pokemon inventory.

**Comment by starf** [comment]
probably because favorited are not returned because you don't want them removed etc...
please close

**Comment by bastiflew** [comment]
I read the code, GetPokemons() call GetInventory without any filter
