### ISSUE TITLE
[Request] Randomize walking Speed

### ISSUE THREAD

**Issue by Sylencer90** [NecronomiconCoding/NecroBot#857]
Since they might track the walking speed why don't we add a feature to randomize the walking speed?
Like custom range :  X - X km/h to not constantly run 50 or even more.

**Comment by cawk** [comment]
i quite like this idea ill work on it now

**Comment by SweetCherry** [comment]
Yes please randomize #WalkingSpeedInKilometerPerHour and #DelayBetweenPokemonCatch

This would help alot to keep the account safe

**Comment by fwlemos** [comment]
+1

**Comment by ShawnHardwick** [comment]
Please see #808 Post your randomization ideas there. Closing since it is a duplicate.
