### ISSUE TITLE
[BUG?]

### ISSUE THREAD

**Issue by barandeniz** [NecronomiconCoding/NecroBot#859]
`"EvolveAllPokemonWithEnoughCandy": true` doesn't work. I have lots of envolveable pokemons but it doesnt envolve them. Do i have to add all pokemon names one by one to `"PokemonsToEvolve":` section in order to envolce all of them?

**Comment by crixon** [comment]
yes the list is also not working!

**Comment by ShawnHardwick** [comment]
Read the FAQ wiki. If you have further questions, join the Discord server #helpme channel.

https://github.com/NecronomiconCoding/NecroBot/wiki/FAQ/#why-are-some-pokemon-not-being-transferred

https://github.com/NecronomiconCoding/NecroBot/wiki/FAQ/#i-have-so-many-candies-for-one-pokemon-and-i-want-to-use-them-for-experience-farming-how-do-i-do-that
