### ISSUE TITLE
[Request] Options to chose what bot needs to do

### ISSUE THREAD

**Issue by giesti** [NecronomiconCoding/NecroBot#860]
I would like to focus on hatching eggs instead of catching pokemon/pokestops with an GPX track.

- Catch pokemon -> yes/no
- Spin pokestop always -> yes/no
  If no --> only spin nearby pokestops, if no more eggs

**Comment by SweetCherry** [comment]
+1

The best way to to accomplish this would be to build a seperate *.exe just for setting up the configs. With option descriptions and so.

**Comment by ShawnHardwick** [comment]
Duplicate of #803. Closing this entry.
