### ISSUE TITLE
[+] Run multiple accounts with same config without duplicating files/running a new exe

### ISSUE THREAD

**Issue by KicksDNA** [NecronomiconCoding/NecroBot#862]
Is there any way to run 20 different ptc accounts at once besides duplicating the unzipped file, renaming it, and changing config auth for each different account?

**Comment by cawk** [comment]
would you want the settings the same on each bot i suppose i could make it so you have to login via the bot so it doesnt rely on the auth.config?

**Comment by KicksDNA** [comment]
@cawk yes same settings for each just different logins...currently I have 20 exe files duplicated and running...I'd rather just have one running with multiple accounts

**Comment by cawk** [comment]
oh sorry i misunderstood this is a good idea but would take some time so personally i wont try to code this but maybe someone who has some spare time might

**Comment by Shroomzie** [comment]
Something like batch files will do the trick?

**Comment by KicksDNA** [comment]
@cawk ya it'll definitely be a major update...hoping it comes soon

**Comment by Shroomzie** [comment]
oh, you want one bot running 20 different accounts. Geeze, i don't think so mate. python maybe.

**Comment by cawk** [comment]
It is possible but you would have to spend some time on it, it wouldnt be a simple tweak

**Comment by Shroomzie** [comment]
Yeah something like node.

**Comment by rpdiss** [comment]
@KicksDNA What if one process will make exception that kills program?

**Comment by hirschmann** [comment]
I think it is a stupid idea to let one process handle multiple sessions.
It is already possible to create different profiles, so you don't have to copy the whole folder anyway.

If you want the same config for every instance, just hardlink _config.json_ into every profile.
If you don't want to do it manually, just write a small script which does the work for you.

**Comment by atemerino** [comment]
@hirschmann Then how can we create multiple profiles and run them as well?

**Comment by hirschmann** [comment]
Start the bot with a specific profile: `PoGo.NecroBot.CLI.exe <profileName>`
If the profile does not exist, a new profile will be created.
