### ISSUE TITLE
PokemonsToEvolve

### ISSUE THREAD

**Issue by crixon** [NecronomiconCoding/NecroBot#863]
i want to envolve the pokemon which i paste into the "PokemonsToEvolve" list but it doesn't envolve! and yes i have enough candies and pokemon from the list

**Comment by rbnbrls** [comment]
"EvolveAllPokemonWithEnoughCandy": true, in settings?

**Comment by crixon** [comment]
i want not envolve all pokemon just the pokemon i've put into the "PokemonsToEvolve" list. Otherwise the name of envolve"ALL"Pokemonwithenoughcandy is not a good match in my opinion

**Comment by barandeniz** [comment]
afaik, envolve"ALL"Pokemonwithenoughcandy doesn't work at all.

**Comment by proesd** [comment]
try to change you EvolveAboveIvValue to lower than 95 ..

**Comment by crixon** [comment]
then it would be great to rename the envolve**ALL**Pokemonwithenoughcandy to envolve**LIST**Pokemonwithenoughcandy

**Comment by zno3** [comment]
#676 sort of like this?

**Comment by proesd** [comment]
update : confirmed, I can't evolve 
the only success evolve : [19:42:03] Pidgey successfully for 500xp is when i set EvolveAllPokemonWithEnoughCandy to true, after this never evolving.

**Comment by zno3** [comment]
since the bot prioritizing and checking transfer first everytime, evolving seems happen only at start

**Comment by crixon** [comment]
maybe someone would fix this?

**Comment by ShawnHardwick** [comment]
https://github.com/NecronomiconCoding/NecroBot/wiki/FAQ#i-have-so-many-candies-for-one-pokemon-and-i-want-to-use-them-for-experience-farming-how-do-i-do-that
