### ISSUE TITLE
[Request] IV Rename tool

### ISSUE THREAD

**Issue by kaardilugeja** [NecronomiconCoding/NecroBot#869]
Easy to use tool for automatically renaming your pokemon with their IV.

If set to true rename your pokemon to:
Name (IV) eg. Vaporeon (98.2)

**Comment by blidrosia** [comment]
Nice idea. I think it should be.

**Comment by rbnbrls** [comment]
already in the bot, see  "RenameAboveIv": true,

**Comment by kaardilugeja** [comment]
@rbnbrls True. My bad. What does it rename the pokemon to ? Name and IV or ? It doesn't really say in Wiki.

> RenameAboveIv
>
>When RenameAboveIv is set to TRUE, any Pokemon above the value in KeepMinIvPercentage is renamed.

**Comment by rbnbrls** [comment]
name followed by: _IV

**Comment by Deviantv** [comment]
Name_IV

**Comment by kaardilugeja** [comment]
Thanks. Gonna close this.

**Comment by kaardilugeja** [comment]
Ok, I can. :)

**Comment by kaardilugeja** [comment]
Looks like this feature does not work. I just tested this and nothing happened. Gonna re-open.

**Comment by rbnbrls** [comment]
seems a "RenameAboveIvValue" is missing in the config, like:   "EvolveAboveIvValue": 99.0,
Could be   "EvolveAboveIvValue": or   "KeepMinIvPercentage":  now, not clear.

**Comment by kaardilugeja** [comment]
Does it rename all the pokemons you currently own or just the new ones you gonna catch?
I'll try adding RenameAboveIvValue in the config file.

**Comment by rbnbrls** [comment]
I tested with   "KeepMinIvPercentage": 1.0, It renamed all pokemon, I guess it renames all pokemon above   "KeepMinIvPercentage":

**Comment by kaardilugeja** [comment]
@rbnbrls You are right. It worked when I set "KeepMinIvPercentage" to 1.0
But I think that should not be the case. If "RenameAboveIv" is true then it should rename all pokemons regardless of "KeepMinIvPercentage" value. Was that intended behaviour?

**Comment by rbnbrls** [comment]
@kaardilugeja see newest release:   bool RenameAboveIv { get; } https://github.com/NecronomiconCoding/NecroBot/blob/master/PoGo.NecroBot.Logic/ILogicSettings.cs

**Comment by kaardilugeja** [comment]
Awesome. I just have to wait for new release then. :)
