### ISSUE TITLE
[BUG] Can't find `PoGo.NecroBot.Logic.dll`

### ISSUE THREAD

**Issue by deknarf** [NecronomiconCoding/NecroBot#882]
`Metadata file 'C:\Users\Frank\Documents\_NECROBOT\_LATEST_MASTER\NecroBot-master\PoGo.NecroBot.Logic\bin\Debug\PoGo.NecroBot.Logic.dll' could not be found	`

**Comment by MythHack** [comment]
The type or namespace name 'PokemonMovesCombo' could not be found (are you missing a using directive or an assembly reference?)

**Comment by MythHack** [comment]
Missing this function definition file

**Comment by MythHack** [comment]
Missing this function definition file

**Comment by deknarf** [comment]
I download the .zip from the github (latest version: Merge pull request #879 from mich3lam/patch-3)
I downloaded the API & placed it inside the FeroxRev folder
Ran the .sln pressed CTRL+F5, error.

**Comment by MythHack** [comment]
Yes, I also like this

**Comment by MythHack** [comment]
@deknarf This function is not referenced, it can be a comment

**Comment by MythHack** [comment]
This function is not referenced, it can be a annotate

**Comment by MythHack** [comment]
This function is not referenced, it can be a comments

**Comment by Temaska** [comment]
Looks like that the current version is broken. Lets wait for fixes

**Comment by deknarf** [comment]
I'm waiting, because commenting out something based on something written in poor english (no offense) doesn't sit well with me ^^

**Comment by rayn21dev** [comment]
Yeah I can't build the current version also ... some kind of issue with DoPtcLogin here.
