### ISSUE TITLE
Trasfer all pokemons under IV %

### ISSUE THREAD

**Issue by Massi17** [NecronomiconCoding/NecroBot#886]
it's possible to add this feature?

**Comment by lorenzowalz** [comment]
This should not be asked in the issues section here - check the Discord via the Wiki/ReadMe.

There are a lot of features similar to what you are asking here, you just need to read and figure out what they are.

**Comment by JoshYuen** [comment]
This already exists... Set your KeepMinIV

**Comment by KurtCocain** [comment]
^ this and put IV>CP
