### ISSUE TITLE
Shorten distance lenght

### ISSUE THREAD

**Issue by jsieler** [NecronomiconCoding/NecroBot#888]
Please, make distance a bit shorter, because "3,92050841451134E-05m" looks a bit strange! :D
![1187c51738f8824616e4d13](https://cloud.githubusercontent.com/assets/12472001/17175998/e34238b0-540a-11e6-84c3-724f54934181.png)

**Comment by PureCS** [comment]
It should just round down.

**Comment by GraspGG** [comment]
Distances have been cut down to two decimals (centimeters) with release 0.1.8.

**Comment by ShawnHardwick** [comment]
Duplicate of #802
