### ISSUE TITLE
Remember Window Size and possition

### ISSUE THREAD

**Issue by xyannis** [NecronomiconCoding/NecroBot#890]
Remember Window Size and possition of window please, thanks

**Comment by lorenzowalz** [comment]
Wouldn't this be different per OS? This doesn't seem like a necessary feature, more of a convenience. 

There are programs that can do this, take a look via Google.

**Comment by linkz-db** [comment]
Dragging takes a few seconds. Not necessary / first world problems imo

**Comment by ShawnHardwick** [comment]
I believe this takes little effort to implement so I will keep it open if a dev wants to implement it or someone wants to do a pull request.

See: http://stackoverflow.com/questions/1873658/net-windows-forms-remember-windows-size-and-location

**Comment by PandaWalz** [comment]
@xyannis See the comment above - write the code for it and do a PR, simple.
