### ISSUE TITLE
Adding Pokemon to "Types of Pokemons not to catch"

### ISSUE THREAD

**Issue by Jackman1000** [NecronomiconCoding/NecroBot#891]
I added Pinsir to my Type of Pokemon Not to Catch list but it still does
![pinsir](https://cloud.githubusercontent.com/assets/20683318/17176363/5ca06b90-53da-11e6-9853-4dd4811fdcb2.png)

**Comment by GamespikeYT** [comment]
did you add it in the config?

**Comment by lorenzowalz** [comment]
@Jackman1000 So you edited this file before compiling? Why not just do it via the config file?

**Comment by 036** [comment]
I've got the same issue, I've modified config.json however it will still catch the pokemon under pokemon not to catch.

**Comment by Jackman1000** [comment]
How do I add to config? Which file is it?

**Comment by 036** [comment]
@Jackman1000 if you are using the compiled version you will find it in /config/config.json however this still doesn't work for me.

**Comment by Jackman1000** [comment]
@036 Same. It ignores the rattatas, zubats, and pidgeys, but not the pinsirs

**Comment by 036** [comment]
@Jackman1000 change it in config.js and set the setting to true and it will work.

**Comment by Jackman1000** [comment]
@036  Can't seem to find config.js... I found all the config files for the pokemon names but I dont know how to change it to True other than using the .API file

**Comment by Jackman1000** [comment]
Nvm, I figured it out

**Comment by ShawnHardwick** [comment]
Next time, join the Discord server for faster help.
