### ISSUE TITLE
[Request] Sniper far away Pokemons while botting

### ISSUE THREAD

**Issue by 5andr0** [NecronomiconCoding/NecroBot#893]
It would be cool to sniper pokemons while botting by userinput of coordinates and pokename (websocket ->browser or simple gui input). So it would have to pause bot tasks, teleport to the pokemon, encounter it, teleport back, catch it and resume wherever it was.

Background Info:
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/563391-guide-avoid-softban-while-sniping-pokemons-nox-app.html

**Comment by Resaec** [comment]
dupe #636
