### ISSUE TITLE
Scanning issue?

### ISSUE THREAD

**Issue by BocajisH3R3** [NecronomiconCoding/NecroBot#901]
I've noticed several times that the bot will spam 
"No usable PokeStops found in your area. Is your maximum distance too small?"
When in locations that I have physically been to and know there are stops in the area. Take these coords for eg 
[-32.269792, 115.688758](https://goo.gl/maps/SUye785cy132)
From that location (Start) I monitored the bot and where it went, and it ended up looking like [this](http://puu.sh/qgfVD/dcaa352365.jpg), from the finish it simply went back to where it started and continued on its way.

As you can see from the screen the bot missed a stop just north of the starting position, and further updating the coords to try and include that stop (Start 2 in screen) simply made things worse. In that it would then ONLY visit the Pokestop that wasn't being visited in the first loop. And it was unable to find any of the other stops in the area.

This is just a personal case I've encountered, but I have had contact with people with the same issue and their bot spamming, when in previous versions it was fine with the same location.

**Comment by tw88** [comment]
I have this same issue too. It happens to me after some hours of runtime - in a spot where a lot of pokestops are.
Stopping the bot and starting it again helps. In earlier version i deleted log files etc..

It has to be a bug, becuase i farm the same spot with 5 Accounts at the same time, 1-2 have the error while the others are still farming.

**Comment by agp89** [comment]
@BocajisH3R3 How did you monitor the bot? Or did u do this map manually?

**Comment by BocajisH3R3** [comment]
@agp89 Manually with IngressIntel map and the log from the bot
