### ISSUE TITLE
Evolve issues

### ISSUE THREAD

**Issue by Roooooooooooock** [NecronomiconCoding/NecroBot#905]
Hi there, i'm trying your last release for 4-5 hours now. And it seems it doesn't evolve anything. I choose evolve everything with enough candy section true but doesn't help. I believe there should be a list for "not evolve" and the rest should have pick for evolve somehow. 

About transfering, it works very nice but sometimes it deletes something which i wouldn't. Most of people wants for some kind of option to keep %90+ IV & 1000cp+ pokemons. If you could give us this kind of option there wouldn't be this much complication i guess.

Suggestion: Fast spins unbanning soft bans. You may want to be implement this too. 

Immediately edit: I'm noob. I don't know where this kind of things should have write i don't even have discord account. So please, forgive me.

**Comment by BocajisH3R3** [comment]
All of this is already in the bot

**Comment by ShawnHardwick** [comment]
Join the Discord server for common questions and read the wiki, especially the FAQ page.
