### ISSUE TITLE
【bug】subfile loading error

### ISSUE THREAD

**Issue by MythHack** [NecronomiconCoding/NecroBot#914]
private static void Main(string[] args)
        {
            var subPath = "";
            if (args.Length > 0)
                subPath = Path.DirectorySeparatorChar + args[0];
to
        private static void Main(string[] args)
        {
            var subPath = "";
            if (args.Length > 0)
                subPath =  args[0];
Will work Otherwise it will create a folder in the root directory of the drive letter

**Comment by ShawnHardwick** [comment]
Verify this still exists in 0.1.8 please
