### ISSUE TITLE
Ability to start WebSocket without TLS

### ISSUE THREAD

**Issue by nicoschmitt** [NecronomiconCoding/NecroBot#916]
I've built a GUI that works well with WebSocket, but only if TLS is disabled.  I'm guessing it's a certificate trust issue.
Would be good to be able to start without TLS.

**Comment by AlienHack** [comment]
u could add this 

ServicePointManager.ServerCertificateValidationCallback +=
    (sender, cert, chain, sslPolicyErrors) => true;

at the entry point to make the validation callback always return true

**Comment by xX7** [comment]
Is the websocket callback in the bot connected? Or is it just listening on the port without function?

**Comment by agp89** [comment]
Looks like its broadcasting the events.
@nicoschmitt Would you share your Gui?

**Comment by xX7** [comment]
@agp89 was just about to ask haha.

**Comment by nicoschmitt** [comment]
Hi all. Here is the GUI: https://github.com/nicoschmitt/necrobotvisualizer.
@AlienHack : It's in JavaScript, but I managed to go around it so it should work now.
