### ISSUE TITLE
Current translations implementation won't allow to translate everything

### ISSUE THREAD

**Issue by panthernet** [NecronomiconCoding/NecroBot#919]
Sadly, translations are loaded after the settings and the loading logic for settings implements user prompt for auth setup.  Generally we can get translation setting right after the config file load but it rises the question: where to store translations in this case? GlobalSettings class? It goes right into LogicSettings after that and it is not good to store translations there.

Or may be it will be better to do some step aside and made translations static available throughout the app? This will also solve translation problems with  some API messages displayed in event handler methods, webSockets and statistics info

**Comment by panthernet** [comment]
I can do the changes just need to know the better way from the view of the original devs. Is it ok to cut translations from the current settings and made em static or maybe it is ok to load Translations in GlobalSettings and then move them to Context on context creation?

**Comment by ShawnHardwick** [comment]
Ask your question in #development on the Discord server and come back here with what you find then close the issue.
