### ISSUE TITLE
priority capture pokemon  list rare pokemon

### ISSUE THREAD

**Issue by xMasterSolidx** [NecronomiconCoding/NecroBot#923]
Hello, I would like to add the option priority all capture pokemon in list rare pokemon. ignoring the "PrioritizeIvOverCp": true,

example
"prioritycappokemon": true,

"prioritycappokemonlist": [
"dragonite",
"Snolax",
"Lapras",
"charizard",
"dratini"
],

**Comment by lhzeng888** [comment]
Great! Like this idea.
