### ISSUE TITLE
probem cant use it, anyone can help? pokemonGORocketAPI.console shutting down

### ISSUE THREAD

**Issue by royaal89** [NecronomiconCoding/NecroBot#927]
Unhandled Exception: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'PokemonsNotToTransfer[6]', line 157, position 4.
   ved Newtonsoft.Json.JsonTextReader.ParsePostValue()
   ved Newtonsoft.Json.JsonTextReader.Read()
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   ved Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   ved Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   ved Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   ved PoGo.NecroBot.CLI.GlobalSettings.Load(String path) i C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.CLI\Settings.cs:linje 126
   ved PoGo.NecroBot.CLI.Program.Main(String[] args) i C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.CLI\Program.cs:linje 46

pokemonGORocketAPI.console shutting down

**Comment by royaal89** [comment]
pokemonGORocketAPI.console shutting down

**Comment by antwa** [comment]
something wrong with your config.json

> Unhandled Exception: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'PokemonsNotToTransfer[6]', **line 157, position 4.**
