### ISSUE TITLE
Rereleased 0.1.8 catch lure causing softban detection

### ISSUE THREAD

**Issue by KurtCocain** [NecronomiconCoding/NecroBot#928]
https://i.gyazo.com/1cfb86c9a280f7d04a18fb634b335afb.png

Failed to catch lurepokemon

Clairly not soft banned

This is the 5th time in a row and you can see i looted earlier, and it was doing it before.

**Comment by KurtCocain** [comment]
I left the bot running, it's been 8 minutes now, still trying to unsoftban

**Comment by TheBorna** [comment]
Are you sure it's latest version? Mine is running without issues.
Try to delete all files (excluding config and logs) and download release again and extract it in same directory.

**Comment by KurtCocain** [comment]
Thats exactly what i did from the bad release of 0.1.8, i deleted everything, kept config folder and dumped it in the new 0.1.8

3 accounts working perfect, 3 not working. Actually think they are softbanned now but i dont understand why

**Comment by Ilses** [comment]
Can you post your config?

**Comment by KurtCocain** [comment]
Sorry was afk for a while, 1.9 got it fixed. #close
