### ISSUE TITLE
Transfer not working properly anymore

### ISSUE THREAD

**Issue by GamespikeYT** [NecronomiconCoding/NecroBot#930]

**Comment by rayn21dev** [comment]
Can you provide some details?

**Comment by Lovebucket25** [comment]
I also have this issue.I checked my account and I have like 45 Magikarp, and the bot keeps saying cant catch Pokemon bag full

**Comment by GamespikeYT** [comment]
I have my settings set that if i have a duplicate that has an IV of lower than 99% and lower than 1400cp should be transferred. But after an auto transfer from the program, there are still some weedle's etc

**Comment by GamespikeYT** [comment]
Did you put keeppokemonthatcanevolve = false, because i did, it works fine in the 0.1.7 release but not in the latest version of the code

**Comment by Lovebucket25** [comment]
its default set to that

**Comment by W1nd0x** [comment]
I got the same problem..
