### ISSUE TITLE
No pokestops within radius

### ISSUE THREAD

**Issue by PumbaMelbye** [NecronomiconCoding/NecroBot#931]
The bot tells me that there is no pokestops within my radius. I am using max travel distance of 10 kilometers, and there is a pokestop only a few hundred metres from where the coordinates are set. How do i deal with this?

**Comment by XiCynx** [comment]
I have noticed this in certain regions.  I changed where I was botting and and everything worked fine.  Not sure if it is an issue with the bot or the server getting information in the area.

**Comment by PumbaMelbye** [comment]
tnx, but i used the bot with coordinates just 10 kilometres away from these, and there was no problem.
