### ISSUE TITLE
gyms and pokemon bug

### ISSUE THREAD

**Issue by haldrugo** [NecronomiconCoding/NecroBot#934]
Hi, since I started to use the bot, when I log in to the game every pokemon i try to catch is run after I throw pokeball at him and I cant get into gym battles =[
hope you can find me solution to this, tnx very much=)

**Comment by TheBorna** [comment]
You can't be logged in bot + on phone at the same time, what you could do is to disable location on phone to check new pokemons and stuff but you can't play at the same time when the bot is running.

**Comment by haldrugo** [comment]
Yes I know , when I log in to the app it's only after I exit the bot on my computer.

**Comment by XiCynx** [comment]
The bot is not meant to be able to do gym battle for the sake of the only multiplayer aspect of the game.  This is something that is not going to be implemented in the future either.  This is not a bug either, it is a lack of knowledge on using the bot.  When you log off the bot, you have to wait a considerable amount of time 1 hour before you log back in and try using your phone as the location jump is soft banning you.

**Comment by haldrugo** [comment]
oh tnx a lot about your andswer I didn't know that. so now my account is banned? or I need to wait 1 hour and the app will back to normal functioning?

**Comment by XiCynx** [comment]
Soft Ban is just a temporary ban that can last from 5 minutes to a couple hours.  It will come back and work fine in a little bit.

**Comment by haldrugo** [comment]
Ok. really thank you very much about everything. =)

**Comment by rayn21dev** [comment]
that's a softban because you teleported from your bots location to your phone location.
