### ISSUE TITLE
v0.1.8 evolves all pokemon

### ISSUE THREAD

**Issue by perryhuynh** [NecronomiconCoding/NecroBot#941]
v0.1.8 evolves all pokemon regardless of whether they are specified in `PokemonsToEvolve`

```
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
    "ekans",
    "geodude",
    "caterpie",
    "weedle",
    "sandshrew"
  ],
```

Excerpt from Log:
```
[09:51:12] Cubone successfully for 500xp
[09:51:15] Eevee successfully for 1000xp
[09:51:18] Rhyhorn successfully for 500xp
```

**Comment by sp1ti** [comment]
are they high IV?

**Comment by perryhuynh** [comment]
@sp1ti I set the min IV to evolve at 0 in v0.1.7 and it only evolved the Pokemon specified in the `PokemonsToEvolve` Filter

**Comment by sp1ti** [comment]
there was a commit that changed the logic I believe > always evolve those above your high-IV thing. this because that would actually be what you would expect out of the feature.

**Comment by sp1ti** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/870 that one. Fix your 0 and you're good.

**Comment by perryhuynh** [comment]
I tried disabling evolve high IV and I don't believe it evolved anything at all after that, I will try again and report results
