### ISSUE TITLE
[Request] Pokemon Name translation

### ISSUE THREAD

**Issue by GraspGG** [NecronomiconCoding/NecroBot#948]
Sorry if the following question might have been asked before - I could not find it through reading all topics:

**Question/Request:**
Is there a chance to get the Pokemon names translated on all cient outputs (message window, logs), at least for the languages with latin letter alphabets (fr, de)? Maybe as option to choose in config?

**Examples:**
~ Pokemon (ISO 639-1 language code)
• Mewtwo (en), Mewtwo (fr), Mewto (de), ... (ja), ... (ko), ... (zh)
• Blastoise (en), Tortank (fr), Turtok (de), ... (ja), ... (ko), ... (zh)
• Shellder (en), Kokiyas (fr), Muschas (de), ... (ja), ... (ko), ... (zh)
• Hitmonchan (en), Tygnon (fr), Nockchan (de), ... (ja), ... (ko), ... (zh)
• 146 others

**Backround:**
As far as i know, all Pokemons which are currently included (151, except Pikachu) have different names at the 6 different languages the game offers by now. Therefore players using the french or german (japanese, korean, chinese) app do have to translate all the 150 pokemon names all the time ... which is frustrating and time consuming ... unless they can remember all of them.

I would search and write down a list of translated Pokemon names (fr, de) if that could help or speed up the implementation of such a feature!?

Thanks for either this great project as well as for at least thinking about this request (:

**Comment by BjkGkh** [comment]
I tried something like this for french pokemon:

public static string GetFRPokemonName(int PokemonId)
        {
            switch (PokemonId)
            {                
                case 1:
                    return "Bulbizarre";                
                case 2:
                    return "Herbizarre";
                case 3:
                    return "Florizarre";
                case 4:
                    return "Salamèche";
                case 5:
                    return "Reptincel";
                case 6:
                    return "Dracaufeu";
                case 7:
                    return "Carapuce";
                case 8:
                    return "Carabaffe";
                case 9:
                    return "Tortank";
                case 10:
                    return "Chenipan";
                case 11:
                    return "Chrysacier";
                case 12:
                    return "Papilusion";
                case 13:
                    return "Aspicot";
                case 14:
                    return "Coconfort";
                case 15:
                    return "Dardargnan";
                case 16:
                    return "Roucool";
                case 17:
                    return "Roucoups";
                case 18:
                    return "Roucarnage";
                case 19:
                    return "Rattata";
                case 20:
                    return "Rattatac";
                case 21:
                    return "Piafabec";
                case 22:
                    return "Rapasdepic";
                case 23:
                    return "Abo";
                case 24:
                    return "Arbok";
                case 25:
                    return "Pikachu";
                case 26:
                    return "Raichu";
                case 27:
                    return "Sabelette";
                case 28:
                    return "Sablaireau";
                case 29:
                    return "Nidoran♀";
                case 30:
                    return "Nidorina";
                case 31:
                    return "Nidoqueen";
                case 32:
                    return "Nidoran♂";
                case 33:
                    return "Nidorino";
                case 34:
                    return "Nidoking";
                case 35:
                    return "Mélofée";
                case 36:
                    return "Mélodelfe";
                case 37:
                    return "Goupix";
                case 38:
                    return "Feunard";
                case 39:
                    return "Rondoudou";
                case 40:
                    return "Grodoudou";
                case 41:
                    return "Nosferapti";
                case 42:
                    return "Nosferalto";
                case 43:
                    return "Mystherbe";
                case 44:
                    return "Ortide";
                case 45:
                    return "Rafflesia";
                case 46:
                    return "Paras";
                case 47:
                    return "Parasect";
                case 48:
                    return "Mimitoss";
                case 49:
                    return "Aéromite";
                case 50:
                    return "Taupiqueur";
                case 51:
                    return "Triopikeur";
                case 52:
                    return "Miaouss";
                case 53:
                    return "Persian";
                case 54:
                    return "Psykokwak";
                case 55:
                    return "Akwakwak";
                case 56:
                    return "Férosinge";
                case 57:
                    return "Colossinge";
                case 58:
                    return "Caninos";
                case 59:
                    return "Arcanin";
                case 60:
                    return "Ptitard";
                case 61:
                    return "Têtarte";
                case 62:
                    return "Tartard";
                case 63:
                    return "Abra";
                case 64:
                    return "Kadabra";
                case 65:
                    return "Alakazam";
                case 66:
                    return "Machoc";
                case 67:
                    return "Machopeur";
                case 68:
                    return "Mackogneur";
                case 69:
                    return "Chétiflor";
                case 70:
                    return "Boustiflor";
                case 71:
                    return "Empiflor";
                case 72:
                    return "Tentacool";
                case 73:
                    return "Tentacruel";
                case 74:
                    return "Racaillou";
                case 75:
                    return "Gravalanch";
                case 76:
                    return "Grolem";
                case 77:
                    return "Ponyta";
                case 78:
                    return "Galopa";
                case 79:
                    return "Ramoloss";
                case 80:
                    return "Flagadoss";
                case 81:
                    return "Magnéti";
                case 82:
                    return "Magnéton";
                case 83:
                    return "Canarticho";
                case 84:
                    return "Doduo";
                case 85:
                    return "Dodrio";
                case 86:
                    return "Otaria";
                case 87:
                    return "Lamantine";
                case 88:
                    return "Tadmorv";
                case 89:
                    return "Grotadmorv";
                case 90:
                    return "Kokiyas";
                case 91:
                    return "Crustabri";
                case 92:
                    return "Fantominus";
                case 93:
                    return "Spectrum";
                case 94:
                    return "Ectoplasma";
                case 95:
                    return "Onix";
                case 96:
                    return "Soporifik";
                case 97:
                    return "Hypnomade";
                case 98:
                    return "Krabby";
                case 99:
                    return "Krabboss";
                case 100:
                    return "Voltorbe";
                case 101:
                    return "Electrode";
                case 102:
                    return "Noeunoeuf";
                case 103:
                    return "Noadkoko";
                case 104:
                    return "Osselait";
                case 105:
                    return "Ossatueur";
                case 106:
                    return "Kicklee";
                case 107:
                    return "Tygnon";
                case 108:
                    return "Excelangue";
                case 109:
                    return "Smogo";
                case 110:
                    return "Smogogo";
                case 111:
                    return "Rhinocorne";
                case 112:
                    return "Rhinoféros";
                case 113:
                    return "Leveinard";
                case 114:
                    return "Saquedeneu";
                case 115:
                    return "Kangourex";
                case 116:
                    return "Hypotrempe";
                case 117:
                    return "Hypocéan";
                case 118:
                    return "Poissirène";
                case 119:
                    return "Poissoroy";
                case 120:
                    return "Stari";
                case 121:
                    return "Staross";
                case 122:
                    return "M.Mime";
                case 123:
                    return "Insécateur";
                case 124:
                    return "Lippoutou";
                case 125:
                    return "Elektek";
                case 126:
                    return "Magmar";
                case 127:
                    return "Scarabrute";
                case 128:
                    return "Tauros";
                case 129:
                    return "Magicarpe";
                case 130:
                    return "Léviator";
                case 131:
                    return "Lokhlass";
                case 132:
                    return "Métamorph";
                case 133:
                    return "Évoli";
                case 134:
                    return "Aquali";
                case 135:
                    return "Voltali";
                case 136:
                    return "Pyroli";
                case 137:
                    return "Porygon";
                case 138:
                    return "Amonita";
                case 139:
                    return "Amonistar";
                case 140:
                    return "Kabuto";
                case 141:
                    return "Kabutops";
                case 142:
                    return "Ptéra";
                case 143:
                    return "Ronflex";
                case 144:
                    return "Artikodin";
                case 145:
                    return "Électhor";
                case 146:
                    return "Sulfura";
                case 147:
                    return "Minidraco";
                case 148:
                    return "Draco";
                case 149:
                    return "Drracolosse";
                case 150:
                    return "Mewtwo";
                case 151:
                    return "Mew";

            }
            return "Missingno";
        }
