### ISSUE TITLE
[TYPO] default config -> Eevee -> KeepMinIvPercentage: 800.0

### ISSUE THREAD

**Issue by FreddyLIE** [NecronomiconCoding/NecroBot#949]
**Fresh Compiled Default config.json**

800 Percent min IV ?
Typo ?

"Eevee": {
	"KeepMinCp": 600,
	"KeepMinIvPercentage": 800.0,
	"KeepMinDuplicatePokemon": 2
},

**Comment by sp1ti** [comment]
BYE BYE my horde of high IV evevee's (should have set it to auto evolve regardless)

I even fixed the typo before running. WTF

**Comment by sp1ti** [comment]
made a pull request

https://github.com/NecronomiconCoding/NecroBot/pull/964
