### ISSUE TITLE
Everytime a pokemon caught show "Candies: {0}"

### ISSUE THREAD

**Issue by Khayalan** [NecronomiconCoding/NecroBot#953]
I think the Title says all:
Everytime a pokemon caught show "Candies: {0}"

Please fix

**Comment by FreddyLIE** [comment]
Use diffrent language translation?
Working for me with german translation

**Comment by TheBorna** [comment]
Try to delete config -> translations folder and open the program again.

**Comment by Talamar1** [comment]
This was a bug in 0.1.7, fixed in 0.1.8

**Comment by Khayalan** [comment]
Thanks :)
