### ISSUE TITLE
Error: PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException:

### ISSUE THREAD

**Issue by JankoH8** [NecronomiconCoding/NecroBot#956]
Hi,

I use PTC and when start NecroBot I obtain this:

 [19:00:04] System.AggregateException: Došlo k jedné nebo více chybám. ---> PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException: Byla vyvolána výjimka typu PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException.
   v PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() v D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:řádek 48
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() v D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:řádek 51
   --- Konec trasování zásobníku pro vnitřní výjimku ---
   v System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   v System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   v PoGo.NecroBot.Logic.State.LoginState.Execute(Context ctx, StateMachine machine) v D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:řádek 17
   v PoGo.NecroBot.Logic.State.StateMachine.Start(IState initialState, Context ctx) v D:\Dev\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:řádek 50
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException: Byla vyvolána výjimka typu PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException.
   v PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() v D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\PtcLogin.cs:řádek 48
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__5.MoveNext() v D:\Dev\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:řádek 51<---

**Comment by GraspGG** [comment]
Did you verify the Email you've got after creating the account? (Link within the email)

Log on to the pokemon trainer club website and have the email resend. Then activate through the link within the mail and you should be fine.

**Comment by JankoH8** [comment]
PTC write: Your account has already been activated.

I activated the account when i start play (before one week)
