### ISSUE TITLE
Evolve Bug

### ISSUE THREAD

**Issue by nguyenvanduocit** [NecronomiconCoding/NecroBot#957]
Settings: 
`"EvolveAllPokemonWithEnoughCandy": true,
"UseLuckyEggsMinPokemonAmount": 5,
  "UseLuckyEggsWhileEvolving": true,`

Expected:

If 5 pokemons have enough candy to evolve, use lucky eggs then evolve all of them.

Reality:

It's only work at the first time bot started. then it dont. Restart the bot, it work again.

**Comment by Khayalan** [comment]
Really important please add :)
