### ISSUE TITLE
Feature: Transfer if under IV/CP and not on evolve list

### ISSUE THREAD

**Issue by ibcurly** [NecronomiconCoding/NecroBot#959]

**Comment by bulubebek** [comment]
already implemented, kindly check wiki page, config section.

**Comment by ibcurly** [comment]
Im sorry, I am confused how to make this happen, i have read through the config wiki  many times and I could not find an appropriate setting.

Example:
When using **TransferDuplicatePokemon** that transfers everything and **KeepPokemonsThatCanEvolve** set to true
And only a pidgey is listed under: **"PokemonsToEvolve"**
what setting forces transfers on other pokemon that are not pidgey which are able to be evolved?

the only other list that pertains is **PokemonsToIgnore** but to my understanding that prevents those from being caught in the first place?
