### ISSUE TITLE
Feature Request: Display Pokestop Name

### ISSUE THREAD

**Issue by Pacoboyd** [NecronomiconCoding/NecroBot#962]
This is just a quality of life request, but I would like to see the Pokestop name in the logs.  This also would help when creating / correcting a GPX path.

**Comment by ibcurly** [comment]
A warning about this feature from another pokemon go bot
https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template

# should the bot display information of where it's walking to (true/false)
# this will show the name of the pokestop that it's walking to and
# replace on the loot log the pokestop id for its name
# WARNING:  this will increase the https requests without any need. if
#           the servers are slow it's recommended to turn off this setting

**Comment by Pacoboyd** [comment]
I don't think it needs to show where it's walking, just the name in the Pokestop when it "spins" it.

**Comment by TheBorna** [comment]
Logger message changes as few users requested #1004

**Comment by ibcurly** [comment]
> I don't think it needs to show where it's walking, just the name in the Pokestop when it "spins" it.

> # this will show the name of the pokestop that it's walking to

Which is exactly what it does, and what it is warning about.
