### ISSUE TITLE
Always use lucky egg

### ISSUE THREAD

**Issue by bigal1542** [NecronomiconCoding/NecroBot#968]
I can't seem to find any way to add the ability to use a lucky egg constantly.  I tried searching and messing with the "UseLuckyEggsMinPokemonAmount": with no luck.

It would be great to have just so that it racks up experience twice as fast.

**Comment by emoisback** [comment]
there is no function to use lucky eggs every 30 minutes..
the function just use lucky eggs when you have pokemon to evolve.

you can make UseLuckyEggsWhileEvolving : true
and UseLuckyEggsMinPokemonAmount : 1

even you put 0 on it, its still check did you have pokemon that can be evolve or not, if you have bot will use luckyeggs and evolve your pokemon but if you havent bot will not use lucky eggs..


there is no function for use lucky egg constantly every 30 minutes..
hope they will make it.

**Comment by bigal1542** [comment]
Okay yeah, that's kinda what I was using and I guess it works the same in the long run.

Thanks!

**Comment by cawk** [comment]
Will do this now so it will be every 30 minutes a new egg is used (aslong as you have one)

**Comment by emoisback** [comment]
cawk can you make fir incense too...

similiar just depending itemid

**Comment by cawk** [comment]
Look at my pull request and just do the same but for incense instead
