### ISSUE TITLE
Incubate only happens on startup.

### ISSUE THREAD

**Issue by ArmsAsuncion** [NecronomiconCoding/NecroBot#976]
Egg Incubate and status display only happens on app startup/login.

**Comment by Antyantifa** [comment]
True. It will be nice if we will get info what pokemon we get from egg.

**Comment by Gawdor** [comment]
I'm running 0.1.9 which includes the #907 branch, but it doesn't appear to be working. I'm running a GPX through Central Park and 2km eggs at 18km/h so the eggs should be hatching every 7mins roughly though nothing is appearing in the logs (or on screen). I have to stop/start the bot before eggs are processed.
