### ISSUE TITLE
[Please] fix evolving! 

### ISSUE THREAD

**Issue by Rawrlex** [NecronomiconCoding/NecroBot#977]
Please do a feature where it checks if enough candy is there for evolving and then evolves before transfering. That would be nice since KeepPokemonsThatCanEvolve and EvolveWhenEnoughCandy is not working great together. It still transfers the pokémon on the pokémons to evolve list.

**Comment by Rawrlex** [comment]
It only is doing it after a restart..

**Comment by emoisback** [comment]
KeepPokemonsThatCanEvolve :true

 "PokemonsToEvolve": [
    "pidgey",
     "pidgeoto"
  ],

"PokemonsNotToTransfer": [
      "pidgey",
     "pidgeoto"
]


with that setting will help you to keep pidgey and pidgeoto, and will evolve when it hit the function..after pidgeoto turn into PIDGEOT it will be transfered..

there is no function to evolving before transfering..
if its hit transfering before evolve then bot will transfer your pokemon.
so to keep your pokemon evolve and transfered when your pokemon turn into last evolution.
