### ISSUE TITLE
Sorting on Iv,Cp,LvL

### ISSUE THREAD

**Issue by WaRMacTep** [NecronomiconCoding/NecroBot#978]
I suggest to add option on preservation of Pokemons based on level.
At the 30th level it is possible to catch Pokemons with max CP, for further evolved, but when sorting according to Iv,Cp it is very difficult to be guided. -level sorting will solve this problem.
it is also necessary to add automatic renaming of such Pokemons, for example "Magikarp/30(187/203)92%"

I apologize for the English, I use the translator.

**Comment by Newkz** [comment]
Heard, while level is a "hidden" thing in the game, it's a lot more telling combined with the IV to tell how good of a Magikarp or w/e you have. A KeepMinLvL is a lot more useful than a KeepMinCp cause the lvl applies to all pokemons where as not all pokemons can reach 1500CP.

**Comment by WaRMacTep** [comment]
For this reason it would also be desirable sorting according to level

**Comment by WaRMacTep** [comment]
in the last update have added personal sorting according to CP but this solution for 50%.
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 800.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }

**Comment by Fenixxia** [comment]
Great offer! 30+ levels to have low-level pokemon but with high Perfekt unprofitable. It will need to upgradet from star dust to the desired level after the transformation. This leads to unnecessary spending dust. Dust is always small at all.

**Comment by WaRMacTep** [comment]
up
