### ISSUE TITLE
Google auth exception error

### ISSUE THREAD

**Issue by SashkaKot** [NecronomiconCoding/NecroBot#979]
![image](https://cloud.githubusercontent.com/assets/20688667/17187635/c91ae828-5442-11e6-9b50-060edfa5be25.png)

Plz make function with manual put code, not searching in clipboard.

**Comment by Jackman1000** [comment]
Started happening to me now

**Comment by seitzbg** [comment]
I have the same issue, the clipboard code seems to crash the app:

https://www.bsd-unix.net/seitz/screenshots/PoGo.NecroBot.CLI_2016-07-27_15-57-06.png
