### ISSUE TITLE
Unable to use in areas without Pokestops

### ISSUE THREAD

**Issue by v-d-x** [NecronomiconCoding/NecroBot#984]
There's a certain area that I'd like to patrol for pokemon, but the bot will not start moving because it's busy locating a pokestop to gather supplies at. Would it be possible to have the bot start anyways and then turn off when I run out of pokeballs? This wasn't an issue in the build i downloaded a few days ago.

**Comment by Talamar1** [comment]
Use GPX and create a path, that will force it to walk (supposedly).
