### ISSUE TITLE
Logger not showing enough information

### ISSUE THREAD

**Issue by skupfer** [NecronomiconCoding/NecroBot#985]
I dont want to do a PR because I think you wanted it like that, but imho the logger doesn't print enough information.
Am I really moving? Does it loot PokeStops?
With 0.1.8 (maybe prior, too) I don't know whats going on anymore. All I see is Skipped X and sometimes a CatchSuccess due to my ignore list during a "special" farm..

If this is intended, ok. But for me (and what I have seen others) there's a lack of information :)

**Comment by skupfer** [comment]
Whatever, I do it for myself ;)

**Comment by TheBorna** [comment]
Logger message changes as few users requested #1004
Feel free to add more.
