### ISSUE TITLE
GPX/pokestops still having issue

### ISSUE THREAD

**Issue by Talamar1** [NecronomiconCoding/NecroBot#986]
There is still weirdness with GPX and pokestops:
Without GPX:
```
[15:00:36] (INFO) Trumpeter Swan Sign in (54m)
[15:00:49] (POKESTOP) XP: 50, Gems: 0, Items:
```
With GPX:
```
[14:58:36] (INFO) Skipped Squirtle
[14:58:36] (POKESTOP) XP: 50, Gems: 0, Items:
[14:58:41] (INFO) Skipped Squirtle
```

As you can see, with GPX, the Pokestop info is not printed (still trying to figure out why I'm getting XP but no items off every Pokestop)

**Comment by TheBorna** [comment]
I think it's visual bug, or you have full inventory?
Can you try to delete language folder and restart the bot?

**Comment by Talamar1** [comment]
This was an upgrade from 0.1.7, so not a clean install.  I noticed in the config file that language was set to null and not "en", adjusted that, still seeing the same behavior.  I deleted the whole thing, fresh install and reset my config file and it seems to be behaving now with respect to collection, but GPX is still failing to print the Pokestop information before it tries to collect.

**Comment by MINKI1985** [comment]
Same issue here!
I see the items I receive from a pokestop for a different amount of times and suddenly it stops.

After that I only receive XP, but no items. Checked my inventory, but it's free. 

It only helps, if you restart the Bot. This problem started a few hours ago.

**Comment by MINKI1985** [comment]
Attached to screenshot of the issue.

![bug](https://cloud.githubusercontent.com/assets/20698750/17205637/16ac4352-54ac-11e6-99dd-97e69e16e0fe.JPG)

![bug2](https://cloud.githubusercontent.com/assets/20698750/17205653/254814ea-54ac-11e6-8848-e774b67520ca.JPG)

**Comment by MINKI1985** [comment]
A new behaviour - pokestop loot is sometimes successful!

![bug3](https://cloud.githubusercontent.com/assets/20698750/17205722/71b2a2d2-54ac-11e6-9254-b6a287f6621a.JPG)

**Comment by MINKI1985** [comment]
Ok, Problem solved! 

When your inventory is full, no loot from the Pokestop will be displayed! But why did I see now warning message?Bug?

**Comment by TheBorna** [comment]
I'm working on message when inventory is full.
I said in 2nd post to check your inventory.

**Comment by MINKI1985** [comment]
Yeah, when I first checked it was not full at all(at least 25 empty spaces). But when I checked again after the issue had a new behaviour, the inventory was full.

**Comment by TheBorna** [comment]
Show that inventory is full if pokestop gives no items #1183
