### ISSUE TITLE
Feature Request: List of pokemon NOT to evolve

### ISSUE THREAD

**Issue by dirkvanbergen** [NecronomiconCoding/NecroBot#992]
Hi,

I keep manually changing somecode to filter out some pokemon that I do not want to evolve so that I can keep gathering candies for the 3rd step evolution. This particularly hurt when I saw the bot evolving 3 dratini's ... >.< (other examples that I don't want to evolve are the starter pokemon, gastly, oddish, machop, nidoron babies, well you get the idea)

Could also try to add this feature myself as a pull request, but I don't know how git(hub) works really :) So would need some help with that.

Thanks!

**Comment by Talamar1** [comment]
The inverse is already in config.json:
  "PokemonsToEvolve": [],
Just put everything but the ones you want in there.

**Comment by skyicon** [comment]
i've tried but it still evolve all pokemon without filter

**Comment by dirkvanbergen** [comment]
Yeah I know the inverse is there. It's just the question of typing in 140 pokemon vs typing in 10 :) Ok, not 140 since they don't all evolve, but probably 80 at least. I'll just keep customizing it myself, as I can see a general switch about not evolving 1st level of 1/2/3 type pokemon families is also easily built. But I want to keep evolving those pidgeys and poliwags that are so easily available for exp.

**Comment by Navyguy330** [comment]
Ever heard of copy paste?
