### ISSUE TITLE
Transfering not all pokemon

### ISSUE THREAD

**Issue by Khayalan** [NecronomiconCoding/NecroBot#996]
Hmmm... It transfers not all pokemon like some pokemon it keeps twice or more often... dont know why?
Heres my Config:
https://www.dropbox.com/s/zf43vgvbadgr5a1/config.json?dl=0
or:
{
  "AmountOfPokemonToDisplayOnStart": 20,
  "AutoUpdate": true,
  "ConfigPath": "D:\\Matze\\NecroBot\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 34.008629219864694,
  "DefaultLongitude": -118.49763393402098,
  "DelayBetweenPokemonCatch": 1000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1400,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1500,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "zubat",
    "pidgey",
    "rattata",
    "caterpie",
    "weedle",
    "spearow",
    "doduo",
    "eevee",
    "poliwag"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": false,
  "ProfilePath": "D:\\Matze\\NecroBot",
  "RenameAboveIv": true,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}

**Comment by Mewys** [comment]
same problem here

**Comment by Lasek** [comment]
Yes, I too

**Comment by sahil16** [comment]
"KeepMinCp": 1400,
"KeepMinDuplicatePokemon": 1,
"KeepMinIvPercentage": 85.0,

Raise your bar, i have kept it at 2500 and 100.

it could mean they are above mp cp or iv so they are not transferring

report back thanks, i did it that with my bot and few mins back to my sister and it transferred about close to 200 in 2 mins

**Comment by Khayalan** [comment]
I see which Pokemon have IVS and which not... Thanks to the rename and CP too

**Comment by skyicon** [comment]
sahil if that's your config you'll transfering all pokemon under 100% IV
