### ISSUE TITLE
Ignoring pokemon keeps skipping the same ones

### ISSUE THREAD

**Issue by parameciaCx** [NecronomiconCoding/NecroBot#998]
This is my console 
![image](https://cloud.githubusercontent.com/assets/20605322/17189245/91517e4a-540e-11e6-9304-033fef5b60f1.png)

I've only had it running for about 5 mins but it literally just skips pokemon the whole time and has only caught 1 pokemon at the very beginning of the bot, I know there are other pokemon in the vicinity that are not on my ignore list, but it doesn't catch them but just keep skipping the ones on the ignore list. All it's doing right now is skipping the same pokemons over and over again and going to pokestops and recycling items, not catching any pokemon.

Could a fix for this be implemented?

**Comment by parameciaCx** [comment]
also the skipped pokemon does change so clearly it's moving around but it still doesn't catch anything

**Comment by dewblackio2** [comment]
just make it catch everything but pinsirs and youll be fine... as long as you have enough pokestops near your lat and lng you wont have an issue. it doesnt hurt to get those extra candies and extra xp from a pidgey and it will also solve your issue for the time being. just set pidgey in your evolve list so it evolves them and transfers them. EZ win

**Comment by parameciaCx** [comment]
The thing is I'm using this on an account I don't want to level up super fast, what I want is to just leave it in a location that spawns a certain pokemon until it gets a 95% of that pokemon. I have bot accounts and on those I don't care about candies and EXP gain or ignoring pokemon but this account I'm trying to make it level up as slow as possible so I'm trying to ignore all the pokemon I don't need to avoid unnecessary exp

**Comment by dewblackio2** [comment]
then your best bet would be to be patient and hope they fix the issue with skipping. Nothing you can change in the config to help that, that i know of... sorry man

**Comment by fewtcher** [comment]
So you want to hunt for only one pokemon but then complain when the bot skips all other pokemon...? I can't follow your line of thought, isn't it exactly what you want it to do?

**Comment by parameciaCx** [comment]
No, I don't want it to only hunt one pokemon, I just want it to skip useless pokemon I don't need. What I want it to do is not skip the same pokemon for 3 minutes straight when there are pokestops and many other pokemon around. Anyways idk why you even bothered to comment on this, it got closed like 2 weeks ago and skipping pokemon in the current version works much better than when this was posted.
